### PR TITLE
Spelling mistake fixes

### PR DESCRIPTION
**Pull request by domdomegg**
**Description (required)**

What changes did you make and why?

Fixed various spelling mistakes in code

**Tests performed (required)**

All automated tests pass

Tested `2.9.0-debug-spelling-mistakes~efad4720` on `Galaxy Nexus (emulator)` with API level `28`.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @domdomegg , but since this affect too many files and we are at one of times that we have several open PRs, I might suggest to postpone merging this one, since probably it will cause too conflicts for several PRs, then reviewing PRs will be delayed.

**Comment by domdomegg** [comment]
I agree, this and @2114 can wait.

**Comment by domdomegg** [comment]
@neslihanturan Thinking it could be time to merge this and #2114 as we've cut down quite a bit on number of open pull requests in the last few days.

Currently only 14 PRs are open that are not authored by me. Of these,
- 1 is ready to merge (#1856)
- 1 will be definitely unaffected
- 7 require significant changes to be in a mergeable state anyways, and may be unaffected
- 5 seem stale

I will handle merge conflicts that do come up, feel free to tag me on active PRs that need merging.

**Comment by neslihanturan** [comment]
> @neslihanturan Thinking it could be time to merge this and #2114 as we've cut down quite a bit on number of open pull requests in the last few days.
> 
> Currently only 14 PRs are open that are not authored by me. Of these,
> 
>     * 1 is ready to merge (#1856)
> 
>     * 1 will be definitely unaffected
> 
>     * 7 require significant changes to be in a mergeable state anyways, and may be unaffected
> 
>     * 5 seem stale
> 
> 
> I will handle merge conflicts that do come up, feel free to tag me on active PRs that need merging.

This statistics are great, thanks for simplifying thing @domdomegg . Starting to review.

**Comment by neslihanturan** [comment]
Can you fix conflicts, or create a new PR with your already non conflicted branch?

**Comment by domdomegg** [comment]
**Test results**

All automated tests pass

Tested `2.9.0-debug-spelling-mistakes~20beb01a7 (betaDebug)` on `Galaxy Nexus (emulator)` at API level `28`
- Home, media details, upload, notifications, bookmarks, settings, about

Tested `2.9.0-debug-spelling-mistakes~20beb01a7 (prodDebug)` on `Galaxy Nexus (emulator)` at API level `28`
- Home, media details, nearby, explore, category, search, bookmarks, settings, night theme, about, tutorial

Image on beta commons: https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test2151.jpg

**Comment by neslihanturan** [comment]
Thanks for fast action as always @domdomegg !

**Comment by domdomegg** [comment]
Thank you to you for reviewing it so quickly, within a few minutes of Travis passing!

**Pull request merged**
