### PR TITLE
Add module for file picker for camera and gallery uploads

### LINKED ISSUE #2283: Discuss the new camera permission required by the app
**Summary:** 

> The image picker library that has been added in this PR seems to have one unintended consequence which seems to have been overlooked (as I don't see it discussed here). The app now asks for extra permission while upgrading. It asks for permission to access the camera which seems unnecessary to me as I don't see where it's used. This might go unnoticed for Android versions which have runtime permissions (I think Android 6 and later) but it's noticeable when upgrading the app in devices running an Android version < 6
> 
> Is there a way to prevent the extra permission from being asked in some way?

As pointed out by @sivaraam, after #2278 the app requires an extra permission ie CAMERA. 

There are 2 things to be addressed: 

- is it fine to request camera permission
- API > 23 isn't prompting for runtime permissions, which needs to be fixed. Will submit a PR soon. 

Personally, I would be fine with granting permissions to a photo uploader app requesting for Camera permission. Going forward, having control of the camera will have several advantages.

### LINKED ISSUE #2286: Image Picker lets only local images to be picked
**Summary:** 

#2278 introduced a library for picking images. Unfortunately, the library or other libraries that are available, let you choose only local images. We cannot access Google Photos, Drive or other places for photos. 

The library had 2 advantages: 
1) lets you limit the number of images that can be picked for upload
2) removes all boilerplate and potential bugs related to picking images from gallery and images. 

Not having Google photos or Drive is not an option so definitely, some action needs to be taken. 

I was discussing the same with @ashishkumar468 and finally reached some consensus about using another library that at least fixes (2). We still have our reservations as it won't address (1), but the positive side is that it would bring consistency around the handling of content URIs. 

We need more opinions before we make any changes and possible suggestions if anyone is familiar with it. 

The other option is to not use any library and handle the intents on our own. Even this is feasible and would just need some investment to ensure that issues like #2033 are eliminated completely. 

cc @nicolas-raoul @domdomegg @misaochan @neslihanturan

### LINKED ISSUE #2376: Pressin "Next" at step 1 of upload does nothing
screenshot_20190130-224319

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2286 
Fixes #2283
Fixes #2376

Changes: 
- instead of adding `EasyImage` as a library dependency, I have added a `filepicker` module in our codebase that can be used for picking files(currently image files are only used). 
- have added `MimeTypeMapWrapper` to handle mime types that are not understood by the default `MimeTypeMap`. Have consolidated the extraction and fixing of mimetype/extension to a single place. 
- `FilePicker` provides a permanent location of the copied file. So have removed the logic for handling temp files. 
- `simplemagic` library is no longer required.

### CODE REVIEW

**Comment by neslihanturan** [comment]
When I try to upload from Contib Activity, lets say I clicked to gallery button, it asks me "chose image to upload via gallery or camera"
Same thing happens when I click camera icon too. But I already gave my decision by clicking camera or gallery button, second question seems redundant.

Here screen shot of my click to both gallery and camera buttons:
image

**Comment by maskaravivek** [comment]
@neslihanturan I have fixed both the issues. Its ready for testing now. 

device-2019-02-02-100658

**Comment by maskaravivek** [comment]
@neslihanturan Its ready for testing now. :)

**Comment by neslihanturan** [comment]
Both issues are fixed, thanks @maskaravivek :+1:

**Pull request merged**
