### PR TITLE
Open map of place where picture was taken

### LINKED ISSUE #1126: Open map of place where picture was taken
I often want to check on Google Maps what is the exact name of a building, or find out what is that thing in the background, or determine whether I was technically in North-Kilda or South-Kilda.
This could be another button in the description screen, but actually I often need it in the categories screen, when two proximity categories appear and I need to choose the right one.
It should open the default map app.

### PR DESCRIPTION
**Pull request by tanvidadu**
## Description

Fixes #1126 

Added a Floating Button which open Google map app with street view showing the location specified by the coordinates.

## Tests performed

Tested on API level 24  , Samung J7 max with betaDebug.

## Screenshots showing what changed
 
map

### CODE REVIEW

**Comment by misaochan** [comment]
Looks good to me, what do you think @neslihanturan ?

**Comment by neslihanturan** [comment]
I have tested this one, but I have two questions:
1- If this get merged, where we will put zoom button and vice versa:)
2- This should be disabled whenever location information isn't exist in photo

**Comment by tanvidadu** [comment]
1) when one of the pr either #1300 or #1360 gets merged I will immediately submit another patch to convert them to nested FAB.
2) when coordinates are not present a toast saying "Coordinates were not specified during image selection" will be displayed to user

**Comment by misaochan** [comment]
I think it might be better to hide the button entirely if coordinates are not present? :)

**Comment by tanvidadu** [comment]
I think it will be more intuitive to hide the FAB button I will change the fix accordingly ! thanks :)

**Comment by tanvidadu** [comment]
I have added nested FAB in this pull request. Screenshots are below : 

fab1
fab2

**Comment by misaochan** [comment]
Looks good to me! 👍

**Comment by neslihanturan** [comment]
@tanvidadu great job, I have a few more suggestions and we are done. 
- Can you please give an information messaje when there is no location information provided and user clicked to map icon?
- Can we use a plus icon on fab, instead of arrow, similar to our new nearby look. And can we change FAB colors as in nearby FABs, to make our app consistent.

**Comment by misaochan** [comment]
@neslihanturan , sorry, I personally think that the up arrow is more appropriate than a plus button. :) Because in Nearby the FAB is for uploading (i.e. "adding") something, whereas in this case it is just a view (zoom and coordinates).

Maybe if the up arrow isn't suitable, we can think of a 3rd option?

**Comment by neslihanturan** [comment]
You might be right @misaochan , but according to material design https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button , doesn't matter if you mean "add" or not, they use plus as example. So it feels more natural to me. I think meaning of plus is not "add", instead "expand". What do you think?

**Comment by tanvidadu** [comment]
- I forgot to un-comment a condition that allows the map option to be present only when coordinates are present, which will fix the first issue.  
- I found the up arrow more suitable but I am happy to change it after @misaochan opinion on it.

**Comment by misaochan** [comment]
Ah, interesting! In that case yes, I'm good with changing it to a "+". :)

**Comment by nicolas-raoul** [comment]
Sorry I am late to the discussion, but personally I also preferred the arrow haha
The guideline page actually has examples with something else than a +, it seems:

screenshot from 2018-05-01 11-37-04
screenshot from 2018-05-01 11-37-20

The Facebook Messenger app was using the "+" before, but they replaced it with the "text bubble" symbol above, I guess users were finding the "+" confusing:

screenshot_20180501-140756

**Comment by misaochan** [comment]
Haha, poor Tanvi! How about we just leave the arrow for now and merge this PR after the color change and coordinate checks are implemented? We can always continue discussion and change it later if desired.

**Comment by misaochan** [comment]
@neslihanturan Shall we go ahead and merge?

**Comment by neslihanturan** [comment]
Great job @tanvidadu !

**Pull request merged**
