### PR TITLE
Fixes #3376, letters in review going out of view

### LINKED ISSUE #3376: Letters in Peer Review
**Summary:** 
Some words doesn't appear correctly to the user . The line <VIOLATION> under the <NO, COPYRIGHT> and some of the descriptions.

**Steps to reproduce:** 
We could change the dimensions.

**Device and Android version:** 
Redmi note 5 , Android version 9

**Commons app version:** 
2.12.3

**Screen-shots:** 
Screenshot_2020-02-05-19-40-04-954_fr free nrw commons

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by GearGit**
**Description (required)**

Fixes #3376 Letters in Peer Review

**What changes did you make and why?**
Changed the dimensions of the layout of Peer Review by 20dp.

**Tests performed (required)**

Tested on Android 9.

**Screenshots showing what changed**

**Before:**

**After:**

### CODE REVIEW

**Comment by maskaravivek** [comment]
@GearGit can you add a little bit of more padding for the "No copyright violation" text. Also, can you post a screenshot from a small device as well. :)

**Comment by GearGit** [comment]
Okay sure, i will increase the bottom padding.

**Comment by GearGit** [comment]
I changed the bottom padding. Here is a screenshot on a smaller device:

**Comment by madhurgupta10** [comment]
@GearGit can you resolve the merge conflicts?

**Comment by GearGit** [comment]
> @GearGit can you resolve the merge conflicts?

The changes I made are causing the conflicts, but changes that I made resolves the issue. So I guess the Mentors should handle this, because If I revert the changes then the error will still persist.

**Comment by madhurgupta10** [comment]
> > @GearGit can you resolve the merge conflicts?
> 
> The changes I made are causing the conflicts, but changes that I made resolves the issue. So I guess the Mentors should handle this, because If I revert the changes then the error will still persist.

There is no need to revert your changes, just push another commit to your branch. A recent [commit ](https://github.com/commons-app/apps-android-commons/commit/69e7161c61472ee4a175db9672c0086545b37d81) is causing the conflicts, so I suggest you move your changes to `app/src/main/res/values/dimens.xml`

**Comment by domdomegg** [comment]
Also a potentially simpler solution would be making the strings just 'Yes' and 'No' where we can - IMO the question is obvious and binary enough to not require such long 'answer text', and that'll save us this headache and make the UI cleaner.

**Comment by GearGit** [comment]
> Also a potentially simpler solution would be making the strings just 'Yes' and 'No' where we can - IMO the question is obvious and binary enough to not require such long 'answer text', and that'll save us this headache and make the UI cleaner.

@maskaravivek @nicolas-raoul What do you think about this?

**Comment by maskaravivek** [comment]
Yes, I like the idea of simplifying the strings.

**Comment by misaochan** [comment]
I guess the longer text is there because the user might be confused whether they are saying "yes, delete it", or "yes, it looks fine". But I agree that the question is straightforward enough that anyone who reads the question should be able to know what "yes" means.

**Comment by macgills** [comment]
You could make it more explicitly answer the question asked. "Yes, it does" "No, it doesn't", reordering it so the question is the last thing you read could help too, keeps it fresh in the mind.
Also I would never bet on "Yes" & "No" being short strings, I have had it it bite me in other projects because spanish people use `Acceptar` for `Ok` and my circular button was not expecting that.

**Comment by GearGit** [comment]
So, which one:
1.Yes
2.Yes it does

**Comment by sivaraam** [comment]
>  Also I would never bet on "Yes" & "No" being short strings, I have had it it bite me in other projects because spanish people use Acceptar for Ok and my circular button was not expecting that.

That's a good point but _when compared to_ "Seems fine", "Yes" is shorter, indeed 😉 

> So, which one:
> 1.Yes
> 2.Yes it does

IMO, "Yes" and "Yes, it does" conveys the same thing to the questions shown in the Review screen. So, my preference would be to go with the shorter version i.e., "Yes".

**Comment by GearGit** [comment]
> > Also I would never bet on "Yes" & "No" being short strings, I have had it it bite me in other projects because spanish people use Acceptar for Ok and my circular button was not expecting that.
> 
> That's a good point but _when compared to_ "Seems fine", "Yes" is shorter, indeed 😉
> 
> > So, which one:
> > 1.Yes
> > 2.Yes it does
> 
> IMO, "Yes" and "Yes, it does" conveys the same thing to the questions shown in the Review screen. So, my preference would be to go with the shorter version i.e., "Yes".

I agree with that. @maskaravivek @nicolas-raoul What's your take on this? We should finalize it as quick as possible as it has been long overdue.

**Comment by misaochan** [comment]
It seems like the majority of responses here are in favour of the simplified strings "Yes" and "No". We can go with that. :)

**Comment by GearGit** [comment]
Ok then, I wil make the changes and commit

**Comment by madhurgupta10** [comment]
@GearGit Any update on this PR?

**Comment by GearGit** [comment]
I am having difficulties in building the project, i updated android studio to latest version and deleted the old fork and reforked the master branch and git cloned it on local computer.

I will post the log, please let me know how i can resolve the issue. The error is somewhat like this:

java.net,ConnectException : connect : Address is invalid on local machine, or so port is not valid on remote machine

**Comment by madhurgupta10** [comment]
> I am having difficulties in building the project, i updated android studio to latest version and deleted the old fork and reforked the master branch and git cloned it on local computer.
> 
> I will post the log, please let me know how i can resolve the issue. The error is somewhat like this:
> 
> java.net,ConnectException : connect : Address is invalid on local machine, or so port is not valid on remote machine

I suspect this problem is caused by some Antivirus running in the background!

**Comment by GearGit** [comment]
I did disabled the antivirus but the error still persists. I even switched my internet connection, but no luck.

**Comment by GearGit** [comment]
The issue has been resolved. Platform-tools was not installed and build-tools needed to be updated. Aslo made an exception for android studio in the antivrus.

Now coming to the pull request,should i delete the strings like, "No, copyright violations", or should i create new strings "yes" and "no"?

**Comment by domdomegg** [comment]
> The issue has been resolved. Platform-tools was not installed and build-tools needed to be updated. Aslo made an exception for android studio in the antivrus.

🎉

> Now coming to the pull request,should i delete the strings like, "No, copyright violations", or should i create new strings "yes" and "no"?

Strings for "yes" and "no" I think should be built into Android somewhere (possibly `android.R.string.yes` and `android.R.string.no`?)

**Comment by sivaraam** [comment]
> Strings for "yes" and "no" I think should be built into Android somewhere (possibly android.R.string.yes and android.R.string.no?)

I believe it's better if we use our "Yes" and "No" strings (`R.string.yes` and `R.string.no`) which seems to have been translated into 90 other languages.

**Comment by domdomegg** [comment]
> I believe it's better if we use our "Yes" and "No" strings (`R.string.yes` and `R.string.no`) which seems to have been translated into 90 other languages.

I think the Android ones are translated into more languages, however they're actually 'ok' and 'cancel' so wouldn't work anyways (see https://developer.android.com/reference/android/R.string#yes). You solution is best (`R.string.yes` and `R.string.no`).

**Comment by GearGit** [comment]
Okay then i wil implement it and make the pull request.

**Comment by GearGit** [comment]
Created a new pull request with the changes
https://github.com/commons-app/apps-android-commons/pull/3552

**Comment by sivaraam** [comment]
Continued in #3552

**Pull request closed without merging**
