### PR TITLE
Fixes #671: Ability to launch welcome activity again

### LINKED ISSUE #671: Make tutorial/guidelines/welcome screen accessible again at any time
I've found #274 and #501, they are somewhat similar, but don't include the simplest option, which I'd like to suggest in this issue: let's allow users to review the welcome screen again whenever they please. I think it could be another menu item, for example.

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #671

### CODE REVIEW

**Comment by misaochan** [comment]
Travis is not happy and I'm not sure why. Are we even using JacocoAgent....?

```
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:androidJacocoAgent'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:169)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:118)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.doGetFiles(DefaultConfiguration.java:519)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:356)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
	at com.android.build.gradle.tasks.factory.JacocoAgentConfigAction$1.call(JacocoAgentConfigAction.java:63)
	at com.android.build.gradle.tasks.factory.JacocoAgentConfigAction$1.call(JacocoAgentConfigAction.java:59)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)
```

**Comment by maskaravivek** [comment]
@misaochan Restarting the travis build should solve the issue. I am not able to see the button to restart build. :)

**Comment by misaochan** [comment]
I restarted it. We probably need to figure out at some point why this is happening so often and how we can fix it, heh.

**Comment by misaochan** [comment]
Fails again on restart.  :(

**Comment by maskaravivek** [comment]
@misaochan This time the build failed for this task `:app:processDebugResources`. When I run the task locally, it succeeds. Can anyone take a look at why it might be failing on travis. @whym @dbrant

**Comment by tobias47n9e** [comment]
It also fails because of https://github.com/commons-app/apps-android-commons/issues/698

Most likely you did not pull the translatewiki commit yet? It caught me by surprise too.

**Comment by misaochan** [comment]
Right, sorry, I forgot about the translatewiki issue (it was 5am when I last posted, haha). I think I'm just going to go ahead and merge this first, and we'll deal with the translations and Travis issues separately.

**Pull request merged**
