### PR TITLE
My proposed solution for #1318.

### LINKED ISSUE #1318: Wrong URL not found toast
**Summary:** 

URL not found toast is visible when license is null (I am not sure if this case is possible). The related code is here:
```
if (licenseLink(media) != null) {
            license.setOnClickListener(v -> openWebBrowser(licenseLink(media)));
        } else {
            Toast toast = Toast.makeText(getContext(), getString(R.string.null_url), Toast.LENGTH_SHORT);
            toast.show();
        }
```
However I can go to the license page by clicking license, so it shouldn't be null. 

**Steps to reproduce:** 

I faced this issue with some images. Just click on images to see media details page. However, this doesn't happen on each images, so try several:) 

**Add System logs:**

No logs

**Expected behavior:** 

Code should enable if statement instead of else

**Observed behavior:** 

Else statement is runned

**Device and Android version:** 
19 API level, prodDebug

**Screen-shots:** 
https://commons.wikimedia.org/wiki/File:Special_bread_from_Turkey.jpg

image

**Would you like to work on the issue?**

No:D

### PR DESCRIPTION
**Pull request by Helvijs-t2t**
## Description

Fixes #1318 

{Added an extra condition to if statement, to ensure that licence will not appear as an empty string  in case if an android system fails to read the name of the licence .}

## Tests performed

Tested on {google Pixel 2 created in Android Studio default debug method} with 3 different pictures each one having a different licence selected.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Yes @Helvijs-t2t adding an else statement is a solution but we are trying to find root cause of this issue. It can cause other bugs too. 
Please do not edit other files, that are not related with your task.

If you are interested to work on this issue, to find root cause, I will be happy to reopen this.

**Comment by Helvijs-t2t** [comment]
@neslihanturan  I did not add an else statement.  It was there already originally. Please look again at changes I made in the code.

I added a second parameter to check in the if condition.  
I believe that originally this issue appears because Android system does not see the licence type in licence field and does not think that the information in licence text field  = null, therefore I added the part which says `!licenseLink(media).equals("")` This is checking if the value in licence field is equal to an empty string. 

If you believe that this is not a solution. Please Let me know and I will do my best to fix this.

**Comment by Helvijs-t2t** [comment]
Do you have any idea of this i.e could you point me in the correct direction if you have an idea of what could cause the issue to appear @neslihanturan  ? 

P.s. I would like to continue working on this.

**Comment by neslihanturan** [comment]
Sure @Helvijs-t2t :) 
To be honest I don't know the root cause. If I were you, I would set a breakpoint and debug on betaDebug mode. You can try to reproduce the issue and see what is going wrong. But I think this can be about synchronization since there are bacground tasks so it can be hard to find the root cause. Good luck:)

**Comment by Helvijs-t2t** [comment]
According to the source code in the app and the User Interface, I believe that `else` statement should not get executed at all. 
1. When App is opened the first time, it will assign a default licence automatically.
2. The user can change default licence in settings which will be automatically selected for the photo.(I.e. there is no legal way to upload a photo without any licence specified for it. 
2. When new Photo is added, whether the user wants it or not, the photo will be licenced.

Therefore Licence field should never be an empty string or `null`. 

I have tested this now and I believe that this issue can be fixed by deleting the `else` statement completely. ( with a brakepoint set at the start of `line 298 `   ` license.setOnClickListener((View v) -> openWebBrowser(licenseLink(media)));`

Debug monitor shows : 
`D/MediaDataExtractor: MediaDataExtractor found self-license cc-by-4.0
D/MediaDetailFragment: Media license is: cc-by-4.0`
I tried this with all five licences and could not recreate the error when `else` statement is executed.

As I mentioned before, this issue most likely is caused by a _failure_ in Android background processes, which did not detect the information in Licence text field. to see what exactly is going wrong at the time. Would be beneficial to know which android version and the mobile phone was used at the time when this issue was faced.  
Then I could recreate the same system in emulator as well and try to debug again, however then this issue, in my opinion, is not  **_beginner friendly_** anymore.

**Comment by neslihanturan** [comment]
I agree, changing the label. Thanks @Helvijs-t2t :) Android 4.2.2

**Comment by Helvijs-t2t** [comment]
@neslihanturan Can I know the phone manufacturer and model as well please?

**Comment by neslihanturan** [comment]
sure Lenovo A3300-HV, Android version is 4.4.2 (*). Do you need anything else?

**Comment by Helvijs-t2t** [comment]
At the moment no. Thanks 👍

**Comment by Helvijs-t2t** [comment]
I have now tested this on  _Lenovo A3300-HV with  Android version is 4.4.2_.

I did recreate the same bug on the first try and here is a screenshot from debugging log. 
debugsnap1
This error message does not appear on newer Android versions ( I tested on Android 8.1 Oreo and 7.1.1 Nougat).

Also, Android background processes failed to do some background processes with pixel mapping.
snipp2debug

> eglCreatePixmapSurface — create a new EGL pixmap surface

> EGL_BAD_MATCH is generated if the attributes of native_pixmap do not correspond to config or if config does not support rendering to pixmaps (the EGL_SURFACE_TYPE attribute does not contain EGL_PIXMAP_BIT).
[Full description here](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglCreatePixmapSurface.xhtml)
This comes out of my knowledge and I am not sure what exactly is this error talking about. 

However, I would still suggest that we delete `else`statement completely as it should not get executed at all times. 
As a +1 for my own suggestion, I can mention that this is a common approach for all apps to stop supporting older android/mobile phone versions at some point when integration between latest software's and hardware and older ones.

let me know if I should send a request with my proposed solution or we will leave this for someone more knowledgeable than me.

**Comment by neslihanturan** [comment]
Thanks for your detailed inspection @Helvijs-t2t , I am convinced for basic solution. Will test ASAP

**Comment by Helvijs-t2t** [comment]
@neslihanturan  Just wondering if you are willing then to accept the pull request I have sent or at least test it when you have time, so we can continue with this issue or close it?

**Comment by neslihanturan** [comment]
Sorry it took very long since we tried to make a release and solve release bugs. Tomorrow will be my merging PRs day. Is it okay to test and mere this tomorrow @Helvijs-t2t ?

**Comment by neslihanturan** [comment]
Sorry @Helvijs-t2t according to my tests, I am still able to reproduce the error. So this PR doesn't give a temporary solution too. Thanks for your contribution:)

**Comment by Helvijs-t2t** [comment]
@neslihanturan  Could you please email me the test cases or a bit more information about the tests you made to oleninshelvijs@gmail.com so I can take a look into this again ?

Thanks,

**Pull request closed without merging**
