### PR TITLE
added ReviewImageFragment Unittest

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Added ReviewImageFragment Unittest

What changes did you make and why?

Added ReviewImageFragment Unittest

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 All test in ReviewImageFragmentsTest is passed when i run it in  android Studio but in pull request it show Travis cl build failed

**Comment by madhurgupta10** [comment]
> @madhurgupta10 All test in ReviewImageFragmentsTest is passed when i run it in android Studio but in pull request it show Travis cl build failed

Here are the tests which are not passed on Travis, did you try to run our tests with all other tests together?

```
fr.free.nrw.commons.review.ReviewImageFragmentTest > testOnYesButtonClicked FAILED
    java.lang.Exception at AndroidTestEnvironment.java:502
        Caused by: java.lang.IllegalStateException at ReviewImageFragmentTest.kt:124

fr.free.nrw.commons.review.ReviewImageFragmentTest > testOnUpdateCategoriesQuestion FAILED
    java.lang.Exception at AndroidTestEnvironment.java:502
        Caused by: java.lang.reflect.InvocationTargetException at ReviewImageFragmentTest.kt:112
            Caused by: java.lang.IllegalStateException at ReviewImageFragmentTest.kt:112

fr.free.nrw.commons.review.ReviewImageFragmentTest > testOnGetReviewActivity FAILED
    java.lang.Exception at AndroidTestEnvironment.java:502
        Caused by: java.lang.reflect.InvocationTargetException at ReviewImageFragmentTest.kt:141
            Caused by: java.lang.IllegalStateException at ReviewImageFragmentTest.kt:141

649 tests completed, 3 failed, 2 skipped
```

**Comment by Prince-kushwaha** [comment]
@madhurgupta10  i do not run all test of reviewImageFrament with  other all   tests together

**Comment by madhurgupta10** [comment]
> @madhurgupta10 i do not run all test of reviewImageFrament with other all tests together

Can you try it locally if all tests are passed along with your new tests? Also can you post a screenshot of code coverage so that we can see lines hit/miss?

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 how i run all the unit test  together i do search but not found correct solution ?

**Comment by madhurgupta10** [comment]
> @madhurgupta10 how i run all the unit test together i do search but not found correct solution ?

You can right-click on test folder and run

Capture

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 i already try the above method this method output is in below image
test

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 In my android studio on right-click on test 
Screenshot (4)

**Comment by madhurgupta10** [comment]
@Prince-kushwaha can you share a screenshot of your configuration file?

**Comment by madhurgupta10** [comment]
@Prince-kushwaha can you post a screenshot of code coverage for this file so that we can see lines hit/miss?

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 thanks for help 
code coverage
reviewimageTEs

**Comment by madhurgupta10** [comment]
> @madhurgupta10 thanks for help
> code coverage
> reviewimageTEs

You can export this report and open the ReviewImageFragment to see lines miss/hit and take a screenshot, current tests only cover 26% of lines for this class, it would be great if it can be around 70-80%

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 can i shift all the selected code in new function show that it is easy to write unit test for it ?
test1

**Comment by madhurgupta10** [comment]
> @madhurgupta10 can i shift all the selected code in new function show that it is easy to write unit test for it ?
> test1

We should try to write unit tests without refactoring the code unless it is absolutely necessary, in this case, I don't see why refactoring is needed? You can different tests for each case in the switch statement, use when-then  to mock position

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 shift all the selected code in new function is absolutely necessary becouse i try to test  
`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {`
ll

it give error `java.lang.NullPointerException: Layout parameters cannot be null
`and we do not change the  value of position `        position = getArguments().getInt("position");
`

**Comment by madhurgupta10** [comment]
> @madhurgupta10 shift all the selected code in new function is absolutely necessary becouse i try to test
> `@Override public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {`
> ll
> 
> it give error `java.lang.NullPointerException: Layout parameters cannot be null `and we do not change the value of position ` position = getArguments().getInt("position");`

@Prince-kushwaha You should set your layoutInflater in setUp()

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 i try this solution but it not work https://github.com/commons-app/apps-android-commons/pull/4413#issuecomment-841764644 i have  to refactoring the code

**Comment by madhurgupta10** [comment]
@Prince-kushwaha Sorry for super late reply, I missed notification for this PR.

Here is what you can do to test the onCreateView method

```
@Test
@Throws(Exception::class)
fun testOnCreateView() {
    fragment.onCreateView(layoutInflater, null, savedInstanceState)
}
```

In your `setUp()` method initialize the layout inflater like this
```
layoutInflater = LayoutInflater.from(activity)
```

You need to replace the `getString()` method in onCreateView with `layoutView.getContext().getString()` in order for the tests to run without being attached to context

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 we have` position = getArguments().getInt("position");` in onCreateView Method so we not have to use 
`layoutView.getContext().getString()`

**Comment by madhurgupta10** [comment]
> @madhurgupta10 we have` position = getArguments().getInt("position");` in onCreateView Method so we not have to use
> `layoutView.getContext().getString()`

I haven't tried it but if changing `getString()` to `layoutView.getContext().getString()` is not needed then it is much better.

**Comment by neslihanturan** [comment]
Hey @Prince-kushwaha , thanks a lot for the PR:) Are there any updates after @madhurgupta10 's reviews?

**Comment by madhurgupta10** [comment]
@neslihanturan It seems like the author isn't active on this PR, we can still merge it and if @Prince-kushwaha want to continue working on the suggested changes, can create a new PR :)

**Comment by neslihanturan** [comment]
Thanks @madhurgupta10 and @Prince-kushwaha then :)

**Pull request merged**
