### PR TITLE
Fixes #4589 :- The empty screen while no images found in custom picture selector [bug]

### LINKED ISSUE #4589: Empty screen while no images found in custom picture selector
**Summary:** 

When there is no image in the device, Custom picture selector opens with a white empty screen.

**Steps to reproduce:** 

1. Make sure there is no image in the device
2. Click the + icon 
3. Select custom picture selector

What did you expect the app to do, and what did you see instead?

There should be some information like "No images found" (with some graphic)

**Device and Android version:** 

Pixel 2 API 30
 
**Commons app version:** 

Betadebug latest master

**Screen-shots:** 

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by Rishavgupta12345**
Fixes https://github.com/commons-app/apps-android-commons/issues/4589 :- The empty screen while no images found in custom picture selector @madhurgupta10 merge this pull requests and the old problem with the test will be solved .

### CODE REVIEW

**Comment by Rishavgupta12345** [comment]
> Fixes #4589 :- The empty screen while no images found in custom picture selector @madhurgupta10 merge this pull requests and the old problem with the test will be solved .

@nicolas-raoul you can merge this, it is now perfect

**Comment by Rishavgupta12345** [comment]
> [ @github-actions](/apps/github-actions)

@madhurgupta10 @4D17Y4 please merge this pull request so that the BUILD failed due to #4863 fixes

**Comment by madhurgupta10** [comment]
@Rishavgupta12345 One of the tests is still failing.

```
fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:129
            Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:129

1359 tests completed, 1 failed, 2 skipped

```

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 One of the tests is still failing.
> 
> ```
> fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:129
>             Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:129
> 
> 1359 tests completed, 1 failed, 2 skipped
> ```

@madhurgupta10 fixed it now ready to merge

**Review by nicolas-raoul — APPROVED** [review]
Looks OK to me, and it indeed fixes 2 of the 4 failing unit tests.

**Pull request merged**
