### PR TITLE
Fix Leaks in Nearby activity

### PR DESCRIPTION
**Pull request by maskaravivek**
#941

### CODE REVIEW

**Comment by maskaravivek** [comment]
Seems to fix #938 as well. Unable to reproduce the leaks.

**Comment by neslihanturan** [comment]
Unfortunately, I reproduced leaks, and seem like have found another leak:
image5370

**Comment by maskaravivek** [comment]
@neslihanturan Can you try testing once again. I have done some more checks for possible memory leaks. I played with the app for around 15-20 mins but wasnt able to reproduce the leak. I tried:
- Rotating the screen multiple times
- Coming back and forth to the `NearbyActivity`
- Multiple refreshes and map/list view switches without waiting for responses.

**Comment by neslihanturan** [comment]
Hmm I couldn't reproduced it either this time. Probably my mistake, very sorry for your 20 minutes @maskaravivek :/ If you solve conflicts I am ready to merge it.

**Comment by maskaravivek** [comment]
@neslihanturan No problems. Atleast now we can be sure that these 2 leaks are fixed. Thanks for helping with testing. Have resolved the merge conflicts. :)

**Comment by neslihanturan** [comment]
@maskaravivek sorry for inconsistency but I saw some new leaks again and it my last build was your branch as I remembered. Please give me some more time to make sure about leaks, because you know it is hard to detect them.

**Comment by maskaravivek** [comment]
Sure, @neslihanturan. Please report any leaks in `NearbyActivity` and `ContributionsActivity`

**Comment by neslihanturan** [comment]
I am convinced:)

**Pull request merged**
