### PR TITLE
Fix for issue #1508 

### PR DESCRIPTION
**Pull request by ShridharGoel**
Made changes to the error message displayed when user enters wrong login credentials.
Changed "Unable to login - Please check your username" to "Unable to login - Please check your username and password".
Changed "Unable to login - Please check your password" to "Unable to login - Please check your username and password".

Changed to a common error message string for the two cases where user either entered a wrong username or a wrong password to reduce the work for translators.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Nice hack @ShridharGoel :)

**Comment by nicolas-raoul** [comment]
How about maybe using a single string though? :-)
That would make less work for the translators.

**Comment by ujjwalagrawal17** [comment]
@ShridharGoel looks like your first Open Source Contribution. Welcome to the community. Do join our Hangouts group, you will get to learn a lot of interesting stuff.

**Comment by ShridharGoel** [comment]
@neslihanturan Thanks! :)

@nicolas-raoul That was a nice suggestion. I have implemented it.

@ujjwalagrawal17 Thanks! I'll surely be joining that group. :)

**Comment by neslihanturan** [comment]
And recall from our Contributions.md  https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21

> Go to your fork of the repository, select the "Pull Requests" tab and click "create a pull request", as a comment, write something like "Fix for issue #12345 crash when rotating screen", then submit the pull request.

So just "Fix for issue #12345" :x:  is not enough. Tester have to open another tab and remember what was #123456 first then they understand what does this PR do. And it looks super confusing while you are looking at list of PRs (generally we have 20) and trying to find one that you interested by just looking at title. Instead you should add a description, ideally something very similar to related issue title, to title of your PR ("Fix for issue #12345 crash when rotating screen" :heavy_check_mark: )

**Comment by neslihanturan** [comment]
Besides you should mention from issue number at description part, so that issue will be linked. #1508

**Comment by neslihanturan** [comment]
Thanks for your first contribution @ShridharGoel , looking forward to merge more:)

**Pull request merged**
