### PR TITLE
Fix NullPointer when clicking on image in MediaDetailFragment (#3730)…

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
Uri.parse would throw NullPointerException if the image in MediaDetailFragment was clicked before the image URL is available

**Tests performed (required)**

Tested betaDebug on S7

### CODE REVIEW

**Comment by misaochan** [comment]
Seems like Travis failed?

**Comment by ashishkumar468** [comment]
Looking into it @misaochan

**Comment by ashishkumar468** [comment]
Actually 2.13 somehow has a compile-time error

**Comment by ashishkumar468** [comment]
Fixed @misaochan

**Pull request merged**
