### PR TITLE
Fix #1139: Nominate uploaded image for deletion

### LINKED ISSUE #1139: Add Option to delete the uploaded image.
**Summary**
Sometimes we upload images that are not good and later on we should have an option to delete or suspend the image. This can be done by providing buttons in image list on clicking will call an HTTP request to delete/Suspend it from the database.

### PR DESCRIPTION
**Pull request by diddypod**
## Description

Fixes [#1139](https://github.com/commons-app/apps-android-commons/issues/1139) Add Option to delete the uploaded image. 

Added DeleteTask and added new functions to MediaWikiApi to make edits to the pages

## Tests performed

Tested on Xiaomi (Wingtech) Redmi 2, with betaDebug.

## Screenshots showing what changed

screenshot_20180313-112023
screenshot_20180313-112028
screenshot_20180313-112031

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Sounds reasonable, judging from the screenshots :-)
I guess needs for subsequent iterations will appear as users start to use the feature, but that's good for now I would say.

**Comment by neslihanturan** [comment]
@diddypod Thanks for this great job. I think we should display "Succesfully nominated" message in more visible way, ie. with an alert. 
Besides, @nicolas-raoul is it possible to get any information as "nominated for deletion" via MWAPI? If so we can prevent several nominations. If this is not technically possible, we can add this information to  "Succesfully nominated" message, as  "Succesfully nominated, please do not nominate this image again" (In more polite English)

**Comment by neslihanturan** [comment]
There is a notification for nomination process, so maybe we can recognize if an image is nominated for deletion.

**Comment by diddypod** [comment]
Okay, @neslihanturan I'll incorporate a check for that ASAP.

**Comment by diddypod** [comment]
#### Fixes issue: Potential multiple nominations 
The AsyncTask now checks if the Commons:Deleion_Requests subpage exists to verify if the file has previously been nominated for deletion, and proceeds accordingly. Thus, each file may be nominated for deletion only once.
Also, the results of the nomination process are displayed as an alert, as @neslihanturan suggested, with an option to open the file page in the browser.

**Comment by neslihanturan** [comment]
Great @diddypod , very good job:) Will be testing this immediately

**Comment by neslihanturan** [comment]
@diddypod it works quite nice, thanks for your contribution. Maybe we can notify the user about "already nominated issue"  before entering the message second time. What do you say?

But this can be a seperate PR, merging this one.

**Pull request merged**
