### PR TITLE
[WIP] Remove unused resources

### PR DESCRIPTION
**Pull request by maskaravivek**
Checking if Android's "remove unused resources" is actually effective or does it remove resources that are currently being used.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@domdomegg @whym Have you used Android Studio's "Remove unused resources" before? I am skeptical that it might remove resources that are currently being used(esp for resources that are not in values/strings.xml ie it might think values-mg/strings.xml is not used).

**Comment by maskaravivek** [comment]
Note: It is just a test PR. Marked it as "ready for review" as Travis build wasn't kicking in without it. :/

**Comment by domdomegg** [comment]
I've never used "Remove unused resources". From the surface it looks like this has worked (given Travis builds). I'd be happy to merge this after extensive testing (I could do this evening if you'd be okay with me merging it).

**Comment by domdomegg** [comment]
The one annoying thing it's done is weirdly indented some of the `.xml` files, which is the cause of the additions.

**Comment by maskaravivek** [comment]
> I've never used "Remove unused resources". From the surface it looks like this has worked (given Travis builds). I'd be happy to merge this after extensive testing (I could do this evening if you'd be okay with me merging it).

Yup, even if I am testing on my end. Will test in 2 languages to see if things work.

**Comment by domdomegg** [comment]
Bug: navigation drawer missing dividing sections:

| master | 2685 |
| - | - |
| Screenshot_1553110711 | Screenshot_1553110704 |

**Comment by domdomegg** [comment]
Bug: nice license names lost

| master | 2685 |
| - | - |
| Screenshot_1553110953 | Screenshot_1553110978 |

**Comment by maskaravivek** [comment]
Since it breaks a few things, i am closing the PR.

**Pull request closed without merging**
