### PR TITLE
Activity upload made full screen

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Improved UI of UploadActivty**

Fixes #2339 {Shifted position of progressbar in Upload activity please wait screen

What changes did you make and why?

- Changed attribute of ViewFlipper to match-parent
- Copied the content of activity_upload_top_card and activity_upload_right_card to activity_upload_bottom_card

Tested  on vivo1713 with API level 24.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@vanshikaarora Does this work for you? The layouts are not visible properly. Please post screenshots once you are able to test it.

**Comment by vanshikaarora** [comment]
I am extremely sorry for the previous commit 
I have modified the code.
Here is a preview of how the activity appears now:

whatsapp image 2019-01-30 at 6 58 33 pm
whatsapp image 2019-01-30 at 6 58 33 pm 1

**Comment by vanshikaarora** [comment]
>The progress bar is not visible in the screenshot?

@maskaravivek I haven't made any changes to the progressbar so the probably the progressbar might take a little more time to load hence not visible in the screenshot.
Or do you have any other particular opinion in mind?

**Comment by vanshikaarora** [comment]
Thanks for approving the Pull Request :)

**Comment by maskaravivek** [comment]
Kudos for squashing these bugs. 🎉

**Comment by vanshikaarora** [comment]
Thanks :)

**Pull request merged**
