### PR TITLE
Get rid of HandlerService #3555

### LINKED ISSUE #3555: Get rid of HandlerService
**Summary:** 

We have RxJava if we need to simulate a queue of work, by binding we can just pass acquire a service reference and directly invoke methods instead of using message passing.

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
**Description (required)**
Removed `HandlerService` class.
Implemented upload queue with `PublishProcessor`.

Fixes #3555 

**What changes did you make and why?**
Substituted `HandlerService` with `UploadService`.

**Tests performed (required)**
Tested betaDebug on emulator with API level 28.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Since this is one of critical areas of the code, I added 3 more reviewers.

**Comment by neslihanturan** [comment]
My tests:
Single upload worked as intended :heavy_check_mark: 
Multiple upload worked as intended :heavy_check_mark: 

Other required tests:
Nearby upload

**Comment by maskaravivek** [comment]
@VitalyVPinchuk Can you resolve the merge conflicts.

**Comment by VitalyVPinchuk** [comment]
> @VitalyVPinchuk Can you resolve the merge conflicts.

@maskaravivek Done

**Pull request merged**
