### PR TITLE
Fixes #1801  (Media details view for Browse is lacking author field)

### LINKED ISSUE #1519: Swiping featured images limited to 10 images
Steps:
1. Go to featured images
2. Touch one featured image
3. Swipe right to see the next featured image
4. Swipe again many times
5. After the 10th image, swipe does not work anymore. Subsequent images do not get loaded.
screenshot_20180515-214212

### LINKED ISSUE #1801: Media details view for Browse is lacking author field
**Summary:** 

The media details view for Browse (search > media/categories) is lacking the author field. I believe this needs to be added, otherwise we are infringing the license for images that are under an attribution license. Featured images have the author field.

@nicolas-raoul @ujjwalagrawal17 Can this be fixed urgently? I am hesitant to release the browse feature without this in place

**Steps to reproduce:** 

Browse > media > search for an image > select the image 

**Device and Android version:** 

API 24 Samsung Galaxy s7
 
 **Commons app version:** 

2.8-release 

**Screen-shots:** 

screenshot_1533548365

**Would you like to work on the issue?**

No

### LINKED ISSUE #1805: Expected adapter item count: 20, found: 30
Just happened once a few minutes ago, can't reproduce.
I was scrolling pictures in Explore (the featured pictures), and tapped on an interesting image of a mushroom.

```
08-07 19:46:09.636  5444 11908 V NetworkInterceptors: <<<<<<<<<<<<<< END OF REQUEST LOGGING [/w/api.php?titles=Commons%3ADeletion_requests%2FFile%3ARubjerg+Knude+Fyr%2C+Hj%C3%B8rring%2C+Denmark%2C+1807072231%2C+ako.jpg&action=query&format=xml] >>>>>>>>>
>>>                                                                                                                                                                                                                                                          
08-07 19:46:09.646  5444  5444 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                                                                                           
08-07 19:46:09.653  5444 11902 D CustomApiResult: API request is in.yuvi.http.fluent.Http$HttpGetRequestBuilder@7b46a36                                                                                                                                      
08-07 19:46:09.654  5444 11902 D CustomApiResult: API params are org.apache.http.params.BasicHttpParams@3871bd0                                                                                                                                              
08-07 19:46:09.711  5444  5444 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                                                                                           
08-07 19:46:09.713  5444  5444 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                                                                                           
08-07 19:46:09.740  5444  5444 D AndroidRuntime: Shutting down VM                                                                                                                                                                                            
08-07 19:46:09.742  5444  5444 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                                                                                       
08-07 19:46:09.742  5444  5444 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 5444                                                                                                                                                                     
08-07 19:46:09.742  5444  5444 E AndroidRuntime: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 20, found: 30 Pager id: fr.fr
ee.nrw.commons:id/mediaDetailsPager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter                               
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.support.v4.view.ViewPager.populate(ViewPager.java:1137)                                                                                                                                   
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1059)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:692)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:621)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-07 19:46:09.742  5444  5444 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
```
 
 **Commons app version:** 

current master with 2-8-release merged into it

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
## Fixes
- Fixes #1805 (Expected adapter item count: 20, found: 30)
- Fixes #1801  (Media details view for Browse is lacking author field)
- Fixes #1519  (Swiping featured images limited to 10 images) 

## Description (required)

- Changed parameters in API to receive image info too
- Changed visibility Conditions in render to show author name too
- notifiedViewPager onSuccess of each API response
- added listener to ViewPager to detect last page and calling API for more responses then.

Link to documentation: https://commons.wikimedia.org/w/api.php?action=help&modules=query%2Bsearch

API used: https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=iit%20ism%20dhanbad&gsrnamespace=6&gsrwhat=text&prop=imageinfo&format=xml

## Tests performed (required)

Manually Tested on API 25, with ProdDebug variant

### CODE REVIEW

**Comment by misaochan** [comment]
@ujjwalagrawal17 , as I mentioned at #1801 , could you please separate the author field PR from the other changes, rebase it on 2.8-release branch, and submit it to 2.8-release branch? As that will be going into the 2.8 release, but not the other changes. ProdRelease testing has already been done and the release is waiting. We can make an exception for the author field as it is necessary, but we don't have the time to test the additional features sorry.

**Comment by nicolas-raoul** [comment]
Just tested on master, it works great! 🙂

Le mer. 8 août 2018 à 14:00, Josephine Lim <notifications@github.com> a
écrit :

**Comment by ujjwalagrawal17** [comment]
Umm, @misaochan I can do that. But I think #1805 is also equally important. It is causing crash if you go fast and click on last image in featured image, search results, category details page.

**Comment by misaochan** [comment]
Ah I see, OK. We could get both of those in 2.8-release then? You would need to check that the other bugfixes are still relevant to that branch, as it was separated from master about a week ago.

**Comment by ujjwalagrawal17** [comment]
Also #1519 will be nice to have in release. Can I send the same PR to release after rebasing.? @misaochan

**Comment by nicolas-raoul** [comment]
#1519 and #1801 are fixed, but not #1805 it seems.
Anyway I merge to master.

**Comment by misaochan** [comment]
@ujjwalagrawal17 Sure, if you like, you can submit that tomorrow and we can include that in the next hotfix (probably will be out in the next week or two). But not the current release.

**Pull request merged**
