### PR TITLE
Refactor variable names of nearby_query.rq (#1334)

### LINKED ISSUE #1334: Refactor variable names of nearby_query.rq
**(Please don't work on this before June 2018, as the file is currently being worked on)**

Right now we have a mix of snake_case and camelCase at app/src/main/resources/queries/nearby_query.rq

Please note that refactoring must also be done in the Java source code, and tested.

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
**Description (required)**

Fixes #1334  

What changes did you make and why?

All variables were refactored to camelCase

**Tests performed (required)**

Tested betaDebug on emulator with API level 27.

### CODE REVIEW

**Comment by VitalyVPinchuk** [comment]
@nicolas-raoul Is there anything else I ought to do to have my commit merged? Or would the approved commits be merged all together later on?

**Comment by nicolas-raoul** [comment]
I don't have a development environment at the moment so we are just waiting for a volunteer to test your pull request, sorry for the delay and thanks for your understanding :-)

**Comment by nicolas-raoul** [comment]
Feel free to start working on other issues in the meantime.

**Comment by ujjwalagrawal17** [comment]
I have tested this PR. It seems to work fine.

**Pull request merged**
