### PR TITLE
Cahnge gallery icon color if it is on overlay menu

### PR DESCRIPTION
**Pull request by neslihanturan**
Fixes point 1 of #442 .
If you suggest a more clear way to solve, I would be appreciated. 
selection_011
selection_010

### CODE REVIEW

**Comment by veyndan** [comment]
How about something like [this](http://stackoverflow.com/a/13735919/3424405)?

**Comment by domdomegg** [comment]
@veyndan That's changing the color based off the theme, we need to change the color depending on whether it is in the overflow menu or not

**Comment by neslihanturan** [comment]
@veyndan Actually, our icon colors are already set with the method in stackoverflow post you showed. But it wouldn't work in our case. We need to detect if icon is on overlay menu or not.

**Comment by veyndan** [comment]
Oops sorry I misunderstood the problem. Thanks for the clarifications!

**Comment by veyndan** [comment]
Here's a suggestion that may work. If we use a Toolbar instead of the ActionBar then we can specify the theme specifically for the popup menu via `popupTheme`. Here we can change the icon to the opposite icon.

**Comment by veyndan** [comment]
It appears that we aren't using `AppCompatActivity` consistently throughout the codebase, so I need to convert that before working on the rest.

If we need this solution straight away then I guess it'd be fine to merge and then a better solution can replace it later on. I don't know how urgent this is.

**Comment by misaochan** [comment]
Unless there are objections, I would go with merging as soon as possible, so we can get the new UI into beta on schedule.

**Comment by veyndan** [comment]
Having a hardcoded value of 360 to check if there is enough room for two icons feels a bit hacky, but this will be solved in a later commit. Apparently time is of the essence, so thanks for the speedy fix!

**Pull request merged**
