### PR TITLE
Fixed the crashing on uploading media from camera

### LINKED ISSUE #4238: App crashes on trying to upload a media directly from camera.
**Summary:** 

On selecting a image clicked from the camera for upload, the app crashes.

**Steps to reproduce:** 

• Click on the **+** (floating action button) icon in contributions tab.
• Select camera from there.
• Click a photo and select that photo.
• App will crash there.

**System logs:**

```
2021-02-17 15:44:31.801 16499-16499/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 16499
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.contributions.MainActivity$ActiveFragment.name()' on a null object reference
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:238)
        at android.app.Activity.performSaveInstanceState(Activity.java:2088)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5419)
```

**Device and Android version:** 
Redmi Note 7S (Android 10)

**Commons app version:** 
betaDebug master (3.0.0-debug-master~7cb5ff916)

**Screenshots**

https://user-images.githubusercontent.com/65870389/108192667-8f3b4480-713a-11eb-9e13-d450de27d5a1.mp4

**Would you like to work on the issue?**
**Yes**, I want to work on this issue.

### PR DESCRIPTION
**Pull request by mrudultora**
**Description (required)**

Fixes #4238 

What changes did you make and why?
Added a **if** block to check that `activeFragment != null`

**Tests performed (required)**
Tested {build variant- betaDebug} on {Redmi Note 7S} with API level {29}.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Could you please post a video showing how the app behaves with this PR, when uploading media from camera?
Thanks!

**Comment by mrudultora** [comment]
@nicolas-raoul Attaching the video (I would like to inform you that video is bit longer than usual as my phone was lagging). Please move to **0:34** in video.


https://user-images.githubusercontent.com/65870389/108382738-21247980-722f-11eb-8a44-c36d5cd1ec90.mp4

**Review by nicolas-raoul — APPROVED** [review]
No problem at all, good screencast!
It is great (although a bit surprising to me) that upload seems to continue as usual, even though there was an unexpected null value.
I will approve from my non-technical point of view, as the bug seems solved, but **I will let someone else check whether the null value is best handled like** this or not (as it might be a symptom of a wider root problem).
Cheers!

**Comment by mrudultora** [comment]
@nicolas-raoul Would you please clarify the meaning of this line,

> I will let someone else check whether the null value is best handled like this or not (as it might be a symptom of a wider root problem).

If you will explain me a bit about the null value issue I would like to work on that issue also :-)

**Comment by nicolas-raoul** [comment]
Sorry for not being clear. I am just asking other reviewers to double-check the code :-)

**Comment by mrudultora** [comment]
@neslihanturan Okay! I will update you with all the cases as soon as possible.

**Comment by neslihanturan** [comment]
Hey  @mrudultora , did you have any time to test this one further? Even if the fix seems harmless, I would like to make sure if consequent operations continues without problem after this fix. However, since I am not able to reproduce this issue, I can not test your PR properly. So 
Option 1, you can test it further and share the result with us, so that we can decide to merge or not.
Option 2, we can close this PR and hope someone else also experience this issue 

To clarify, the thing I want to make sure is with the null check here, after the line is not operated since activeFragment was null, will you be able to move between tabs, complete your upload or select a media to see media details and come back.

**Comment by neslihanturan** [comment]
A kindly reminder @mrudultora :) Please let us know if you are no more interested with the issue.

**Comment by mrudultora** [comment]
Hi @neslihanturan, I will not be able to work on this for next few days. Please feel free to re-assign it to someone else :)

**Comment by neslihanturan** [comment]
Thanks for the update @mrudultora !:) So I am closing this PR so that people will know we need further effort on this.

**Pull request closed without merging**
