### PR TITLE
With attribution enabled for OSM

### LINKED ISSUE #2911: No OpenStreetMap attribution
The map in the Nearby tab has no OSM attribution. OSM requires attribution in a very specific way: in the map frame, as "© OpenStreetMap Contributors".

See https://www.openstreetmap.org/copyright

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2911

What changes did you make and why?

Enabled attribution as per https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-android

**Tests performed (required)**

Tested on prodDebug

**Screenshots showing what changed (optional - for UI changes)**

device-2019-06-05-194524

### CODE REVIEW

**Comment by neslihanturan** [comment]
I don't know why is travis still in progress. Will merge after it is done.

**Comment by maskaravivek** [comment]
Actually travis has passed but somehow it wasn't able to notify Github about it. I saw the same happening for a few other PRs. 

Screenshot 2019-06-10 at 9 55 01 PM

**Comment by neslihanturan** [comment]
Weird... What should be our policy for such cases? I will go ahead and merge this time since changes probably safe.

**Comment by misaochan** [comment]
I think it's OK to merge as long as the Travis site itself says the build passed.

**Pull request merged**
