### PR TITLE
WIP Use beta commons site when in debug mode

### PR DESCRIPTION
**Pull request by addshore**
This means people don't have to worry about uploading
images / maybe doing bad things while testing and
debugging.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
People debugging category suggestion might want to turn this off, though (on beta there probably are not enough nearby images to make relevant suggestions)

**Comment by addshore** [comment]
@nicolas-raoul you make a good point.

In debug mode this could allow the user to choose either beta or the live site.

TODOs:
 - This probably needs to save the accounts separately on the phone to avoid confusion
 - Make it clear on the login screen which site is being logged into

**Comment by nicolas-raoul** [comment]
I am not sure this special case (categorization testing) is worth developing a UI to choose which site to use. How about a true-by-default UPLOAD_TO_BETA_WHEN_DEBUGGING constant that developers could manually set to false if they wish?

**Comment by whym** [comment]
Is it possible to a flavor for that? Because flavors can have different application IDs, I believe they can have separate account configurations.

**Comment by addshore** [comment]
A product flavour sounds like a great idea.
Right now this app only have one flavour

**Comment by misaochan** [comment]
@addshore , can we merge this? Folks would like to have it for testing.

**Comment by whym** [comment]
Using flavors seems like a better solution in the long term, but nicolas-raoul's idea of adding a variable to switch is much simpler and would work for now.

Also, before merging, there is a conflict to solve in CommonsApplication.java.

**Comment by neslihanturan** [comment]
Can we close this after #857 ?

**Comment by misaochan** [comment]
Yup, let's close it :)

**Pull request closed without merging**
