### PR TITLE
unformatted search text field for depicts and categories search field of upload wizard

### LINKED ISSUE #4722: Unformat text pasted into depicts search field
Steps:
1) Copy some formatted text from another app, for instance an article title in the Wikipedia app
2) Paste into the "Depicts" search field of the Upload Wizard.
3) Problem: Pasted text looks huge. It should be the same size as when typing text using the keyboard

Same for categories search.

The solution at #4514 might give clues.

adb
.

### PR DESCRIPTION
**Pull request by KhyatiSaini**
**Pasted text into the ```` depicts ```` and ```` categories ```` search field is unformatted**

Fixes #4722 

Replaced the ```` TextEditInputText ```` widget with ```` PasteSensitiveTextInputEditText ```` 
(PasteSensitiveTextInputEditText widget: [pull request](https://github.com/commons-app/apps-android-commons/pull/4667))
<br>
Tested on Realme Narzo 20 with API level 30.

### CODE REVIEW

**Review by neslihanturan — APPROVED** [review]
Thanks and congrazt for your first PR @KhyatiSaini :)

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Oh, this code breaks some tests, they should be fixed before I merge them. You can see which tests are failing by running tests

**Comment by KhyatiSaini** [comment]
> Oh, this code breaks some tests, they should be fixed before I merge them. You can see which tests are failing by running tests

oh sorry, I'll look into the issue and fix it soon.
thanks!

**Comment by KhyatiSaini** [comment]
I've fixed the issue by replacing the type of search text field from ```` TextInputEditText ```` to ```` PasteSensitiveTextInputEditText ```` in the files: ```` UploadCategoriesFragmentUnitTests.kt ```` and ```` DepictsFragmentUnitTests.kt ````. Can you please check it once. Thanks

**Review by neslihanturan — APPROVED** [review]
Thanks @KhyatiSaini :)

**Pull request merged**
