### PR TITLE
Fix Crash in LocationPickerActivity when device configuration is changed

### LINKED ISSUE #5474: [Bug]: App Crashes when Switched Between Dark/Light Mode in Location Picker Activity
### Summary

The App Crashes when you switch between Light/Dark mode on your device in the Location Picker Activity. I believe it will crash in any Configuration change on your device, Like changing Font-size Similar to issue #5437 opened by @nicolas-raoul , I think we need to handle configuration change for this activity , I will be doing that in my next PR

### Steps to reproduce

1. Open the App
2. Go to any of your Contributions
3. Select Edit Location Icom
4. Switch Between Light/Dark Mode on your Device

### Expected behaviour

App Should not Crash

### Actual behaviour

App Crashes

### Device name

Xaomi 11 Lite NE

### Android version

13

### Commons app version

4.2.1-debug-main

### Device logs

_No response_

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/f2015614-6b4c-4b30-a5bf-dbcda5f4eea0

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5474 

What changes did you make and why?
Identified and fixed a critical issue in the open-source project related to the ```LocationPickerActivity```.
The crash occurred when the device configuration changed, specifically during UI mode switches (dark to light or light to dark mode)

Investigated the crash root cause, which was tied to how the activity handled UI mode changes.

**Tests performed (required)**

Tested 4.2.1-debug on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

https://github.com/commons-app/apps-android-commons/assets/126143257/e44b401f-3fed-4982-b468-be3401fd0803

### CODE REVIEW

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review this PR

**Comment by shashankiitbhu** [comment]
Hi @nicolas-raoul , is there any change required in this PR?

**Comment by ShashwatKedia** [comment]
**Student Review**

Screencast of Before:
https://drive.google.com/file/d/1w2wtnYh1ax3mIMfRStepET9Zl7efmLNl/view?usp=share_link

Screencast of After:
https://drive.google.com/file/d/1w9F14a22OPhHsAIgxmeHvvEa-XsV1KjL/view?usp=share_link

The crash does not happen after merging this PR, but a bug still remains that if I move the marker to some other position and then change the configuration, then that change is lost (can be seen in the 'After Screencast' ). I've added some minor code-style and test-related comments, rest all looks good to me :)

**Comment by shashankiitbhu** [comment]
> 1. If I move the marker to some other position and then change the configuration, then that change is lost (can be seen in the 'After Screencast' ). 

This one is not a bug as you haven't selected any location , you are just hovering over it so it is not saved anywhere.

**Comment by shashankiitbhu** [comment]
@ShashwatKedia Thanks for reporting the Null Pointer Exception, fixing it now

**Comment by shashankiitbhu** [comment]
@nicolas-raoul @RitikaPahwa4444 can you review and merge this , thanks

**Review by nicolas-raoul — APPROVED** [review]
Tested, fixes the crash.
Thanks!

**Pull request merged**
