### PR TITLE
Set height of ReviewViewPager to wrap_content

### PR DESCRIPTION
**Pull request by Szymon20000**
Resolves : https://github.com/commons-app/apps-android-commons/issues/2908

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Cool thanks!
Would you mind posting a screenshot? :-)

**Comment by Szymon20000** [comment]
I think it just looks good and we don't need another ScrollView. The ViewPager height is always adjusted to the content height. 
@nicolas-raoul It's not easy to show the effect cause you need to scroll to see all categories and not all photos have so many of them. I can try but I think it will be easier if you just checkout my branch.

**Comment by ashishkumar468** [comment]
@Szymon20000 IMO,  issue could be fixed by adjusting view boundaries, using a relative or constraint layout, instead of capping the height of the view pager, could you elaborate that exactly why  do we need to play with the height of the view pager?

**Comment by Szymon20000** [comment]
[First Page](https://drive.google.com/file/d/1TY3ztq67T5eAxwcOAV9RgEzE-_0edXpV/view)
[Category page before scroll(I scrolled it a little bit by accident)](https://drive.google.com/file/d/19Jd0SM6pry02ctAeRrpnmnDTsv7c8ZI7/view)
[scrolled category page](https://drive.google.com/file/d/1iYry6FJrLzQUrrJkEnGZzh93wwZqeJzt/view)

**Comment by Szymon20000** [comment]
@ashishkumar468 We have everything in ScrollView. It's natural for me that ViewPager should present all its content.

**Comment by Szymon20000** [comment]
Guys?

**Comment by Szymon20000** [comment]
@maskaravivek Probably I didn't describe properly what I did. I changed your hardcoded height of ViewPager(300dp) to warp_content and also added a necessary code to make it work because Android wrap_content doesn`t change a view height dynamically.

**Comment by neslihanturan** [comment]
Hi @Szymon20000 thanks for your contribution, seems like there was some technical doubts about using this technique. On the other hand a refactor is made on these classes, and it solved this issue too. So we can close this PR, please feel free to reopen if you have further comments.

**Pull request closed without merging**
