### PR TITLE
#3120 Suggest categories based on depictions 

### LINKED ISSUE #3120: Suggest categories based on depictions
In the Upload activity, after the user inputs that her picture depicts an [elephant](https://www.wikidata.org/wiki/Q7378), in the next screen (category selection) we should append to the list of suggested categories, the category associated with that Wikidata item.

https://www.wikidata.org/wiki/Q7378 -> Retrieve the P373 (Commons category) property -> Suggest https://commons.wikimedia.org/wiki/Category:Elephants

If the user has selected several Wikidata items, the corresponding categories should all be suggested.

### PR DESCRIPTION
**Pull request by macgills**
**Description (required)**

Fixes #3120 

What changes did you make and why?
- fetch p373 for selected Depictions

Note: this is based off of #3735 and will be marked draft until that is resolved

**Tests performed (required)**

Tested ProdDebug on Nexus5x with API level 27

**Screenshots (for UI changes only)**

image

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Wonderful, it works great! (after merging master into this branch so that I can find depictions)
I also checked that it works when selecting several items (it suggests each relevant category).

**Comment by neslihanturan** [comment]
Thank you @macgills , I have approved the code but my tests failed. It does not propose depictions to me, if I wrote it down it says no depiction is chosen, so I can't continue to the further steps. Possibly related log:
```
2020-05-20 12:17:21.506 11651-11651/fr.free.nrw.commons E/DepictsPresenter$onAttachView: kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.upload.structure.depictions.DepictModel$searchAllEntities$1$2.apply(DepictModel.kt:33)
        at fr.free.nrw.commons.upload.structure.depictions.DepictModel$searchAllEntities$1$2.apply(DepictModel.kt:14)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14826)
        at io.reactivex.Flowable.subscribe(Flowable.java:14773)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:129)
        at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.test(BehaviorProcessor.java:640)
        at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.emitFirst(BehaviorProcessor.java:586)
        at io.reactivex.processors.BehaviorProcessor.subscribeActual(BehaviorProcessor.java:250)
        at io.reactivex.Flowable.subscribe(Flowable.java:14826)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
        at io.reactivex.Flowable.subscribe(Flowable.java:14826)
        at io.reactivex.Flowable.subscribe(Flowable.java:14773)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
device-2020-05-20-121825

**Comment by macgills** [comment]
image

@neslihanturan are you sure you pulled the latest code?

image

**Comment by neslihanturan** [comment]
image

You are right I was at one of the older commits :( Sorry for the confusion, it works like a charm

**Pull request merged**
