### PR TITLE
Remove Image From Upload Wizard

### LINKED ISSUE #5630: Option to Remove Specific Images from Upload Wizard
### What is the user problem or growth opportunity you want to see solved?

Currently When Choosing to Upload Multiple Images at once you have to Upload All Images that You have selected but Let's Consider a case where I have Selected 1 Wrong Image without realizing that is in the Middle, In this case, all My Changes Will be lost If Chose to Not Upload this Image.

### How do you know that this problem exists today? Why is this important?

Upload Multiple Images in this app is very common and it's also common to make mistakes while selecting Images but users should not have to reselect all the Images in order to remove that Image.

### Who will benefit from it?

All Commons App Users

### Anything else you would like to add?

To Solve this, There should be a Cross Icon at the Top Right corner of each Image That Will allow us to remove that Image without affecting the rest. 

WhatsApp Image 2024-03-18 at 5 24 30 PM

I have some interesting mockups to Improve this Overall Process of Removing Specific Images from Upload Queue, will be showing them soon in the discussion

I am working on this

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5630 

What changes did you make and why?
Added Option to Remove Image From Upload Wizard by clicking on a Cross Icon

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

WhatsApp Image 2024-03-22 at 1 41 07 AM

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Edge case bug: When removing the last pic in a multi-upload, then going to previous, top bar not visible anymore.

https://github.com/commons-app/apps-android-commons/assets/99590/8ac8d9a9-5fc0-4f79-a8ec-ee3fb2b8aea4

**Comment by shashankiitbhu** [comment]
@nicolas-raoul good catch, I'll look into it now, thanks

**Comment by shashankiitbhu** [comment]
@nicolas-raoul fixed it, Please Review

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Another small bug:

https://github.com/commons-app/apps-android-commons/assets/99590/d563176c-db0b-4c29-b0d8-2e775a049f26

**Comment by shashankiitbhu** [comment]
@nicolas-raoul thanks for spotting it, fixed it in the latest commit, Please Review

**Comment by shashankiitbhu** [comment]
https://github.com/commons-app/apps-android-commons/assets/126143257/22c3812c-a968-49a5-8ae8-f08dbd470b77

**Review by nicolas-raoul — APPROVED** [review]
Working great!

**Pull request merged**
