### PR TITLE
Fix 2FA login

### LINKED ISSUE #3144: 2FA logins not working in 2.11
A report from one of our users:

I had trouble with the app and then uninstalled and reinstalled but I simply cannot log in. (I have 2FA enabled). I can login via browser the app simply says failed login (and then too many failed logins)

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #3144

### CODE REVIEW

**Comment by misaochan** [comment]
Tested this with Nexus S API 27 emulator. My 2FA login works well, thanks!

**Comment by Steinsplitter** [comment]
For me it isn't working. The last version on the Play Store is the fixed one, right?

When i login with correct password:
c (1)

When i login with a wrong pw:

c (2)

**Comment by misaochan** [comment]
@Steinsplitter are you registered for beta testing? v2.12 is still in beta, although it should be going out to production shortly.

**Comment by Steinsplitter** [comment]
@misaochan Nope, will do. Thx.

**Comment by misaochan** [comment]
Thanks, let us know if beta still doesn't work for you.

**Pull request merged**
