### PR TITLE
Tech Improvement; Remove Hard Coded Column Indices. issue #1119

### PR DESCRIPTION
**Pull request by hismaeel**
issue #1119 
Best :-)

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks a lot @hismaeel , but I get this error : 

> Process: fr.free.nrw.commons.debug, PID: 23975
                                                                           java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                               at android.database.CursorWindow.nativeGetString(Native Method)
                                                                               at android.database.CursorWindow.getString(CursorWindow.java:434)
                                                                               at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:62)
                                                                               at android.database.CursorWrapper.getString(CursorWrapper.java:114)
                                                                               at fr.free.nrw.commons.contributions.ContributionDao.fromCursor(ContributionDao.java:133)
                                                                               at fr.free.nrw.commons.contributions.ContributionsListAdapter.bindView(ContributionsListAdapter.java:32)

Are you able to run it with no error?

**Comment by maskaravivek** [comment]
This might be helpful. @hismaeel 

https://blog.tapreason.com/how-to-resolve-java-lang-illegalstateexception-couldnt-read-row-0-col-y-from-cursorwindow-make-sure-31c58a2b3d83

**Comment by hismaeel** [comment]
Thanks @maskaravivek Oh I see. But I would have to add the entire code for creating contribution in each block of the try catch. This is very verbose. So I thought just make check if getCoulmnIndex() returns -1. If so, make index 15. 
Thanks :-)

**Comment by maskaravivek** [comment]
@hismaeel  If you have made a new PR for the same fix please close this one.

**Comment by hismaeel** [comment]
@maskaravivek  @neslihanturan  Ah sorry this is from days back when I was fiddling around with VCS. I have reforked my repository since then. Please close this request I'll make a new one. Thanks

**Pull request closed without merging**
