### PR TITLE
Fix - No Precise Error Message After Error Due to Password Change

### LINKED ISSUE #5642: [Bug]: No Precise Error Message After Error Due to Password Change
### Summary

@whym @sivaraam @nicolas-raoul 
This Issue was first reported for Uploading Contributions at #5522 and Upon Further Investigation it was found that other issues are Occurring too After the Password is changed from the Commons Website.

What is happening is that the user's login is no longer valid and the User is required to log in again but the app gives no Error Message or Indication as to what went wrong.

As discussed in #5522 and more in #5544 User Should be Redirected to the Login Screen to log in Again.

This Issue aims to fix the following :

- [x]  Sending Thanks In Review Activity, Nominating "No" in Review Activity
- [x]  Sending "Thanks" for Contributions
- [x]  Editing Depictions, Categories, Description, Coordinates for Contributions
- [x]  Mark Notifications as Read 

All these errors are arising due to the same reason and that's why I have made a Single Issue to Cover all this and will complete this in a Single PR, as discussed here #5522

### Steps to reproduce

1. Open the Open
2. Select any Contribution and try to send "Thanks"
or
2. Select any Contribution and try to Edit Categories , depictions, descriptions or Coordinates
or
2. Open Review Activity
3. Nominate "No"  or Send "Thanks" to the Author

### Expected behaviour

There should Precise Error Message as to why the action that the user is trying to perform has failed (Which in all of the above cases is that the User's Password has Changed making their current login Invalid) and it should redirect user to the Login Page.

### Actual behaviour

There is no Error Message and All these Operations Just Fail Without any Message Leaving users Confused.

### Device name

Xaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Device logs

```
java.lang.RuntimeException: App believes we're logged in, but got anonymous token.
                                                                                                    	at fr.free.nrw.commons.auth.csrf.CsrfTokenClient.getTokenBlocking(CsrfTokenClient.kt:51)
                                                                                                    	at fr.free.nrw.commons.actions.PageEditClient.prependEdit(PageEditClient.kt:60)
                                                                                                    	at fr.free.nrw.commons.delete.DeleteHelper.delete(DeleteHelper.java:106)
                                                                                                    	at fr.free.nrw.commons.delete.DeleteHelper.makeDeletion(DeleteHelper.java:67)
                                                                                                    	at fr.free.nrw.commons.delete.DeleteHelper.lambda$askReasonAndExecute$5$fr-free-nrw-commons-delete-DeleteHelper(DeleteHelper.java:223)
                                                                                                    	at fr.free.nrw.commons.delete.DeleteHelper$$ExternalSyntheticLambda6.call(Unknown Source:8)
                                                                                                    	at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3603)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at javaa.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
```

### Screen-shots

_No response_

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5642 

What changes did you make and why?

I identified the source of all these Errors (Which is No Accurate Information Provided to the User as to why an operation has failed because of a Single Type Of Exception that is getting lost due to Multiple layers of method calls), Hence I made a separate Exception Class for that Exception called - `IvalidLoginTokenException` so that it is easier to Identify and Propagate it. 

Then I handled that Exception for each of the cases and since all of these Exceptions are the same their action is also Similar which is to Notify the user that **Their Login Session has Expired Due to Password Change and They Must Login Again**

**Tests performed (required)**

Tested on Xiaomi 11 Lite NE  with API level 33.

### CODE REVIEW

**Comment by shashankiitbhu** [comment]
@nicolas-raoul @sivaraam @whym Please Review this PR

**Comment by shashankiitbhu** [comment]
@nicolas-raoul @psh @whym @sivaraam Fixed all merge conflicts Please Review

**Review by nicolas-raoul — APPROVED** [review]
Working great!
After changing password and trying "thank":

**Comment by nicolas-raoul** [comment]
Even though the above says `1 check passed : Run tests and generate APK`, somehow the two unit tests below started failing in branch `main` from the present commit.
```
fr.free.nrw.commons.description.DescriptionEditActivityUnitTest > testUpdateDescription FAILED
    java.lang.reflect.InvocationTargetException at DescriptionEditActivityUnitTest.kt:120
        Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException at DescriptionEditActivityUnitTest.kt:120

fr.free.nrw.commons.description.DescriptionEditActivityUnitTest > testOnSubmitButtonClicked FAILED
    java.lang.reflect.InvocationTargetException at DescriptionEditActivityUnitTest.kt:132
        Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException at DescriptionEditActivityUnitTest.kt:132
```
Any idea what might be causing this, or even how to fix the tests? Thanks! :-)

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Seems like this error is due to Unchecked Exception at editDescription() Method that is added later on in another commit, looking into it.

Should I create a new PR for the fix or commit here?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul added a PR fixing this #5685

**Pull request merged**
