### PR TITLE
Add adaptive icon foreground and background designs

### PR DESCRIPTION
**Pull request by thedeadline**
Relates to issue #868 . Add adaptive icon foreground and background files with short video of what it looks like implemented.

### CODE REVIEW

**Comment by janpio** [comment]
(Add `.mpg` to the video file in `design` so a media player can read it)
(The video should probably not be part of the PR and repo, but just link to an external host)

**Comment by misaochan** [comment]
The new icon files look good to me. :)

I agree that the video should probably not be included directly in our repo though.

**Comment by thedeadline** [comment]
Thanks for the feedback! I deleted the video file. Where should I put the link? Here, on the issue, or somewhere else?

**Comment by nicolas-raoul** [comment]
Please copy the SVG file itself into the Git repository's [design](https://github.com/commons-app/apps-android-commons/tree/master/design) folder, thanks!

**Comment by thedeadline** [comment]
Sure, I can add the regular SVG file that you linked to in the issue to design folder, just keep in mind that the adaptive logo designs are currently pngs because it was created before I had the link to the SVG. 

Turned demo into gif here so it'll be easier see how it should look when implemented: https://imgur.com/a/F1gV0

**Comment by misaochan** [comment]
Nice, thanks @thedeadline !

**Pull request merged**
