### PR TITLE
issue #2446 fixed. Night mode: Achievements

### LINKED ISSUE #2446: Night mode: Achievements
white text difficult to read on silver background.
screenshot_20190213-122205

### PR DESCRIPTION
**Pull request by aniketnath**
Description :

Fixed #2446 Night mode: Achievements

What changes did you make and why?

I have changed the background and text colours of the achievement activity

screenshot_2019-02-15-11-47-37-871_fr free nrw commons beta 1

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Looks good, thanks! :-)

**Comment by aniketnath** [comment]
thank u

**Comment by aniketnath** [comment]
@maskaravivek This issue is also solved will you merge this commit?

**Comment by maskaravivek** [comment]
Thanks for the PR @aniketnath. 

Am not sure if this background looks good above the circular progress bars. 

@nicolas-raoul Can you confirm if it looks good when the circular progress bars are visible? 

device-2019-02-15-173604

**Pull request merged**
