### PR TITLE
Fix#2761: Loading of different image on Peer Review on rotation

### LINKED ISSUE #2761: Peer Review loads different image on rotation
**Summary:** 

After rotating the device peer review Activity is loading a different image 

**Steps to reproduce:** 

Rotate screen on Peer Review activity

**Device and Android version:** 

Motorola Moto G5 plus on API 24
 
**Commons app version:** 

Latest master

ezgif com-video-to-gif

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sp2710**
**Description (required)**

Fixes #2761 

**Tests performed (required)**

Tested ProdDebug on Motorola Moto G5 plus with API level 24.

ezgif com-video-to-gif(2)

### CODE REVIEW

**Comment by sp2710** [comment]
@neslihanturan So should I create a new ViewModel class and use it for retaining views?

**Comment by neslihanturan** [comment]
No it is for carrying large objects. You should use  onSaveInstanceState()

**Comment by sp2710** [comment]
@neslihanturan I have done the changes and have updated the PR.

**Comment by neslihanturan** [comment]
This passes from my tests but there is a point I recognized, and want to wait for review from another person too. Since 
```
    @SuppressLint("CheckResult")
    private void updateImage(String fileName) {
...
        this.fileName = fileName;
...
        reviewPager.setCurrentItem(0);
```

how we don't start from the first question each time?

**Comment by neslihanturan** [comment]
Hi @sp2710 , closing this one since the Review Activity implementation is changed since then and a suitable solution is available. Thanks for your contribution.

**Pull request closed without merging**
