### PR TITLE
fixing issue #2044

### LINKED ISSUE #2044: 2.9.0: Unable to exit app after going to notifications activity
**Summary:**
I am unable to exit the app using the back button just after I go to the notifications activity. Hitting the back button cycles through the notification and main screen infinitely.

**Steps to reproduce:** 
1. Open the app
2. Tap on the notification icon (left end of the top bar)
3. Hit back (should have come to the main screen)
4. Hit back to exit the app
5. Hit back agian

**Observation**
When I hit back in steps 4 I am taken back to the notification activity. In step  5, I'm taken back to home screen. This goes on infinitely and I'm unable to exit the app. This seems very odd.

**Device and Android version:** 
Galaxy J1 ace running Android 5.1.1 (stock)

**Commons app version:** 
2.9.0

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by sp2710**
Fixes #2044 2.9.0: Unable to exit app after going to notifications activity

What changes did you make and why?
Added finish() inside onBackPressed() method in app/src/main/java/fr/free/nrw/commons/notification/NotificationActivity.java

Tested on Motorola Moto g(5) plus with API level 24

### CODE REVIEW

**Comment by domdomegg** [comment]
This builds on #1995. This does fix #2044, but why was the onBackPressed method overridden anyways - @neslihanturan? The back button seems to work fine for me in commit `629bff59` (the one before #1995 was merged).

**Comment by sp2710** [comment]
I tried to remove onBackPressed method. In that case app exits directly from notification activity and does not turns you back to main activity

**Comment by domdomegg** [comment]
Doing some testing, if opened via the nav drawer there are no issues. If opened via the menu bar it does seem to get stuck in a stack.

Nav drawer:
navdraw

Menu bar:
menubar

**Comment by domdomegg** [comment]
Okay I think I've fixed the root cause in `MainActivity.java`. Will open a PR in a bit. Apologies for kinda overwriting your work.

**Pull request closed without merging**
