### PR TITLE
Refactor: wikidta models

### PR DESCRIPTION
**Pull request by ben-mathu**
Part of an ongoing code refactoring to move all models to a common models package.

Fixes #4782

Moved wikidata models to data.models package.

Tested debug on Pixel 4 (Emulator) with API level 30.

### CODE REVIEW

**Comment by ben-mathu** [comment]
There is an issue with the code in master @madhurgupta10

**Comment by madhurgupta10** [comment]
> There is an issue with the code in master @madhurgupta10

Correct, I have created an issue for this (https://github.com/commons-app/apps-android-commons/issues/4927) hope it gets resolved soon.

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Still, there is this empty .jpg file, seems irrelevant

**Comment by neslihanturan** [comment]
Hi, is this PR sleeping @ben-mathu ?:)

**Comment by psh** [comment]
This (and the other 10 PR's associated with refactoring model classes) seem to have stalled since February.  Is this work that is wanted or fair to call it abandoned?  If the work is needed, you want me to pull the changes onto a single *feature branch* get the tests cleaned up and submit a single PR that could be reviewed and merged so these 11 can be closed?

**Comment by misaochan** [comment]
Hi @psh , nice to see you again! :) Unfortunately testing and reviewing large refactors is probably not something that we have the capacity for at the moment. As the PR authors have not gotten back to us, I would actually suggest closing all the stale PRs, and we can revisit the issue and take up your offer in the future if we have a reviewer who can volunteer their time for it. @neslihanturan what do you think?

**Comment by psh** [comment]
Closing: 2 years old and looks abandoned.

**Pull request closed without merging**
