### PR TITLE
Custom picker: Show differently pictures that are currently being uploaded

### LINKED ISSUE #5277: Custom picker: Show differently pictures that are currently bing uploaded
### What is the user problem or growth opportunity you want to see solved?

After a day out, I usually have hundreds of pictures to uploads, that I split in multi-uploads of around 10 to 30.

To save time, I always fill metadata for the next upload while the previous is still uploading.

Problem: When choosing pictures, I often do not remember up to what picture I have uploaded.

Similarly to how the app shows what pictures have been uploaded already (and what pitures are not for upload), it would be great if the app could show differently (for instance with a ⬆️ icon overlay in the bottom right corner) pictures that are currently being uploaded.

### How do you know that this problem exists today? Why is this important?

Allows user to not lose time thinking, or miss some pictures

### Who will benefit from it?

_No response_

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5277 

What changes did you make and why?

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
I keep getting this crash with this branch:

https://github.com/commons-app/apps-android-commons/assets/99590/d1058889-7352-4e5f-b31d-fea5922fd778

```
STACK_TRACE=java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.kt:435)
at androidx.room.RoomDatabase.query(RoomDatabase.kt:476)
at androidx.room.util.DBUtil.query(DBUtil.kt:75)
at fr.free.nrw.commons.contributions.ContributionDao_Impl$7.call(ContributionDao_Impl.java:1467)
at fr.free.nrw.commons.contributions.ContributionDao_Impl$7.call(ContributionDao_Impl.java:1464)
at androidx.room.RxRoom$5.subscribe(RxRoom.java:232)
at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
at io.reactivex.Single.subscribe(Single.java:3603)
at io.reactivex.Single.blockingGet(Single.java:2834)
at fr.free.nrw.commons.customselector.ui.selector.ImageFragment.handleResult(ImageFragment.kt:272)
at fr.free.nrw.commons.customselector.ui.selector.ImageFragment.onCreateView$lambda$1(ImageFragment.kt:203)
at fr.free.nrw.commons.customselector.ui.selector.ImageFragment.$r8$lambda$S7kzNRAlIUqfrtaQwFc4UhtsOKM(Unknown Source:0)
at fr.free.nrw.commons.customselector.ui.selector.ImageFragment$$ExternalSyntheticLambda0.onChanged(Unknown Source:4)
at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Would you mind checking what might be causing the crash? Thanks!

**Comment by shashankiitbhu** [comment]
Sure

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I Fixed the crash,  Please Review

**Review by nicolas-raoul — COMMENTED** [review]
Thanks for fixing the crash!
I tested like this:
1. Launch the upload of a picture
2. Immediately go to the custom picker. Uploading overlay unfortunately not shown
3. Go back to contributions
4. Go to the custom picker again. This time the uploading overlay is visible.

Any idea why the uploading overlay was not visible at step 2?
Thanks!

**Comment by shashankiitbhu** [comment]
@nicolas-raoul did that Fail while the custom Image Picker?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Fixed it to handle all cases, Please Review

WhatsApp Image 2024-03-17 at 8 56 49 PM

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review and Let me know if these changes works as Intended, thanks

**Comment by nicolas-raoul** [comment]
Ah sorry it was my mistake, I can see the white arrows now :-)

**Comment by nicolas-raoul** [comment]
I also see unnecessary arrows on pics that I uploaded several days ago. Any idea why?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Thanks for spotting the issue, fixed it in the latest commit, please review, thanks

**Comment by nicolas-raoul** [comment]
The arrows disappear when disabling then enabling "Show already actioned pictures".

By the way, if not difficult: Ideally pictures that are being uploaded should be hidden when "Show already actioned pictures" is disabled. That would allow the user to focus on pictures that need to be uploaded from now. 🙂 That can be a different GitHub issue.

https://github.com/commons-app/apps-android-commons/assets/99590/3bc55b44-9df7-4850-a4f4-1c8a452a3c86

**Comment by shashankiitbhu** [comment]
> By the way, if not difficult: Ideally pictures that are being uploaded should be hidden when "Show already actioned pictures" is disabled. That would allow the user to focus on pictures that need to be uploaded from now. 🙂 That can be a different GitHub issue.

@nicolas-raoul 
That's a great idea, I think I can fix that in this PR only (no need for a new Issue), that would save quite some time and will also make reviewing easier.

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I have completed following in above commits:

1. Fixed this Issue
> The arrows disappear when disabling then enabling "Show already actioned pictures".

2. Added this Functionality
> Ideally pictures that are being uploaded should be hidden when "Show already actioned pictures" is disabled.

Please Review and Merge, Thanks

**Review by nicolas-raoul — APPROVED** [review]
It is working great now, thanks a lot!

**Pull request merged**
