### PR TITLE
Underscore in author name fix.

### PR DESCRIPTION
**Pull request by hoplite390**
Fix for issue with underscore being inserted into username.

Fixes #{#1901} {Issue with underscore being inserted into username}

What changes did you make and why?
After login store string with username without replacing spaces with underscore and passing this string to CurrentAccount as Bundle() in 3rd parameter userdata.

So it can be used when we need authors name afterwards.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hi @hoplite390 , sorry for late testing but, underscore is still there in my test. Do you have any suggestion?:

image

**Comment by neslihanturan** [comment]
Sorry, I misunderstood the issue first. But then I tested uploads, still my username has underscore on uploads.

image

**Comment by hoplite390** [comment]
@neslihanturan maybe you can help me to test it, or at least please write me how you managed to upload picture, because lately (after pulling changes from master to update my fork) im facing "Failed" when i try to do new upload ether on my real phone or emulator (Nexus 27).

**Comment by neslihanturan** [comment]
Fails are a known issue:/ You can log out ad re-log in. This generally solves upload fails. Surely I can help with testing. Do you need logs, etc?

**Comment by maskaravivek** [comment]
@hoplite390 If you share logcat, we might be able to help you with your uploads issue. :)

**Comment by hoplite390** [comment]
(Yeah sorry about that i should have done that in 1st place)
From emulator Nexus 5x api 27
```
2018-12-01 16:31:14.795 1412-1660/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-12-01 16:31:15.128 1412-1424/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-12-01 16:31:24.541 1595-1608/? E/memtrack: Couldn't load memtrack module
2018-12-01 16:31:25.464 26406-26406/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:31:34.647 1595-1608/? E/memtrack: Couldn't load memtrack module
2018-12-01 16:31:37.363 26406-26406/fr.free.nrw.commons.beta E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2018-12-01 16:31:37.364 26406-26406/fr.free.nrw.commons.beta E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2018-12-01 16:31:43.682 26406-26406/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:31:44.400 1412-1660/? E/SurfaceFlinger: Failed to find layer (InputMethod#0) in layer parent (no-parent).
2018-12-01 16:31:49.417 26406-26406/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:31:52.419 26406-26434/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Error occurred while fetching auth token. Error code is  and message is 
2018-12-01 16:31:52.650 26375-26730/? E/OMXNodeInstance: setConfig(0xaf720900:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:52.681 26375-26379/? E/OMXNodeInstance: getConfig(0xaf720900:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:53.021 26406-26434/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Error occurred while fetching auth token. Error code is  and message is 
2018-12-01 16:31:54.265 1595-1595/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10086
2018-12-01 16:31:54.562 1595-1595/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10086
2018-12-01 16:31:55.030 26375-27326/? E/OMXNodeInstance: setConfig(0xaf19f3c0:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:55.035 26375-27326/? E/OMXNodeInstance: getConfig(0xaf19f3c0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:56.230 26375-27326/? E/OMXNodeInstance: setConfig(0xaf720900:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:56.233 26375-26379/? E/OMXNodeInstance: getConfig(0xaf720900:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:56.737 26406-26415/fr.free.nrw.commons.beta E/SpellCheckerSession: ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
2018-12-01 16:31:56.737 26406-26415/fr.free.nrw.commons.beta E/SpellCheckerSession: ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
2018-12-01 16:31:57.300 26375-26730/? E/OMXNodeInstance: setConfig(0xaf720b40:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:57.301 26375-26730/? E/OMXNodeInstance: getConfig(0xaf720b40:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:58.097 26375-27326/? E/OMXNodeInstance: setConfig(0xaf720ba0:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:58.104 26375-26730/? E/OMXNodeInstance: getConfig(0xaf720ba0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:31:58.221 1595-1608/? E/memtrack: Couldn't load memtrack module
2018-12-01 16:31:58.297 1595-1608/? E/memtrack: Couldn't load memtrack module
2018-12-01 16:31:59.003 1595-1595/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10086
2018-12-01 16:31:59.230 1595-1595/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10086
2018-12-01 16:32:00.072 26375-26377/? E/OMXNodeInstance: setConfig(0xaf720a20:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:00.097 26375-26377/? E/OMXNodeInstance: getConfig(0xaf720a20:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:01.044 26375-26377/? E/OMXNodeInstance: setConfig(0xaf720a20:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:01.054 26375-26377/? E/OMXNodeInstance: getConfig(0xaf720a20:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:01.851 26375-26379/? E/OMXNodeInstance: setConfig(0xaf720ea0:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:01.852 26375-26379/? E/OMXNodeInstance: getConfig(0xaf720ea0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:03.673 26375-26379/? E/OMXNodeInstance: setConfig(0xaf720900:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:03.685 26375-26730/? E/OMXNodeInstance: getConfig(0xaf720900:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2018-12-01 16:32:13.720 26406-26434/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Result: fr.free.nrw.commons.mwapi.CustomApiResult@2c4ae63
2018-12-01 16:32:13.736 26406-26434/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: internal_api_error_LocalFileLockError
2018-12-01 16:32:13.746 1595-4305/? E/NotificationService: No Channel found for pkg=fr.free.nrw.commons.beta, channelId=null, id=3, tag=null, opPkg=fr.free.nrw.commons.beta, callingUid=10086, userId=0, incomingUserId=0, notificationUid=10086, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
2018-12-01 16:32:13.797 1595-1608/? E/memtrack: Couldn't load memtrack module
2018-12-01 16:32:17.758 4328-26486/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
```
Phone Xiaomi Redmi 5 plus api 27

```2018-12-01 16:37:43.956 574-612/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2018-12-01 16:37:43.960 1566-2599/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.android.documentsui/com.android.documentsui.picker.PickActivity/27
2018-12-01 16:37:43.963 1566-2599/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.documentsui/com.android.documentsui.picker.PickActivity/27
2018-12-01 16:37:44.005 1566-2599/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.documentsui/com.android.documentsui.picker.PickActivity/27
2018-12-01 16:37:44.692 1566-1637/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2018-12-01 16:37:46.638 1566-2599/? E/ActivityTrigger: activityResumeTrigger: not whiteListedfr.free.nrw.commons.beta/fr.free.nrw.commons.contributions.MainActivity/92
2018-12-01 16:37:46.640 574-612/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2018-12-01 16:37:46.652 574-612/? E/ANDR-PERF-UTIL: Failed to read 
2018-12-01 16:37:46.652 574-612/? E/ANDR-PERF-UTIL: Failed to read 
2018-12-01 16:37:46.652 574-612/? E/ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
2018-12-01 16:37:46.652 574-612/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
2018-12-01 16:37:46.673 1566-1587/? E/ActivityTrigger: activityStartTrigger: not whiteListedfr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity/92
2018-12-01 16:37:46.674 1566-1587/? E/ActivityTrigger: activityResumeTrigger: not whiteListedfr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity/92
2018-12-01 16:37:46.675 574-612/? E/ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
2018-12-01 16:37:46.675 574-612/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
2018-12-01 16:37:46.698 1566-1587/? E/ActivityTrigger: activityResumeTrigger: not whiteListedfr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity/92
2018-12-01 16:37:46.699 574-612/? E/ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
2018-12-01 16:37:46.699 574-612/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
2018-12-01 16:37:46.872 30299-30299/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:37:47.039 1566-1637/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2018-12-01 16:37:47.100 574-612/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/mmc_host/mmc0/clk_scaling/enable with 1
     return value 2
2018-12-01 16:38:03.059 30299-30299/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:38:11.654 30299-30299/fr.free.nrw.commons.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
2018-12-01 16:38:16.589 1566-14306/? E/ActivityTrigger: activityResumeTrigger: not whiteListedfr.free.nrw.commons.beta/fr.free.nrw.commons.contributions.MainActivity/92
2018-12-01 16:38:16.590 574-612/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2018-12-01 16:38:16.601 574-612/? E/ANDR-PERF-UTIL: Failed to read 
2018-12-01 16:38:16.601 574-612/? E/ANDR-PERF-UTIL: Failed to read 
2018-12-01 16:38:16.601 574-612/? E/ANDR-PERF-OPTSHANDLER: Failed to read /sys/class/kgsl/kgsl-3d0/force_no_nap
2018-12-01 16:38:16.602 574-612/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [10, 7]
2018-12-01 16:38:17.002 574-612/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/mmc_host/mmc0/clk_scaling/enable with 1
     return value 2
2018-12-01 16:38:17.322 30299-30431/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Error occurred while fetching auth token. Error code is  and message is 
2018-12-01 16:38:17.522 30299-30431/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Error occurred while fetching auth token. Error code is  and message is 
2018-12-01 16:38:17.849 1566-2744/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:38:22.138 1566-1769/? E/WifiConnectivityManager: Ignore scan due to heavy traffic
2018-12-01 16:38:23.567 1566-14305/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:38:25.568 1566-14306/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:38:53.340 1566-14305/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:38:56.483 1566-2744/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:39:01.468 1566-14306/? E/NotificationService: Muting recently noisy 0|fr.free.nrw.commons.beta|1|null|10115
2018-12-01 16:39:15.219 30299-30431/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: Result: fr.free.nrw.commons.mwapi.CustomApiResult@a97c1b3
2018-12-01 16:39:15.246 30299-30431/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWi: internal_api_error_LocalFileLockError
2018-12-01 16:39:15.254 1566-14306/? E/NotificationService: No Channel found for pkg=fr.free.nrw.commons.beta, channelId=null, id=3, tag=null, opPkg=fr.free.nrw.commons.beta, callingUid=10115, userId=0, incomingUserId=0, notificationUid=10115, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
2018-12-01 16:39:36.287 845-1066/? E/Netd: Error deleting route ::/0 -> fe80::d0b0:fcff:feb4:2f31 wlan0 to table 1082: No such process
2018-12-01 16:39:36.320 1566-1792/? E/ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: command '33932 network route remove 266 wlan0 ::/0 fe80::d0b0:fcff:feb4:2f31' failed with '400 33932 removeRoute() failed (No such process)'
2018-12-01 16:39:41.197 845-1066/? E/Netd: Error adding route ::/0 -> fe80::d0b0:fcff:feb4:2f31 wlan0 to table 1082: File exists
2018-12-01 16:40:24.683 1566-1857/? E/AppScanObserverService: Result available, null observers for user: 0
2018-12-01 16:40:53.355 8512-8532/? E/CloudScheduler: update failed, not this time
2018-12-01 16:43:05.734 1566-1857/? E/AppScanObserverService: Result available, null observers for user: 0
2018-12-01 16:43:18.492 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:18.493 1566-1769/? E/WifiVendorHal: getSupportedFeatureSet(l.975) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2018-12-01 16:43:18.495 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:18.506 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2018-12-01 16:43:18.506 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2018-12-01 16:43:18.536 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:18.537 1566-1769/? E/WifiVendorHal: getSupportedFeatureSet(l.975) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2018-12-01 16:43:18.538 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:18.547 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2018-12-01 16:43:18.547 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2018-12-01 16:43:19.011 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:19.012 1566-1769/? E/WifiVendorHal: getSupportedFeatureSet(l.975) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2018-12-01 16:43:19.014 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:19.025 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2018-12-01 16:43:19.025 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2018-12-01 16:43:20.445 618-657/? E/libnav: AbaSuspend skips SVI deactivate: state was 3
2018-12-01 16:43:20.518 574-612/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2018-12-01 16:43:20.518 564-564/? E/QTI PowerHAL: Error opening /sys/kernel/hbtp/display_pwr: No such file or directory
2018-12-01 16:43:20.916 2739-2739/? E/LibSecureUISvc: svc_sock_send_message(suisvc): invalid remote socket suitch
2018-12-01 16:43:20.916 2739-2739/? E/LibSecureUISvc: svc_sock_send_message(suisvc): invalid remote socket suilst
2018-12-01 16:43:21.273 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:21.275 1566-1769/? E/WifiVendorHal: getSupportedFeatureSet(l.975) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2018-12-01 16:43:21.276 568-568/? E/WifiHAL: wifi_get_logger_supported_feature_set: Error -3 happened. 
2018-12-01 16:43:21.286 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2018-12-01 16:43:21.287 1566-1623/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2018-12-01 16:44:06.291 845-1066/? E/Netd: Error deleting route ::/0 -> fe80::d0b0:fcff:feb4:2f31 wlan0 to table 1082: No such process
2018-12-01 16:44:06.294 1566-1792/? E/ConnectivityService: Exception in removeRoute: java.lang.IllegalStateException: command '33937 network route remove 266 wlan0 ::/0 fe80::d0b0:fcff:feb4:2f31' failed with '400 33937 removeRoute() failed (No such process)'```

**Comment by maskaravivek** [comment]
@hoplite390 The logs doesn't look relevant. Can you add a filter for the app before checking logcat. If you are using Android studio then your log settings should like: 

screenshot 2018-12-01 at 10 22 13 pm

**Comment by hoplite390** [comment]
Thank you both for cooperation after more re-logs im now able to upload files. And i did find why my solution did not work anymore. UploadController.java it used to construct contribution. Now it is done in UploadModel.java so there is just one line that needs to be changed and it should work again. I will do commit and please try to re-test that one more time. It seems to work for me: [https://commons.wikimedia.beta.wmflabs.org/wiki/File:FInal_Username_Testing.jpg](url)

**Comment by neslihanturan** [comment]
Tested it @hoplite390 , but unfortunatelly it says 

> Author: null 

image

**Comment by hoplite390** [comment]
Probably one more thing (but im guessing) did you relog to application or not? 

If not maybe i have explanation. 
Because its possible that session Manager has your account stored without String rawUsername. (rawUsername = String value without added underscore) because i could not call just string.replace("_"," ") on every username in case somebody used underscore by their decision (and underscore was not just added by app). If there is somebody with "My_Username" or "My Username" app would show them both as "My_Username" so far. That is why upon login i store original string value from EditText usernameEdit. Maybe i should add: if rawUsername is null use username instead to prevent null for users that did not re-log.

**Comment by neslihanturan** [comment]
I think you caught the reason. After your commit I will test with reloging and without, and report results here. Thanks for fast reply @hoplite390

**Comment by neslihanturan** [comment]
Without login, my username with subtitle. With login, my name without subtitle as expected.

**Pull request merged**
