### PR TITLE
Fix log reporting for release builds

### LINKED ISSUE #1489: Modify the "Send Logs" feature
The "send logs" feature in its current state (2.7.1) is not very useful. As mentioned at #1485 , there are two issues with it:

1. The buffer size seems to be very small, we get relatively few lines of logs compared to what Android Studio etc can store. We likely need to increase this.
2. We are getting a lot of unrelated logs from system etc. We need to filter our app's logs out if possible. @tanvidadu has suggested a method for this: 

> To filter out logcats https://stackoverflow.com/questions/17448912/using-grep-command-to-filter-logcat-in-android?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa this might help.

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

Fixes #1489 

## Description (required)

Fixes #1489
- so that the logcat includes logs only from the Commons app. 
- also the amount of logs that is not sent is around 1.5 MB instead of last 100-150 lines
- have removed sensitive logs (needs a comprehensive test to ensure nothing sensitive is still being logged)

I made an effort to fix ACRA error reporting but it still doesn't work for me. I suspect proguard settings might be the issue. 

## Tests performed (required)

Sent logs using send log option. Got logs as expected.

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @maskaravivek ,

I tested this on a Nexus S emulator running API 27. I loaded Nearby, uploaded 1 picture through Nearby, then sent logs. A few things of note:
- Please set the target email address as commons-app-android-**private**, not commons-app-android. This is really important, we can't have people's logs publicly visible to everyone
- I sent mine through anyway, with this result: https://groups.google.com/forum/#!topic/commons-app-android/Qc0Jqd97Uzg . The zip file doesn't seem to contain anything at all unfortunately? All it says is 
> org.acra.data.CrashReportData@eea14b6MediaWiki Username = Misaochan2
> No extra information to attach
- Is there a reason for splitting into two .txt files and thus necessitating the use of a zip? The old style with just 1 txt file was convenient because we could just view it directly in the browser if we wanted to. But this isn't a big problem if two files are needed

Does this work for you? I don't see any logs sent by you to the google group forum either.

Also, it seems there are quite a few new libraries added, we would need to discuss these as per new library policy. I know you mentioned hyperlog in the issue, which has been approved, but what about the others? Could we please get a brief list of the new libraries and the rationale for each of them?

**Comment by maskaravivek** [comment]
@misaochan I wasn't able to check on API level 27 during my tests. I tested on Android 6.0 and it worked perfectly. 

Will test it on API 27 in the next couple of days and will also change the target email address. 

A couple of things that I didn't mention in the PR summary: 
- Ensure that the app has external storage write permissions so that logs can be written to the file. During testing, I used to grant permissions manually. 
- Will be removing any extra library that is unrelated to the PR. I omitted this step for the initial testing. 

The group doesn't have logs sent by me because I had hardcoded my email ID while testing as I didn't want to spam the group. 
Also, now we are using a `.zip` because now we can have multiple log files. 
- Instead of sharing just the last few hundred lines of logs, I have increased the logs that would be stored. Right now, the limit is 1MB. We can increase/decrease it if the need be. 
- The PR introduces a log rotator that could use multiple files for the logs as the whole log data would be amounting to 1MB. 

PS: Am forwarding you one of the log files that I generated while testing.

**Comment by misaochan** [comment]
Thanks for sending the log through! It looks great, and as far as I can see it also looks fine from a privacy standpoint as long as we send to the private group and we keep the current manual sending procedure.

Would be fantastic if we can get a newline for each line (probably before each of the [DEBUG] statements), but that's hardly a major issue. :)

One final request: In the subtext of the Settings "Send log file" item, we should probably say "Send log file to developers via email to help debug problems with the app. Note: logs may potentially contain sensitive information". Just to be safe...

**Comment by maskaravivek** [comment]
@misaochan It works perfectly now. 

- All logs are on separate lines. I checked in sublime/VS code editor. Which editor are you using to check logs?
- Have changed the subtext for send logs
- Have removed all unrelated library additions/changes
- Have added java docs
- Works fine for API 27 

As mentioned above log dumping requires external storage permissions. 

> Ensure that the app has external storage write permissions so that logs can be written to the file. 

After granting the permissions, log dumps work after an app kill.

**Comment by misaochan** [comment]
@maskaravivek Fantastic job!!! :) Just tested this again on a Nexus S emulator on API 27, prodRelease.

The first time I tapped Send Logs, got the permission request and toast. 

I uploaded an image and then went back to Settings. The second time I tapped Send Logs, it crashed with this error:

```
10-14 18:45:23.524 32614-32614/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 32614
    java.lang.NullPointerException: Attempt to get length of null array
        at fr.free.nrw.commons.logging.LogsSender.writeLogToZipFile(LogsSender.java:158)
        at fr.free.nrw.commons.logging.LogsSender.getZippedLogFileUri(LogsSender.java:108)
        at fr.free.nrw.commons.logging.LogsSender.sendLogs(LogsSender.java:60)
        at fr.free.nrw.commons.logging.LogsSender.send(LogsSender.java:51)
        at fr.free.nrw.commons.settings.SettingsFragment.checkPermissionsAndSendLogs(SettingsFragment.java:111)
        at fr.free.nrw.commons.settings.SettingsFragment.lambda$onCreate$5$SettingsFragment(SettingsFragment.java:101)
        at fr.free.nrw.commons.settings.SettingsFragment$$Lambda$4.onPreferenceClick(Unknown Source:2)
        at android.preference.Preference.performClick(Preference.java:1137)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
        at android.widget.AbsListView$3.run(AbsListView.java:4042)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I uploaded another image and then tapped Send Logs again. Seems third time was the charm, it worked perfectly!! 👍  And indeed the newlines work in a proper text editor (Notepad++ worked, Notepad didn't). It contains all the logs we would ever need to debug anything. 

Great job with the Javadocs, too.

I am happy to approve this PR pending a fix for the crash above. After that is fixed, we can merge this. I may not be around at that time, but @neslihanturan feel free to merge once the fix is done.

Thanks so much guys!

**Comment by misaochan** [comment]
Edit: Oh, I just noticed these lines:

**2018-10-14 18:47:13,760     [DEBUG] [file-logging-thread-1] [CustomMwApi] : Token being used is redacted+\
2018-10-14 18:47:13,769     [DEBUG] [file-logging-thread-1] [CustomMwApi] : Final cookies are [[version: 0][name: GeoIP][value: AU:QLD:Brisbane:-redacted:v4]**

We probably want to just comment out these log lines from CustomMwApi. I think the risks exceed the benefits in having them there. Devs who want the lines to be displayed can always uncomment.

**Comment by misaochan** [comment]
Merging this. First task complete for WMCZ project, woohoo! :D

**Pull request merged**
