### PR TITLE
removing duplicate </a>

### PR DESCRIPTION
**Pull request by jhsoby**

### CODE REVIEW

**Comment by misaochan** [comment]
Hm, we're still getting Travis build errors:

> Execution failed for task ':app:mergeDebugResources'.
> > /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-x-invalidLanguageCode: Error: Invalid resource directory name

@whym @nicolas-raoul thoughts? Thanks :)

**Comment by misaochan** [comment]
@whym , do you know if there is a way to get Travis to rebuild this PR?

**Comment by whym** [comment]
Does this help? http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

Otherwise, I would simply merge it - the failure seems to be in the parent commit not this one. I believe merging it will not make master unbuildable.

**Comment by misaochan** [comment]
Odd, the restart build button isn't available to me even though (I think) I have write access. But yeah, I think merging should be fine. Thanks @whym !

**Comment by whym** [comment]
We could perhaps have asked if jhsoby wants to rebase and resubmit it. This is already solved, so just for the record.

**Pull request merged**
