### PR TITLE
#3493 App freezes for 15 seconds when you press Next in UploadMediaDetailsFragment

### LINKED ISSUE #3493: App freezes for 15 seconds when you press Next in UploadMediaDetailsFragment
**Summary:** 

There should be some indication of progress and the app should be responsive

**Steps to reproduce:** 

Try to upload anything

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by macgills**
**Description (required)**

Fixes #3493 App freezes for 15 seconds when you press Next in UploadMediaDetailsFragment

What changes did you make and why?
Corrected the misuse of RxJava so the main thread was not blocked. Converted minor classes to kotlin. Removed boolean parameter from api because it was always true

**Tests performed (required)**

Tested betaDebug on Nexus5x with API level 8.1.0

### CODE REVIEW

**Comment by macgills** [comment]
@maskaravivek I'd prefer not, when I start a project conversion I like to adhere by the [boyscout rule](https://www.matheus.ro/2017/12/11/clean-code-boy-scout-rule/) and if I touch a class then leave it better than when I found it. Seeing as how both the file changed were sub 50 lines the changes I made to them represented quite a large proportional change, no reason to constrain them to being in java.

**Comment by maskaravivek** [comment]
@macgills Just to clarify I am very happy to have them converted to Kotlin but I don't think that that should be part of this PR. For bug fixes, we try to include just the required changes in the PR and other changes can be a different PR. 

Also, as per #747 for existing classes, we are planning to move to Kotlin starting with just the simpler classes like model classes. For new classes, it is up to the contributor to choose whether he wants to use Java or Kotlin.

**Comment by macgills** [comment]
How about we update #747? If you update a class significantly also change it to kotlin if you are willing?

Individually tickets for conversion are just too slow I think and I prefer a more organic method.

I didn't update every class changed in this PR because I couldn't justify "significantly change".

I would feel hamstringed on my work on the structured data class if I don't have the freedom to proceed with conversions as I see fit especially given turnaround times on PRs.

**Comment by misaochan** [comment]
I think that for the structured data PRs specifically, it is okay to submit Kotlin conversions in the same PR because it will be sent to the development branch. Also given that the SDC branch has never been part of our codebase before this, the classes are essentially all "new" and therefore it is up to the person submitting them whether they want it to be in Kotlin or Java.

For PRs sent directly to master like this one, it is best to separate them, we cannot expect volunteers to adhere to our processes if we don't do the same ourselves. :) Sorry about that.

**Comment by macgills** [comment]
@misaochan I would ask you to reconsider for this scenario

>In the first chapter of the clean code, Uncle Bob talks about the boy scout rule, which can be summarized as:
Leave the code cleaner than you found it.

This is a core principle of clean code.

But I won't press the issue further than this comment if you choose to stick by your guns.

**Comment by misaochan** [comment]
@macgills I understand, and for a smaller project I think that is viable (development branches, which only a few people work on at a time, would function similar to this, hence why I said there is no restriction on PRs sent to development branches). For a project with many people sending PRs to master (where there is a very wide range of experience between contributors), more modular PRs help us find out more easily where something went wrong, and to revert that change easily.

Sorry for the inconvenience, but as the majority of your work will be done on dev branches, I believe this process won't adversely affect it too much.

**Comment by sivaraam** [comment]
> This is a core principle of clean code.

I'm just gonna leave this here as you mentioned clean code: [Goodbye, Clean Code](https://overreacted.io/goodbye-clean-code/)
Don't get wrong. I'm not against clean code but I agree with what's mentioned in the article. ☮️

**Comment by sivaraam** [comment]
> I'm just gonna leave this here as you mentioned clean code: [Goodbye, Clean Code](https://overreacted.io/goodbye-clean-code/)
> Don't get wrong. I'm not against clean code but I agree with what's mentioned in the article. ☮️

Forgot to mention one important thing. This is just _my opinion_.

**Comment by macgills** [comment]
> I'm just gonna leave this here as you mentioned clean code: Goodbye, Clean Code

`Refactor Everything!` Is a trap and code must be able to grow organically if similar looking code _is actually_ different features. Things that are the same feature should not be duplicated across multiple classes. That is the lesson I would take from that article.

**Comment by misaochan** [comment]
Tested on prodDebug, Nexus 5X API 28, works for me. Thanks for making the requested changes, @macgills !

**Pull request merged**
