### PR TITLE
Reduce scope of places field

### PR DESCRIPTION
**Pull request by veyndan**

### CODE REVIEW

**Comment by misaochan** [comment]
Would you mind if I postpone the merge for a while until the current issues #485 with the pre-release version of Nearby are fixed? I meant to test it by reverting the last refactor, but haven't had the time til today. After that is done, chances are there will be conflicts that need to be resolved.

**Comment by veyndan** [comment]
Yeah no problem

**Comment by misaochan** [comment]
Do we still need this? If we do, I'm happy to merge if conflicts are resolved.

**Comment by veyndan** [comment]
I accidentally deleted the repo with this branch in, I'll create another PR.

**Pull request closed without merging**
