### PR TITLE
Detecting pictures that are too dark

### PR DESCRIPTION
**Pull request by Bluesir9**
As discussed in #74, this attempts to detect 2 kinds of unwanted pictures:
1-Images that are too dark
2-Images that are blurry. 

When the app detects an image which it finds to be too dark or blurry it shows a popup with an error message. The popup is basically a warning since the user can choose to ignore it and continue uploading the image. 

As for the image processing part,  detecting images that are too dark works quite flawlessly as per my testing. I have never come across an image that was pointed out as being too dark incorrectly or vice versa. 

On the other hand, while blurry images detection works well enough, the results become less consistent for images taken during the night and/or in poor lighting. It isn't that it fails every time, just that every now and then you will run into an image which looks sharp but was marked as blurry by the app. I have tweaked and played with the configuration quite a lot with the current setup working best for me. However I am not completely convinced. 

That said, having worked on it for quite a while, I felt best to put the code out for others to see. Maybe having some fresh eyes could lead to changes/improvements.   

P.S: I have added the OpenCV library to the repository as part of this pull request. However I found [this](https://github.com/jlhonora/opencv-android-sample/blob/master/.gitignore) gitignore file that suggests excluding the library from the repository. This will need to be discussed. 

Also we will definitely need to add a section in the Wiki about setting up OpenCV.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks a lot!
About blurriness:

Indeed some pictures might appear blurry because their definition is artificially high, but the important thing is that it is not too blurry when the picture is viewed normally. If the picture is 4000 pixels wide then it can afford to be blurry, because even if viewed fullscreen it will be sharp.

So, how about reducing proportionally the size of the image to make its longest dimension (either height or width) 500 pixels?

I am not sure whether it would help with the detection problem or not, but it might be worth considering.
Cheers! :-)

**Comment by Bluesir9** [comment]
I was testing the app the other day and tried to upload an image which I had taken off my DSLR and the app ran into an OutOfMemoryException. So yeah scaling images down seems necessary. Also, one thing I haven't taken care of as of now is processing images when the user is attempting to upload multiple images.

**Comment by neslihanturan** [comment]
By looking at the discussion I see there is some problems with this PR, but also there is a lots of effort. And by time conflicts will increase. Does anyone have an idea how to make this PR merge ready @misaochan , @maskaravivek , @psh , @Bluesir9 ? Maybe we can merge some parts of it, if all parts don't works as expected.

**Comment by Bluesir9** [comment]
Apologies for having gone dark on this. As far as I recall, detecting images that are too dark works quite well and I don't see any reason to wait on that.  

Detecting blurry images was the one that was causing some trouble. @nicolas-raoul had suggested scaling the image down before processing it and testing that out. Unfortunately I haven't had the time to do that. 

Let me know how you guys wish to proceed with this. In the meanwhile, I will at least fix the conflicts and push the changes.

**Comment by neslihanturan** [comment]
I think we can implement black image detection for this PR, and create an issue for detecting blurry images. It would be great if you can un-commit blury detection codes and solve conflits. And also it would be great if you can add related parts of your code into the issue, so that only scaling images down step will be missing. How does that sound @Bluesir9 ?

**Comment by neslihanturan** [comment]
@Bluesir9 thanks for being so quick, and I will test and merge it immediately, no more conflicts:)

**Comment by Bluesir9** [comment]
Have removed the conflicts and removed the chunk of code detecting blurry images.

**Comment by neslihanturan** [comment]
@Bluesir9 thanks! Now we may need a team discussion about using OpenCV. Besides, we need to exclude openCV html codes even if we decide to use that library in the project. I will wait for team to review.

**Comment by maskaravivek** [comment]
Thanks for the PR @Bluesir9. Great work.

I went through the process of adding OpenCV to an android app and it looks like adding it as a library project is the only suggested option. I was hoping for a gradle plugin that could be added and then adding the source code would have not being required. 

@Bluesir9 It would be great if you could address @neslihanturan's comments on removing unused bits(like some html files or unused opencv libraries). Also it would be wonderful if you could add a wiki that could serve as a starter guide for anyone trying to use OpenCV in our appplication. :)

@neslihanturan If you are able to patch the PR on your system and able to test it without any special setup effort for openCV then I guess you can go ahead and merge it.

**Comment by misaochan** [comment]
Thanks for the PR, @Bluesir9 ! :)

I agree, we will need to remove the HTML files at the very least. This PR has 146k lines of code. ;)

**Comment by nicolas-raoul** [comment]
How much heavier does the APK become with OpenCV merged?

**Comment by Bluesir9** [comment]
The HTML files were all related to OpenCV's documentation. I added the "javadoc" folder in the OpenCV library directory and we are down from 146K to 34K lines of code in this PR :sweat_smile:  

@maskaravivek Will definitely add a wiki guide in relation to OpenCV setup and usage. 

@nicolas-raoul The apk I built off this branch stands at 128.4 MB, whereas the one I built off master was at 128 MB.

**Comment by maskaravivek** [comment]
Oh wow! I had no idea that our APK size is that large. 

Interestingly the last built APK size for me is ~18mb. 
screen shot 2018-01-14 at 11 44 50 pm

**Comment by nicolas-raoul** [comment]
wow I had no idea, 128 MB is really huge, and will eat a considerable part of the monthly data of many of our users who don't have access to WiFi. Actually in many countries where 1 GB packages are the norm http://prepaid-data-sim-card.wikia.com/wiki/Bangladesh

We have to balance the advantages the feature brings vs. the consequences of an increase in size.

This could be investigated: https://stackoverflow.com/questions/42019028/how-to-reduce-the-apk-size-of-my-android-app-with-opencv-library-integrated

**Comment by misaochan** [comment]
Umm, our current download size on the Play Store is 17.97 MB. But it seems @Bluesir9 is saying that our master branch (without this PR merged) currently builds at 128 MB? That is strange, will need further investigation.

>100MB is definitely way too large IMO.

**Comment by psh** [comment]
@misaochan - I agree that over 100Mb is far too big, but for an app of our complexity, so is 20Mb.  I ran a couple of tests and the size is largely due to binary files included by *mapbox* - I suggest adding 

```gradle
android {

    ...

    splits {
        abi {
            enable true
            universalApk false
        }
    }
}
```
so that our build generates separate APK files for the different processor types that *mapbox* binaries are targeting. Each is only **8.7Mb** in size!  Adding this would mean uploading the 7 generated APK files when you release the app, but it would be a huge boon to users on limited data connections.

**Comment by Bluesir9** [comment]
Mapbox has been part of this app since quite some time right? Why is it that we are finding this apk size bloat just now?

**Comment by misaochan** [comment]
@psh Interesting idea! Lets discuss this further at #1067 :)

@Bluesir9 I just built an APK from the current master branch and the upload size was ~18 MB. I think the 100+MB file is just from this PR?

**Comment by whym** [comment]
As I understand, 'AI' libraries like OpenCV are generally resource-intensive. I wonder if it works well on low-range smartphones. Do we know what kind of phones our userbase use?

OpenCV is a full-fledged computer vision library (including features like object recognition) - is there any simpler one for this problem?

**Comment by Bluesir9** [comment]
So that size bloat on master was a false alarm. While building the master branch, the jniLibs and opencv library folders were still part of the project. As a result of that the builds were bloated. When I stashed those 2 folders, the build size came down to the expected 20 MB. 

I have applied the abi split change suggested by @psh here itself and it does the job as expected:

screenshot from 2018-01-16 22-20-50

**Comment by whym** [comment]
Another idea might be to split the detection module into a web service, for example on tools.wmflabs.org. Your Java code should work on the server side JVM with little to no changes, at least in principle. It will not work when the phone is offline, though.

**Comment by nicolas-raoul** [comment]
A web service would only work after upload, though, so probably after the user has entered a title/description.

**Comment by whym** [comment]
> A web service would only work after upload, though, so probably after the user has entered a title/description.

That's one way to do it, but the app can also send the image (or maybe a thumbnail of the image to save the bandwidth) to the detection web service directly, right? This can happen before uploading it to Commons.

**Comment by nicolas-raoul** [comment]
That would take double the bandwidth, right?

By the way, I think we should discuss all of this on the issue rather than on the PR :-)

**Comment by whym** [comment]
All right, see https://github.com/commons-app/apps-android-commons/issues/74#issuecomment-358257110

**Comment by Bluesir9** [comment]
Given the direction the discussion has taken, I have removed all usages and references to the OpenCV library in this PR. Detecting images that are too dark doesn't need OpenCV anyways so we can take up that issue fix as part of this PR. Will edit the title of the PR as well accordingly. 

Hope this works for all.

**Comment by neslihanturan** [comment]
Hi @Bluesir9 , thanks for your last edits. But still there is 145 files edited. Do we really need this to only detect dark pictures?

**Comment by Bluesir9** [comment]
@neslihanturan Whoops, forgot to remove the library folder from the directory, done now.

**Comment by maskaravivek** [comment]
@Bluesir9 It would be great if you could resolve the merge conflicts. We can go ahead and merge your PR once that is taken care of. :)

**Comment by Bluesir9** [comment]
Have fixed merge conflicts and tested the changes post that. Dark image detection was working as expected.

**Pull request merged**
