### PR TITLE
Fixes issue #1380 Changed Notification UI. 

### LINKED ISSUE #1380: Fix whitespace and padding for Notifications
**Summary:** 

Notifications activity needs a bit of aesthetic improvement.

**Steps to reproduce:** 

Go to Notifications in nav drawer

**Expected behavior:** 

Whitespace needs to be stripped from the start of some types of notifications (although to simplify things we can probably strip from the start of all messages). 

Also, this may be personal preference, but I think we could increase the padding a bit to make it look less cluttered.

**Observed behavior:** 

notifications_whitespace

**Device and Android version:** 

Nexus S API 25
 
 **Commons app version:** 

2.6.7

**Would you like to work on the issue?**

Ideally not, please feel free. ;)

### PR DESCRIPTION
**Pull request by Jatin0312**
## Description

Fixes #1380 
Added padding for title and removed extra spaces from title text.

## Tests performed

Moto g4 plus Android 7.0.0

## Screenshots showing what changed
 
notification ui

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @Jatin0312 , just tested this - I like the padding, but the whitespace issue persists for me. 

It is mostly just the deletion nomination messages that cause the problem. If you don't have any, what you can do is to upload a picture and then nominate your own picture for deletion. That will generate a suitable message for testing. :)

**Comment by Jatin0312** [comment]
Ok thanks @misochan I will look into it :)

**Comment by Jatin0312** [comment]
@misaochan I nominated many photos for deletion but still was not able to generate any notifications.

**Comment by misaochan** [comment]
@Jatin0312 Could you link your Wikimedia user talk page please?

**Comment by Jatin0312** [comment]
https://commons.m.wikimedia.beta.wmflabs.org/wiki/User:Codedoper0312 This the link of my user talk page.

**Comment by misaochan** [comment]
I nominated https://commons.wikimedia.beta.wmflabs.org/wiki/File:Taj_mahal_3.jpg for deletion, try and see if you get any notifications?

We usually test notifications on the actual Commons server, but I don't see any reason why beta wouldn't work.

**Comment by misaochan** [comment]
Edit: Oh, wait, that one's not yours. Sorry. :/ How about you create a new account and see if nominating via the other account works (instead of nominating your own)?

**Comment by Jatin0312** [comment]
Ok I will check that. :)

**Comment by Jatin0312** [comment]
I did nominate images from different account It's working fine I guess.

hello

**Comment by misaochan** [comment]
Hmm, not sure why some of my notifications still have excess whitespace. I guess we can go with merging this PR since it is an improvement anyway, and we can investigate further later on. :) Thanks!

**Pull request merged**
