### PR TITLE
Convert profile package to kotlin

### PR DESCRIPTION
**Pull request by psh**
Fixes: #5977
Parent issue: #5928

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
```
e: file:///home/runner/work/apps-android-commons/apps-android-commons/app/src/main/java/fr/free/nrw/commons/profile/achievements/AchievementsFragment.kt:49:5 Cannot weaken access privilege 'protected' for 'compositeDisposable' in 'CommonsDaggerSupportFragment'

> Task :app:compileBetaDebugKotlin FAILED
e: file:///home/runner/work/apps-android-commons/apps-android-commons/app/src/main/java/fr/free/nrw/commons/profile/achievements/AchievementsFragment.kt:49:17 'compositeDisposable' hides member of supertype 'CommonsDaggerSupportFragment' and needs 'override' modifier
```
Would you mind checking? :-)

**Comment by neeldoshii** [comment]
Hi @psh,
seems like tests are failing for AchievementFragments. If you don't mind can you revert this commit for AchievementFragment Migration [4fcbb81](https://github.com/commons-app/apps-android-commons/pull/5979/commits/4fcbb81e5dd95c1eab5910cab3d728959ad569f0) as this would lead to duplication with #5666.

**Comment by psh** [comment]
Reverted 👍

**Review by nicolas-raoul — APPROVED** [review]
Seems to work fine. Thanks! :-)

**Pull request merged**
