### PR TITLE
Show bookmarked nearby locations differently (#2059)

### LINKED ISSUE #2059: Show bookmarked nearby locations differently
I bookmark locations that I shot with my DLSR camera but have not uploaded yet.
If bookmarks were shown differently on the map, it would be very easy to see what locations I have not shot yet.
Everyone uses bookmarks differently, but I believe that everyone would benefit from seeing them differently, for instance as stars, or in a different color.
People who use bookmarks to select places where they plan to go will benefit as well.

### PR DESCRIPTION
**Pull request by sp2710**
**Fixes #2059** 

**What changes did you make and why?**

* Used a different marker for representing bookmarked locations in map
* updated the marker icon after it is bookmarked from bottom sheet and nearby list
* updated the markers of locations which are removed from bookmarks from bookmark activity on resuming the nearby map

**Tested on Motorola Moto G5 plus with API level 24.**

Bookmarked locations are represented by red markers
screenshot_20190126-173823

### CODE REVIEW

**Comment by maskaravivek** [comment]
Thanks for the PR @sp2710! The code changes look good to me. 

Personally, I would prefer an icon that indicates bookmarked location more clearly. Something similar to https://www.iconfinder.com/icons/217091/bookmark_browser_favorite_favorites_internet_location_map_marker_marketing_oplimization_optimization_pin_star_icon

PS: this icon is not free to use. Can we find a similar alternative? 

@neslihanturan opinions?

**Comment by nicolas-raoul** [comment]
How about going with this icon first and creating another issue for the icon?
It can interest newcomers who like graphic design :-)

**Comment by maskaravivek** [comment]
@sp2710 It works for me but only after killing the app once. Can you redraw the marker after it is bookmarked?

**Comment by sp2710** [comment]
Sure will implement it and send PR for this soon:)

**Comment by sp2710** [comment]
Sure. I will implement it and will send a PR soon:)

**Comment by sp2710** [comment]
@maskaravivek  I have made the changes.
Kindly review the PR and share your feedbacks :)

**Comment by sp2710** [comment]
Thanks for approving the PR :)

**Pull request merged**
