### PR TITLE
New ui design from pre-hackathon

### PR DESCRIPTION
**Pull request by neslihanturan**
Note: It is not ready yes please do not approve it.

On pre-hackathon UI designers prepared 3 design suggestion for our app and we decided to use the one in the middle. 
somethiny

Yours tab is the tab for our contributions, and others tab is to explore nearby photos. I implemented it as following screen shots and still working on it. 

device-2017-06-02-165749
device-2017-06-02-165826

Don't get too excited, notification isn't working. I hardcoded it:). 

Known problems:

- Fragment becomes empty on resume
- Explore tab is not written yet
- Notification for closest nearby place (or something else) is not working.
- Crashes on rotation change:)
- And I think some memory problem

If one of you knows a quick solution for these problems please go for it.

On the other hand, I need your ideas about:

1. Because we carried upload buttons from action bar to a cell in gridview, if user go down, then she needs to come back all the way up to upload something.

- The solution of mine is adding a floating button to the right bottom corner to go top. 

2. It looks nice in this orientation, but what if user decides to use phone horizontal? Then there needs to be 4 cells per row (because 2 is too big for vertical), consequently the short side of the notification rectangle will be next to the one of square images. It would look like : 
device-2017-06-02-170912
Some possible solutions that I can imagine:

- Use 2 rows for both vertical and horizontal
- Use squares instead of rectangles when orientation is horizontal (my vote goes to this)

3. If there is no notification, and we decide to use rectagle shaped upload button area, then we have the same problem. Possible solutions:

- Never remove notification area, even if there is no notification, we can put "You dont have any notifications" (this option would be mush easier)
- When there is no notification, remove notification area and make upload area square as other grid cells. 

İdeas?

### CODE REVIEW

**Comment by misaochan** [comment]
@neslihanturan Nice work! I like it. :)

1. Good point re: the scrolling, that hadn't occurred to me. Instead of a hover button to go to the top when you scroll down, possibly the hover button could go directly to the gallery? I'm not sure about this, would be good if we can get everyone's input.

2. Wouldn't you need to redesign the layout of the upload & notification grid cells if we used squares instead?

3. I would vote for "You have no notifications". I really don't think it should be replaced with an image, that might feel quite inconsistent for the user. (Also, an issue I realized is that if someone uploads a photo of a nearby place that needs photos, Wikidata doesn't update it, so the notification will carry on being displayed even after the user goes to it and uploads a picture)

One more thing: Do you think the camera and gallery icons are a bit too close together? Since fingers can be pretty clunky, I'd vote for more padding between the two.

**Comment by neslihanturan** [comment]
1. I think directly going gallery with hover button is much better.
2. Yes, there will be new designs for squares.
3. No notifications to display option is easier though. Yes your concern is valid, maybe we can temporarily store this information in application db?

**Comment by misaochan** [comment]
For 3, I definitely agree we should keep the "no notifications found" option. :) Just wondering what we could do about that problem. I should have listed it as a separate point because it's not really related to your question 3, haha.

**Comment by neslihanturan** [comment]
After last changes the situation is: 
device-2017-06-03-211836

Some questions:

1. Should we store images in database?
2. Should we store only image urls in database?
3. Should we upload information by location changes?
    - We can add a button to refresh
    - We can update it per x km.
4. How many photos from nearby places should be displayed initially?

**Comment by misaochan** [comment]
Just realized that we don't really have an issue for this. Will create one so hopefully more people will join in the discussion, and also because it's easier to track an issue. :)

**Pull request closed without merging**
