### PR TITLE
4671: Change the deprecated RuntimeEnvironment.application in all the Robolectric unit tests

### LINKED ISSUE #4671: Robolectric 'application: Application!' is deprecated. Deprecated in Java
**Summary:** 
`'application: Application!' is deprecated. Deprecated in Java` so we should use `ApplicationProvider.getApplicationContext()` in All Robolectric Unit Tests

Link for help: https://stackoverflow.com/questions/52883747/robolectric-runtimeenvironment-application-is-deprecated-where-is-applicationpr

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #4671 

What changes did you make and why?

Changed the deprecated RuntimeEnvironment.application to ApplicationProvider.getApplicationContext() in all the robolectric unit tests and optimised the imports accordingly.

**Tests performed (required)**

Tested BetaDebug on Redmi 5A with API level 26.

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
Is tis change necessary: app/CommonsContributions/551b5101-d2e1-49db-882e-df07f132950b15998328188345850540.jpg ?

**Review by nicolas-raoul — COMMENTED** [review]
Tested, everything seems to be working normally 🙂

**Comment by RitikaPahwa4444** [comment]
> Is tis change necessary: app/CommonsContributions/551b5101-d2e1-49db-882e-df07f132950b15998328188345850540.jpg ?

Still wondering how this got generated as I had not created any folders. I'll remove it. Thank you for reviewing and letting me know :)

**Review by nicolas-raoul — APPROVED** [review]
Unit tests running fine

**Pull request merged**
