### PR TITLE
Lint issues

### PR DESCRIPTION
**Pull request by domdomegg**
Minor codestyle fixes

### CODE REVIEW

**Comment by domdomegg** [comment]
Is @codacy right in saying that the imports are in the wrong order - Android studio is extremely adamant that they are (using default style)

**Comment by misaochan** [comment]
Yeah, I usually ignore those codacy issues and would go with Android Studio personally.

**Comment by whym** [comment]
I can try adjusting the Checkstyle (Codacy) settings to conform with the Android Studio's default, if that is preferred.

**Comment by addshore** [comment]
> I can try adjusting the Checkstyle (Codacy) settings to conform with the Android Studio's default, if that is preferred.

That sounds amazing!

**Comment by whym** [comment]
It looks like we can leave the import issue aside. I'll probably make a PR or issue for that.

**Comment by whym** [comment]
See https://github.com/commons-app/apps-android-commons/issues/646

**Pull request merged**
