### PR TITLE
Limit number of images uploaded at a time

### PR DESCRIPTION
**Pull request by harith96**
Images that can be uploaded at a time has to be limited (current max. number : 5) to avoid the issue of users uploading a lot of unnecessary images.

Fixes ##3101 Limit on number of images uploaded at once

**Changes**

As the number of images selected at a time cannot be limited in Android Image Picker and to avoid redundant code the functionality of removing images was integrated into the existing image upload flow.
Each thumbnail of top card has a close button and users can delete a image using that button at any time during upload process. 
If user has selected too many images an error icon will be displayed next to the top card title and an dialog will be displayed if user clicks the error icon mentioning the
max. number of images allowed and min. number of images that have to be deleted. And also user will not be able to progress to select the category until there are only max. number of images in the selection. (The next button on the last image fragment will be disabled and a toast will be displayed if user clicks next button on the last image fragment.)

**Tests** - no new unit tests were written as all the new function were written in UploadActivity class and ThumbnailsAdapter class related to the UI.

**Screenshots showing what changed (optional - for UI changes)**

Screenshot_2019-08-12-10-41-53-147_fr free nrw commons beta
Screenshot_2019-08-12-10-42-24-950_fr free nrw commons beta

### CODE REVIEW

**Comment by harith96** [comment]
All the new functions are in view layer. Therefore no new unit tests have been written as mentioned in the description .

**Comment by harith96** [comment]
@ilgazer @maskaravivek Would be great if someone could review this code and provide feedback.

**Comment by neslihanturan** [comment]
This PR is old and has several conflicts. On the other hand, the code does the job. @harith96 thanks a lot for this PR, are you interested to fix conflicts? If not other volunteers are encouraged to claim this PR and solve it by inspiration from this code:)

**Comment by neslihanturan** [comment]
Closing since this PR seems like sleeping. I noted that this code can be revisited to inspire from under issue page.

**Pull request closed without merging**
