### PR TITLE
Fixes #1801 (Media details view for Browse is lacking author field)  in 2.8-release branch

### LINKED ISSUE #1801: Media details view for Browse is lacking author field
**Summary:** 

The media details view for Browse (search > media/categories) is lacking the author field. I believe this needs to be added, otherwise we are infringing the license for images that are under an attribution license. Featured images have the author field.

@nicolas-raoul @ujjwalagrawal17 Can this be fixed urgently? I am hesitant to release the browse feature without this in place

**Steps to reproduce:** 

Browse > media > search for an image > select the image 

**Device and Android version:** 

API 24 Samsung Galaxy s7
 
 **Commons app version:** 

2.8-release 

**Screen-shots:** 

screenshot_1533548365

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
Fixes #1801 (Media details view for Browse is lacking author field) in 2.8-release branch

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
@misaochan Please review it once. I am also testing it.

**Comment by ujjwalagrawal17** [comment]
All 3 seems to be fixed. 
Fixes #1805 (Expected adapter item count: 20, found: 30)
Fixes #1801 (Media details view for Browse is lacking author field)
Fixes #1519 (Swiping featured images limited to 10 images)
@nicolas-raoul  @misaochan Please review it.

**Comment by misaochan** [comment]
Testing now, thanks!

**Comment by misaochan** [comment]
Tested on API 24 emulator, works well for me. I'll take the liberty of merging as we need to include this in the release today, @nicolas-raoul and @neslihanturan hope that's OK! :)

**Pull request merged**
