### PR TITLE
fix issue Hard to tell if we are looking at a scrolling list

### LINKED ISSUE #4513: Hard to tell if we are looking at a scrolling list
It's hard to tell if we are looking at a complete list or if there are more items that can be scrolled further.

Version: latest beta.

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #4513 

What changes did you make and why?
Added vertical scrollbar to all instances of RecyclerView so that when the underlying list is populated and overflows the view a scrollbar temporarily appears indicating to the user that scrolling is possible

**Tests performed (required)**

Tested {ProdDebug} }.

**Screenshots (for UI changes only)**
Screenshot_1639564065

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks! Would you mind solving the conflict?

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul  can review this PR

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
It looks like you changed the wrong place?
The depictions selection screen does not show the scrollbar even if items overflow:
adb
On the opposite, a scrollbar is now visible on the contributions activity, where it is not needed.

**Comment by neslihanturan** [comment]
Hİ @Prince-kushwaha , is this PR still active?:)

**Pull request closed without merging**
