### PR TITLE
Use quadtree from jitpack instead of a jar file

### PR DESCRIPTION
**Pull request by est31**
This is needed for f-droid where only source dependencies are allowed.

F-Droid logo
[F-Droid](https://f-droid.org) is an Android app store exclusively for **open source** apps. See F-Droid's [Wikipedia page](https://en.wikipedia.org/wiki/F-Droid).
You can browse the catalog of available apps on [Fossdroid](https://fossdroid.com/).

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks a lot for the change!

Somehow Travis does not manage to compile anymore with this change... would you mind having a look?
https://travis-ci.org/commons-app/apps-android-commons/builds/159746447#L1685

**Comment by est31** [comment]
mhh, seems a patched version is used, and jitpack can't build it [because unit tests are failing]( https://jitpack.io/com/github/nicolas-raoul/Quadtree/bb3cc7608a27e94/build.log).

It can be made working if the the unit tests in https://github.com/varunpant/Quadtree/pull/3 are fixed.

**Comment by misaochan** [comment]
We need the owner of varunpant/Quadtree to merge nicolas's pull request first, I guess?

**Comment by nicolas-raoul** [comment]
Since varunpant has not been seen since a year, I guess we can compile and push the jar to jitpack ourselves?

**Comment by est31** [comment]
@misaochan that isn't even required. Right now it points to nicholas's fork already (with the customisations of that PR). All that's needed now is for @nicolas-raoul to publish a fix for the unit tests on github and then update the commit hash.

**Comment by nicolas-raoul** [comment]
@est31: I just ran `mvn test` and strangely it works:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running SpatialTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec - in SpatialTest
Running QuadTreeTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in QuadTreeTest

Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by est31** [comment]
@nicolas-raoul did you use the code from https://github.com/varunpant/Quadtree/pull/3 ?

**Comment by nicolas-raoul** [comment]
@est31 Yes, more precisely I am running tests on this fork: https://github.com/nicolas-raoul/Quadtree

**Comment by est31** [comment]
@nicolas-raoul I've freshly cloned that repo and am getting the error that jitpack gets. Maybe delete the target directory?

**Comment by nicolas-raoul** [comment]
Indeed!

**Comment by nicolas-raoul** [comment]
Fixed now :-)

**Comment by est31** [comment]
Wonderful :) I've updated the PR to the new commit.

**Comment by nicolas-raoul** [comment]
Not sure why it is failing this time?

**Comment by est31** [comment]
Mhh, no idea, I've rebased now lets try it again.

**Comment by est31** [comment]
Okay, it should be now fixed.

**Comment by est31** [comment]
(problem was duplicate junit)

**Comment by est31** [comment]
Btw, The app is on f-droid now. If you want, you can include a [badge on your website](https://gitlab.com/fdroid/artwork/tree/master/badge) like this one:

[](https://f-droid.org/app/fr.free.nrw.commons)

**Comment by nicolas-raoul** [comment]
@est31 https://github.com/commons-app/commons-app.github.io/issues/14 :-)

**Comment by nicolas-raoul** [comment]
@est31 Commons app 1.32 includes your fix, would you mind getting it published on F-Droid? Thanks a lot!
#82

**Comment by est31** [comment]
Yes, of course, in a moment...

**Comment by est31** [comment]
Hrmm, seems you didn't tag commit 1927dfb1b9c7d9c8e7151287350f620597c58b09. Could you do that (and with future releases as well)? Then I could turn on automatic syncing of the versions, and updates would appear without manual action 0-2 days after your release on f-droid.

**Comment by nicolas-raoul** [comment]
I now tagged the latest commit as "v1.32", is it enough?

**Comment by est31** [comment]
Yes its what I wanted :) I've pushed the update and enabled auto update mode: https://gitlab.com/fdroid/fdroiddata/commit/e629f706

**Comment by nicolas-raoul** [comment]
Thanks! By the way, the app is not in beta anymore, we are stable and actually if things go smoothly we could reach 2.0 in less than a year :-)

**Pull request merged**
