### PR TITLE
Shorten query - please do not merge this

### LINKED ISSUE #4560: Split Nearby into a fast query for coordinates + a details query for each pin
Nearby is too slow to use in Paris:
1. Be in the center of Paris (or use a fake GPS app to pretend)
2. Open Nearby
3. Spinning forever, never finishes

I suggest **splitting** the current big SPARQL requests into:
- a first simple request that only returns **QID,coordinates** pairs.
- for each pin, an asynchronous request that loads the place's **details**: name, description, class, existence, etc.

I did some tests (both with 1km radius):
- [Request currently performed by the app](https://query.wikidata.org/sparql?query=SELECT%0A%20%20%20%20%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%0A%20%20%20%20%20%3Fitem%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemLabelPreferredLanguage%2C%20%3FitemLabelAnyLanguage%29%29%20as%20%3Flabel%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FitemDescriptionPreferredLanguage%2C%20%3FitemDescriptionAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3Fdescription%29%0A%20%20%20%20%20%28SAMPLE%28%3FclassId%29%20as%20%3Fclass%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3FclassLabelPreferredLanguage%2C%20%3FclassLabelAnyLanguage%2C%20%22%3F%22%29%29%20as%20%3FclassLabel%29%0A%20%20%20%20%20%28SAMPLE%28COALESCE%28%3Ficon0%2C%20%3Ficon1%29%29%20as%20%3Ficon%29%0A%20%20%20%20%20%3FwikipediaArticle%0A%20%20%20%20%20%3FcommonsArticle%0A%20%20%20%20%20%28SAMPLE%28%3FcommonsCategory%29%20as%20%3FcommonsCategory%29%0A%20%20%20%20%20%28SAMPLE%28%3Fpic%29%20as%20%3Fpic%29%0A%20%20%20%20%20%28SAMPLE%28%3Fdestroyed%29%20as%20%3Fdestroyed%29%0A%20%20%20%20%20%28SAMPLE%28%3FendTime%29%20as%20%3FendTime%29%0A%20%20%20WHERE%20%7B%0A%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%282.3294%2048.8674%29%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%221.00%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelPreferredLanguage.%20FILTER%20%28lang%28%3FitemLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20description%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20description%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionPreferredLanguage.%20FILTER%20%28lang%28%3FitemDescriptionPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20OPTIONAL%20%7B%3Fitem%20schema%3Adescription%20%3FitemDescriptionAnyLanguage%20%7D%0A%0A%20%20%20%20%20%23%20Get%20Commons%20category%20%28P373%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP373%20%3FcommonsCategory.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P18%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP18%20%3Fpic.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P576%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP576%20%3Fdestroyed.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20%28P582%29%0A%20%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP582%20%3FendTime.%20%7D%0A%0A%20%20%20%20%20%23%20Get%20the%20class%20label%20in%20the%20preferred%20language%20of%20the%20user%2C%20or%20any%20other%20language%20if%20no%20label%20is%20available%20in%20that%20language.%0A%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20p%3AP31%2Fps%3AP31%20%3FclassId.%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelPreferredLanguage.%20FILTER%20%28lang%28%3FclassLabelPreferredLanguage%29%20%3D%20%22en%22%29%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%3FclassId%20rdfs%3Alabel%20%3FclassLabelAnyLanguage%7D%0A%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FwikipediaArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fen.wikipedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%3FcommonsArticle%20%20%20schema%3Aabout%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fcommons.wikimedia.org%2F%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20%7D%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%20GROUP%20BY%20%3Fitem%20%3FwikipediaArticle%20%3FcommonsArticle%0A&format=json): Timeout after 60 seconds
- [Simplified request](https://query.wikidata.org/sparql?query=SELECT%0A%20%20%20%20%20%3Flocation%0A%20%20%20%20%20%3Fitem%0A%20%20%20WHERE%20%7B%0A%20%20%20%20%20%23%20Around%20given%20location...%0A%20%20%20%20%20SERVICE%20wikibase%3Aaround%20%7B%0A%20%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point(2.3294%2048.8674)%22%5E%5Egeo%3AwktLiteral.%0A%20%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%221.00%22%20.%20%23%20Radius%20in%20kilometers.%0A%20%20%20%20%20%7D%0A%20%20%20%7D&format=json): Returns all results in 11 seconds

Due to radius stepping, the request that fetches coordinates is often performed several times, making it even more important to fine-tune.
Fetching details afterwards means that some pins will disappear when `Exists` is enabled, but I don't think it is problematic as it is disabled by default, users who willingly enabled it will understand why the pins disappear.

Latest master.

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**
Dear reviewer, I know you can't resist to merge my PRs but this one is for test purposes only :)
Fixes #4560 

This PR simplifies nearby query to see how much time we will save. Thus it does not get information about places, it passes mock strings to them instead. You can compare API call times for master and this branch to see if there is any difference.

(You may think that markers are not loaded, please select "Exists" and "WLM" filters and deselect "Needs photo" to see them)

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
- Near my place: loads noticeably faster than before.
- In Paris: Takes a long time but at least it loads, whereas on master it times out.

**Comment by ashishkumar468** [comment]
Thanks for the quick PR @neslihanturan . I will share the comparison soon

**Comment by ashishkumar468** [comment]
Unfortunately for me, Paris still timesout.

**Comment by ashishkumar468** [comment]
For Brisbane City : Nearby Query took 13 secs on Nes's commit while on master it took 45 secs

**Comment by nicolas-raoul** [comment]
This query seems to work even faster:
```
SELECT
    ?location
    ?item
  WHERE {
    # Around given location...
    SERVICE wikibase:around {
      ?item wdt:P625 ?location.
      bd:serviceParam wikibase:center "Point(${LONG} ${LAT})"^^geo:wktLiteral.
      bd:serviceParam wikibase:radius "${RAD}" . # Radius in kilometers.
   }
}
```
It might require the addition of a few Java-side dummy values.
@neslihanturan Would you mind trying? :-)

**Pull request closed without merging**
