### PR TITLE
Introduce dagger

### PR DESCRIPTION
**Pull request by maskaravivek**
Really excited to finally introduce dagger to our app. #890

This PR simply introduces dagger, a lot of `CommonsApplication` usage can be reduced by replacing it with DI. 

Test plan:
Ran the app and checked. Things work as expected.

### CODE REVIEW

**Comment by psh** [comment]
The full benefit of Dagger wont be realized until we've gone through and applied it in more places within the app so this PR feels (on first blush) like its all the pain and little gain ... and with Dagger there's definitely some pain in getting it properly setup.  That said, you've given us a solid working foundation to build from here.  I'm in favor of merging this so we can keep the cleanup moving forward.  

👍

**Comment by maskaravivek** [comment]
Yes, @psh I agree with you that its benefits can be realised when its used in many more places. But a lot of cleanup at other places would be needed before we reach to a point where dagger can be used. For eg. `AsyncTask` is something where I am not sure if dagger could be applied without custom injectors. 

Have kept this PR minimal just so that we have dagger in our code base and then other contributors can easily take up small cleanup tasks.

**Comment by neslihanturan** [comment]
Actually, for I while I am trying to test this PR. But it fails with:
`Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForBetaDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
`
Note: it builds successfully on master. I couldn't find the solution. Do you have any idea @maskaravivek ?

**Comment by maskaravivek** [comment]
@neslihanturan I was experiencing the same issue some time back on a different branch and a clean build solved the issue. Not sure why it happens. Thanks for testing and merging it :)

**Pull request merged**
