### PR TITLE
Fixes 4745 : Add bookmarked items to suggested depictions

### LINKED ISSUE #4745: Add bookmarked items to suggested depictions
The app now allows the user to bookmark Wikidata items, thanks to Ayan-10.

Since bookmarked items are probably things that the user has an interest for or encounters frequently, it would be good to append them when suggesting depictions (typically at the Upload Wizard's "depicts" step).

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Fixes #4745 

What changes did you make and why?

Since bookmarked items are probably things that the user has an interest in, I append them when suggesting depictions.

**Tests performed (required)**

Tested ProdDebug on Pixel 3 with API level 30.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
I will start reviewing this after https://github.com/commons-app/apps-android-commons/pull/4725 (which is higher priority) is perfected and merged, thanks for both! :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul As #4725 is merged, you can review it now.

**Review by nicolas-raoul — COMMENTED** [review]
Looks good to me, and it works fine.
I will test a bit more and probably merge in a few days.
Thanks! :-)

**Review by nicolas-raoul — APPROVED** [review]
Apologies for the very long delay Ayan, this is working well! Thanks a lot :-)

**Pull request merged**
