### PR TITLE
(fixes #5856) Unchanged / inconsistent username in different pages . (#5856) #5856

### LINKED ISSUE #5856: [Bug]: Unchanged / inconsistent username in different pages
### Summary

After changing the username, the user can see the changed name in contributions page.
However, in explore section, the username hasn't changed in their post.

For example, user changed the name from Haonan11123 to Haonan, which can be seen in contribution page.
image

In explore page, the username was still Haonan11123
image

https://github.com/user-attachments/assets/782fc81d-6602-4c56-a1e5-ee89ff7d3a6f

### Steps to reproduce

1. upload and post a picture
2. change the user name
3. set "use custom author name" in setting 
4. check username in explore page and contribution page

### Expected behaviour

When turning on the "use custom author name" button, we expected the **custom username** edited by user should be shown in every page. In other words, the username should be consistent.

### Actual behaviour

The username in explore page hasn't been changed.

### Device name

_No response_

### Android version

Android 12 

### Commons app version

5.0.2

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by lzh12311**
**Description (required)**

Fixes #5856

What changes did you make and why?

Use the getAuthor(metadata) instead of imageInfo.user

The original code used imageInfo.user, which simply fetched the registered username of the media uploader. In contrast, the new code employs getAuthor(metadata), pulling the author information from the ExtMetadata object to emphasize the custom author name. This adjustment is deliberate, ensuring that the licensing name (custom author name) is showcased in the user profile rather than the default registered username.

**Tests performed (required)**

Tested {ProdDebug} on {MuMu emulator  Android 12} with API level {API 34}.

**Screenshots (for UI changes only)**

3161729077628_ pic

3171729077628_ pic

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Code looks good!
If you think it is ready, please remove the "draft" status of this pull request and I will review. :-)

**Comment by nicolas-raoul** [comment]
Actually I just tested and it seems to work.

**Comment by lzh12311** [comment]
I've removed the draft status/

**Review by nicolas-raoul — APPROVED** [review]
Tested, fixes the issue in Explore

**Comment by nicolas-raoul** [comment]
Thanks a lot! :-)

**Pull request merged**
