### PR TITLE
[GSOC] Added Image Fetch

### PR DESCRIPTION
**Pull request by 4D17Y4**
Added coroutine Image fetch from the device.

### CODE REVIEW

**Comment by 4D17Y4** [comment]
Tasks remaining.

- [ ] Permission
- [ ] Folder count
- [ ] Image thumbnail
- [ ] Sha1 of original image
- [ ] Documentation.

**Comment by 4D17Y4** [comment]
Up for review @nicolas-raoul, @madhurgupta10.
Folder framgment is almost final.
State of images in image fragment would change depending on the selected and uploaded images.

**Comment by nicolas-raoul** [comment]
It works great!
The scrolling is as smooth as before, thumbnails load very quickly.

Images seem to be faded compared to other gallery apps, maybe some setting when loading thumbnails? Or when applying the overlay?

Colors seen on Galaxy's stock gallery, the open source OpenGallery app, Google Photos, as well as when seeing each of the pictures themselves:
adb

Colors seen in the Commons custom selector:
adb

**Comment by 4D17Y4** [comment]
Disabled overlay, now it should work just fine.

**Comment by nicolas-raoul** [comment]
Ah, I understand now, the fading was intentional, sorry I forgot that! 😅

**Review by nicolas-raoul — APPROVED** [review]
Looks good to me :-)

**Pull request merged**
