### PR TITLE
Fix-Peer Review Buttons not get disabled after voting an Image for deletion

### LINKED ISSUE #5516: [Bug]: Peer Review Buttons are not disabled while next image is Loading After Nominating it for deletetion
### Summary

In Peer Review the No and Yes Buttons are not disabled even after nominating it for deletion and it is loading the next Image

### Steps to reproduce

1. Open The App
2. Go to "Review"
3. Nominate any Image For Deletion By Clicking No

### Expected behaviour

The "No" and "Yes" Buttons Should be Disabled Until Next Image is Loaded (as it happens after clicking yes)

### Actual behaviour

The Buttons are still active and you can interact with them which will result in unwanted results or even errors.

### Device name

Xaomi 11 Lite NE

### Android version

Android 13

### Commons app version

4.2.1-debug-main

### Device logs

_No response_

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/126143257/6efe59f6-c89d-4a64-8d27-2a2ea1863efa

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5516 

What changes did you make and why?
Peer Review Buttons ("Yes" and "No") gets disabled to after nominating an Image for deletion to avoid Incorrect Input from user.

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

https://github.com/commons-app/apps-android-commons/assets/126143257/401791e7-accb-4007-a02c-f61ef3967113

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I noticed a bug:

1. At question `Does this follow the rules of copyright?`, tap `No`. The buttons are correctly disabled.
2. Continue reviewing the next picture.
3. At question `Does this follow the rules of copyright?`, the buttons are incorrectly already disabled, before I have a chance to tap any for that picture.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]

**Comment by shashankiitbhu** [comment]
@nicolas-raoul thanks for reviewing and finding this bug, will make changes to fix this

**Comment by shashankiitbhu** [comment]
@nicolas-raoul If these changes I made works then can you review this PR please, thanka

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Just Pinging In case you missed it, Please Review

**Comment by nicolas-raoul** [comment]
Apologies, I have been trying to peer review until I see a bad image to delete, but the uploads are all good...

**Review by nicolas-raoul — APPROVED** [review]
Seems to be working.

After nominating for deletion I repeatedly tapped on Yes and No but the buttons did nothing, they appear to be greyed out. Also, I could review more pictures afterwards normally.

https://github.com/commons-app/apps-android-commons/assets/99590/a933d3b4-62b8-4675-b412-c62ea80af25d

**Pull request merged**
