### PR TITLE
resolved rtl issue in category

### LINKED ISSUE #2566: Category suggestions wrong in RTL
**Steps to reproduce:** 

1. Switch Android to RTL language such as Hebrew
2. Upload image
3. When selecting categories, you see this:
Screenshot_20190306-203852
Checkboxes should be on the left and category names on the right.

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Checbox visible at right in RTL languages and to left in ltr languages**

Fixes #2566 Category suggestions wrong in RTL

### Changes made
Checked whether configuration is for RTL if yes then modify checkbox layout for RTL

**Screenshots showing what changed (optional - for UI changes)**
WhatsApp Image 2019-03-10 at 1 07 54 AM

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Only judging from your screenshot: Checkboxes should be on the left and category names on the right, I believe?

**Comment by vanshikaarora** [comment]
@nicolas-raoul, Sincere apologies I have misunderstood the Issue before :( .Here is the modified code. Kindly review the changes :)

**Comment by vanshikaarora** [comment]
**Updated Screenshot is here**
WhatsApp Image 2019-03-11 at 4 29 36 PM

**Comment by nicolas-raoul** [comment]
Looks good!
It will look even better when categories are localized or when we switch to Structured Commons, but that will be much much bigger change ^_^

**Comment by vanshikaarora** [comment]
>It will look even better when categories are localized

I completely agree with you, this needs to be done. Aren't the localised category available from API?

**Comment by nicolas-raoul** [comment]
> Aren't the localised category available from API?

This is more or less the topic of #44, an issue opened 3 years ago :-)

**Comment by vanshikaarora** [comment]
>This is more or less the topic of #44, an issue opened 3 years ago :-)

I just saw that
It would be great if this can be implemented, either by language setting after retrieving data from API. I'll look into that the issue.

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @nicolas-raoul @maskaravivek :)

**Pull request merged**
