### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by misaochan**
It feels like the template for reporting bugs is a bit redundant - we have summary, steps to reproduce, observed behaviour AND expected behaviour, which all are very similar. I think that by paring it down to the essentials, people will be less likely to skip steps.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
I would argue that the expected/observed part is important, especially when receiving reports from users with low IT literacy and must describe all problems as "it does not work".

**Comment by misaochan** [comment]
Hmm. How about if I add information about how to describe the problem under the **Steps to reproduce:**  section?

**Comment by neslihanturan** [comment]
I also agree they are redundant, what about adding an extended description under **Steps to reproduce** section something like "what was expected behaviour and what did you get"

**Comment by misaochan** [comment]
Added extended description. :)

**Pull request merged**
