### PR TITLE
fixes issues related to location permission denial even when allowed inside in-app camera flow

### LINKED ISSUE #5273: In-app camera does not open when location permission is revoked
### Summary

The in-app camera should open even when the user does not grant location permission to the app. While this works fine in the first run, it does not open when the permission is denied for the second time or revoked later. For more details, you may check [this comment](https://github.com/commons-app/apps-android-commons/pull/5249#pullrequestreview-1566689963).

### Steps to reproduce

1. On a fresh installation, tap the in-app camera button 
2. Allow the app to record location for in-app shots 
3. Tap "Deny" when asked for location permission. The in-app camera will open with a toast
4. Try to open the in-app camera again and repeat step 2

### Expected behaviour

The in-app camera should open again with the same toast.

### Actual behaviour

The in-app camera does not open at all.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

master and prodDebug

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by srishti-R**
**Description (required)**

Fixes #5273 

What changes did you make and why?
Location permission issue fixed for in-app camera flow.

**Tests performed (required)**

Tested {prodDebug} on {pixel 5 emulator} with API level {30}.

**Screenshots (for UI changes only)**
https://github.com/commons-app/apps-android-commons/assets/53987325/961d4a5d-5a00-4cfd-9fcf-afe2cf873379

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by srishti-R** [comment]
Some bug came up with #5299 merging, sorry for all the confusion caused. Just needed to add a return statement at one place.

**Review by nicolas-raoul — COMMENTED** [review]
I start testing, I will hopefully be able to merge within 12 hours. :-)

**Comment by nicolas-raoul** [comment]
Unless I misunderstand, it seems like the issue described in #5273 is still present on my Android 14 Pixel 7 Pro as seen in the screencast below?

https://github.com/commons-app/apps-android-commons/assets/99590/6b8a940d-38f9-48e4-862e-c50728356e45

Namely, the in-app camera does not open the second time after tapping "_Don't allow_" when asked "_Allow Commons to access this device's location?_" by the Android OS.

Note: I believe the notification permission dialog seen in the screencast is unrelated.

**Comment by nicolas-raoul** [comment]
Ah yes, I can confirm that the issue reported by Sivaraam in that comment is fixed indeed, thanks! 🙂

**Comment by srishti-R** [comment]
@nicolas-raoul Made the fixes for location flow when using camera. Removed the use of dexter library for location permissions and used native permission methods instead, please review. Thanks!

**Review by nicolas-raoul — APPROVED** [review]
Looks fine, and works well, I tried many times, denying or removing location permission, and never observed the problem of in-app camera not opening.
Removing Dexter usage is sensible as that library is unmaintained.

**Pull request merged**
