### PR TITLE
Clicking "More" on tabLayout caused it to be displayed on toolbar (in any other language than English)

### PR DESCRIPTION
**Pull request by dado1111**
When you clicked "More" option on bottom tabLayout, it should NOT be displayed on toolbar.

There was a hardcoded: 

### **String.equals("More"),** 

so it worked only for English version and i changed it to: 

### **String.equals(getString(R.string.more))**

I dont think screenshots are so neccessary for this, as it is a trivial issue. 
If needed, i can add them :)

### CODE REVIEW

**Comment by dado1111** [comment]
May i ask what the problem is? Im first time (globally) pull-requesting and am not sure, what the codecov/patch check wants.

I should meet the target of 38.81%  diff, what does that mean actually?

Thought this would be a simple merger tho :/

**Comment by madhurgupta10** [comment]
> May i ask what the problem is? Im first time (globally) pull-requesting and am not sure, what the codecov/patch check wants.
> 
> I should meet the target of 38.81% diff, what does that mean actually?
> 
> Thought this would be a simple merger tho :/

Hi @dado1111, your branch is 3 commits behind the master, if you rebase your branch, it should fix the checks.

The build is passing successfully so merging your PR would not be an issue :)

**Comment by madhurgupta10** [comment]
@neslihanturan I looked up the reason for the patch check fails. It is due to the reason that no new lines added in this PR are covered in tests i.e. 0.00% of diff hit, even though the author @dado1111 has added a test. Currently, any lines inside Lambda functions are skipped by the test framework, the only way (that I am aware of) is to refactor the code like in https://github.com/commons-app/apps-android-commons/pull/4675

For this PR, I don't think it is necessary since the number of lines is minimal.

**Comment by dado1111** [comment]
So, as i understand now. You will merge this PR, even tho tests failed, right?

**Pull request merged**
