### PR TITLE
[GSoC] Show uploaded images differently.

### PR DESCRIPTION
**Pull request by 4D17Y4**
Tasks :

- [x] Clear the cache dir.
- [x] Uploaded images thumbnail.
- [x] Improve loading.
- [x] Document code.
- [ ] Remove Temporary map.

### CODE REVIEW

**Comment by 4D17Y4** [comment]
Can be tested now @nicolas-raoul, @madhurgupta10. 
May crash as some conditions are unchecked (Like cache dir overflow, file not found exceptions to name a few.)

**Comment by nicolas-raoul** [comment]
I somehow get this build error:
```
app/src/main/res/values/strings.xml:631:2: Resource and asset merger: The content of elements must consist of well-formed character data or markup.
    org.xml.sax.SAXParseException; lineNumber: 631; columnNumber: 2; The content of elements must consist of well-formed character data or markup.
    ```

**Comment by nicolas-raoul** [comment]
I somehow had a conflict, solving it fixed the build, now it works great! The loading of uploaded-or-not information is pretty fast :-)
Thumbnails do not appear for already-uploaded pictures, it seems.

**Comment by nicolas-raoul** [comment]
It seems that thumbnails do not appear until uploaded-or-not status is known?
How about making thumbnails and uploaded-or-not independent (asynchronous)? For instance, thumbnails should load as fast as usual even when there is no Internet connection.

**Comment by nicolas-raoul** [comment]
After testing for a minute, my IP address got banned. 😅
It seems that we need to slow down the pace of API requests, unfortunately.
How about having a queue that limits requests to 1 request per second?
Ideally the queue should be LIFO rather than FIFO, so that pictures that the user are seeing on screen right now are queried first.

**Comment by 4D17Y4** [comment]
> It seems that thumbnails do not appear until uploaded-or-not status is known?

Yup, I loaded the same image loading thumbnail as contributions until the results are available.

> How about making thumbnails and uploaded-or-not independent (asynchronous)? For instance, thumbnails should load as fast as usual even when there is no Internet connection.

Yup that could be done, but sometimes the loading is not as fast as we would expect, for eg on scrolling multiple times.
In that case, we have to disable the listeners from all of the images so that the user does not select any uploaded image.
I can set the default listeners of the view to false, that way we can see the image but cannot select it until the request is complete.

I'll try and let u know.


> EDIT: I was not banned, it was my mistake 😅

No problem, but is there a certain limit we should be worried about?

Also, the application cache might have blown up, I did not clear it.
I'll fix it in further commits.

**Comment by 4D17Y4** [comment]
For the LIFO, I've blocked the query of images that are not in view anymore, but the queries which are posted would still be waiting for the result and I need to figure out a way to cancel them. 
I had tried the request queue previously but there was no significant difference as I was checking the view visibility on every stage of operation. 
I'll try to figure out a way to do this in a coroutine.
Thanks.

**Comment by 4D17Y4** [comment]
Also as I have mapped the query result, it saves time on the subsequent queries of the same image.

**Comment by nicolas-raoul** [comment]
> "so that the user does not select any uploaded image"
We should indeed prevent the user from selecting images that we know have been uploaded already, but whenever the API is too slow or whenever the API is down, we should allow users to select pictures for which we do not know uploaded-or-not status.

I would say that allowing the user to quickly scroll and see thumbnails to find a picture they took in the past is the most important. Retrieving uploaded-or-not status is the purpose of this GSoC, but it should not jeopardize finding images fast.
The ideal would be: scrolling/thumbnails as fast as in your previous PRs + uploaded-or-not status showing within a second if cached, or within a few seconds if the API is reachable, or not showing otherwise.

I don't know the API limit, I guess there is one, even if not documented. I will test the app with tons of pictures, if I do not reach the limit then it is probably a non-problem :-)

Thanks for caching the results in `mapResult`! That is a good first step towards caching in SQLite :-)

**Comment by nicolas-raoul** [comment]
No need to cancel queries, don't worry. Cancelling a query would probably not even reduce server load, so better catch the response and save it in cache.

I was talking about LIFO when I thought I had been banned, but then I edited my comments to remove any mention of it (I often edit my messages so better read on the GitHub website than read the GitHub emails). I hope API limits are high so that you don't have to worry about that :-)

**Comment by nicolas-raoul** [comment]
Wonderful, the loading is great now! :-)
I used the selector to upload dozens of pictures, single or sets, all worked nicely.

**Comment by 4D17Y4** [comment]
Up for review @nicolas-raoul, @madhurgupta10.

Will start with SQLite caching in the next PR.

**Comment by nicolas-raoul** [comment]
Tested with a dozen uploads, worked great.

**Pull request merged**
