### PR TITLE
Fixes #3231 "Nearby" always first puts me in Punta Arenas

### LINKED ISSUE #3231: "Nearby" always first puts me in Punta Arenas
**Steps to reproduce:** 

- Start app
- Go to Nearby

Expected: map centered on Tokyo
Actually: map centered on Puntas Arenas, at the other side of the globe.

Every time.

**Device and Android version:** 

On two different recent phones.
 
**Commons app version:**

2.11.0.500~8472c63

### LINKED ISSUE #3233: No items shown in Nearby
Wherever I go, no pins are shown:

Screenshot_20191129-182904_Commons

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #3231 "Nearby" always first puts me in Punta Arenas and Fixes #3233 
No items shown in Nearby. Previously BookmarkLocationDao tables were updates with an extra column. But upgradeDb method is not called. currently I upgraded and altered new column. However, since our app is on production, I am not sure if this will solve the issue for everyone. Please someone  with more experiences with upgrading databases "safely" consider them during review. Solves issue for me.

### CODE REVIEW

**Comment by ashishkumar468** [comment]
@neslihanturan The code looks fine, but can you maybe elaborate a little as in how this change would solve the referred issue?

**Comment by neslihanturan** [comment]
After we included picture information to our search to check if a place has a picture already or not, I added this information as a column to bookmark locations but I forgot to update db, so there was a no such a column found exception.This exception during populate places method failed the method from successfully returned. So places and correct location never load to map.

**Comment by ashishkumar468** [comment]
Thanks for the explanation @neslihanturan

**Comment by misaochan** [comment]
Solves the problem for me. :) Will merge it and push to master so @nicolas-raoul can try it too.

**Pull request merged**
