### PR TITLE
Hide category view pager in case of no categories

### LINKED ISSUE #2698: Improve peer review feature quality
**Summary:** 

After #2602 is merged #2253 is completed. Now some quality issues from hackathon still needs to be fixed.

- [ ] Code style issues @maskaravivek 
- [x] Move from XML to JSON @maskaravivek 
- [ ] It scrolls, I would prefer static/ support different screen sizes
- [x] Images moves on swipe, just questions should move instead @vanshikaarora 
- [ ] A beta alert should be added somewhere
- [x] Make image clickable - Open media details activity when clicked.
- [ ] Not showing the categories peer review screen for the images having zero categories.
- [ ] Or let the user categorize the image.
- [x] Adding a question mark next to "skip this image" button and Peer Review title which will display an explanation about their usage. @silkypriya 
- [x] Refactor asynctasks to Rxjava implementation @vanshikaarora 
- [ ] Write unit tests with kotlin @neslihanturan 
- [ ] Optimize randomizer
- [x] Extracting string resources for i18n

I am willing to work on some of them. But we can share, anyone wants to work on them please comment down.

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**
In case of no category of image skip to next question in review activity

Fixes #2698 Improve peer review feature quality

### Changes made
On category view pager in case of zero categories enlisted swipe to next view pager.

### CODE REVIEW

**Comment by neslihanturan** [comment]
@domdomegg , can you share how did you tested? I also tried to test this PR but I couldn't. Because I couldn't find any upload with no category at all. There are auto added categories, so I couldn't test. @vanshikaarora how did you tested this when you are working on? Can you please share the exact successful file?

**Comment by domdomegg** [comment]
> @domdomegg , can you share how did you tested? I also tried to test this PR but I couldn't. Because I couldn't find any upload with no category at all. There are auto added categories, so I couldn't test. @vanshikaarora how did you tested this when you are working on? Can you please share the exact successful file?

On beta there are a lot of uncategorized images as I don't think they are automatically added. For example the one in the GIF `MobileTest 190321-112640.jpg`

**Comment by neslihanturan** [comment]
But there are categories on mentioned file @domdomegg , see bottom of the page https://commons.wikimedia.beta.wmflabs.org/wiki/File:MobileTest_190321-112640.jpg

**Comment by domdomegg** [comment]
Screenshot_1553724796

Yeah, I'm not sure how but it seems to ignore automatic categories. Another example in screenshot above: https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test_93.jpg

<details>
<summary>Maybe relevant logs</summary>

```
2019-03-27 22:12:43.714 30186-30233/fr.free.nrw.commons.beta D/CustomApiResult: API response for method https://commons.wikimedia.beta.wmflabs.org/w/api.php is
     <?xml version="1.0" encoding="UTF-8"?><api batchcomplete=""><warnings><main xml:space="preserve">Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.</main><revisions xml:space="preserve">The parameter "rvgeneratexml" has been deprecated.
    Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.</revisions></warnings><query><pages><page _idx="64070" pageid="64070" ns="6" title="File:Test 93.jpg"><revisions><rev parsetree="&lt;root&gt;&lt;h level=&quot;2&quot; i=&quot;1&quot;&gt;== &lt;template&gt;&lt;title&gt;int:filedesc&lt;/title&gt;&lt;/template&gt; ==&lt;/h&gt;&#10;&lt;template lineStart=&quot;1&quot;&gt;&lt;title&gt;Information&#10;&lt;/title&gt;&lt;part&gt;&lt;name&gt;description&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;&#10;&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;source&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;&lt;template&gt;&lt;title&gt;own&lt;/title&gt;&lt;/template&gt;&#10;&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;author&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;[[User:Whym test1|Whym test1]]&#10;&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;date&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;&lt;template&gt;&lt;title&gt;According to EXIF data&lt;/title&gt;&lt;part&gt;&lt;name index=&quot;1&quot;/&gt;&lt;value&gt;2019-02-05&lt;/value&gt;&lt;/part&gt;&lt;/template&gt;&#10;&lt;/value&gt;&lt;/part&gt;&lt;/template&gt;&#10;&lt;h level=&quot;2&quot; i=&quot;2&quot;&gt;== &lt;template&gt;&lt;title&gt;int:license-header&lt;/title&gt;&lt;/template&gt; ==&lt;/h&gt;&#10;&lt;template lineStart=&quot;1&quot;&gt;&lt;title&gt;self&lt;/title&gt;&lt;part&gt;&lt;name index=&quot;1&quot;/&gt;&lt;value&gt;cc-by-sa-3.0&lt;/value&gt;&lt;/part&gt;&lt;/template&gt;&#10;&#10;&lt;template lineStart=&quot;1&quot;&gt;&lt;title&gt;Uploaded from Mobile&lt;/title&gt;&lt;part&gt;&lt;name&gt;platform&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;Android&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;version&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;2.9.0-debug-stash-upload~119384e40&lt;/value&gt;&lt;/part&gt;&lt;/template&gt;&#10;&lt;template lineStart=&quot;1&quot;&gt;&lt;title&gt;Uncategorized&lt;/title&gt;&lt;part&gt;&lt;name&gt;year&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;2019&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;month&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;February&lt;/value&gt;&lt;/part&gt;&lt;part&gt;&lt;name&gt;day&lt;/name&gt;&lt;equals&gt;=&lt;/equals&gt;&lt;value&gt;5&lt;/value&gt;&lt;/part&gt;&lt;/template&gt;&lt;/root&gt;" contentformat="text/x-wiki" contentmodel="wikitext" xml:space="preserve">== {{int:filedesc}} ==
    {{Information
    |description=
    |source={{own}}
    |author=[[User:Whym test1|Whym test1]]
    |date={{According to EXIF data|2019-02-05}}
    }}
    == {{int:license-header}} ==
    {{self|cc-by-sa-3.0}}
    
    {{Uploaded from Mobile|platform=Android|version=2.9.0-debug-stash-upload~119384e40}}
    {{Uncategorized|year=2019|month=February|day=5}}</rev></revisions></page></pages></query></api>
```
</details>

**Comment by neslihanturan** [comment]
@domdomegg no template added on my tests when there is an automatic category. Actually, nothing happens when I skip the image under this condition, and this is expected behaviour I think. But I never experience a entirely non categorized image.

Maybe @nicolas-raoul can know. It is possible to find an image with literally no categories (If no, this PR has no impact on real life). Or every image will have some categories, at least auto added ones.

**Comment by nicolas-raoul** [comment]
@neslihanturan I am not sure sorry, the easiest to to just try, I guess :-) Or check the many images that get uploaded without categories every day.

**Comment by neslihanturan** [comment]
Please feel free to reopen this PR again if you really feel that this is needed. currently it seems like a caution for an impossible case

**Pull request closed without merging**
