### PR TITLE
fixed typo in nearbyActivity

### PR DESCRIPTION
**Pull request by 97balakrishnan**
Fixed small typo in nearbyActivity :)

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @97balakrishnan but I think this is fine as is. Since people used to use that word as Lng:)

**Comment by 97balakrishnan** [comment]
It was like LatLang i have changed it to Lng
Since it represents Latitude and Longitude it should be either LatLong or LatLng.. pls go through the changes once again if possible

I dont know if this has been corrected already

**Comment by neslihanturan** [comment]
Sorry for misunderstanding, thanks @97balakrishnan

**Comment by 97balakrishnan** [comment]
Thank you :)

**Pull request merged**
