### PR TITLE
Fixes Issue #4787: Update Java version from Java 8 to Java 11

### LINKED ISSUE #4787: Moving to JDK 11?
**Summary:** 
I see this warning in the console, so maybe we should consider moving to JDK 11+

```
warning: Current JDK version 1.8.0_312-b07 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.
```

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by elemcraft**
**Description (required)**

Fixes #4787

What changes did you make and why?
Changes the `JavaVersion.VERSION_1_8` to  `JavaVersion.VERSION_11` in `build.gradle`

**Tests performed (required)**

Tested `betaDebug`, `betaRelease`, and `prodDebug` on emulator Pixel 6 API 34

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by elemcraft** [comment]
Hello, @nicolas-raoul 

No worries. 
This is the result I have on my desktop using virtual device Pixel 6 API 34 
image

**Comment by elemcraft** [comment]
Hello, @nicolas-raoul 

No worries. This is the upload I ran on virtual device Pixel 6 API 34

image
image

**Comment by nicolas-raoul** [comment]
Thanks!

**Review by nicolas-raoul — APPROVED** [review]
Built and tested, all main features still working. Thanks for your contribution!

**Comment by elemcraft** [comment]
Thank you for giving me this chance to contribute.

**Pull request merged**
