### PR TITLE
Fixes #1268 Update buildTools and libraries.

### LINKED ISSUE #1268: Update libraries version to the latest stable version.
**Summary:** 

The project is using old version of libraries, for which already an update version have been released.
Following libraries are outdated:

- Gson from 2.8.1 to 2.8.2

- okHttp from 3.8.1 to 3.9.1

- Fresco from 1.3.0 to 1.5.0

- Leakcanary from 1.5.1 to 1.5.4

- Kotlin from 1.1.15 to 1.2.30

Should be also update buildToolsVersion and compileSdkVersion to 27?

### PR DESCRIPTION
**Pull request by knight-shade**
## Description

Fixes #1268 

Below are the libraries then have been updated and all tests in betaDebug and betaRelease are successful.
fresco to 1.5.0
leak-canary to 1.5.4
support library version to 27.1.0
compileSdkVersion to 27
buildToolsVersion to 27
targetSdkVersion to 27
multidex to 1.0.3

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @knight-shade ,

Thanks for your PRs, we really appreciate them! One request - could you please use more descriptive titles for your PRs? For instance, "Fixes #1278" is great for the first line of the PR description, but not for the title of the PR. The aim of the title is to tell people at a glance what the PR does, and in this case it wouldn't tell them anything unless they search for issue 1278. 

In this case, "Update libraries and build tools" might be a better title. ;)

**Comment by nicolas-raoul** [comment]
Indeed, "`Fixes <title of the issue> (#issuenumber)`" or similar makes it easier to not get lost in the high number of pull requests :-)

**Comment by knight-shade** [comment]
Sure @nicolas-raoul @misaochan :smile:

**Comment by neslihanturan** [comment]
@knight-shade sorry not to merge this earlier, but if you fix conflicts I will merge.

**Comment by knight-shade** [comment]
@neslihanturan Merge conflicts have been fixed, and i updated the travis CI file a little bit to include android-27 and latest build tools version(27.0.2).
All the test pass successfully locally, but 2 test fails on Travis CI.

`fr.free.nrw.commons.nearby.NearbyAdapterFactoryTest > clickView FAILED
    java.lang.AssertionError at NearbyAdapterFactoryTest.java:117
fr.free.nrw.commons.nearby.NearbyAdapterFactoryTest > rendererCorrectlyBoundForUnknownPlace FAILED
    org.junit.ComparisonFailure at NearbyAdapterFactoryTest.java:100`
Any idea why this might be happening?

**Pull request closed without merging**
