### PR TITLE
Issue 3236: Change nearby search text to white

### LINKED ISSUE #3236: White font for place type search box and "x"
I could not find 😂
It hides part of the map.
Screenshot_20191129-185633_Commons

### PR DESCRIPTION
**Pull request by albendz**
**Description (required)**

Fixes #3236  White font for place type search box and "x"

What changes did you make and why?

Applied the white search box theme to the nearby search bar. This theme is currently in use by the explore search bar.

**Tests performed (required)** Manual

Tested prodDebug on emulator with API level 28.

**Screenshots showing what changed (optional - for UI changes)**

nearby

What it looks like with entered text:

nearbysearchtext

Dark mode:

darkhint

darktext

I see the blank white in the dropdown on master as well.

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by maskaravivek** [comment]
@albendz Can you also share a screenshot for the dark mode?

**Comment by albendz** [comment]
@maskaravivek Added the dark mode captures as well. Something is up with the dropdown on dark mode but I confirmed it's the same on master.

**Comment by nicolas-raoul** [comment]
Looks great! :-)

**Comment by neslihanturan** [comment]
I verify there is a night mode issue apart from this issue. This code perfectly works:)

**Review by neslihanturan — APPROVED** [review]
Thanks a lot @albendz !

**Pull request merged**
