### PR TITLE
Image downloading fixed

### LINKED ISSUE #1216: Image downloading fails
### Summary
Clicking the download button after going to My Recent Recent Uploads fails to download an image to the phone's storage even when the app has been granted Storage Permission.

### Screenshots

whatsapp image 2018-02-27 at 9 09 05 am 2
whatsapp image 2018-02-27 at 9 02 21 am 2

### System Logs
The log report can be found at this link:
[Log Report File](https://docs.google.com/document/d/1iFANGofxS37m9KHb7kZIQOdNAK3aybGCTXPTFY6m8vs/edit?usp=sharing)

### Device and Android version
Redmi Note 3
6.0.1 MMB29M
MIUI Version: MIUI Global 8.5
 
 **Commons app version:** 
2.6.7

### PR DESCRIPTION
**Pull request by gupta-meghna64**
### Description
Clicking the download button now downloads each image uploaded in future without any kind of failure. The first download is however a bit slow, but the subsequent downloads happen in < 1 second.
The PR fixes #1216  

### Testing
The changes have been tested on a real-time device and a few corner cases for image titles have been tried out as well.
Tried out test cases: 
1) ČSD ř. M 260.001 1939-02.17. 24.jpg
2) دمشق جبل قاسيون.jpg
3) A. b. c. d 1.2 . 3

### CODE REVIEW

**Comment by gupta-meghna64** [comment]
Please review this :)

**Comment by misaochan** [comment]
Sorry for the slow review. This does not work for me - when I tap "Download", nothing happens and this error displays:

```
03-26 00:51:02.647: W/System.err(19362): org.json.JSONException: No value for imageinfo
03-26 00:51:02.647: W/System.err(19362): 	at org.json.JSONObject.get(JSONObject.java:389)
03-26 00:51:02.647: W/System.err(19362): 	at org.json.JSONObject.getJSONArray(JSONObject.java:584)
03-26 00:51:02.647: W/System.err(19362): 	at fr.free.nrw.commons.media.MediaDetailPagerFragment$1.onResponse(MediaDetailPagerFragment.java:200)
03-26 00:51:02.647: W/System.err(19362): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-26 00:51:02.647: W/System.err(19362): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-26 00:51:02.647: W/System.err(19362): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-26 00:51:02.647: W/System.err(19362): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-26 00:51:02.647: W/System.err(19362): 	at java.lang.Thread.run(Thread.java:761)

```

**Comment by gupta-meghna64** [comment]
@misaochan could you please provide the browsing link of the image you tried downloading? Thanks

**Comment by misaochan** [comment]
https://commons.wikimedia.org/wiki/File:Seafood_platter_at_the_lighthouse_restaurant_Brisbane.jpg and https://commons.wikimedia.org/wiki/File:Restaurant_at_Wellington_point_lighthouse.jpg

**Comment by neslihanturan** [comment]
Is this PR sleeping? Or do you continue to work on it @gupta-meghna64 ?

**Comment by misaochan** [comment]
@gupta-meghna64 Feel free to post here if you would like us to reopen this, thanks!

**Pull request closed without merging**
