### PR TITLE
Add list of nearby places without photos

### PR DESCRIPTION
**Pull request by misaochan**
Implement #73

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Conflict it seems? Would you mind rebasing or pulling from master?

**Comment by nicolas-raoul** [comment]
Otherwise, the code looks good so feel free to merge :-)

**Comment by misaochan** [comment]
Oof, there are 71 files that have merge conflicts, mostly the various strings.xml files for different languages. :/ Do I really need to go through all of them and resolve them manually?

**Comment by nicolas-raoul** [comment]
You changed 24 files, so there will only be 24 conflicts at most.

**Comment by misaochan** [comment]
The conflicts aren't in the files that I changed though. For instance in values-te/strings.xml the conflicting lines of code are

```
 <string name="app_name_beta">వికీమీడియా కామన్స్ బీటా</string>
<string name="provider_campaigns">ప్రచారాలు</string>
```

And so on and so forth for other languages

**Comment by nicolas-raoul** [comment]
Very strange.
To solve the problem quickly: Download the current master as a zip, replace all of your language files (except the English one) with those from the ZIP, and `git add` all of them and commit/push

**Comment by nicolas-raoul** [comment]
(after merging the real conflicts of cours ^^)

**Comment by misaochan** [comment]
Odd, that doesn't work either, now I just have 130 conflicts (because the error.xml in all the language folders are conflicting now). Is it okay if I just put the language folders in .gitignore?

**Comment by misaochan** [comment]
Okay, I think this might be what's causing the issue:

```
2016-09-03 16:58:41.6702|WARN|thread: 1|StandardUserErrors|Showing user error Failed to create a new commit.
GitHub.IO.ProcessException: fatal: pathspec 'app/src/main/res/layout/activity_campaigns.xml' did not match any files
```

I checked, and before I even pulled from commons-app/master, these xml files did not exist in my layout directory. And the PR that I'm trying to merge is removing those files. So I can't merge a commit that removes a file that I didn't already have, I guess?

Although I'm not sure why they are in commons-app/master. I thought I had already removed them some time ago, hmm.

**Comment by misaochan** [comment]
Edit: I think I should have mostly fixed it via command line. Will test and merge shortly.

**Pull request merged**
