### PR TITLE
Fixed issue #812

### PR DESCRIPTION
**Pull request by ftsalamp**
Fixed issue #812 using Approach A.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks for this PR @ftsalamp . 
According to my tests on android 5.0.2:
- It works as intended, saves the photo to gallery on cancellation of upload.
However, tests on android 4.2.2:
- Failed with security exception, gallery is stopped. With such error:
`java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{42992670 2928:com.android.gallery3d/u0a52} (pid=2928, uid=10052) that is not exported from uid 10151`

**Comment by neslihanturan** [comment]
This is a quite important fix, however need some small changes to pass tests. I want to edit this PR to merge it as soon as possible, however there is several approaches to edit someone else's PR. Does anyone can tell me the best approach, to make our commit history stay clean?

**Comment by nicolas-raoul** [comment]
@neslihanturan 
1. Have the person git rebase to master, if possible
2. Create a feature branch with the same name from the same point
3. Pull from their branch
4. Do as if it were yours
I would say.
Here ftsalamp worked directly in master, but I suggest you create a feature branch for it.

**Comment by neslihanturan** [comment]
Thanks @nicolas-raoul , but I have a small uncertainty. Since this changes on master branch of ftsalamp's fork, and you said create a feature branch from same point, with same name, what should be the name of the new feature branch?

**Comment by nicolas-raoul** [comment]
How about something like bugfix-812 ?

**Comment by neslihanturan** [comment]
It seems like my tests failed because of a problem that exists on master branch too. So I decided to resolve that issue on another PR. For now, I only resolved conflicts to be able to merge this changes, on another branch by @nicolas-raoul advise. Thanks for this changes @ftsalamp .

**Comment by misaochan** [comment]
@neslihanturan Shall we close this so we can focus on #876 ?

**Pull request closed without merging**
