### PR TITLE
Combined upload

### PR DESCRIPTION
**Pull request by psh**
Based on designs shared in #1128, this code introduces a new `UploadActivity` that aims to replace the old Share / Multi-Share activities.  As mentioned in #1091, this is a work in progress but should help get things started.

### CODE REVIEW

**Comment by misaochan** [comment]
@psh Thanks for submitting this! :) I loved the mockups on #1128 and the code structure in UploadActivity looks far better than its predecessor's IMO.

Just to clarify, do the basic functions of UploadActivity work for you currently? I understand from what you mentioned at #1091 that all the additional stuff (e.g. quality checks, GPS extraction etc) has not yet been implemented. However, I haven't managed to get any of the basic functionality to work personally. I can see that the gallery/camera icons in Contributions haven't been hooked up, but even using Gallery > Share > Commons app (which looks like it SHOULD work) crashes me every time (error log below). I'm not very familiar with Jacoco and not very sure why a code coverage library keeps throwing fatal exceptions, or if the exceptions are even related to this PR (this is not our only jacoco-related crash, see #1483 ).

Am I missing something, or is the basic functionality not intended to be tested yet?

```
05-10 03:10:47.207 17259-17259/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.debug, PID: 17259
    java.lang.IllegalAccessError: Final field 'fr.free.nrw.commons.upload.UploadView.$jacocoData' cannot be written to by method 'boolean[] fr.free.nrw.commons.upload.UploadView$$CC.$jacocoInit$$STATIC$$()' (declaration of 'fr.free.nrw.commons.upload.UploadView$$CC' appears in /data/app/fr.free.nrw.commons.debug-2/base.apk:classes2.dex)
        at fr.free.nrw.commons.upload.UploadView$$CC.$jacocoInit$$STATIC$$(Unknown Source)
        at fr.free.nrw.commons.upload.UploadView.<clinit>(UploadView.java)
        at fr.free.nrw.commons.upload.UploadPresenter.<init>(UploadPresenter.java:26)
        at fr.free.nrw.commons.upload.UploadPresenter_Factory.get(UploadPresenter_Factory.java:21)
        at fr.free.nrw.commons.upload.UploadPresenter_Factory.get(UploadPresenter_Factory.java:7)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$UploadActivitySubcomponentImpl.injectUploadActivity(DaggerCommonsApplicationComponent.java:1513)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$UploadActivitySubcomponentImpl.inject(DaggerCommonsApplicationComponent.java:1493)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent$UploadActivitySubcomponentImpl.inject(DaggerCommonsApplicationComponent.java:1474)
        at dagger.android.DispatchingAndroidInjector.maybeInject(DispatchingAndroidInjector.java:81)
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:102)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.inject(CommonsDaggerAppCompatActivity.java:40)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:22)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:23)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onCreate(AuthenticatedActivity.java:32)
        at fr.free.nrw.commons.upload.UploadActivity.onCreate(UploadActivity.java:106)
        at android.app.Activity.performCreate(Activity.java:6912)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

```

**Comment by psh** [comment]
Two things that could have contributed - 
* I was only testing by sending pictures from the photos app on the phone rather than buttons within the app - specifically driven by wanting to test the incoming intents in the manifest.  
* I rebased and rebuilt the code against master, but didnt run it before submitting.

I have been playing with the newest versions of Android Studio - they might have updated the gradle version / gradle wrapper properties - the `.gradle` and `gradle` directories might be suspect and could be flushed + copied from the `master` version.

**Comment by maskaravivek** [comment]
Thanks for the PR @psh 

Although we appreciate the efforts put into making these changes, I am not in favor of merging it as:
- the mentioned PR is still a WIP. It's sometimes difficult to build upon code that has changed 1000s of lines and might break/undo a few functionalities. Analysing and fixing all those issues would take a lot of time as our testing process is still manual. 
- the PR in itself tries to address two issues: refactoring, adding combined uploads. A PR should ideally address just one issue unless the changes can't be segregated
- It would add a substantial amount of workload on the team if the combined upload is picked up along with the refactoring at this moment. Originally the plan was to pick up just the refactoring for now.

**Comment by psh** [comment]
If it's not useful right now, and conflates multiple issues, that's fine.

**Pull request closed without merging**
