### PR TITLE
Null checks for activity to prevent unwanted crashes

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

There are multiple warnings in the `MediaDetailPagerFragment` for `getActivity()` or `getContext()` being null. This PR fixed that.

### CODE REVIEW

**Comment by neslihanturan** [comment]
@maskaravivek , does these null checks increase possibility of hiding crash logs from user reports? Because if something is null, we want to know it. Maybe you can add logs to these null checks?

**Comment by maskaravivek** [comment]
Yes, I guess adding logs to these null checks makes sense. Most of the checks that I have added are related to the activity being active or destroyed so it shouldn't affect the upload flow(which is a service). 

But I agree that we should have logs for this. I will update the PR with log lines.

**Comment by neslihanturan** [comment]
This PR waits for log lines and fixing conflicts:)

**Comment by maskaravivek** [comment]
@neslihanturan Have added the required logs. :)

**Comment by neslihanturan** [comment]
Thanks @maskaravivek

**Pull request merged**
