### PR TITLE
Rephrase title/desc without slash

### PR DESCRIPTION
**Pull request by amire80**
This looks more natural in English.

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @amire80 ,

Thanks for submitting this. However, the reason the short form was chosen was because this text is on a button underneath the title and desc fields - having a long sentence might be a bit unwieldy there. We are quite new to localization; is there a convention we should use for denoting that a particular string needs to be short (for a button, etc)?

**Comment by amire80** [comment]
Just don't do it. Strings may have to be longer in many languages by their nature; Russian, Finnish, and Tamil are common examples. It can be a problem in English, too, because many devices may be smaller than the developer's device. Because of all this, forcing strings to be short is usually a bad idea. The right solution is to make sure that the interface element can grow with the string.

Technically, you can suggest this in the documentation (values-qq), but I strongly recommend not doing this.

**Comment by misaochan** [comment]
The button is able to grow with the string - however, it looks better when relatively short.

**Comment by amire80** [comment]
If this app is supposed to be useful for people who aren't used to developers jargon, it's better to say "description" in English and not "desc".

**Comment by misaochan** [comment]
Could "use previous title & description" work?

**Comment by amire80** [comment]
Yeah, that's OK in English. I can do it.

**Comment by whym** [comment]
I have created https://translatewiki.net/wiki/Wikimedia:Commons-android-strings-use_previous/qqq . I guess it is acceptable to suggest, rather than to enforce, translators to use short forms, is it?

**Comment by misaochan** [comment]
Oh, just noticed this was still in the list of PRs. There was a misunderstanding where I made the change in my fork at the same time that @amire80 modified his PR. Closing, feel free to reopen if you disagree.

**Pull request closed without merging**
