### PR TITLE
Give toast when trying to upload image without giving a Title #1195

### LINKED ISSUE #1195: Give toast when trying to upload image without giving a Title
small issue. When uploading a new image, if I click on the next button at top right without filling in a title, it does nothing. A toast that reads "Please give a Title to proceed" would be helpful. I can start working on this :)
shot

### PR DESCRIPTION
**Pull request by tshradheya**
## Description

Fixes #1195

**Outline of Soultion**
- Made submit button always enabled. Before it was disabled when title was empty and it wasn't intuitive to user as to what is happening on click when title is empty
- Whenever the submit button is clicked with title empty a toast is shown as in screenshot

## Screenshots showing what changed
 
whatsapp image 2018-02-26 at 2 17 59 pm

### CODE REVIEW

**Comment by tshradheya** [comment]
@neslihanturan Could you review this as you have reviewed my PR's before?

**Comment by neslihanturan** [comment]
@tshradheya currently it works exactly as intended. 
Giving disabled design to send button is also an approach. Currently it is meaningless because it looks same when it is disabled or enabled. I think this approach is more expected and familiar. What do you think?

And what everyone else think? If any one agrees with the strategy implemented here, I will merge.

**Comment by tshradheya** [comment]
While trying to find a solution to this, initially I was unaware that the button was disabled cause it looked exactly the same to me. This is not very good for users cause they can still press the button but see no response. 

I feel the current solution is better cause
1. The button is always enabled so it always responds
1. Giving a toast makes the instruction clear

**Comment by maskaravivek** [comment]
We can probably have this fix for now and maybe take up the enabled/disabled design later.

**Comment by tshradheya** [comment]
@maskaravivek  @neslihanturan Any update on this?

**Comment by tshradheya** [comment]
Sorry for bothering.
This PR is ready for review :)

**Comment by maskaravivek** [comment]
LGTM.

**Comment by misaochan** [comment]
Sorry for the late comment, but "Please give a Title to proceed" feels slightly off to me. Perhaps "Please provide a title for this file" (without the capital T) might be better?

**Comment by neslihanturan** [comment]
Should we revert @misaochan ?

**Comment by tshradheya** [comment]
I will just create another PR to quickly fix the message

**Pull request merged**
