### PR TITLE
Migrated logEvents to retrofit

### PR DESCRIPTION
**Pull request by ilgazer**
This PR migrates ContributionsSyncAdapter to the new UserClient method and refactors the old and messy sync code in ContributionsSyncAdapter to use RxJava. It also changes ContributionsSyncAdapter so that all previous uploads are retrieved on sync instead of just new ones. This was causing bugs and the difference is a few more kilobytes of data.

I have no idea how to test this :|

### CODE REVIEW

**Comment by maskaravivek** [comment]
IMO, it would be better if we start using `imageinfo` API instead of `logEvents` for fetching contributions. See #2904

**Comment by ilgazer** [comment]
IMO it would be better if we did away with ContributionsSyncAdapter. How important is caching the user's contributions?

**Comment by maskaravivek** [comment]
> IMO it would be better if we did away with ContributionsSyncAdapter and connected our data sources(ContributionDao for failed uploads etc. and UserClient for online data) to the recyclerview directly. How important is caching the user's contributions offline?

Yes, I agree. Its being discussed here #3070. Can you put your thoughts on the issue thread. If no one disagrees, we can go ahead with the change. :)

**Comment by ilgazer** [comment]
IMO anything we do for #3070 will be much larger in scope than this PR. I think we should merge this in the short term so that we can get rid of ApacheHttpClientMediaWikiApi, CustomMwApi, and the related logic.

**Comment by maskaravivek** [comment]
@ilgazer Can you check the build failure?

**Comment by ilgazer** [comment]
I have, and it passes the same test on my PC. Could you take a look at #3102

**Comment by ashishkumar468** [comment]
@ilgazer Have you tried running this particular test handleSubmitTest in UploadPresenterTest.kt:63. Travis complains that this is failing

**Comment by ilgazer** [comment]
Yes, and it's passing on my pc.

**Pull request merged**
