### PR TITLE
added bookmarkLocationFragment unit tests

### PR DESCRIPTION
**Pull request by 4D17Y4**
**Description (required)**
Added BookmarkLocationFragmentUnitTests.

**Tests performed (required)**
Tested betaDebug on Nokia 6.1+  with API level 29.

### CODE REVIEW

**Comment by 4D17Y4** [comment]
Up for review. 
@nicolas-raoul , @madhurgupta10

**Comment by madhurgupta10** [comment]
@4D17Y4 can you post a screenshot of code coverage report for this class?

**Comment by 4D17Y4** [comment]
image
@madhurgupta10 screenshot of code coverage.
Thanks.

**Comment by madhurgupta10** [comment]
@4D17Y4 can you export this report and share a screenshot of the file where we can see lines hit/miss. Thanks!

**Comment by 4D17Y4** [comment]
image
image

Here are the screenshots @madhurgupta10 
I'm not sure what u mean by exporting this report, should I send the HTML script of the report?

**Comment by madhurgupta10** [comment]
> I'm not sure what u mean by exporting this report, should I send the HTML script of the report?

The screenshot is fine, Thanks

Will it be possible to cover few more missed lines?

**Comment by 4D17Y4** [comment]
image
image
image

Added some tests @madhurgupta10

**Comment by madhurgupta10** [comment]
@4D17Y4 Thanks, good coverage!

**Review by madhurgupta10 — APPROVED** [review]

**Pull request merged**
