### PR TITLE
Changed the share button color in About activity.

### LINKED ISSUE #4217: Share button color should be changed from white to black in About Activity.
**Summary:** 

In the About Activity screen, a share button is present at the top right corner but not visible due to its white color. To make it visible its color should be changed to black.

**Steps to reproduce:** 
Open About section in Menu Bar.
There is a share button at the top right corner of the toolbar. 

What did you expect the app to do, and what did you see instead?
The share button should be visible in black color.

**Device and Android version: ** 
Samsung J7 Prime

 
**Commons app version:**  
Latest Master

**Screen-shots:** 
ShareButtonAboutActivityPic

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Roshan13046**
**Description (required)**

Fixes #4217

What changes did you make and why?

Changed the share button color from white to gray color. Previously in the About Activity share button was not visible due to its white color.

**Tests performed (required)**

UI changes are successfully done.

Tested {ProdDebug} on {Samsung J7 Prime} device.

**Screenshots (for UI changes only)**
ShareButtonColorChangedInAboutActivity

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @Roshan13046 , thanks for the PR. We dont directly edit drawable colors, since it can be used in the app and it may suppose to remain white there. When we edit the color directly from the drawable we change colors of whole usages. Instead we better to use "?attr". So that we can use proper one in dark theme and the other one in light theme. You can simply search "?attr" in code to see example usages. We have tons of them. 

Please do not forget to add screenshoots for both light and dark theme next time.

**Comment by neslihanturan** [comment]
Hi, any update with this? If you have questions please do not hesitate to ask, if you don't interested anymore please let us know so that another contributor can solve the issue :)

**Comment by Roshan13046** [comment]
> Hi, any update with this? If you have questions please do not hesitate to ask, if you don't interested anymore please let us know so that another contributor can solve the issue :)

working on this issue. will fix it soon.

**Comment by sivaraam** [comment]
Hi @Roshan13046, Just wanted to check-in on the status of this issue. Were you able to look into making the suggested changes?

**Comment by madhurgupta10** [comment]
I am closing this PR because the author seems to be inactive, feel free to reopen if needed :)

**Pull request closed without merging**
