### PR TITLE
Feature/localised image descriptions

### PR DESCRIPTION
**Pull request by ashishkumar468**
## Specify language when adding image descriptions 

Specify language when adding image descriptions #1501

## Description : 
Converted the descriptions edit text to a recycler veiw with and option to add description in various languages

## Tests performed :  
Open the app, click on the camera/gallery icon to upload an image, the next screen which would usually show an option to add a single description, would now let you add description in multiple languages (the default (first) one would be the device locale). Submit the request. After upload success, open the image description, I could now see description in my device current locale. 

Tested on {27l & name of Moto x, with {build variant,  ProdDebug}.

## Screenshots showing what changed (optional)
 
screenshot_20180618-160310

### CODE REVIEW

**Comment by maskaravivek** [comment]
The feature works well for me and I was able to upload an image with descriptions in multiple languages. The descriptions show up well on Commons. 

https://commons.wikimedia.org/wiki/File:Gandhi_ji_painting_at_Aga_khan_palace.jpg

@ashishkumar468 Can you sort the languages drop-down list alphabetically. Right now it's a bit difficult to browse through so many language options.

**Comment by ashishkumar468** [comment]
@maskaravivek  Thanks for the review, have updated the same

**Comment by misaochan** [comment]
@ashishkumar468 I'm not sure about the block. but will ping @whym and @nicolas-raoul who might hopefully be able to help.

In the future, for uploading test images please use the **betaDebug** build variant as far as possible. All uploads to the prodDebug build variant will go to the real Commons, and indeed the community may not be too happy with it.

**Comment by nicolas-raoul** [comment]
Sorry about the block!
The only way to remove a block is to follow https://commons.wikimedia.org/wiki/Commons:Blocking_policy#Appealing_a_block

But before doing this, maybe we should use your case to test the block detection code in the app? :-)

**Comment by ashishkumar468** [comment]
Thanks guys, will do the same

**Comment by ashishkumar468** [comment]
Just a gentle reminder, the PR is ready for review

**Comment by misaochan** [comment]
Sorry for the wait for review, @ashishkumar468 , we are having a bit of a backlog with work at the moment. :/ Will get to it ASAP.

**Comment by neslihanturan** [comment]
Works with no problem for me @ashishkumar468 , thanks for this great feature. Just a few points:
- Instead of just scroll view for languages, can we use scroll view with input field? There are several languages, and hard to find one by scrolling.
- On Media Details Activity we just see latest description. I think we should be able to see descriptions in all languages. But This can be another issue and PR. As:
    **En**: some description
    **Tur**: Bazı açıklamalar
- Should we let entering description in same language twice? I think we shouldn't. But this also can be a separate issue and PR.

For this PR, first bullet and fixing conflicts is important. Others can wait.

**Comment by ashishkumar468** [comment]
Hi @neslihanturan, Thanks for the feedback, Could you elaborate the first bullet, As far as i understand, you mean to say that instead of two recycler views which is there currently, you want only one recycler view which would hold both the language field and  the description field?

**Comment by neslihanturan** [comment]
It is very normal you didn't get what I meant:) I was trying to say, you can use a listview with "search filter". So that when I want to use Turkish language, I can just type Turkish to search bar, instead of scrolling all the languages and trying to find Turkish.

**Comment by ashishkumar468** [comment]
@neslihanturan  Ohh yes got it it now, Thanks for the clarification, will work on the same raise a new PR

**Comment by maskaravivek** [comment]
> Instead of just scroll view for languages, can we use scroll view with input field? There are several languages, and hard to find one by scrolling.
This can probably come as an enhancement in a separate PR. Its nice to have the basic functionality for multiple descriptions. Moreover, this screen could get a complete overhaul quite soon.  

@ashishkumar468 Can you please resolve the merge conflicts so that this PR can be merged.

**Comment by ashishkumar468** [comment]
@maskaravivek @neslihanturan Have resolved the conflicts, (@neslihanturan Will take a while to add the filter you suggested, will update you once done). Also I noticed that startForeground has not been handled properly for Oreo devices.

**Comment by ashishkumar468** [comment]
The travis build failed with some exception in SettingsActivityTest, does not seems any way related to my commit, what am i supposed to do ?

**Comment by maskaravivek** [comment]
@ashishkumar468 Have you rebased your branch with latest master? The build for master is successful.

**Comment by ashishkumar468** [comment]
@maskaravivek I have already merged with master, you can see the logs from git

**Comment by ashishkumar468** [comment]
@maskaravivek Did the required changes. Please verify

**Comment by maskaravivek** [comment]
Works well for me. Merging. Thanks @ashishkumar468

**Pull request merged**
