### PR TITLE
Fix:4797:Add one more choice to the list

### LINKED ISSUE #4797: Peer review: Add one more choice to the list
peer review feature:

No FoP in copyright-related reasons for deletion (the second question). This is one of the most common reason for deletion, it should be in the list. Proposed message: "There is no freedom of panorama in the country where this picture was taken, so some installations (even permanently displayed in public spaces) can not be freely photographed and shared."

### PR DESCRIPTION
**Pull request by awanishyadav967**
**Description (required)**

Fixes #4797

What changes did you make and why?
Added one more list in Review section ,Breach of Freedom of Panorama rules. Made two changes ,add a variable no_freedom_of_panorama in file app/src/main/re/value/string.xml and  add a list in file app/src/main/fr/free/nrw/commons/delete. 

**Tests performed (required)**

Tested  on {RealmeRMX2001} with API level {30}.

### CODE REVIEW

**Review by Ayan-10 — COMMENTED** [review]
Screenshot_1678304338

An unexpected extra blank check box is showing.

**Comment by awanishyadav967** [comment]
Thanks ,I will work on it

**Comment by awanishyadav967** [comment]
Done ,the Extra Blank checkbox is not showing now ,thanks.

**Comment by nicolas-raoul** [comment]
I guess this should be closed in favor of #5173, if not do not hesitate to re-open.

**Pull request closed without merging**
