### PR TITLE
Remove BitmapUtils (fixed #2638)

### LINKED ISSUE #2638: Remove BitmapUtils
**Summary:** 

Currently in achievements the level badge (`badge.xml`) has the level number drawn on top with `BitmapUtils`. I think it would be better to somehow use a normal `TextView` overlaid on the badge to do this. This would have three benefits:
- Massively reduce opportunity for bugs
- Crisper text as not rendered to a bitmap
- Marginally better performance

**Screen-shots:** 

Screenshot_1552843041

**Would you like to work on the issue?**

No. For someone that would the appropriate files are likely to be `BitmapUtils` and `AchievementsActivity` (particularly the method `inflateAchievements`)

### PR DESCRIPTION
**Pull request by zhao-gang**
**Description (required)**

Fixes #2638 

Use a TextView on top of badge image to show user's level.

**Tests performed (required)**

Tested current master ProdDebug on Nexus 6P with API level 27.

**Screenshots showing what changed (optional - for UI changes)**

| previous badge | badge with TextView |
| --- | --- |
| badge-original | badge-text |

### CODE REVIEW

**Comment by zhao-gang** [comment]
I found the UI tweaking is a little hard for me. Currently the badge image size is larger than before, and I use hard-coded dp for the TextView's margin and text size. Hope someone can give some advices on how to make it exactly the same as the former badge image :-)

**Comment by nicolas-raoul** [comment]
Looks good!
Have you checked whether the Share button shows the number correctly?

**Comment by zhao-gang** [comment]
@nicolas-raoul share image seems OK.
badge-share

**Comment by neslihanturan** [comment]
Thanks @zhao-gang !

**Pull request merged**
