### PR TITLE
Fix nearby position not updating

### LINKED ISSUE #674: Position is  not updated by nearby
It is still possible to get a empty Nearby list with GPS turned on and position available.

Steps to reproduce in emulator:
1) Turn off GPS
2) Go to Nearby list (don't turn on GPS)
3) In NearbyActivity `curLatLong` will be `null`.
4) List is empty
5) Turn on GPS
6) Go to home screen
7) Back to nearby.
8) In NearbyActivity `curLatLong` will still be `null`.
9) Change location using the emulator.
10) This fires in `LocationServiceManager` the `onLocationChanged` method.
11) Next refresh will now again contain items.

Waiting for Android to detect a location change might not be the best way to get the current location.

### PR DESCRIPTION
**Pull request by neslihanturan**
This PR meant to fix #674 . Tested on Android 4.4.2.

### CODE REVIEW

**Comment by misaochan** [comment]
@tobias47n9e could you let us know if this fixes the issue for you? Thanks! :)

**Comment by neslihanturan** [comment]
Our travis has some problems, I think. It says:
 `Warning: License for package Android SDK Platform 26 not accepted.`
Does anyone know how to fix it?

**Comment by tobias47n9e** [comment]
+1 

I tested it in Android Studio and triggering a position change and then hitting refresh seems to work now.

**Comment by misaochan** [comment]
Great, thanks guys!

**Pull request merged**
