### PR TITLE
add information about translations

### PR DESCRIPTION
**Pull request by janpio**
I added a small paragraph about translating the app with links to the "Commons Android App project" on translatewiki.net where changes have to be made.

### CODE REVIEW

**Comment by mwoguri** [comment]
This is useful information, thanks!  Though it isn't clear to me (as a new contributor) what steps (if any?) I need to take after changing a string resource.  Could that information be included?

**Comment by janpio** [comment]
I just made my first translations on translatewiki myself, so I have no idea. 

Getting "translation rights" there also wasn't easy (have to translate 20 strings, was rejected with no comment, only asking in IRC got my new account approved), but that I considered out of scope for this README.

What information would you be looking for besides "go there and save a translation"?

**Comment by misaochan** [comment]
Thanks for the PR, @janpio . I will merge this soon unless anyone has anything to add.

@mwoguri AFAIK the person submitting the translation does not need to do anything further. Everything after that is done by the translatewiki team and their bots.

I have found that getting an approved translatewiki account was difficult as well. Unfortunately we do not have any say in that.

**Comment by janpio** [comment]
Added this additional information as it seems useful.

**Comment by mwoguri** [comment]
Even adding just the information that the person adding/changing a string in `strings.xml` doesn't have to take any additional steps would be useful.  My first PR (https://github.com/commons-app/apps-android-commons/pull/785) involved string changes and after doing some searching I was (and still am?) unsure if I took the right steps to get it translated correctly.

**Comment by misaochan** [comment]
@mwoguri Sorry I missed your question on your other PR! I will ping @Nikerabbit for confirmation on your question, as well as his opinions on the information in this PR.

**Comment by janpio** [comment]
Let me know if any further changes to my PR are needed. 
Maybe it makes sense to accept it first and add information about handling string stuff in the app in a later PR though so changes don't get too big.

**Comment by mwoguri** [comment]
Thanks @misaochan.

**Pull request merged**
