### PR TITLE
fix for #667 issue https://github.com/commons-app/apps-android-common…

### PR DESCRIPTION
**Pull request by tised**
Fix for #667 

This bug can be reproduced on low/bad connections only. Because of asynchronus work of getting new categories

Problem was in async requests, and reaction on cancel was wrong.
First of all to decrease impact on phone internet connection - request should start on after text changed, and cancel on before text changed to deliver proper results.

Also requesting on create view was unnecessary, because results may deliver BEFORE view attached to fragment

### CODE REVIEW

**Comment by misaochan** [comment]
Thanks @tised ! I've taken the liberty of modifying your original comment to include a reference to the issue number (just typing the hash will retrieve the issue, no need to paste the whole URL).

@neslihanturan Could you please try and see if this works for you? If it does, this would be a very nice and simple solution compared to editing the imported libraries.

**Comment by tised** [comment]
Okay! My future requests will be with same modifications then :) 

_______________________
Best regards, 
Dmytro Vodnik 

Android developer
Phone: +380930318441
E-mail: tised.dev@gmail.com
Skype: divisor4

**Comment by tised** [comment]
The problem there is in exceptions which throw AsyncTask when you cancel it, and in one case, one throw blocking updating the UI for some reason

I will comeback for this tomorrow, i think i have one idea which may help

**Comment by tised** [comment]
I pushed new changes to this fix.

Seems that throwing IOException inside of AsyncTask avoid latch.countDown() so when we will have results only from PrefixUpdater - we will show them and progress bar will not hang

P.S. I found other issue here, when i change my network from WiFi to 3G requests stops to send, can you check it as well ? @misaochan

**Comment by misaochan** [comment]
@tised Indeed, switching from mobile data to wireless (or vice versa) makes the selection hang for me as well. 

Would you like me to re-test your PR now, or do you have more commits planned?

**Comment by tised** [comment]
@misaochan for this issue no. You can test it
I do not think that switching networks its problem only here

**Comment by misaochan** [comment]
@tised The GPS and title-based category suggestions work now, but the category hang issue persists.

**Comment by neslihanturan** [comment]
I will try this fix as soon as possible. I hope we can solve the issue with such clean code. By the way I have worked on this issue too. I am pretty sure that we should cancel the request on cancel async tasks. You can verify this by testing my patch on #749

It would be very nice if you can find a better way to cancel requests than I do. Or maybe my prediction about the root cause is totally wrong :)

**Comment by whym** [comment]
I entered "Test up" in the category screen, the rotating progress bar never stops and the candidates below the input box did not appear.

```
07-15 13:48:41.167 8295-8364/fr.free.nrw.commons D/TitleCategories: Searching for cats for title: org.mediawiki.api.ApiResult@49697c
07-15 13:48:41.170 8295-8364/fr.free.nrw.commons D/TitleCategories: Title cat query results: []
07-15 13:48:41.240 8295-8295/fr.free.nrw.commons D/CategorizationFragment: Results in onPostExecute: []
07-15 13:48:41.241 8295-8295/fr.free.nrw.commons D/CategorizationFragment: TitleCatItems in onPostExecute: []
07-15 13:48:41.529 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Prefix URL filter org.mediawiki.api.ApiResult@f4de205
07-15 13:48:41.657 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Found categories from Prefix search, waiting for filter
07-15 13:48:41.658 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Year: 2017
07-15 13:48:41.658 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Previous year: 2016
07-15 13:48:41.660 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Items: [Tes-Hem (Tesiin-Gol) River, Tes-Khemsky District, Tesa (brand), Tesaglitazar, Tesalia, Tesarius, Tesarius caelatus, Tesauro Beccaria, Tesařov, Tesařov (natural monument), Tesbury Centre, Hong Kong, Tescani, Bacău, Tesch-Sportplatz, Tesch-Tunnel, Tesch (surname), Tesche (Quartier), Tescheditz, Teschemacher Hof, Teschemacherstraße, Teschen, Teschen (surname), Teschendorf, Teschendorfer Weg (Berlin-Märkisches Viertel), Teschener Weg (Berlin-Zehlendorf), Teschenmoschel]
07-15 13:48:41.661 8295-8364/fr.free.nrw.commons W/CategorizationFragment: java.lang.InterruptedException
                                                                               at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1301)
                                                                               at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
                                                                               at fr.free.nrw.commons.category.CategorizationFragment$2.doInBackground(CategorizationFragment.java:284)
                                                                               at fr.free.nrw.commons.category.CategorizationFragment$2.doInBackground(CategorizationFragment.java:278)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
07-15 13:48:42.006 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Prefix URL filter org.mediawiki.api.ApiResult@5eecc8b
07-15 13:48:42.013 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Found categories from Prefix search, waiting for filter
07-15 13:48:42.013 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Year: 2017
07-15 13:48:42.013 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Previous year: 2016
07-15 13:48:42.014 8295-8364/fr.free.nrw.commons D/PrefixUpdater: Items: [Test uploads]
```

**Comment by neslihanturan** [comment]
Hi @tised , do you think this PR can work with requested changes, or should we close it?

**Comment by akaita** [comment]
#667 ended up being fixed in a different PR. This one can be closed, right?

**Comment by neslihanturan** [comment]
I thnik so

**Pull request closed without merging**
