### PR TITLE
Enhancement - Nearby banner shows Item without image

### LINKED ISSUE #5448: Nearby banner: Show item with no image
The Nearby banner currently shows the nearest Wikidata item.

Instead, I think it should show the nearest Wikidata item **with no image**.

Merits:
- Get users to take the most needed pictures
- After the user uploads the item, the banner will start showing a different item, rather than still showing the same one which is uninteresting.

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5448 

What changes did you make and why?
Changed the logic to show Nearby Banner on Contributions Page to show nearest Item without an Image

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on Xaomi 11 Lite NE with API level 33.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by shashankiitbhu** [comment]
Sure, I will look into it

**Comment by shashankiitbhu** [comment]
@nicolas-raoul Please Review the PR now, I rebased it from the main and tested it too. It should work fine now

**Comment by shashankiitbhu** [comment]
Please Review it @nicolas-raoul , I think this solves the issue

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I tested this branch now.
Despite many items without image around me (shown in the Nearby activity), thee banner shows the closest item (which already has an image).

**Comment by shashankiitbhu** [comment]
It may be because of how nearby locations are added to the list of the places (first only the first 5 are added ), I have made the necessary changes and tested it using fakeGPS too. @nicolas-raoul Please review it and let me know the location you are testing it from and screenshots if the issue persists (I believe it will not this time )

**Comment by nicolas-raoul** [comment]
Would you mind pulling from the main branch and fixing the conflict? Thanks! :-)

**Comment by shashankiitbhu** [comment]
Done, Please Review it @nicolas-raoul

**Comment by shashankiitbhu** [comment]
Can you give me the location from where you are testing it? Does it not appear immediately or have you tried waiting on the screen for a few seconds?

**Comment by nicolas-raoul** [comment]
@shashankiitbhu Sure, can you send me an email at my address found at https://nicolasraoul.github.io? Thanks!

**Comment by nicolas-raoul** [comment]
Sent! :-)
Please let me know if you are able to see the banner appear or not (I waited 30 seconds).

**Comment by shashankiitbhu** [comment]
I tested it on your location using FakeGPS but only found Pins that already have pictures



It is working well on my location (below)

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
