### PR TITLE
Fixes previous PR - FIX #2918 Add option for default language for file descriptions

### LINKED ISSUE #2918: Add option for default language for file descriptions
From a user on FB group:

> I have one more idea for improvement: in the app settings, please add the option default language for the file descriptions
> maybe even number of 1-2 default languages
> for me that would be "bg" (if only one) and "bg" + "en" (if 2 are allowed)
> this will save some time for scrolling up and down the menu, and will - i guess - reduce the number of mistaken languages
> some people will probably not care enough to scroll down this menu everytime and will use the default "en" for whichever language they use
> is this doable?

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**

Fixes #2918 . Some minor changes are made on top of @olgalesan 's changes at #2949 . The PR was tested by me, and working in general. After my changes the issue of default language selection (before the user choose anything) which is phone local language is marked on preference list, along with its summary. 

What changes did you make and why?

Previously only summary of default language was added, on the other hand none of the items on the list was selected. 

Note: Reviewer should close #2949 after merging this PR

**Tests performed (required)**

Tested prodDebug API 26 emulator

**Screenshots showing what changed (optional - for UI changes)**

https://support.google.com/android/answer/9075928
image

### CODE REVIEW

**Comment by domdomegg** [comment]
Doing some testing, this doesn't seem to work once uploaded. After setting default as french, the spinner appears correct but when uploaded it says the description is English:
https://commons.wikimedia.beta.wmflabs.org/wiki/File:MobileTest_3020-2.jpg

I suspect you'll need to change something in initLanguageSpinner in DescriptionsAdapter, as currently the language code is only updated when the spinner is updated and not when it is initialized.

**Comment by neslihanturan** [comment]
Thanks for catching this @domdomegg , I never thought this pull request can effect templates will be passed after upload. Let me check

**Comment by neslihanturan** [comment]
Hi @domdomegg , I was investigating this issue and recognized that this issue also exists at master branch. See my uploads from master:
Screenshot from 2019-06-18 13-18-00
Screenshot from 2019-06-18 13-17-21

I think this issue can be fixed under this same pull request though.

**Comment by neslihanturan** [comment]
As I logged at line 
```
Timber.d("Description language code is: "+languageCode);
```
Language code is correctly handled on spinner. Now the remaining problem is saving this description language and adding it to template accordingly.

**Comment by domdomegg** [comment]
I haven't tested this yet but I think I might not have explained the issue properly. It's not that the template is missing (that's just cause Beta commons doesn't have all of them). It's that the wrong template is applied. In the uploaded example the template is English even though the setting is set to French.

**Comment by neslihanturan** [comment]
Oh okay, I tested on prod. After my changes on init function it works:

image

Let me fix the tests and this PR will be ready.

**Comment by neslihanturan** [comment]
Actually restarting tests fixed the build too. So this PR is ready for testing.

**Pull request merged**
