### PR TITLE
Change "Archived" notifications to "Read" notifications

### LINKED ISSUE #3426: "Archived" notifications should be referred to as "Read"
**Summary:** 

"Read" notifications are referred to as "archived" notifications. However, this is inconsistent with how the website displays the notifications. 

image
 
**What did you expect the app to do, and what did you see instead?**

When you open archived notifications, the option to go back says `View unread` which is again, inconsistent. We should either refer to notifications as  _archived_ and _unarchived_, or _read_ and _unread_. In my opinion, we should follow the latter labelling.

image

**Commons app version:** 

2.12.0-debug-master~d0d663578

**Would you like to work on the issue?**

Yes, if we can agree the issue is genuine then I'd like to work on this.

### PR DESCRIPTION
**Pull request by 6point022**
**Description (required)**

Fixes #3426 - "Archived" notifications should be referred to as "Read"

_What changes did you make and why?_

I replaced the word _archived_ in strings with _read_. However, I did not change the string names, e.g., `menu_option_archived` was not changed to `menu_option_read`. Doing this would require changes in many files, so I'm not sure if it's necessary. In case it is better to change the string names too, please let me know and I will make those changes.

**Screenshots (for UI changes only)**

image

### CODE REVIEW

**Comment by macgills** [comment]
https://translatewiki.net/wiki/FAQ#Is_it_possible_to_rename_message_keys?

>As a general rule: localization efforts should not block development. When there is a good reason to rename a key, do so. Just don't do so frivolously, as this unnecessarily hampers localization efforts.

I think renaming them is a good option but I really don't know the criteria for "frivolous"

**Comment by 6point022** [comment]
@macgills I agree. I think it'll also add more clarity when eventually this change is made for other languages. I have pushed this change. Please review.

**Comment by sivaraam** [comment]
I'm not sure but I think we aren't supposed to touch the strings *and* keys of the strings in the other language files. Translate-wiki would handle it all by itself. @misaochan might know better.

**Comment by macgills** [comment]
Translatewiki shouldn't hinder development and the fact that `refactor>rename/shift+f6` was used is - or should be - totally acceptable in my opinion

**Comment by sivaraam** [comment]
Ideally it shouldn't but I'm doubtful as the [FAQ says](https://translatewiki.net/wiki/FAQ#Is_it_possible_to_rename_message_keys?)

> When renaming a key, it is sufficient to rename just the source language (usually English) keys. The keys for the translations will be renamed during the import process on Translatewiki.net.

I'll pinging Translatewiki per that FAQ.

**Comment by sivaraam** [comment]
@translatewiki A key rename is done in this PR along with a string change. The keys have been renamed in the other language files too. Would that be a problem?

**Pull request merged**
