### PR TITLE
merged into a single condition

### LINKED ISSUE #5046: Small-scale code improvement in ImageFileLoader.kt
In [ImageFileLoader.kt](https://github.com/commons-app/apps-android-commons/blob/9c27f8510d8ea0d05e089f46556ada106456ac8e/app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt#L84), merge into single condition: `file != null && file.exists`

### PR DESCRIPTION
**Pull request by TurquoiseHexagonSun**
**Description (required)**
Requested merge into single condition for #5046

What changes did you make and why?
Merged the two conditions into a single condition at line 84.

**Tests performed (required)**
This was tested with build variant ProdDebug on Pixel 2 and Pixel 5 emulator with API 30.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
My apologies for not checking this earlier, would you mind solving the conflict? Thanks!

**Comment by TurquoiseHexagonSun** [comment]
Hi, this is my first pull request. This is for a class project and I'm very new to contributing to OSS. I tried to choose something small and manageable for my first attempt. I want to make sure I follow through with all of the proper procedures.  If there is anything else I need to do, please let me know. Any help you can offer is appreciated.

**Comment by nicolas-raoul** [comment]
This is a great first pull request.

Yes, there is something that need to be solved: The master branch has changed, so you need to rebase your branch.

If you encounter any difficulty, you can also create a new branch and new pull request. :-)

**Comment by nicolas-raoul** [comment]
https://git-scm.com/docs/git-rebase

**Comment by TurquoiseHexagonSun** [comment]
Hi, thanks for the info. I will try to rebase the branch. If it something goes wrong, let me know and I will try creating a new branch.

**Comment by TurquoiseHexagonSun** [comment]
I unfortunately ran into a data sync issue between my computers and it caused data corruption. I started a new pull request.

**Pull request closed without merging**
