### PR TITLE
Tick icon in place of number of images selected in custom picker

### LINKED ISSUE #5243: Custom picker: Replace numbers with ticks, and display total number of selected pictures in title
When you select 3 pictures in the custom picker, each selected picture has `3` in the corner.

As seen in #5221 this is confusing.

A better UI could be to display just a ✅ in the corner of each picture, and display something like `Camera (3 selected)` in the title (which currently only displays `Camera` or similar).

Having the number of selected pictures is quite important, as upload tends to fail when uploading more than N pictures (with N presumably depending on the environment).

### PR DESCRIPTION
**Pull request by srishti-R**
**Description (required)**

Fixes #5243 

What changes did you make and why?

**Tests performed (required)**

Tested prodDebug on Samsung galaxy M31 with API level 31.

**Screenshots (for UI changes only)**
Screenshot_20231008-220838_Commons

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by srishti-R** [comment]
Not sure about the UI here, I tried using a drawable already present in codebase for tick icon.

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Selection and upload work great.

Would you mind making the text color visible in dark mode? 🙂

**Comment by srishti-R** [comment]
@nicolas-raoul fixed the ui a bit in addition to dark mode fixes and tests, the tick icon is now a bit bold, I feel its more visible now that earlier.
Screenshot_20231009-074727_Commons

**Review by nicolas-raoul — APPROVED** [review]
Perfect, thanks!

**Comment by nicolas-raoul** [comment]
Hi @srishti-R

Sorry for hijacking this thread, but did you submit a proposal?
I can't see any at https://phabricator.wikimedia.org/project/view/6921/

You have good chances, so please do not hesitate unless you have other plans :-)
Just copy/pasting the tasks list from https://phabricator.wikimedia.org/T356237 and adding a minimal schedule (start/finish dates) is enough.

**Comment by srishti-R** [comment]
> Hi @srishti-R
> 
> Sorry for hijacking this thread, but did you submit a proposal? I can't see any at https://phabricator.wikimedia.org/project/view/6921/
> 
> You have good chances, so please do not hesitate unless you have other plans :-) Just copy/pasting the tasks list from https://phabricator.wikimedia.org/T356237 and adding a minimal schedule (start/finish dates) is enough. The deadline is April 2 - 18:00 UTC.

Hi @nicolas-raoul, thank you for the reminder, but this year I have some other unforeseen personal commitments, so I won't be able to dedicate time completely to any project I pick. Nevertheless, I would love to contribute as and when I get time in between.

**Pull request merged**
