### PR TITLE
Fixed image quality warning dialog appears 2 times if you quick on next quickly(#2442)

### LINKED ISSUE #2442: Image quality warning dialog appears 2 times if you quick on next quickly
**Summary:** 

The warning dialog appears twice for an image that fails one of the checks

**Steps to reproduce:** 

- select a place from nearby
- choose a picture to upload (say duplicate image/image with wrong geolocation)
- quickly click on next

You will see an error dialog but notice a flicker. On clicking Yes/No, you can still see the dialog. This is because the dialog appeared twice.

### PR DESCRIPTION
**Pull request by zhao-gang**
**Description (required)**

Fixes #2442 

What changes did you make and why?

Add flag isChecking to class UploadItem to indicate whether it's being
checked for image quality. Checking this flag before starting a new
validation. This should avoid starting a new validation while another
validation is running, which causing image quality warning dialog
appears twice.

**Tests performed (required)**

Tested master betaDebug on Nexus 6P with API level 27.

**Screenshots showing what changed (optional - for UI changes)**

No screenshots but I tested that the warning dialog just appear once if image quality test failed.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@zhao-gang Thanks for the PR. :)

Your approach doesn't look correct to me at first look. I will take a look at the PR tonight. 

You might be aware of `Subject` in Rxjava. If you are not familiar with the concept then this blog might be interesting for you. 

https://blog.mindorks.com/understanding-rxjava-subject-publish-replay-behavior-and-async-subject-224d663d452f

FYI, we are using `BehaviourSubject` to get the processing result.

**Comment by zhao-gang** [comment]
@mashawan Surely there may be a better way to solve this issue than mine :-) I think the reason caused this bug is that the first validation starts running, and then quickly the next button is pressed which caused the second validation starts. Since the first validation has not completed so it does not show the dialog to let the user set the IMAGE_KEEP flag in BehaviourSubject imageQuality, so the second validation also starts the checking(it does not see the IMAGE_KEEP flag, since it has not been set yet and starts the real checking work, which is duplicated to the first one).

The main point is that to the same UploadItem, we should not start a second validation before the first one finished. I add a flag to indicate whether an UploadItem is being checked. There may be other ways to do this.

**Comment by maskaravivek** [comment]
Yes you are right. We should not start a second validation if the first is running. BehaviourSubject would return the latest result to the new callable. Do you mind if I make edits to your PR?

**Comment by zhao-gang** [comment]
@mashawan Please feel free to edit my PR :-)

**Comment by zhao-gang** [comment]
Rebased to current master.

**Comment by macgills** [comment]
I don't think this is an issue anymore, please reopen if this can be reproduced

**Pull request closed without merging**
