### PR TITLE
Handle special characters in notification title

### LINKED ISSUE #1600: Notifications Activity crashes
**Summary:** 

Notifications activity crashes.

**Steps to reproduce:** 

Just opening activity

**Add System logs:**

```
FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons, PID: 7654
                                                 java.util.regex.PatternSyntaxException: Unrecognized backslash escape sequence in pattern near index 4:
                                                 (^\h*)|(\h*$)
                                                     ^
                                                     at java.util.regex.Pattern.compileImpl(Native Method)
                                                     at java.util.regex.Pattern.compile(Pattern.java:411)
                                                     at java.util.regex.Pattern.<init>(Pattern.java:394)
                                                     at java.util.regex.Pattern.compile(Pattern.java:381)
                                                     at java.lang.String.replaceAll(String.java:1785)
                                                     at fr.free.nrw.commons.notification.NotificationRenderer.setTitle(NotificationRenderer.java:73)
                                                     at fr.free.nrw.commons.notification.NotificationRenderer.render(NotificationRenderer.java:62)
                                                     at com.pedrogomez.renderers.RVRendererAdapter.onBindViewHolder(RVRendererAdapter.java:121)
                                                     at com.pedrogomez.renderers.RVRendererAdapter.onBindViewHolder(RVRendererAdapter.java:41)
                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
```

**Device and Android version:** 
Android 4.2.2
 
 **Commons app version:** 

master / productionRelease built variant

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

Fixes #1600 

## Description (required)

Fixes #1600 where notification activity was crashing as soon as it was opened. It was happening for a subset of users who had special characters(read characters in other scripts). Have simply added a `try catch` handling for such cases as I wasn't able to find an elegant solution.

## Tests performed (required)

Not reproducible for me. @neslihanturan Can you help in testing this. :)

### CODE REVIEW

**Comment by neslihanturan** [comment]
Now it gives this error after notifications are displayed:

` FATAL EXCEPTION: main
                                                                         Process: fr.free.nrw.commons.debug, PID: 3839
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
                                                                             at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1723)
                                                                             at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
                                                                             at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:248)
                                                                             at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
                                                                             at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1652)
                                                                             at android.widget.ImageView.applyImageTint(ImageView.java:560)
                                                                             at android.widget.ImageView.updateDrawable(ImageView.java:895)
                                                                             at android.widget.ImageView.setImageDrawable(ImageView.java:472)
                                                                             at android.support.v7.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:99)
                                                                             at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:56)
                                                                             at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:57)
                                                                             at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:15)
                                                                             at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:103)
                                                                             at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:579)
                                                                             at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
                                                                             at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
                                                                             at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:148)`

**Comment by maskaravivek** [comment]
@neslihanturan Can you share the response object for your notification? This seems to be a different error.

**Comment by neslihanturan** [comment]
Sure, here:
`08-20 00:24:27.193 5147-5147/fr.free.nrw.commons.debug D/deneme notification is: ‪Wikimedia Commons We...‬ left a message on your talk page.  , type is:EDIT_USER_TALK
    You just made your first edit; thank you, and welcome!  , type is:THANK_YOU_EDIT
    You just made your tenth edit; thank you, and please keep going!  , type is:THANK_YOU_EDIT
    ‪Jæ‬ left a message on your talk page.  , type is:EDIT_USER_TALK
    ‪Jæ‬ left a message on your talk page.  , type is:EDIT_USER_TALK
    You just made your hundredth edit; thank you very much!  , type is:THANK_YOU_EDIT`
And it actually displays notifications first as in picture, then crashes:
image

Lastly given error is:
` Process: fr.free.nrw.commons.debug, PID: 5282
    java.lang.NullPointerException
        at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
        at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
        at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
        at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:608)
        at android.widget.ImageView.applyColorMod(ImageView.java:1216)
        at android.widget.ImageView.updateDrawable(ImageView.java:716)
        at android.widget.ImageView.setImageDrawable(ImageView.java:421)
        at android.support.v7.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:99)
        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:56)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:57)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:15)
        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:103)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:579)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
        at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
        at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)`

**Comment by neslihanturan** [comment]
Can it be related with loading icon drawables?

**Comment by neslihanturan** [comment]
Update: It also crashes with same error on API level 23, as in 19. So it seems like independent from API level, probably my notifications trigger this crash. I feel like there is an uncovered case about drawables and notification types.

**Pull request closed without merging**
