### PR TITLE
Fix hardcoded dimensions

### LINKED ISSUE #3197: The xml files contain a lot of hardcoded dimensions
**Summary:** 

The xml files contain a lot of hardcoded dimensions
 
**More Information**

Currently, a lot of the layout files contain hardcoded dimension values as layout_width, layout_height, padding, etc. Instead of being hardcoded, these values should be a part of the dimens.xml file from which they should be accessed each time needed. The same should be done for text size which is currently hardcoded in a lot of places. 

**Commons app version:** 

2.11.0-debug-master

**Would you like to work on the issue?**

Opening for GCI.

### PR DESCRIPTION
**Pull request by m-alzam**
**Fix hardcoded dimensions**

Fixes #3197 The xml files contain a lot of hardcoded dimensions

**Tests performed**
Gradle build successfully.

### CODE REVIEW

**Comment by m-alzam** [comment]
Why there are conflicts with java files if I have not changed that files? Thanks

**Comment by nicolas-raoul** [comment]
I guess there are conflicts because of a recent refactoring?
Please rebase from master, I believe that should fix the problem :-)

**Comment by m-alzam** [comment]
How I rebase from master? Git says that my branches are updated.

**Comment by yashk2000** [comment]
First fetch upstream. 
Try this: `git rebase -i origin/master`

**Comment by m-alzam** [comment]
Thanks @yashk2000:
> First fetch upstream.
> Then try: git rebase -i origin/master

Sorry, these git operations are a bit difficult for me. I don't know what I'm doing, but somehow I've pushed two more commit with "yesterday" as date :confused:. Help needed!

**Comment by m-alzam** [comment]
Please ignore this PR, I'm going to open another to try to solve the problems.

**Pull request closed without merging**
