### PR TITLE
Change toolbar color to Primary color

### LINKED ISSUE #1189: Change toolbar color to primary color
**Summary:** 

According to guidelines by Google 
Toolbar background color should be the primary color.
Statusbar background color should be primary Dark color.

**Steps to reproduce:** 

Change toolbar background to primary color in toolbar.xml

**Expected behavior:** 

Toolbar background color should be the primary color.

**Observed behavior:** 

Toolbar background color is primary dark color.

**Screen-shots:** 
<table>
<tr>
<td>

screenshot_20180224-180318

</td>
<td>

screenshot_20180224-180552

</td>
</tr>
</table>
Image 1->Before

Image 2->After

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
## Description

Fixes #1189 

Changed toolbar background to primary color instead of primaryDark in toolbar.xml

## Screenshots showing what changed
<table>
<tr>
<td>

screenshot_20180224-180318

</td>
<td>

screenshot_20180224-180552

</td>
</tr>
</table>
Image 1->Before

Image 2->After

### CODE REVIEW

**Comment by misaochan** [comment]
I actually like the "before" image better personally, lol. Is there a rationale for the change? But I'm happy to let @neslihanturan choose, either way. ;)

**Comment by neslihanturan** [comment]
I also like before image more, sorry:D

**Comment by ujjwalagrawal17** [comment]
@neslihanturan @misaochan I had added a comment on the issue https://github.com/commons-app/apps-android-commons/issues/1189 please give some feedback.

**Comment by ujjwalagrawal17** [comment]
@neslihanturan @misaochan Can we choose any one of these?

<table>
<tr>
<td>

screenshot_20180228-010941

</td>
<td>

screenshot_20180228-010819

</td>
</tr>
</table

I had attached 2 combinations 

Image 1 has our Primary color and Primary Dark color 2 shades darker than primary color 
Image 2 has our Primark Dark color and primary color 2 shades lighter than primary dark color

Shades are selected from https://coolors.co/0c609c-0a4f80-2e5b87-00376d-685044

**Pull request closed without merging**
