### PR TITLE
Add WelcomeActivityTest

### PR DESCRIPTION
**Pull request by domdomegg**
**Description (required)**

Adds Android Test: WelcomeActivityTest

**TODO** - moved to #2644

Probably want to flesh this out a bit with some more tests. Ideally we'd have one which would swipe the correct number of times and then click 'yes', and check we were out of WelcomeActivity

Also maybe check that on beta clicking the skip tutorial exits WelcomeActivity

Also maybe check we can swipe both ways (i.e. backwards and forwards)

Also maybe check swiping beyond the proper bounds shouldn't do anything e.g. swiping left on the first page or right on the last page.

### CODE REVIEW

**Comment by domdomegg** [comment]
Have removed WIP tag as I think we may as well merge this, and then future PRs can flesh out the tests more. Have moved the TODOs to #2644.

**Comment by maskaravivek** [comment]
@domdomegg Is travis running these tests at all? Codacy report doesn't show any change in the coverage.

**Comment by domdomegg** [comment]
No, Travis stopped running instrumentation tests in #2595, particularly 0d203a4c04573b7cf8bf40f1668e725e7631052b

**Comment by maskaravivek** [comment]
Now, that we have more instrumentation tests, it should be fine to add it back again.

**Comment by maskaravivek** [comment]
Merging this and travis instrumentation tests can be enabled in a different PR.

**Pull request merged**
