### PR TITLE
Enhance behaviour of Media detail enhance

### PR DESCRIPTION
**Pull request by akaita**
This PR build up on #777 .

The layout of the Fragment suggested that the License should be clickable and open a URL containing the license.
For consistency, it made sense to add the same behaviour to the coordinates.

| Before  | After |
| ------- | ----- |
| mediadetail nohyper | mediadetail hyper |

### CODE REVIEW

**Comment by misaochan** [comment]
Copying over my concerns from the other thread - I'm undecided about coordinate-clicking leading to the map application. I personally feel that anything that leads the user to switch apps (opens up the browser or map app) on finger tap without explicitly making it clear that it would do that, needs to be handled very cautiously, otherwise users might get annoyed by the unexpected behaviour. Licenses could perhaps offer a benefit that exceeds the risks (and even then I might argue for a button for "open in browser/webview" if we redesign the media details screen), but adding coordinates feels a bit much to me.

If others think that tapping Coordinates should open up a map app (and the same for Licenses -> browser), I'm happy to go with the majority though. 

Would greatly appreciate feedback/thoughts, you guys. :)

**Comment by nicolas-raoul** [comment]
On the nearby map, I often tap the screen to make a popup disappear.
I often also tap the map for no special reason, or move it a bit, just to feel it, especially when it is a bit slow.
Obviously, I also double-tap to zoom-in, and I am sure that often my double-clicks are understood as simple clicks, especially when the weather is cold.

For these reasons, I would personally prefer to not launch another application (nor a modal confirmation popup) on click. A very discreet and ignorable bar appearing from the bottom to propose open the map app would be OK I guess, a bit like a bar appears when you tap somewhere in Google Maps.

**Comment by akaita** [comment]
@nicolas-raoul I'm confused by your mention of "nearby map"... The interaction with a map element or a scrollable list (Media Details screen) seems completely different to me.
Was your proposal to make the License field clickable, so it opens a SnackBar with an action, and that action actually opens a new screen with the license?
`License field -> SnackBar -> Webpage`
`Coordinated field -> SnackBar -> Map`

**Comment by nicolas-raoul** [comment]
Sorry I was totally misunderstanding!
I now watched the animation you posted, thanks a lot it makes the changes very understandable I should really have watched it before commenting.

Opening the map app when tapping coordinates does not sound shocking to me. In the future we might add the option to edit the picture location (which is sometimes wrong), so revealing a dialog with "open in map app" would be even better, but I am in favour of merging even without that.

Similarly, opening the license when tapping the license name sounds good to me.

**Comment by misaochan** [comment]
Thanks for the feedback, @nicolas-raoul . I wonder if it might make sense to go with "tapping the field -> dialog asking if they want to open the map app or browser -> bring them to map app or browser if they say 'yes'" instead? Or alternatively, having a button with the map icon at the side of the coordinates field, and a button with some other icon "maybe '?'" at the side of the license field?

**Comment by akaita** [comment]
@neslihanturan Should we just close this one?

**Comment by neslihanturan** [comment]
I am reallyy sorry, I don't know how did I miss this one for such long time. I have watched the animations and my decision is it is not very annoying for user, but to make it feel like a link to another place,  maybe we can 
- add buttons as @misaochan suggested
- maybe adding view on map, view on borwser clickable texts to right side of the layout
- change their text color to link blue at least (but this one is my less favourable option)
Then we can merge and close it I think. I won't be missing this one next time I promise @akaita .

**Comment by akaita** [comment]
Myself I prefer to make it easy to navigate between apps. I don't like apps which tell me "are you sure you want to leave the app?", "but seriously, are you very very sure", "come on, really? this app is so awesome, please don't leave it"... I would discard the option about the modal menu right away.

We do though have a few similar components, some of them clickable and some of them not.
We should give the user some clue about which elements are actually clickable.

I'll try the option of adding clickable icon on the right-hand side for those two components. That will be the clearest 👍

**Comment by janpio** [comment]
My limited (and possibly outdated) Android design knowledge includes the bit that Android normally doesn't use these "caret" symbols to indicate "click/tapability" of things. But I always wondered how this is be done then...

**Comment by psh** [comment]
The material design spec says that dialog buttons should be flat and right aligned so users of modern Android apps should be trained to see text on the right (such as "view") as a button and know it's tappable without having to give it hyperlink style colors and underlines.

Personal opinion, at the very simplest, I think a flat style "View" button would work nicely as could image buttons (https://material.io/icons/#ic_info_outline and https://material.io/icons/#ic_place) as they mark out which of the text fields are _different_ to the others and invites tapping.

**Comment by akaita** [comment]
@psh I believe we are saying the same thing, so I agree :)
I'll get something ready today or tomorrow. Let's finish off this PR :ganbare: !

**Comment by akaita** [comment]
For instance (also added to Categories, which were already clickable):
screenshot_1501707440

**Comment by neslihanturan** [comment]
It seems good to me now. Thanks for your patience @akaita . I couldn't test it somehow I get error when I clicked to see media detail fragment. But I am sure it is not related with your code (maybe related with #711). Can someone else also test it please, so that we can merge it finally. Thanks!

**Comment by neslihanturan** [comment]
Hİ @akaita , I want to merge it soon. But when I tested it again, it failed. Maybe because of adding vector drawables as side-drawable thing is being problematic. Does it works on your tests? Do you have any idea about the reason that it doesn't work on my case? My test device is version 4.4.2.

**Comment by akaita** [comment]
@neslihanturan I didn't really test against 4.4.2. I usually test with 6 and 7... 
I don't have access to any real 4.2.2 device, but I will test with a 4.2.2 emulator. Thanks for being so thorough!

**Comment by akaita** [comment]
You are right, it is because of using vectors in `drawableLeft`. The support library is broken: https://issuetracker.google.com/issues/37090849
I usually do't use `drawableLeft`, so I didn't know 😅 . I didn't want to modify this layout too much...

**Comment by akaita** [comment]
I didn't want to make the layout more complex, so I thought about adding a new View which actually supports vectors in `drawableStart`. I hope that is fine 👍

**Comment by neslihanturan** [comment]
It works perfect, thanks @akaita . If you have time can you please add line breaks to make codacy happy? If you are AFK, I will merge it as is anyway.

**Comment by akaita** [comment]
Great!
I didn't know how to put line breaks in a nice way for those two lines highlighted by codacy. I'll try again.

**Comment by akaita** [comment]
I realised there were a few unused `import` so I removed them. I can't think about a sensible way to make those lines shorter, though :(

**Comment by neslihanturan** [comment]
I also think it is better as is. Thanks @akaita !

**Pull request merged**
