### PR TITLE
Fix #2231: Recent searches list updation issues while exploring

### LINKED ISSUE #2231: History issues while exploring
**Summary:** 

When i press the explore button, history comes up with my previous searches. When i search something new and results shows up, i press 'x' button on right top and goes back to my history. But history does not refresh and i have to go to main page and then back to 'explore' ( in order to refresh my history ).

This may cause a lot of issues , one of them is this below

**Steps to reproduce:** 

Go to 'explore'
( Clear your history )
Search something
Press 'x' button
Delete your history

Your history will not be empty but it will contain your last search

**Screen-shots:** 

49253476_591294174658349_1579986041471762432_n
48908433_2290950857591024_8970439518712758272_n
48413605_2054084407964047_9175477018291077120_n
48926283_2033832026696717_5357977998182055936_n
49106298_336037940314969_6255988353343160320_n

''Το ιστορικό αναζήτησης διεγράφη''     ---->   History cleared 
the other message with options 'yes' , 'no' is the message when you try to clear your history

### PR DESCRIPTION
**Pull request by ShridharGoel**
**Description (required)**

Fixes #2231 

Now, the list of recent searches will update before the RecentSearchesFragment is shown.

**Tests performed (required)**

Tested betaDebug on API 25.

**GIF showing the change:**

ezgif com-video-to-gif 37

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Closed and reopened the issue so that the Travis CI build runs again. Don't know why some tests failed earlier due to which the build failed. Those tests passed when ran locally and my PR was not related to those tests in any way. Now, the build passed on running again.

**Comment by ShridharGoel** [comment]
@neslihanturan @domdomegg Please review.

**Comment by domdomegg** [comment]
Doesn't seem to fix the issue:

**Comment by maskaravivek** [comment]
@ShridharGoel Can you take a look at this and bring the PR to completion. :)

**Comment by ShridharGoel** [comment]
@maskaravivek Yes, surely. Sorry for leaving it incomplete.

**Comment by ShridharGoel** [comment]
@maskaravivek Please review.

**Comment by maskaravivek** [comment]
@ShridharGoel Can you attach a GIF showing the fix.

**Comment by ShridharGoel** [comment]
@maskaravivek Please tell if some changes are required. :)

**Comment by domdomegg** [comment]
[Commons Beta upload](https://commons.wikimedia.beta.wmflabs.org/wiki/File:MobileTest_2232.jpg)

**Comment by ShridharGoel** [comment]
@domdomegg Thanks.

**Pull request merged**
