### PR TITLE
Fixes #2888: Use Dexter for requesting location permissions

### LINKED ISSUE #2888: First time ever tapping "Nearby": Tab does not show
**Steps to reproduce:** 

1. Install app on new phone
2. Log in
3. Tap "nearby"
4. Location permission popup appear, accept
5. Nearby tab is not opened (nearest location bar is shown, though)

Workaround: Tap on "Nearby" again.

**Commons app version:** 
2.10.2-debug-master~84637c5fe

**Screen-shots:** 
Screenshot from 2019-04-17 17-38-54

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2888

nearby

### CODE REVIEW

**Comment by neslihanturan** [comment]
One more issue: if I send the app to background while nearby tab is selected, then disable the permission, when I come back to the app it does not request permission. Even more if I switch to contributions tab and come back to nearby tab, it still doesn't request for permission.

**Comment by maskaravivek** [comment]
> Thanks @maskaravivek , I have tested this. Tabs works fine but nearby doesn't load on API26 device.
> Screenshot from 2019-04-25 10-48-00

Is there any error in the logs?

**Comment by neslihanturan** [comment]
No, there is just an error about SettingsActivity which seems irrelevant.

**Comment by neslihanturan** [comment]
These are the logs I see after seeing loading screen for long time and switching back to contribution tab and come back to nearby tab:

```
2019-04-25 10:50:36.496 6366-6366/fr.free.nrw.commons.beta D/MainActivity: Contributions activity notifications menu item is visible
2019-04-25 10:50:38.478 1443-1492/? D/hwcomposer: hw_composer sent 50 syncs in 398s
2019-04-25 10:50:38.480 6366-6366/fr.free.nrw.commons.beta D/MainActivity: Nearby tab selected
2019-04-25 10:50:38.486 6366-6366/fr.free.nrw.commons.beta D/MainActivity: Contributions activity list sheet menu item is visible
2019-04-25 10:50:38.487 6366-6366/fr.free.nrw.commons.beta D/NearbyFragment: On nearby tab selected
2019-04-25 10:50:38.599 1537-1657/? D/AudioFlinger: mixer(0xa6b83480) throttle end: throttle time(5)
```

**Comment by maskaravivek** [comment]
device-2019-06-04-231550 (1)

**Comment by maskaravivek** [comment]
@neslihanturan I have fixed the pending issues with this PR and its ready for review now. :)

PFA the attached video for various scenarios. 

https://drive.google.com/file/d/1aCuegxzwD4NUY0f5xzyT_g0VQ1YkNuyh/view?usp=sharing

**Pull request merged**
