### PR TITLE
fixing issue #2072:Fix default license selector in Settings

### LINKED ISSUE #2072: Fix default license selector in Settings
From a user on our forum:

> I've selected CC-BY-SA 4.0 as my default license, but the upload wizard in step three defaults to CC-BY-SA 3.0 unless I manually change it each time.

### PR DESCRIPTION
**Pull request by sp2710**
Fixes #2072 Fix default license selector in Settings

What changes did you make and why?
Added getDefaultLicense() method in UploadModel.java class that return default license to updateLicenses() method in UploadPresenter.java class which sets the list of licences and the default license

Tested on Motorola Moto G(5) plus with API level 24

### CODE REVIEW

**Comment by briancollins-92** [comment]
Hi @maskaravivek, @misaochan , I submitted a pull request for this very issue 10 days ago that has been overlooked.  see: https://github.com/commons-app/apps-android-commons/pull/2084

Whats more is that it appears obvious on the issue tracker (link https://github.com/commons-app/apps-android-commons/issues/2072) that I volunteered for this and submitted the fix! Perhaps I did not follow the process correctly.

@sp2710 Why did you do this when it was clear it has already been done? I feel a bit cheated to be honest...this was my first open source submission.

**Comment by sp2710** [comment]
@briancollins-92 I am new to open source
I saw that your request was not merged and also there was no assigned label to that issue. So i thought to give it a try.

**Comment by briancollins-92** [comment]
Hi @maskaravivek, @misaochan. This may sound trivial, but can you please at least look at my pull request.

Like @sp2710 I am new to open source, but unlike him I maticulously followed the guidence and communicated what i was doing clearly. He has taken what i had finished and presented it as his own with some differences. As a fellow first timer, I am especially unimpressed by his feeble excuse. I had clearly staked out this issue and submitted my pull request *before* sp got involved and therefor deserve the credit of a merge - if it is good enough quality of couse, which i think it is.

**Comment by nicolas-raoul** [comment]
@briancollins-92 Sorry about that, developers are often contributing as a hobby when they have 5 minutes, and they might choose a PR rather than another randomly.
Also, we all have a common goal of seeing the app being improved, so copying ideas or code or patches is not seen as "stealing", but rather seen as the normal way open source works.
I hope this will not deter you from contributing further, there are so many open issues that need people :-)
Cheers!

**Comment by neslihanturan** [comment]
Hi all, firstly sorry for our  late review time, we are at one of rush times. I do agree about the importance of communication under issues because we don't want two people spend their energy for same task. On the other hand, I agree to @nicolas about random and fast picking issues. This coincidence should be considered as an accident, unintentional situation. Overall, we are happy you both are new to open source and trying to contribute, thanks for your time and help

**Comment by misaochan** [comment]
Hi guys, sorry about the confusion. As @neslihanturan says, this was an accident, and I don't think anyone is truly "at fault" here, mistakes happen. 

I do agree that we should give #2084 priority as it was submitted far in advance, and @briancollins-92 had posted on the issue requesting to take it up. In situations where the person taking it up is unresponsive, we can and do re-assign the issue, but that is not currently the case here.

We can still leave this PR up for now, but @neslihanturan will be testing #2084 when she has time next. If @briancollins-92 is responsive to code changes requested, we will merge that one and close this. 

Sorry about that @sp2710 , but we need to follow the sequence usually. Please feel free to try your hand at another one of the issues that are open, thanks!

**Comment by sp2710** [comment]
@misaochan 
As I am new here so i thought that there is no assign label and the PR was also not approved so i can try my hands on it. Was not at all intentional
And I also agree that #2084 should be given priority. I will try my hands on other issues :)

**Comment by briancollins-92** [comment]
Thank you all for your responses. May I offer my apologies to the mods as I very much appreciate the effort you make in volunteering. I was more frustrated at sp because it seemed obvious to me how it works. Thank you for taking time to look at this.

**Comment by domdomegg** [comment]
Closing #2124 now that #2084 is merged.

I've written up some clearer contributor documentation on the [wiki](https://github.com/commons-app/apps-android-commons/wiki/Developer-workflow
) which I hope should help reduce the chances of this happening in the future. Would love any feedback you have on it.

**Pull request closed without merging**
