### PR TITLE
Nearby ui

### PR DESCRIPTION
**Pull request by neslihanturan**
Still working on it, but I think it is time to get feedbacks and change things accordingly.
Known issues:
-Buttons don't work
-Orientation change will be handled by side sheet
-FAB appears on upper left corner when I remove its anchor (to hide them), I have some hacks to solve this but would love to learn the best practice
-Comments aren't added
-Leaks occurs

I am waiting your feedbacks for rest

### CODE REVIEW

**Comment by misaochan** [comment]
Yay @neslihanturan ! :D Will take a look at it ASAP.

One thing - did you rebase this on master? It seems to include commits from dbrant etc, and modifications to files that they made.

**Comment by neslihanturan** [comment]
Yes, I rebased as we talked. But the commits also looks to me weird :/

**Comment by misaochan** [comment]
Could you rebase both your branch as well as direct-nearby-uploads on master again, and see how that goes? If it still doesn't work then we'll just try to review around that I guess.

**Comment by maskaravivek** [comment]
@neslihanturan Can you add a few screenshots to the PR. :)

**Pull request closed without merging**
