### PR TITLE
Fix English remnant causing failed build

### LINKED ISSUE #698: Localization errors in values-kn.xml
In the current master branch I get these errors:

```
/home/tobias/git/apps-android-commons/app/build/
intermediates/res/merged/debug/values-kn/values-kn.xml
Error:(4) Found tag </item> where </plurals> is expected
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
Error:(4) Multiple substitutions specified in non-positional format; 
did you mean to add the formatted="false" attribute?
Error:(4) Found tag </item> where </plurals> is expected
Error:(4) Multiple substitutions specified in non-positional format; 
did you mean to add the formatted="false" attribute?
```

### PR DESCRIPTION
**Pull request by misaochan**
Fix #698

### CODE REVIEW

**Comment by whym** [comment]
It looks like @Nikerabbit has done the fix.

https://github.com/commons-app/apps-android-commons/commit/d05714d3db855b5cf1be7e7254e57b8aa40dc468#commitcomment-22319938
https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-uploads_pending_notification_indicator/kn&diff=prev&oldid=7402078

Perhaps is it better to wait for the next automatic update (probably in a day or sooner) to avoid any conflict?

**Comment by Nikerabbit** [comment]
I do updates in Monday and Thursday mornings (Europe). They are not fully automated so sometimes there are exceptions.

**Comment by misaochan** [comment]
@Nikerabbit if we merge this now, will there be an issue on Thursday morning? 2 days is a bit long to wait when we cannot build the project at all, as anyone wanting to work on the project will have to implement their own fix locally if they want to test anything.

**Comment by Nikerabbit** [comment]
Go ahead, it won't cause issues.

**Comment by whym** [comment]
Sounds good. I will merge this.

**Pull request merged**
