### PR TITLE
Effective UI in nightmode

### PR DESCRIPTION
**Pull request by silkypriya**
**Description**

Improved UI in night mode.

**Fixes** #2573 Effective UI in night mode

**What changes did you make and why?**

1. Changed colour of bottom row buttons for easy visibility in night mode.

Before change             |  After change 
:-------------------------:|:-------------------------:
 bottom_buttons | button

2. Changed navigation header colour in night mode for consistency in UI.

Before change             |  After change
:-------------------------:|:-------------------------:
nevigation | navi

3. Changed background colour of achievement activity to make text visible in night mode.

Before change             |  After change
:-------------------------:|:-------------------------:
achievement | achi

4. Changed background colour of tutorial activities in night mode same as all other activities. 

Before change             |  After change
:-------------------------:|:-------------------------:
tutorial | tut1

**Tests performed**

Tested betaDebug on Realme 2 pro (Android Version 8.1.0) with API level 27.

### CODE REVIEW

**Comment by silkypriya** [comment]
#2180 Night mode issue list

Also fixes #2446 Night mode: Achievements

**Comment by silkypriya** [comment]
Hello @nicolas-raoul 

The the last commit does 
1. Revert the first commit which was fixing #2562. I am sorry for the inconvenience.
2. Change the bottom row button color to slightly light blue in night mode.

Squashing the commits will cause above mentioned four changes.
Fixing issues #2573 and #2446 

Would love your feedback.
Thank you!

**Comment by nicolas-raoul** [comment]
Would you mind updating the screenshots above? Thanks :-)

**Comment by silkypriya** [comment]
Updated the screenshots.
Thank you! @nicolas-raoul

**Pull request merged**
