### PR TITLE
Fixes :- [Bug]: UnknownFormatConversionException: Conversion = 'এ' #4877

### PR DESCRIPTION
**Pull request by Rishavgupta12345**
[Bug]: UnknownFormatConversionException: Conversion = 'এ' #4877 

completely fixed, it was just a minor typing error that created the problem

### CODE REVIEW

**Comment by 4D17Y4** [comment]
This fixes the upload bug.
But I see some other bugs with Bengali as a language.

bug
Notice the title bar in the gif it changes from English to Bangla when tapped on menu. Notice the name change in other tabs as well.

There are multiple such instances and Its better if we get to its root cause.

**Comment by Rishavgupta12345** [comment]
> This fixes the upload bug. But I see some other bugs with Bengali as a language.
> 
> bug Notice the title bar in the gif it changes from English to Bangla when tapped on menu. Notice the name change in other tabs as well.
> 
> There are multiple such instances and Its better if we get to its root cause.

@4D17Y4 Then we should merge and close this issue and make separate issues for them

**Comment by Rishavgupta12345** [comment]
> > This fixes the upload bug. But I see some other bugs with Bengali as a language.
> > bug Notice the title bar in the gif it changes from English to Bangla when tapped on menu. Notice the name change in other tabs as well.
> > There are multiple such instances and Its better if we get to its root cause.
> 
> @4D17Y4 Then we should merge and close this issue and make separate issues for them

And the root cause is some errors in the String.xml (bn) file, the upload crash was also a silly mistake done by the author, I will create separate issue and rectify them

**Comment by 4D17Y4** [comment]
> > This fixes the upload bug. But I see some other bugs with Bengali as a language.
> > bug Notice the title bar in the gif it changes from English to Bangla when tapped on menu. Notice the name change in other tabs as well.
> > There are multiple such instances and Its better if we get to its root cause.
> 
> @4D17Y4 Then we should merge and close this issue and make separate issues for them.
> 
> And the root cause is some errors in the String.xml (bn) file, the upload crash was also a silly mistake done by the author, I will create separate issue and rectify them

Sounds good, make sure you fix all of them in that PR.

**Comment by 4D17Y4** [comment]
Thanks @Rishavgupta12345

**Pull request merged**
