### PR TITLE
[WIP] Fixed 4620: Reused categories selection UI from the Upload Wizard

### LINKED ISSUE #4620: Editing categories of an existing picture: Reuse categories selection UI from the Upload Wizard
I think categories editing should be revamped: It currently uses a special UI, which takes time to improve and maintain.

It would be better if it reused the existing category selection UI of the Upload Wizard.
adb

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Reused the existing category selection UI as the current UI takes time to improve and maintain.
Fixes #4620 

**Tests performed (required)**

Tested latest master on Pixel 3 with API level 30.

### CODE REVIEW

**Comment by Ayan-10** [comment]
@nicolas-raoul Should I delete the old category edit UI?

**Comment by nicolas-raoul** [comment]
> Should I delete the old category edit UI?

Yes thanks :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I just tried, great work!
There are a few issues:
- After tapping on the pen icon, categories that the picture already has should be checked☑︎ but they are currently unchecked☐.
- The nearby banner appears at the top (screenshot below), it should not be visible.
- After saving, added categories are not visible in the picture's details.
- Some categories get duplicated: https://commons.wikimedia.org/w/index.php?title=File%3A%E5%8C%97%E8%B0%B

Screenshot_20211130-222828_Commons
7%E5%85%AC%E5%9C%92.jpg&type=revision&diff=610964728&oldid=610921664

**Comment by Ayan-10** [comment]
@nicolas-raoul I have looked into the issues. I fixed the duplicated categories and the banner is also removed now. Please check it once. 

But as you said here that existing categories are not checked. I can't reproduce this problem. As you can see here, in this screenshot. The existing categories are already checked.


Can you please elaborate on this line `After saving, added categories are not visible in the picture's details.
`

**Review by nicolas-raoul — COMMENTED** [review]
Thanks, it seems that it is working better now! :-)
I still notice a few problems though:
- After adding a category to 2 pictures, I tapped the pen for a third picture, and was surprised to see that the checkbox for this category was already checked, even though that third picture does not have this category yet (I checked on the Commons website). Maybe a cache problem?
- After adding a category to a picture, the category does not immediately appear in the Media Details activity above the pen icon. To make the new category appear, I have to restart the app.
- I still get the nearby banner sometimes.
- Categories are still duplicated: https://commons.wikimedia.org/w/index.php?title=File%3AShibuya_station_in_2021_2.jpg&type=revision&diff=613411763&oldid=613396688

**Review by nicolas-raoul — COMMENTED** [review]
Could you please check this scenario:
1. Add a category to a picture, press "Save"
2. Press "Back" to go back to my contributions list
3. Tap the same picture again
4. Category is now absent

Thanks!

**Comment by Ayan-10** [comment]
@nicolas-raoul I think the duplicate categories and categories appearing after restarting the app, these issues are fixed now. 

I checked the other scenario which you have pointed out. It's not happening every time and also sometimes after restarting the app the new categories are not showing (Sometimes it's working as expected). I tried with some logs and observed it several times. I think it's happening because the app is taking time for fetching the categories. Although the new categories are updated on the server, media.getCategories is returning old categories and the app is not showing it, restarting immediately after updating.  Also, I didn't change anything for showing categories in MediaDetailFragment.

**Comment by nicolas-raoul** [comment]
Yes I noticed that duplicate categories seems to be fixed now, thanks a lot!

Indeed the problem of refreshing Media Details already existed with the previous category modification UI.
I think that now is a good opportunity to fix this problem, by forcing Media Details to reload categories from the server.
If you want to leave this issue for later, you can also create a different bug issue.

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, there is a TODO written on `updateCategory()` method 
```
            // TODO this added categories logic should be removed.
            //  It is just a short term hack. Categories should be fetch everytime they are updated.
```

I will prefer to create another issue and resolve it later (If there is no problem with that).

**Comment by nicolas-raoul** [comment]
Understood, thanks!
Could you create the issue?

**Comment by nicolas-raoul** [comment]
Would you mind fixing the conflict here too? Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Even though the picture has category https://commons.wikimedia.org/wiki/Category:Ch%C5%AB%C5%8D,_Tokyo when I open the category it does not show it as selected, it seems to believe that I am already searching for something.

Also, at the end, after leaving this activity on the screen for 40 seconds, the "Back" button works strangely, sometimes freezing for a few seconds, sometimes going directly to Contributions instead of Media Details.

https://user-images.githubusercontent.com/99590/150139990-89226128-b3ab-417b-ae26-1ba68ea1a0b4.mp4

Thanks!

**Comment by Ayan-10** [comment]
@nicolas-raoul This PR is working in progress now. Actually, I implemented this PR almost the same way with the depiction editor #4725 . As soon as all issues get fixed in #4725 PR I will start working on this PR.

**Pull request closed without merging**
