### PR TITLE
Fix format parameters for strings

### PR DESCRIPTION
**Pull request by veyndan**

### CODE REVIEW

**Comment by whym** [comment]
I believe this is a good change, but doesn't it have to be done on TranslateWiki.net? e.g. by editing https://translatewiki.net/wiki/Wikimedia:Commons-android-strings-upload_progress_notification_title_finishing/he

I fear the bot may later "update" and revert the changes done here.

That said, maybe we can just try. We just have to keep an eye on such possible revert.

**Comment by veyndan** [comment]
I'm good with doing it on the website, though I've never used it before as I don't speak a second language. Does anybody mind updating it on the site?

**Comment by whym** [comment]
Let's try this. If it doesn't work as expected, I can do it on the website later.

**Comment by misaochan** [comment]
Yeah, sounds good to me.

**Comment by whym** [comment]
https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-upload_progress_notification_title_finishing/he&diff=7336512&oldid=4543668

It has been propagated to translatewiki.net, so we are all set.

**Pull request merged**
