### PR TITLE
Fix #2881 (Change Media Details UI) 

### LINKED ISSUE #881: SignUpActivity still leads to main(production) signup page even when using beta debug builds
Was trying to sign up on the beta debug build which lead me to the main(production) sign up page. So when I used the same credentials as my production account it of course showed me that my account exists. 

But we should be lead to the sign up page for the beta server right? The way its right now, if a user tries to sign up on the beta build, their account will be created on the production server while the app is built to hit the beta server at all times, which is just plain wrong, right? 

I read the associated pull request #857 and did not find any mention of this. Am I missing something obvious here?

### LINKED ISSUE #2881: New Media Details UI
**Summary:** 

Hi, here is a UI suggestion, which fits wit our new upload UI, for our Media Details interface.
Option 1:
mediaDetailsUI

Option 2:
mediaDetailsUI2

After nomination for deletion, for both options:
mediaDetailsUINominated

Feedback is appreciated.

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
**Description (required)**

Fix #2881 (New Media Details UI) 

What changes did you make and why?
- Made changes in XML files

**Screenshots showing what changed (optional - for UI changes)**

WhatsApp Image 2019-05-17 at 4 48 47 PM
WhatsApp Image 2019-05-17 at 4 48 47 PM (1)

### CODE REVIEW

**Comment by neslihanturan** [comment]
This is fast @ujjwalagrawal17 , please ping me when ready for test:)

**Comment by ujjwalagrawal17** [comment]
Sure @neslihanturan . You can test the UI now also but the onclicks on buttons are not working now and needs some code improvements. Will try to finish it soon.

**Comment by ujjwalagrawal17** [comment]
@neslihanturan it is ready to test now.

**Comment by nicolas-raoul** [comment]
wow very nice! :-)

**Comment by neslihanturan** [comment]
Hi @ujjwalagrawal17 , thanks for the great job!
I got this error consistently, even after fresh install:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
        at fr.free.nrw.commons.theme.NavigationBaseActivity.changeDrawerIconToBackButton(NavigationBaseActivity.java:59)
        at fr.free.nrw.commons.contributions.MainActivity.hideTabs(MainActivity.java:298)
        at fr.free.nrw.commons.contributions.ContributionsFragment.setMediaDetailPagerFragment(ContributionsFragment.java:317)
        at fr.free.nrw.commons.contributions.ContributionsFragment.showDetail(ContributionsFragment.java:460)
        at fr.free.nrw.commons.contributions.ContributionsFragment.onEvent(ContributionsFragment.java:768)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter.openMediaDetail(ContributionsListAdapter.java:113)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter.access$200(ContributionsListAdapter.java:22)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter$1.onClick(ContributionsListAdapter.java:69)
        at fr.free.nrw.commons.contributions.ContributionViewHolder.imageClicked(ContributionViewHolder.java:152)
        at fr.free.nrw.commons.contributions.ContributionViewHolder_ViewBinding$1.doClick(ContributionViewHolder_ViewBinding.java:38)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-05-25 11:30:48.593 28560-28560/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
        at fr.free.nrw.commons.theme.NavigationBaseActivity.changeDrawerIconToBackButton(NavigationBaseActivity.java:59)
        at fr.free.nrw.commons.contributions.MainActivity.hideTabs(MainActivity.java:298)
        at fr.free.nrw.commons.contributions.ContributionsFragment.setMediaDetailPagerFragment(ContributionsFragment.java:317)
        at fr.free.nrw.commons.contributions.ContributionsFragment.showDetail(ContributionsFragment.java:460)
        at fr.free.nrw.commons.contributions.ContributionsFragment.onEvent(ContributionsFragment.java:768)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter.openMediaDetail(ContributionsListAdapter.java:113)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter.access$200(ContributionsListAdapter.java:22)
        at fr.free.nrw.commons.contributions.ContributionsListAdapter$1.onClick(ContributionsListAdapter.java:69)
        at fr.free.nrw.commons.contributions.ContributionViewHolder.imageClicked(ContributionViewHolder.java:152)
        at fr.free.nrw.commons.contributions.ContributionViewHolder_ViewBinding$1.doClick(ContributionViewHolder_ViewBinding.java:38)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Beta debug, API 26 emulator.

**Comment by maskaravivek** [comment]
@ujjwalagrawal17 Can you take a look at the pending issues in the PR?

**Comment by ujjwalagrawal17** [comment]
Yup @maskaravivek I will check it out tomorrow.

**Comment by maskaravivek** [comment]
@ujjwalagrawal17 The PR has been pending for a long time. It would be great if you could fix the minor pending issues. 

Let us know if you won't be able to work on it so that we can assign it to someone else. :)

**Comment by maskaravivek** [comment]
Merging it to `wikimedia-hackathon-2019`. We can fix the pending issues in the hackathon branch.

**Pull request merged**
