### PR TITLE
Fixes #2337 - Show captions of image in media details (conflicts fixed)

### LINKED ISSUE #2337: Show caption in media details
from Structured Commons.
Show on first line, before title, in user's language or fallback language.

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**
Fixes the conflicts from #2662 which solves #2337 to be able to merge changes, the code of @sp2710 was already working perfectly.

image

### CODE REVIEW

**Comment by neslihanturan** [comment]
Tests fails because of changes, please someone with RxJava knowledge review this.

**Comment by ashishkumar468** [comment]
@neslihanturan I have raised a pr for the same on your branch. Tests pass with the same on my local machine. Please have a look : )

**Comment by ashishkumar468** [comment]
@neslihanturan I just noticed that xml api's have been used in the PR, would you mind switching them to the corresponding json one ?

**Comment by iadeelzafar** [comment]
Thanks for working on this. It was long due. 
Cheers!

**Comment by nicolas-raoul** [comment]
@misaochan Is it OK to merge this after converting the XML call to JSON?
Or do we strictly have to use data-client?

**Comment by maskaravivek** [comment]
Data client just provides an instance of OkhttpClient. The API would be written as a custom call. So there should be no extra effort required for using it via the data client :)

**Pull request merged**
