### PR TITLE
Fix 4615: Option for editing caption and description

### LINKED ISSUE #4615: Media details: Make caption and description editable

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Fetched current wikitext, extracted descriptions from it by in-built algorithm, compare and merge them with caption according to language code, reflected description and caption in an activity for adding and editing, get new description and made new wikitext and put it into the server.

Fixes #4615 

**Tests performed (required)**

Tested master on Pixel 3 with API level 30.

### CODE REVIEW

**Comment by madhurgupta10** [comment]
Hi @neslihanturan and @Ayan-10 I noticed that Butterknife is used here, we are actually moving away from it (https://github.com/commons-app/apps-android-commons/issues/4664)

If the changes are not urgent, I would suggest you wait till the view binding dependencies are added.

**Comment by Ayan-10** [comment]
@madhurgupta10 I was trying to add test for GET call for getting Wikitext. But I am getting this error at the last line. Is this error occurring because of asynchronize call? I was trying to find some solution but can't find any.
**Test**
```
    @Test
    fun `getWikiText`() {
        val wikiText = mock<MwQueryResponse>()
        whenever(mediaDetailInterface.getWikiText("File:Test.jpg")).thenReturn(Single.just(wikiText))
        mediaClient.getCurrentWikiText("File:Test.jpg").test()
            .assertValues(wikiText.query()?.pages()?.get(0)?.revisions()?.get(0)?.content())
    }
```
**Error**
```
Value count differs; expected: 1 [null] but was: 0 [] (latch = 0, values = 0, errors = 1, completions = 0)
java.lang.AssertionError: Value count differs; expected: 1 [null] but was: 0 [] (latch = 0, values = 0, errors = 1, completions = 0)
```

**Comment by madhurgupta10** [comment]
> @madhurgupta10 I was trying to add test for GET call for getting Wikitext. But I am getting this error at the last line. Is this error occurring because of asynchronize call? I was trying to find some solution but can't find any. **Test**
> 
> ```
>     @Test
>     fun `getWikiText`() {
>         val wikiText = mock<MwQueryResponse>()
>         whenever(mediaDetailInterface.getWikiText("File:Test.jpg")).thenReturn(Single.just(wikiText))
>         mediaClient.getCurrentWikiText("File:Test.jpg").test()
>             .assertValues(wikiText.query()?.pages()?.get(0)?.revisions()?.get(0)?.content())
>     }
> ```
> 
> **Error**
> 
> ```
> Value count differs; expected: 1 [null] but was: 0 [] (latch = 0, values = 0, errors = 1, completions = 0)
> java.lang.AssertionError: Value count differs; expected: 1 [null] but was: 0 [] (latch = 0, values = 0, errors = 1, completions = 0)
> ```

It seems like there is a NPE in your expected result `wikiText.query()?.pages()?.get(0)?.revisions()?.get(0)?.content()` 
You don't need to assert for the exact result here, just a type check or even no assert here is fine :)

**Comment by Ayan-10** [comment]
@neslihanturan @madhurgupta10 Can you please review this PR?

**Review by neslihanturan — APPROVED** [review]
Hey @Ayan-10 , thanks a lot it works as intended:)

**Pull request merged**
