### PR TITLE
Removed next button in quiz

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Fixes https://github.com/commons-app/apps-android-commons/issues/4309#issuecomment-810241656

What changes did you make and why?

Removed next button in Quiz layout, Set onclicklistener for radio buttons. Now no need to press the next button.

**Tests performed (required)**

Tested {3.0.0-debug-remove_next~7a3a978eb} on Pixel 4 with API level 27.

@nicolas-raoul Please review and let me know if any issue occurs.

### CODE REVIEW

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @Ayan-10 , I have noted my suggestions under related issue. The code looks fine to me but I have doubts about the issue.

**Comment by neslihanturan** [comment]
hey @Ayan-10 , any updates regarding to my review? Please let us know if you are not interested with this issue anymore :)

**Comment by Ayan-10** [comment]
@neslihanturan My code is ready for PR. I am done with what @nicolas-raoul proposed e about the UI. I attached a screenshot of the UI in issue thread #4309 in May. But no one responds to me for long. Please see my last [comment](https://github.com/commons-app/apps-android-commons/issues/4309#issuecomment-841307850) in issue #4309 and let me know about your opinion on the UI.

**Comment by nicolas-raoul** [comment]
Sorry for the delay!
Actually I am not sure how to test this.
Is there an easy way to make the quiz appear?

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, There is a trick.

1. Go to the WelcomeActivity
2. In the onDestroy method do `isQuiz = true;` before `if (isQuiz) {` (Most probably on line 63)

But before do that please see my last [comment](https://github.com/commons-app/apps-android-commons/issues/4309#issuecomment-841307850)  in issue #4309 . There I attached a screenshot of UI that you told me to change. I was waiting for your response. So I did not make the PR for that. So see it once and let me know your opinion on the UI. Then I will make a commit to this PR. After that, This PR will be ready for review.

**Comment by neslihanturan** [comment]
Hey @Ayan-10 , I have sent my UI review under the issue [here](https://github.com/commons-app/apps-android-commons/issues/4309#issuecomment-866949107)

**Review by nicolas-raoul — APPROVED** [review]
Nice, thanks for this improvement and sorry for the time it took!

**Pull request merged**
