### PR TITLE
Extend from AppCompatActivity instead of Activity

### PR DESCRIPTION
**Pull request by veyndan**
This removes repetitive code as well as laying out the foundations for future backwards compatible uses e.g. using the `Toolbar`.

### CODE REVIEW

**Comment by maskaravivek** [comment]
Looks good to me. @veyndan Are you planning to add more commits to this PR or is ready for review?

**Comment by veyndan** [comment]
It's ready to review. I think that adding any more commits would violate the one change per PR.

**Comment by maskaravivek** [comment]
There are some merge conflicts. Could you please resolve it. :)

**Comment by veyndan** [comment]
Resolved

**Pull request merged**
