### PR TITLE
Added Click To View Photo on Home Screen Widget

### LINKED ISSUE #2767: Add Click to View Photo to Home Screen Widget
**Summary:** 
Add onClick Event to View Photo to the Home Screen Widget so that a user can view the original image.

**Steps to reproduce:** 
Click on the image of Home Screen Widget

**Commons app version:** 
latest prodDebug

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
Added Click To View Photo on Home Screen Widget

Fixes #2767 Add Click To View Photo on Home Screen Widget

**Tests performed**

Tested prodDebug on Xiaomi Mi A1 with API level 28 stock.

**Screenshots showing what changed**
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by domdomegg** [comment]
Would it be possible to have it open in the app in explore mode instead?

**Comment by madhurgupta10** [comment]
@domdomegg Please suggest the Intent you are referring to and I will change to it.

**Comment by domdomegg** [comment]
> @domdomegg Please suggest the Intent you are referring to and I will change to it.

I'm not sure what intent exactly it is - maybe something in explore activity?

**Comment by domdomegg** [comment]
I'm also not sure if it even exists - if it doesn't I'm happy to merge this. Ideally this call to open a URI can be flagged to be updated as part of #2750 (or maybe already can be done, worth checking).

**Comment by madhurgupta10** [comment]
@domdomegg I tried this method but it did not work with PendingIntent.

**Comment by domdomegg** [comment]
Prod GIF @ 9b27d94

prod

**Comment by madhurgupta10** [comment]
@domdomegg checkout #2756 for the beta vs prod error

**Comment by domdomegg** [comment]
> @domdomegg checkout #2756 for the beta vs prod error

Ah cool, thanks for explanation :) In that case I think beta issues should be dealt with another time. Have edited my review.

**Comment by madhurgupta10** [comment]
@domdomegg No Problem :)

**Comment by madhurgupta10** [comment]
@domdomegg I will update it to open at least commons link

**Comment by neslihanturan** [comment]
I agree with:
> The link works on prod, and takes the user to the raw file page - it might be better to at least take them to the Commons page if not possible to take in app?

Passed from manual tests with API 26 though.

**Comment by madhurgupta10** [comment]
@domdomegg @neslihanturan Changes made, now opens Commons file :)

**Pull request merged**
