### PR TITLE
WIP: Spotless plugin applied

### LINKED ISSUE #3405: Irregular indentation in a lot of places in the application files.
**Summary:** 

Irregular indentation in a lot of places in the application files. 
In several places, the code-style of the app might not be followed. For example, in some places the following style is used:

`if(condition){ }`

In some other places the following style is used:

`if (condition) { }`

We should be using the second type of style since we are following the Google Java Code Style. 
In order to fix this, and prevent any future discrepancies, we should consider using the **[spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle)** gradle plugin. Once added, on running the `spotlessApply` command just once, it will automatically fix the existing faults in the code. And we can also add the check(`spotlessCheck`) to Travis so that if while contributing in future commits the style isn't followed, the Travis check won't pass. 
This will enhance the maintainability and code style of the app a lot. 

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by yashk2000**
**Description (required)**

Fixes #3405 Irregular indentation in a lot of places in the application files

**What changes did you make and why?**

Applied the spotless plugin. Now all java and kotlin files have the same style of indentation. 
Also, put the spotlessCheck test in the travis.yml file to catch any errors in code style for future prs.

**Addtional Context**

There are a lot of file changes, but the changes are only in the coding style.

### CODE REVIEW

**Comment by ashishkumar468** [comment]
@yashk2000 Can you check why is travis failing?

**Comment by yashk2000** [comment]
> @yashk2000 Can you check why is travis failing?

I'm trying to fix it. I'll squash all the extra commits once I'm able to fix the issue.

**Comment by yashk2000** [comment]
@ashishkumar468 @maskaravivek @nicolas-raoul please review. The build is passing now.

**Comment by yashk2000** [comment]
Along with proper code formatting, all the imports have also been optimized. unneeded imports have been removed and wildcard imports have been optimized.

**Comment by sivaraam** [comment]
I have't looked at the complete changeset. But just looking at the number of changed files (353 files!) makes me wonder how this is gonna introduce conflicts to all the other PRs and any other parallel work that's in progress.

Would it be possible to do this change in multiple phases with the initial one possibly being that we just introduce the Travis check and ensure future *changes* don't introduce any improperly formatting?

**Comment by yashk2000** [comment]
@sivaraam it's not possible to do this in multiple phases. The command which does the job is `./gradlew spotlessApply` which makes the entire change in one go and not file by file.

Also if we just put the check in Travis, it'll still fail the build. It checks all files in the app and not just those modified in a or.

It's a big change, but sooner or later it has to be done. If people working on all the open prs are still active, it won't be much of a change. They can reset their branch to the lastest master. Copy paste their earlier changes and again fix the indentation in that by running the spotless apply command.

**Comment by maskaravivek** [comment]
I share @sivaraam's concerns and am not sure if we should merge the whole changeset at this point of time when a lot of GSoC/Outreachy students are trying to make their first contribution. 

Moreover, before making any such formatting changes we should probably discuss the code styling in more detail on the issue thread before adding this plugin. Looks like spotless plugin has a bunch of options and we should decide what settings we want. https://github.com/diffplug/spotless#current-feature-matrix

**Comment by sivaraam** [comment]
> @sivaraam it's not possible to do this in multiple phases. The command which does the job is `./gradlew spotlessApply` which makes the entire change in one go and not file by file.
> 

Though I'm not sure about it, I think we really can make the changes in multiple phases by using the `target` attribute to specify just selected paths of the code base for conversion. Something like the following:

```gradle
spotless {
    java {
        googleJavaFormat()
        indentWithSpaces(4)
        target 'src/main/java/fr/free/nrw/commons/concurrency/*.java','src/main/java/fr/free/nrw/commons/mwapi/*.java'
    }

    ...
}
```

> Also if we just put the check in Travis, it'll still fail the build. It checks all files in the app and not just those modified in a PR.
> 

Either you missed my point or I didn't convey it very clearly. Anyways, I was thinking if there was a way to ask the plug-in to verify that the **changes** made in the PR (the diff) doesn't introduce any improper formatting. If we cannot, then we can just think of an alternative initial phase.

> It's a big change, but sooner or later it has to be done.

Not if you can live with [code that has some irregularities](https://overreacted.io/goodbye-clean-code/) 😉 

> If people working on all the open prs are still active, it won't be much of a change. They can reset their branch to the lastest master. Copy paste their earlier changes and again fix the indentation in that by running the spotless apply command.
> 

There are [better ways](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) to integrate changes. That's not the point, though. The fact that this change is intrusive enough to ask them to do those changes is the point.

**Comment by yashk2000** [comment]
> I share @sivaraam's concerns and am not sure if we should merge the whole changeset at this point of time when a lot of GSoC/Outreachy students are trying to make their first contribution.
> 
> Moreover, before making any such formatting changes we should probably discuss the code styling in more detail on the issue thread before adding this plugin. Looks like spotless plugin has a bunch of options and we should decide what settings we want. https://github.com/diffplug/spotless#current-feature-matrix

@maskaravivek sure. We can maybe put this pr as a WIP and merge it later when fewer first-time contributors will be working. Till then, we can decide on the coding style that we plan.

**Comment by yashk2000** [comment]
> Though I'm not sure about it, I think we really can make the changes in multiple phases by using the target attribute to specify just selected paths of the code base for conversion. Something like the following:

@sivaraam in my opinion, it isn't practical to split the changes this way. Even if we do it, we can't put the check in Travis. If the check is to be put in Travis, the entire app code has to be reformatted. 

> Either you missed my point or I didn't convey it very clearly. Anyways, I was thinking if there was a way to ask the plug-in to verify that the changes made in the PR (the diff) doesn't introduce any improper formatting. If we cannot, then we can just think of an alternative initial phase.

The check will be put in travis by simply adding one line:

`./gradlew spotlessCheck`

This can't be applied to one particular file or just files that have been changed in the pr. It will run for the entire app. 

> Not if you can live with code that has some irregularities :wink:

I personally prefer to have the code properly formatted. I believe it increases the readability way more than when it is unformatted :smile:. And while contributing to the code, the ease of readability does play an important role in how fast a new contributor can grasp what the existing code is doing and make changes accordingly. 

> The fact that this change is intrusive enough to ask them to do those changes is the point.

I believe merge conflicts to happen frequently enough while contributing to an open-source project :)

But I agree with @maskaravivek that right now we'll have a lot of people making their first contributions for GSoC/Outreachy and this might overwhelm them. So for the time being, we can keep this as WIP pr and merge it sometime later.

**Comment by sivaraam** [comment]
> > Though I'm not sure about it, I think we really can make the changes in multiple phases by using the target attribute to specify just selected paths of the code base for conversion. Something like the following:
> 
> @sivaraam in my opinion, it isn't practical to split the changes this way. Even if we do it, we can't put the check in Travis. If the check is to be put in Travis, the entire app code has to be reformatted.
> 

Yeah, I realise we can't put the check in Travis. I was just suggesting a way to make a phased change over a long period of time (10 or 20 files changed in each phase) so that this formatting fix would be less intrusive to the other contributors working on other PRs. We can add the check later on after all parts of the code base has been updated and the discussion about the options to use has concluded.

On a related note, looks like there's a better way to make spotless apply changes only to specific files. Refer [linked QA](https://github.com/diffplug/spotless/tree/master/plugin-gradle#can-i-apply-spotless-to-specific-files).

> The check will be put in travis by simply adding one line:
> 
> `./gradlew spotlessCheck`
> 
> This can't be applied to one particular file or just files that have been changed in the pr. It will run for the entire app.
>

I was thinking of whether we could run this only on diffs alone. But looks like we can't. So, we could just think of a better initial phase if we're considering a phased change. IMHO, a phased change is the best way to go for huge formatting changes like these.

> > Not if you can live with code that has some irregularities :wink:
> 
> I personally prefer to have the code properly formatted. I believe it increases the readability way more than when it is unformatted :smile:. And while contributing to the code, the ease of readability does play an important role in how fast a new contributor can grasp what the existing code is doing and make changes accordingly.
> 

Agreed. Ideally, it's good to have properly formatted code. I used to be like this. But trust me over time you'll get used to working with code that has some irregularities in it without getting irritated by it :slightly_smiling_face: You'll realise that what's mentioned in the [linked blog](https://overreacted.io/goodbye-clean-code/) is ***so ture***. I do. Just wanted to mention this.

That said, let me clarify something to avoid misinterpretation. I don't mean that we should abandon this change. IMO, it's a good change but it would be really nice if we can make this less intrusive.

**Comment by yashk2000** [comment]
>Agreed. Ideally, it's good to have properly formatted code. I used to be like this. But trust me over time you'll get used to working with code that has some irregularities in it without getting irritated by it slightly_smiling_face You'll realise that what's mentioned in the linked blog is so ture. I do. Just wanted to mention this.

I feel this is a matter of personal opinion. I have been contributing to open source for around 2 years now, and I have done my best to maintain code quality whenever I contribute to a project even if the project does not mention any specific guidelines. 

> That said, let me clarify something to avoid misinterpretation. I don't mean that we should abandon this change. IMO, it's a good change but it would be really nice if we can make this less intrusive.

Nothing was misinterpreted :) I agree with you completely and thanks for providing this review 

> On a related note, looks like there's a better way to make spotless apply changes only to specific files. Refer linked QA.

We can proceed with this maybe starting with just around 10-15 files at a time.

@maskaravivek what are your views on this?

**Comment by maskaravivek** [comment]
Thank you @sivaraam and @yashk2000 for your insights. For now I am closing this PR so that its not merged accidentally and let us move the discussion to the issue thread ie. #3405.

**Pull request closed without merging**
