### PR TITLE
Fixed compass overlap issue in Nearby map

### LINKED ISSUE #1395: Map orientation button gets overlapped by recenter button
The directions symbol appears when the map is zoomed in or rotated , that symbol is overlapped by the recenter button.

alt link

**Expected behavior:** 

The directions symbol not appearing at all or the recenter button has to be moved down

**Device and Android version:** 
Android 6.0.1

### PR DESCRIPTION
**Pull request by wanderlustyc**
## Description

Fixes #1395 Map orientation button gets overlapped by recenter button

In NearbyMapFragment.java, line 410, assigned top and right margins to the compass button, since it is by default in the top-right corner.

## Tests performed

Tested on HUAWEI PLK-AL10, Android 6.0, API23.

## Screenshots showing what changed
 
wechatimg31

### CODE REVIEW

**Comment by misaochan** [comment]
@wanderlustyc Could you please rebase your branch on `2.7.x-release`? Thanks. :)

**Comment by wanderlustyc** [comment]
@misaochan done

**Comment by misaochan** [comment]
@wanderlustyc Hm, have you done a git rebase and pushed your branch to remote? I'm still seeing 47 files changed.

**Comment by wanderlustyc** [comment]
@misaochan I did `git rebase upstream/2.7.x-release` and then `git push origin master`. Sorry I'm not quite familiar with to git rebase command. Or am I supposed to submit my PR to the 2.7.x-release branch?

**Comment by misaochan** [comment]
Interesting, that should have worked, but isn't working from what I can see. You were supposed to submit your PR to the 2.7.x-release branch indeed, but usually we can switch it for you (like what I just did), so that should not have caused the problem. 

Did you make sure that you pulled the latest version of the 2.7.x-release branch from upstream beforehand?

**Comment by misaochan** [comment]
At any rate, given that your fix is just one line, it might actually be easier for you to start from scratch. Create a new branch from 2.7.x-release, add the line, then submit the PR to 2.7.x-release?

**Comment by wanderlustyc** [comment]
@misaochan Yes, that's easier. I've submitted a new PR #1423 I guess the problem was that I didn't checkout my local branch from the 2.7.x-release branch.

**Comment by misaochan** [comment]
Thanks @wanderlustyc ! Will close that in this case.

**Pull request closed without merging**
