### PR TITLE
Remove unused interface license message strings

### LINKED ISSUE #243: Unused license messages
There are many apparently unused license messages, like `license_name_pd_usgov`.

Is there any intention to use them in the near future?

### PR DESCRIPTION
**Pull request by dr0ptp4kt**
The app currently displays licenses aligned with MediaWiki's
UploadWizard UploadWizard.config.php file for ownWork. Presently,
the aligned licenses are as follows.h

cc-by-sa-4.0
cc-by-sa-4.0
cc-by-sa-3.0
cc-by-4.0
cc-by-3.0
cc-zero

License messages other than these are removed with this patch.

This closes #243.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@dr0ptp4kt Thanks for the PR. There are some merge conflicts. Can you resolve them :)

**Comment by dr0ptp4kt** [comment]
@maskaravivek does it look okay now?

**Comment by Nikerabbit** [comment]
Most translators will be happy when there is less to translate :)

**Comment by misaochan** [comment]
Awesome, thanks everyone!

**Pull request merged**
