### PR TITLE
Fix issues in Media Detail screen

### PR DESCRIPTION
**Pull request by akaita**
I was initially just going to fix i18n-related issues in MediaDetailFragment, but it had some important bugs that I felt had to be fixed. I hope these are not too many changes for a single PR, as they are all focused on the same screen:

### Crash when no upload date is set

The code assumed that the upload date for `Media` was not nullable. This can happen when the upload fails, for instance.
I added the appropriate annotation and prevented the crash.

Crash-log:

```java
07-15 18:24:00.399 29217-29217/fr.free.nrw.commons E/AndroidRuntime: 
FATAL EXCEPTION: main
Process: fr.free.nrw.commons, PID: 29217
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Date.toString()' on a null object reference
 at fr.free.nrw.commons.media.MediaDetailFragment.prettyUploadedDate(MediaDetailFragment.java:330)
 at fr.free.nrw.commons.media.MediaDetailFragment.access$1500(MediaDetailFragment.java:31)
 at fr.free.nrw.commons.media.MediaDetailFragment$4.onPostExecute(MediaDetailFragment.java:219)
 at fr.free.nrw.commons.media.MediaDetailFragment$4.onPostExecute(MediaDetailFragment.java:186)
 at android.os.AsyncTask.finish(AsyncTask.java:660)
 at android.os.AsyncTask.-wrap1(AsyncTask.java)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6077)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

### Some strings were hardcoded

A couple of strings were hardcoded in the layout xml. I extracted them to `strings.xml`. I followed a naming convention similar to other strings in that area, and avoided adding invisible strings to the translatable set (for instance: `License link`).

### Wrong RTL support

The layout tried to offer RTL support using `left|start`, which is wrong. Fixed it to use `start`.

### Categories would behave wrongly: adding object blindly

| Before  | After |
| ------- | ----- |
| mediadetail categories repeat | mediadetail categories correct  |

### CODE REVIEW

**Comment by misaochan** [comment]
Thanks for the PR @akaita !

It looks great to me, with one issue - I'm undecided about coordinate-clicking leading to the map application. I personally feel that anything that leads the user to switch apps (opens up the browser) on finger tap without explicitly making it clear that it would do that, needs to be handled very cautiously, otherwise users might get annoyed by the unexpected behaviour. Licenses could perhaps offer a benefit that exceeds the risks (and even then I might argue for a button for "open in browser/webview" if we redesign the media details screen), but adding coordinates feels a bit much to me.

If others think that tapping Coordinates should open up a map app, I'm happy to go with the majority though. :)

**Comment by akaita** [comment]
Hi @misaochan, I see your point and I agree with you. I was unsure about adding a modal before taking the user out of the app, or maybe adding a `link` symbol on the right-hand side or each row to trigger the click event...
I decided to go with the clickable row just because it looked like that was the intended behaviour for the License and it was worth keeping it consistent.
It'll be interesting to hear more ideas about this.

**Comment by akaita** [comment]
@misaochan Would it be useful to split this PR in two, so we can get the part with pure fixes in and leave the other part for further review?

**Comment by misaochan** [comment]
@akaita That would be great, I am happy to merge the other sections if they were in a separate PR. :)

**Comment by akaita** [comment]
@misaochan I just updated this PR so it only contains the fixes. I created #796 to host changes for the onClickListeners (hoping this one will be merged, so the diff gets simplified :) ).

**Pull request merged**
