### PR TITLE
[WIP] [GSoC] Insert Images as not for upload

### PR DESCRIPTION
**Pull request by Ayan-10**
**Tasks**

- [x] Connect the database with UI
- [x] Implement Insert operation
- [ ] Mark those inserted images with a 🚫 overlay icon and grey them

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
To do this, you might have to close this PR and open a new one.

**Comment by nicolas-raoul** [comment]
Regarding the overlay:

I suggest first making sure that the following works:
1. Mark an image as "not for upload"
2. Kill the app
3. Restart the app
4. Open the image selector again
5. See whether the overlay is shown

To make the above work, looking at the code for the "already uploaded" overlay should be enough.
The above does not currently seem to work using the code in this branch.

**Comment by Ayan-10** [comment]
@nicolas-raoul Yes, the following works already. I haven't pushed that part of the code yet. I'm having some trouble in-place marking those images.

**Comment by nicolas-raoul** [comment]
Understood, thanks :-)

**Comment by Ayan-10** [comment]
New pr is created. So, closing this one

**Pull request closed without merging**
