### PR TITLE
Fixed issue #927

### PR DESCRIPTION
**Pull request by RSBat**
The issue #927 was caused by not resetting search radius. If there were too little places then search radius would become larger than MAX_RADIUS and no request to the server would be made

### CODE REVIEW

**Comment by whym** [comment]
Perhaps you can enforce the max radius instead when violated? One idea might be to ensure sending one query when (radius > MAX_RADIUS) instead of zero.

My initial intention was to remember the radius from the previous search in order to reduce the number of request. The initial radius may work well for a dense area but not for a sparse area, and the idea was to remember the previous radius which should work well assuming the density doesn't suddenly change. So resetting the radius for every session doesn't seem ideal.

**Comment by RSBat** [comment]
OK, I changed the code so we remember radius so we don't do many requests each time, but if it becomes too big then it is set to max radius.
NB: the largest actually requested radius is approximately 200 while max radius is 300. I am not sure this 100 km increase is wanted.
By the way I have no idea why travis build failed

**Comment by neslihanturan** [comment]
@RSBat thanks for finding and solving the bug! I have tested it and works for me. I checked radius values too, and verified setting it max_radius control works as intended. However I couldn't get what you mean by 
>the largest actually requested radius is approximately 200 while max radius is 300. I am not sure this 100 km increase is wanted.

By looking at the code, we only reduce radius if it exceeds max value, what you mean by increase?

**Comment by RSBat** [comment]
If we look at radius value as it increases then it will be 1, 1.618, ..., 122.96, 198.95. After that it goes to 321.91 and it is larger than max_radius which is 300.
So under normal circumstances the app never asks for places outside 200km radius, but after setting radius to max_radius it will ask for 300km.
I'm not sure if it is important, just wanted to point that out.

**Comment by neslihanturan** [comment]
Hmm, maybe we should consider changing our max radius value to 200 km. Thanks for pointing this out!

**Pull request merged**
