### PR TITLE
Remove dependency on Glide, Picasso, SVG, and multidex.

### PR DESCRIPTION
**Pull request by dbrant**
This removes the dependency on Glide, as well as the SVG rendering library, whose only purpose was to display a single SVG image in the Notification activity. Unfortunately Android doesn't support SVG natively,
but Echo notifications have icons that are SVG formatted. Rather than import a bunch of heavy libraries to support this single case of SVG rendering, we can simply create a few local drawables that correspond to the different types of notifications, and use them instead.

This also removes the (single) use of the Picasso library, and replaces it with correct usage of Fresco.

And because so much bloat has been removed, we can also now remove multidex, since the method count is now well under 65k, and is back in the real world.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @dbrant for great optimization. I wanted to try but couldn't get rid of this error:

`     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons.beta-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.free.nrw.commons.beta-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)`

**Comment by dbrant** [comment]
@neslihanturan Hmm that's curious. Can you try cleaning & rebuilding the project? I just tried a clean checkout and am not seeing any issues. It looks like your APK is still expecting to use multidex, when in fact we've removed it.

**Comment by neslihanturan** [comment]
I tried to disable instant run, clean and rebuild but none worked so far. It should be an Android Studio mystery:/. @misaochan can you also try to test this PR, lets see if you can manage.

**Comment by dbrant** [comment]
What's the configuration (API version, etc) of the device and/or emulator that you're running on?

**Comment by neslihanturan** [comment]
A real device Android 4.4.2. On the other hand I successfully tested the PR on an emulator with API 23.

**Comment by dbrant** [comment]
Thanks; reproduced on a real API 18 device. Will look into it...

**Comment by dbrant** [comment]
@neslihanturan  OK, pls try again with the latest commit! (make sure to clean the project first.)

**Comment by neslihanturan** [comment]
@dbrant unfortunately didn't solved for me:/ Uninstalled the app, disabled instant run, cleaned and rebuilt, but still having same problem on API 19 device.

**Pull request merged**
