### PR TITLE
Update app icon (Fixes #868)

### LINKED ISSUE #868: Change the app's icon
It seems the app's icon needs some update. It doesn't look so nice on some backgrounds.

commons logo

Though the logo seems to be clear in the above screen shot it's not when the brightness is low. It's very hard to identify it.

How about giving it a circular (Android O's coming) white background to it.

### PR DESCRIPTION
**Pull request by sdabhi23**
**Description (required)**

Fixes #868 Change the app's icon

What changes did you make and why?

Created and added required SVGs under the design folder. Generated adaptive and legacy icons for prod and beta versions.

**Tests performed (required)**

Tested BetaDebug and ProdDebug on Moto G5S  Plus with API level 27.

**Screenshots showing what changed (optional - for UI changes)**

image

Need help? See https://support.google.com/android/answer/9075928
---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @sdabhi23 , they look very nice. I tested on API 19 and 26 devices, and it worked as expected. I wonder is usage of .svg files appropriate for this purpose. What do you say @maskaravivek ?

**Comment by sdabhi23** [comment]
@neslihanturan I have used the .svg files to generate vector drawables, and then generated legacy and adaptive launcher icons from the vectors drawables, so that the icons would not blur/pixelate at any screen resolution.

**Comment by neslihanturan** [comment]
Yes @sdabhi23 , I would say so but we tried to avoid usage of .svg files since they are not supported. But I am not sure about details. @maskaravivek if I recall correct you worked on a related task (about turning .svg files back to .png files) . What do you suggest about this PR?

**Comment by nicolas-raoul** [comment]
Source design files are a very good thing to have indeed!
Could you please put them into https://github.com/commons-app/apps-android-commons/tree/master/design ? Thanks! :-)

**Pull request merged**
