### PR TITLE
Convert achievements models to Kotlin

### PR DESCRIPTION
**Pull request by veyndan**
This relates to #747.

This is a demonstration (and hopefully a first step) on how Kotlin can be used in the main application. I have chosen to convert a subset of models as these are fairly ease to convert over, shows the extent of Kotlin's conciseness (250 lines down to 50 lines), and adds Kotlin's niceties when using data classes (like automatically generating `toString()`, `equals()`, and `hashcode()` methods).

### CODE REVIEW

**Comment by misaochan** [comment]
Welcome back, @veyndan ! :)

I don't think we have reached a consensus on whether or not we want to convert everything (besides tests) to Kotlin. Would anyone else like to weigh in on this? This is a big decision IMO, not something to be done lightly. While Kotlin can certainly coexist with Java code, it would be very messy to have patches of it if we don't plan on eventually converting everything.

**Comment by veyndan** [comment]
Thanks! Had to take a bit of a hiatus due to other commitments.

A further discussion around this would be beneficial as the adoption of Kotlin in the Android community has greatly increased since then, so Kotlin being a barrier to entry is now less of a concern. This PR shows some concrete usage of Kotlin in the project, and will hopefully revitalise the previous discussion.

Btw, I opened #2943 a while ago relating to Kotlin in tests if anyone has time to look at it.

**Comment by maskaravivek** [comment]
@veyndan If you could fix the conflicts, I would be happy to merge this PR. Now we have adopted Kotlin in our main codebase. :)

**Comment by madhurgupta10** [comment]
@veyndan Are you still working on this PR, I am converting java files to kotlin, I can add these changes in my PR #3439 :)

**Comment by macgills** [comment]
These files have been converted but could use improvement. I am going to make an issue for that but will be closing this PR

**Pull request closed without merging**
