### PR TITLE
Avoid "form movements" in the login screen

### LINKED ISSUE #1107: Avoid "form movements" in the login screen
By "dynamism", I mean trying to keep the username and password fields always at the center of the available screen space. This distracts the user when he fills in the fields.

From #1106,
>The login page (username and password input fields) seems to shifting itself to remain in the center with respect to the available screen height. This movement doesn't seem to be a big deal if it only happens when the users keyboard pops in and pops out. In some cases the user's keyboard might suggest things as he types. These suggestions pop in and pop out above the keyboard itself as and when required. This results in the login page moving when the user types his username. This seems to be disturbing to the user as he notices something moving on his screen which generally doesn't happen in case of login screens.
>
>...
>
>**Screen shots**
>screenshot_20180123-214313
>screenshot_20180123-214311

### PR DESCRIPTION
**Pull request by noahwalugembe**
I have Avoided "dynamism/movements" of username and password fields in the login screen by stopping the soft keyboard from pushing my view up.

Fixes #1107

### CODE REVIEW

**Comment by noahwalugembe** [comment]
> I can click the password field after entering my username.

Thanks dear but with the new implementation you can still  click the password field after entering my username. The keyboard can still support you.

**Comment by domdomegg** [comment]
Dismissing my previous review on grounds of lacking appropriate issue, as I've now tagged #1107.

**Comment by domdomegg** [comment]
> > I can't click the password field after entering my username.
> 
> Thanks dear but with the new implementation you can still click the password field after entering my username. The keyboard can still support you.

I don't seem to be able to with my emulator config:

```
Name: Galaxy_Nexus_API_28
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/adam/.android/avd/Galaxy_Nexus_API_28.avd
Target: google_apis [Google APIs] (API level 28)
Skin: 720x1280
SD Card: 512 MB
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Galaxy Nexus
hw.lcd.width: 720
hw.initialOrientation: Portrait
image.androidVersion.api: 28
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Galaxy Nexus API 28
hw.gpu.mode: auto
hw.ramSize: 1024
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1280
vm.heapSize: 80
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
skin.path.backup: _no_skin
hw.audioInput: yes
image.sysdir.1: system-images/android-28/google_apis/x86/
showDeviceFrame: no
hw.camera.back: virtualscene
AvdId: Galaxy_Nexus_API_28
hw.lcd.density: 320
hw.arc: false
hw.device.hash2: MD5:fcb1c44f60d9172bb27b44fdd821eed1
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 2G
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

Screenshots

| Before | With changes |
| - | - |
| Screenshot_1552751802 | Screenshot_1552750416 |

**Comment by noahwalugembe** [comment]
> > > I can't click the password field after entering my username.
> > 
> > 
> > Thanks dear but with the new implementation you can still click the password field after entering my username. The keyboard can still support you.
> 
> I don't seem to be able to with my emulator config:
> 
> ```
> Name: Galaxy_Nexus_API_28
> CPU/ABI: Google APIs Intel Atom (x86)
> Path: /home/adam/.android/avd/Galaxy_Nexus_API_28.avd
> Target: google_apis [Google APIs] (API level 28)
> Skin: 720x1280
> SD Card: 512 MB
> fastboot.chosenSnapshotFile: 
> runtime.network.speed: full
> hw.accelerometer: yes
> hw.device.name: Galaxy Nexus
> hw.lcd.width: 720
> hw.initialOrientation: Portrait
> image.androidVersion.api: 28
> tag.id: google_apis
> hw.mainKeys: no
> hw.camera.front: emulated
> avd.ini.displayname: Galaxy Nexus API 28
> hw.gpu.mode: auto
> hw.ramSize: 1024
> PlayStore.enabled: false
> fastboot.forceColdBoot: no
> hw.cpu.ncore: 4
> hw.keyboard: yes
> hw.sensors.proximity: yes
> hw.dPad: no
> hw.lcd.height: 1280
> vm.heapSize: 80
> skin.dynamic: yes
> hw.device.manufacturer: Google
> hw.gps: yes
> skin.path.backup: _no_skin
> hw.audioInput: yes
> image.sysdir.1: system-images/android-28/google_apis/x86/
> showDeviceFrame: no
> hw.camera.back: virtualscene
> AvdId: Galaxy_Nexus_API_28
> hw.lcd.density: 320
> hw.arc: false
> hw.device.hash2: MD5:fcb1c44f60d9172bb27b44fdd821eed1
> fastboot.forceChosenSnapshotBoot: no
> fastboot.forceFastBoot: yes
> hw.trackBall: no
> hw.battery: yes
> hw.sdCard: yes
> tag.display: Google APIs
> runtime.network.latency: none
> disk.dataPartition.size: 2G
> hw.sensors.orientation: yes
> avd.ini.encoding: UTF-8
> hw.gpu.enabled: yes
> ```
> Screenshots
> 
> Before	With changes
> Screenshot_1552751802	Screenshot_1552750416

Can you try it out on a real device . Am using a real device to test

**Comment by domdomegg** [comment]
Real device screenshot:

Screenshot_20190316-162506

It is better, however I'm concerned it won't work on devices with lower resolutions / different aspect ratios. It's also still annoying in the emulator as it makes it harder to copy and paste passwords which I do a lot when logging in etc. to test PRs.

**Comment by noahwalugembe** [comment]
Can i create a new issue for adding{ detect  paste event in password and username  editext  box}

**Comment by noahwalugembe** [comment]
> > > > I can't click the password field after entering my username.
> > > 
> > > 
> > > Thanks dear but with the new implementation you can still click the password field after entering my username. The keyboard can still support you.
> > 
> > 
> > I don't seem to be able to with my emulator config:
> > ```
> > Name: Galaxy_Nexus_API_28
> > CPU/ABI: Google APIs Intel Atom (x86)
> > Path: /home/adam/.android/avd/Galaxy_Nexus_API_28.avd
> > Target: google_apis [Google APIs] (API level 28)
> > Skin: 720x1280
> > SD Card: 512 MB
> > fastboot.chosenSnapshotFile: 
> > runtime.network.speed: full
> > hw.accelerometer: yes
> > hw.device.name: Galaxy Nexus
> > hw.lcd.width: 720
> > hw.initialOrientation: Portrait
> > image.androidVersion.api: 28
> > tag.id: google_apis
> > hw.mainKeys: no
> > hw.camera.front: emulated
> > avd.ini.displayname: Galaxy Nexus API 28
> > hw.gpu.mode: auto
> > hw.ramSize: 1024
> > PlayStore.enabled: false
> > fastboot.forceColdBoot: no
> > hw.cpu.ncore: 4
> > hw.keyboard: yes
> > hw.sensors.proximity: yes
> > hw.dPad: no
> > hw.lcd.height: 1280
> > vm.heapSize: 80
> > skin.dynamic: yes
> > hw.device.manufacturer: Google
> > hw.gps: yes
> > skin.path.backup: _no_skin
> > hw.audioInput: yes
> > image.sysdir.1: system-images/android-28/google_apis/x86/
> > showDeviceFrame: no
> > hw.camera.back: virtualscene
> > AvdId: Galaxy_Nexus_API_28
> > hw.lcd.density: 320
> > hw.arc: false
> > hw.device.hash2: MD5:fcb1c44f60d9172bb27b44fdd821eed1
> > fastboot.forceChosenSnapshotBoot: no
> > fastboot.forceFastBoot: yes
> > hw.trackBall: no
> > hw.battery: yes
> > hw.sdCard: yes
> > tag.display: Google APIs
> > runtime.network.latency: none
> > disk.dataPartition.size: 2G
> > hw.sensors.orientation: yes
> > avd.ini.encoding: UTF-8
> > hw.gpu.enabled: yes
> > ```
> > Screenshots
> > Before	With changes
> > Screenshot_1552751802	Screenshot_1552750416
> 
> Can you try it out on a real device . Am using a real device to test

Can i create a new issue for adding{ detect paste event in password and username editext box}

**Comment by sivaraam** [comment]
>  however I'm concerned it won't work on devices with lower resolutions / different aspect ratios. 

I think you're correct. The screenshot of the "With changes" really doesn't seem to work well low resolution devices (FWIW, I own one).

That said, I'm pretty much not sure what kind of solution I had in mind when I opened #1107. Maybe one that

**Comment by sivaraam** [comment]
>  however I'm concerned it won't work on devices with lower resolutions / different aspect ratios. 

I think you're correct. The screenshot of the "With changes" really doesn't seem to work well low resolution devices (FWIW, I own one).

That said, I'm pretty much not sure what kind of solution I had in mind when I opened #1107. It's been a long time since I opened it. Maybe I was thinking of a solution that would show you both the username and password fields (even in small resolution devices, to an extent of course ;-) but wouldn't adjust the position of the fields when the user switches between fields. I couldn't come up with a real life example that exactly matches what I'm trying to say but the "Wikipedia" android app's login screen could be a good example.

**Comment by noahwalugembe** [comment]
Can I slightly shift the form on top so as to avoid overlaping on vary small devices

**Comment by noahwalugembe** [comment]
> > however I'm concerned it won't work on devices with lower resolutions / different aspect ratios.
> 
> I think you're correct. The screenshot of the "With changes" really doesn't seem to work well low resolution devices (FWIW, I own one).
> 
> That said, I'm pretty much not sure what kind of solution I had in mind when I opened #1107. It's been a long time since I opened it. Maybe I was thinking of a solution that would show you both the username and password fields (even in small resolution devices, to an extent of course ;-) but wouldn't adjust the position of the fields when the user switches between fields. I couldn't come up with a real life example that exactly matches what I'm trying to say but the "Wikipedia" android app's login screen could be a good example.

Can I slightly shift the form on top so as to avoid overlapping on vary small devices

**Comment by sivaraam** [comment]
> Can I slightly shift the form on top so as to avoid overlapping on vary small devices

Before that, I have a doubt. When I tried to reproduce the issue in #1107 using my device I couldn't. I tried using two keyboards and couldn't reproduce using either of them. I doubt if #1107 is an issue at all.

Can anyone else reproduce the issue stated in #1107?

**Comment by noahwalugembe** [comment]
> > Can I slightly shift the form on top so as to avoid overlapping on vary small devices
> 
> Before that, I have a doubt. When I tried to reproduce the issue in #1107 using my device I couldn't. I tried using two keyboards and couldn't reproduce using either of them. I doubt if #1107 is an issue at all.
> 
> Can anyone else reproduce the issue stated in #1107?

Yes i can reproduce the issue on my device. when i remove the new code the soft keyboard from starts pushing the form view up and down hence introducing  "dynamism/movements" of username and password form.  .

**Comment by sivaraam** [comment]
@noahwalugembe What keybooard do you use? Also, can you please post screenshots demonstrating the issue (maybe a video)?

I just wanted to know whether we're on the right page about our understanding of #1107.

**Comment by noahwalugembe** [comment]
> @noahwalugembe What keybooard do you use? Also, can you please post screenshots demonstrating the issue (maybe a video)?
> 
> I just wanted to know whether we're on the right page about our understanding of #1107.

Thanks dear i have shared the gif's blow.  They are big and i could not embed them in here  
Before: 
Soft keyboard  push form view up on login screen

https://drive.google.com/open?id=1xeEMbRd3qHuYTsiK41rLPsK1amMgUqsw

After :
Stoped oft keyboard  from push form view up on login screen 
https://drive.google.com/open?id=1aaB3ujvKKQ3El9jkRfc3eKQs3o801qsZ



Soft keyboard from pushing my view up.

**Comment by nicolas-raoul** [comment]
Only judging from the GIFs in the comment above, the biggest "form movement" that I can see in the "Before" GIF seems to not be present in the "After" video :-)

**Comment by noahwalugembe** [comment]
> Only judging from the GIFs in the comment above, the biggest "form movement" that I can see in the "Before" GIF seems to not be present in the "After" video :-)

Is this some thing we can regard as a user experience improvement?

**Comment by nicolas-raoul** [comment]
I am not familiar with the topic but personally I would say so.
Does it work well in landscape mode, on small and big screens?

**Comment by noahwalugembe** [comment]
> I am not familiar with the topic but personally I would say so.
> Does it work well in landscape mode, on small and big screens?

Yes it can now work well on both small and big screens

**Comment by nicolas-raoul** [comment]
Would you mind posting a screenshot showing how the balance looks on big screens? Thanks! :-)

**Comment by noahwalugembe** [comment]
> Would you mind posting a screenshot showing how the balance looks on big screens? Thanks! :-)

Currently am having issues with running an emulator on my PC i have only tried it on two small phones.
Does your pc support emulators

**Comment by noahwalugembe** [comment]
> Would you mind posting a screenshot showing how the balance looks on big screens? Thanks! :-)
Thanks @nicolas-raoul for your response. I have tried to tried to get a big screen and blow are the images
IMG_20190319_214644_4
IMG_20190319_214656_8
IMG_20190319_214746_1
IMG_20190319_214802_6

**Comment by sivaraam** [comment]
>  Does it work well in landscape mode, on small and big screens?

I suspect this would not work well on small screen devices. Particularly in landscape mode. I haven't tested it but I do have a small screen device. I'll let you know when I manage to build and test this one. If someone gives me an APK I it would be easier for me to test :-)

> I have tried to tried to get a big screen and blow are the images

I have a doubt with the images you posted. I suspect your changes aren't kicking in for the landscape mode. If they do, then the form shouldn't have moved but it seems to be moving when the keyboard opens. May be you have to make changes to the [corresponding landscape mode layout](https://github.com/commons-app/apps-android-commons/blob/3e990ab69a2d7ac2f1c05ef8d7f846d2fb8efdc3/app/src/main/res/layout-land/activity_login.xml) file? Or is it intentionally left untouched?

**Comment by noahwalugembe** [comment]
> it intentionally left untouched?
Yes  it intentionally left untouched on medium and small devices landscape mode layout  so as to avoid scrolling after fixing the view in-static position.

**Comment by sivaraam** [comment]
@noahwalugembe I think you should be creating a separate PR for #2660.

**Comment by noahwalugembe** [comment]
Deletionnomination #2682

**Comment by neslihanturan** [comment]
Hi @noahwalugembe , this pull request needs some more work for fixing conflicts, removing unneeded changes and deciding to the best strategy for the UI change we want. Sending a fresh new PR would only require the last step, so will be easier. That's why I am closing this one, please feel free to reopen it if needed.

**Pull request closed without merging**
