### PR TITLE
[WIP] In depictions selection screen, suggest recently selected items

### LINKED ISSUE #3634: In depictions selection screen, suggest recently selected items
For now, the depictions selection screen does not show anything when no search string is entered.
Instead, it would be good if it could suggest:
- Items that were selected during previous uploads.

This feature exists in the category selection activity, so that activity can be studied for inspiration.

### PR DESCRIPTION
**Pull request by johnnyrev**
**Description (required)**

Fixes #3634 

What changes did you make and why?

**Tests performed (required)**

WIP

**Screenshots (for UI changes only)**

WIP

### CODE REVIEW

**Comment by johnnyrev** [comment]
We have created DepictionsDAO, so we can store user's depictions and retrieve the recently-used ones, but how can we test the functionality of this code? How can we test that a new depiction table is created, in which recently selected depictions are saved in order to get retrieved?

**Comment by macgills** [comment]
@johnnyrev our preferred way of creating a DB is by using [Room](https://developer.android.com/topic/libraries/architecture/room), See ContributionDao in the project

**Comment by johnnyrev** [comment]
Ok, so let's get this straight. We want to create another table for depictions retrieving. The first thought that came to our mind was to follow the guidelines that CategoriesDAO has settled. That means that the implementation for our issue is based on the architecture of the CategoriesDAO and the other required functions. But, after what @macgills said, I see that the implementation must follow the archtitecture of the ContributionDAO, meaning that our DepictionsDAO must be similar to it. Is that right? If so, why does the CategoriesDAO not follow the architecture of ContributionDAO, and why do we need to follow the structure of the second instead of the first one, although our outcome is close to what CategoriesDAO does? Excuse me for that long question, but we need to get it right before we continue to our implementation.

Please inform us if we need to delete what we did in our commit and restructure it!

**Comment by macgills** [comment]
CategoriesDAO is unfortunately a bad example even though it is what is used to create similar functionality. We have created tickets to migrate these old implementations to stop this very [broken window effect](https://medium.com/@matryer/broken-windows-theory-why-code-quality-and-simplistic-design-are-non-negotiable-e37f8ce23dab). These things just happen in large projects that have been around a while.


I suggest you read the [Room](https://developer.android.com/training/data-storage/room) training guide and base your design for RecentDepictionsDAO looslely on ContributionDAO.

You will need to save a depiction when clicked and when we show the UploadDepiction screen you will then need to retrieve these previously saved `RecentDepictions` and display them

**Comment by johnnyrev** [comment]
So we have started working based on ContributionDAO, but we have a question. We have already committed some changes on the code (which are officially wrong) and we want to take it back. How are we supposed to do it? Should we delete these changes in our code and commit the files right back here or delete the changes, without committing anything, and when we manage to implement our new functional code, commit only our new files?

**Comment by johnnyrev** [comment]
We managed to create an entity named "recent_depictions" with the creation of RecentDepictions.java, RecentDepictionsDao.java and an addition in AppDatabase.kt. From this point, we want to insert any depiction we check to that entity.

We created RecentDepictionsRepository.java and RecentDepictionsLocalDataSource.java, which make use of the "save" method, but our selected depictions don't get presented in our database.

How can we proceed?

**Comment by macgills** [comment]
@johnnyrev I was away for 2 weeks, apologies in the delay getting back to you.

My guess is that you have copied the api from our other dao somewhat and have used Rx types in the method signature but may not be aware of the usage of Rx.
If something is a `Single/Maybe/Completable/Flowable/Observable` then you need to call `.subscribe()` for it to start performing work, `.subscribe()` returns a `Disposable` which can be used to cancel the ongoing work, best practice is for a class with many disposable is to use a `CompositeDisposable` which you can add many disposables to and only have to call `clear()` once to stop all the disposables doing work.
Rx is a pretty advanced topic so I can only go into so much detail here

**Comment by neslihanturan** [comment]
Hey @johnnyrev , thanks for your effort and so sory for late review. Are you still around and interested to work on this issue?

**Comment by neslihanturan** [comment]
Sleeping PR, please feel free to reopen it if needed

**Pull request closed without merging**
