### PR TITLE
fixes #3788 achievements: proper number for quality and feaured images

### LINKED ISSUE #3788: Achievements: Bug in Features Pictures number
**Summary:** 

The Featured Pictures number in achievements doesn't accurately reflect the number of featured pictures uploaded by a user

**Steps to reproduce:** 

Image attached

**Device and Android version:** 

Galaxy S9+, Android 10
 
**Commons app version:** 

API level: 29
Android version: 10
Device manufacturer: samsung
Device model: SM-G965U
Device: star2qltesq
Network type: wifi
App version name: 2.13~d950f7219
User name: EoRdE6
[https://commons.wikimedia.org/wiki/User:EoRdE6](https://commons.wikimedia.org/wiki/User:EoRdE6)

**Screen-shots:** 

Screenshot_20200528-132859_Commons

**Would you like to work on the issue?**

n/a

### PR DESCRIPTION
**Pull request by gerardolgvr**
**Description (required)**
achievements: fixing numbers in featured images and adding new item (quality images)

Fixes #3788 

What changes did you make and why?
- I added new string resources for the new item in AchievementsActivity (Quality Images)
- Update and add a new field in Achievements.kt for the new field that must be rendered
- Adding the official logo for "Quality images"

**Note:** At the beginning the objective was just to update and render the proper field, as you can notice at issue other changes were requested to improve this bug and them are reflected in the changes.

**Tests performed (required)**
Manual tests used

Tested ProdDebug on Redmi Note 7  with API level 28 and Nexus 5X API level 28 (this one is a emulator).

**Screenshots (for UI changes only)**
WhatsApp Image 2020-06-18 at 9 13 22 AM

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by ashishkumar468** [comment]
@gerardolgvr  can you resolve the merge conflicts, please. Also, it would be great if someone with a featured image can help test this PR

**Comment by gerardolgvr** [comment]
> @gerardolgvr can you resolve the merge conflicts, please. Also, it would be great if someone with a featured image can help test this PR

Yeah, I can solve those conflicts. I think I can solve the conflicts this weekend c:

**Comment by neslihanturan** [comment]
Hey @gerardolgvr , thanks for this PR :) Are you still interested to solve conflicts? If not could you please inform us?

**Comment by gerardolgvr** [comment]
> Hey @gerardolgvr , thanks for this PR :) Are you still interested to solve conflicts? If not could you please inform us?

Hello @neslihanturan , you're welcome. Please feel free to assign the issue to somebody else

**Comment by neslihanturan** [comment]
Seems like the issue already solved :)

**Pull request closed without merging**
