### PR TITLE
Added callback when removing accounts on logout 

### PR DESCRIPTION
**Pull request by Bluesir9**
This will ensure that the transition to LoginActivity happens only when complete logout process is finished so as to ensure that the race condition mentioned in #848 is avoided.

### CODE REVIEW

**Comment by whym** [comment]
@Bluesir9 Can you please check https://www.codacy.com/app/domdomegg/apps-android-commons/pullRequest?prid=866706 to see if you can solve some of the warnings (ideally all)?

**Comment by Bluesir9** [comment]
@whym Hi haven't had the time to take care of this over the weekend. Will definitely fix as many as I can and push a commit by EOD.

**Comment by whym** [comment]
Thanks. The remaining warnings are arguably moot. Will merge this.

**Comment by Bluesir9** [comment]
@whym Thanks for the opportunity. Expect me to stick around. As for the warnings I believe #778 is tracking that for the project already.

**Pull request merged**
