### PR TITLE
Fix issue with Nearby item descriptions

### LINKED ISSUE #823: Nearby item descriptions not working in v2.5.0 (beta)
Posting on behalf of @VojtechDostal who is unable to do so at the moment:

Item descriptions in Nearby Places do not work for him after the recent patch. For instance, this description used to be` instance of (P31) `(which admittedly isn't the best description, haha, but still) but now only says `?`

vojtech_nearby

### PR DESCRIPTION
**Pull request by misaochan**
Seems to fix #823 for me. Could anyone (especially those with a non-English phone language) help test and see if it works for them?

Edit: While we're at it, I renamed Description to Label to prevent any further misunderstandings, lol.

### CODE REVIEW

**Comment by whym** [comment]
Tested and it works for me on Japanese locale.

I'm not sure 'label' is an improvement, although I don't think it's worse either. See #742.

As far as I understand, the correspondence before this patch

* App's 'name' - Wikidata's 'label'
* App's 'description' - Wikidata's 'instance of' value
* n/a - Wikidata's 'description'

After this patch

* App's 'name' - Wikidata's 'label'
* App's 'label' - Wikidata's 'instance of' value

Any alternative idea?

To be clear, as I said in #742 this naming issue is a minor one, and my comment above shouldn't be a stopper anyway.

**Comment by misaochan** [comment]
Thanks for testing, @whym ! :) The main rationale for me renaming the "instance of" value to Label was to prevent people from confusing it with the actual description (which is named LongDescription). I think what caused the "?" issue to begin with was someone glancing at the code and (understandably) assuming that Description was what he was looking for.

I am good with renaming Label to InstanceOf though if that would be preferred. Anything but Description. :)

**Comment by whym** [comment]
I see what you mean, but it appears like the app's "description" actually stores the original "instance of" value. (My previous explanation was wrong, too, sorry for that.) To be more precise, the current state is

* Place.name - Wikidata's 'label'
* Place.Description - compact form for Wikidata's 'instance of' value
* Place.longDescription - Wikidata's 'instance of' value verbatim
* n/a - Wikidata's 'description'

So 'Description' and 'longDescription' are related. If the former is to be changed, I think the other should be, too.

I'd be fine with Place.InstanceOf and Place.longInstanceOf.

**Comment by misaochan** [comment]
I think the main problem is that the current Place.Description is not meant to be displayed at all, but rather just used to determine which icon to use for the Nearby List. Only Place.longDescription is suitable to display to the user. How do you think we should convey this distinction?

How do we access Wikidata's true "description"? That may be more suitable for display to users, as a potential enhancement.

**Comment by whym** [comment]
How does 'Classification' sound? 'longDescription' could be simply 'instanceOf' then.

> How do we access Wikidata's true "description"? That may be more suitable for display to users, as a potential enhancement.

I think it's fairy easy to add a column for it into the query (nearby_query.rq). Not sure how frequently the values are filled given our scope (entities without images) but it wouldn't hurt to add it.

**Comment by nicolas-raoul** [comment]
Yes getting the Wikidata description in particular language is easy.

Most items don't have a description.
A lot of those who have are like "Church in Paris", which is not much
better than "church" because our users already know where they are. Some
description could really provide value though. How about concatenating, or
using description wgen available?

**Comment by misaochan** [comment]
Thanks @whym and @nicolas-raoul !

How does it sound to you guys if I create an issue for further discussing the appropriate names and concatenating the Wikidata description, and we merge this if there is nothing else blocking it? Ideally we would like to include this in our next hotfix (which will be released when we fix the Dagger crashes).

**Comment by whym** [comment]
Sounds like a good plan. Thanks!

**Comment by misaochan** [comment]
Interesting. I looked at NearbyAdapterFactoryTest.java and it seems that we are hardcoding the longDescription as "desc" in that test suite:

```
    private static final Place PLACE = new Place("name", Place.Description.AIRPORT,
            "desc", null, new LatLng(38.6270, -90.1994, 0), null);
```

So, it seems that this "desc" value would be passed to all the tests being run on the "PLACE" object and that is why the comparison is failing? Or am I reading the tests incorrectly?

**Comment by neslihanturan** [comment]
It works @misaochan , thanks!

**Comment by whym** [comment]
It looks like the test was written by @psh - any chance you can look into this?

**Comment by misaochan** [comment]
Will likely be doing a release with @maskaravivek 's Dagger fix tomorrow. With this PR, we have two options:

1. Wait to resolve the tests and not roll this fix out to users with tomorrow's release
2. Resolve the tests in a separate issue and roll this fix out with tomorrow's release since the PR fixes the problem for all 3 of us.

**Comment by whym** [comment]
I think this fixes the tests: https://github.com/whym/apps-android-commons/tree/misaochan-fix-description-bug  (well, if I interpret the intention of the tests correctly)

**Comment by misaochan** [comment]
@whym That looks good to me, thanks. Shall we submit that as a separate PR?

**Comment by whym** [comment]
Isn't it easier to 'git pull https://github.com/whym/apps-android-commons.git misaochan-fix-description-bug' and update this PR? If doesn't work, I can create a new PR.

**Comment by misaochan** [comment]
Done, thanks for the tip @whym ! :)

**Comment by whym** [comment]
> /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-sr-el: Error: Invalid resource directory name

This was reported in #1059, but I'm not sure why your patch is affected. I don't seem to find the values-sr-el directory here?

Locally I cannot reproduce it - maybe we are good to merge despite Travis's error?

**Comment by divadsn** [comment]
@whym you can merge it, it's a wrong imported translation from translatewiki :)

**Comment by whym** [comment]
@divadsn yeah, but the odd thing is the offending commit 29e667e is not included in the commits here, or is it?

**Comment by misaochan** [comment]
I've encountered issues before with Travis failing for all PRs that were rebased on master when the master build is failing. I guess the assumption is that they are based on master therefore unless they fix master's failed build, they all fail by association?

I would be in support of merging. ;)

**Comment by whym** [comment]
It passed for my branch https://travis-ci.org/whym/apps-android-commons/builds/327725662 with the same changes. Since my master was outdated, Travis doing automatically merging master seems to explain this behavior.

**Comment by VojtechDostal** [comment]
Amazing! Descriptions in Czech now work :-)

**Comment by misaochan** [comment]
Wonderful! Thanks for the feedback @VojtechDostal . :)

**Pull request merged**
