### PR TITLE
Update to Gradle 5

### LINKED ISSUE #2824: Update to Gradle 5
**Summary:** 

Updating Gradle from 4.10 to 5.3.1 should give us
- Faster builds
- Less noisy transform output (https://github.com/gradle/gradle/issues/6334)
- Potentially fix/help towards fixing #1941

I've marked this tentatively as beginner friendly - it's hard to judge things like this, but if it turns out to be difficult can always remove.

Useful links:

https://developer.android.com/studio/releases/gradle-plugin
https://docs.gradle.org/current/userguide/upgrading_version_4.html
https://docs.gradle.org/current/userguide/upgrading_version_5.html

### PR DESCRIPTION
**Pull request by aadilahmed**
**Description (required)**
Fixes #2824 Update to Gradle 5

What changes did you make and why?
Updated Gradle from version 4.10 to 5.3.1 to
get faster builds and help towards fixing #1941.
Added 'org.apache.commons:commons-lang3:3.8.1' 
to fix import errors. 

Tested {betaDebug} on Nexus 5X Emulator with API level {24}.

**Screenshots showing what changed (optional - for UI changes)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Review by domdomegg — APPROVED** [review]
Looks good, waiting on #2868 to merge as unsure if this breaks Espresso tests too.

**Comment by misaochan** [comment]
I am on board with the Gradle update. Not so sure about adding the dependency. Could you please elaborate on what import errors are being experienced, and how the dependency fixes them? Also, should that be in a separate PR from the Gradle update as it addresses a different issue?

**Review by misaochan — CHANGES_REQUESTED** [review]
Please see comment above.

**Comment by domdomegg** [comment]
> I am on board with the Gradle update. Not so sure about adding the dependency. Could you please elaborate on what import errors are being experienced, and how the dependency fixes them? Also, should that be in a separate PR from the Gradle update as it addresses a different issue?

I believe it's been added to build.gradle as it should really have been an app dependency, but previously it just worked because either Gradle 4 added it automatically or some other library we use depended on it. As this updates Gradle to Gradle 5, the dependency is no longer automatically included. So really this PR does not add a dependency, it just makes it explicit.

**Comment by misaochan** [comment]
Ah, thanks for clarifying! In that case I am good with it. Sorry for the slow response, as I have just returned back from the hackathon trip. :)

**Pull request merged**
