### PR TITLE
Delete categoryImagesActivity

### LINKED ISSUE #3785: Remove CategoryImagesActivity
**Summary:** 

This activity is never used and can potentially be removed

**Commons app version:** 

master

### PR DESCRIPTION
**Pull request by FawziyahAlebiosu**
Fixes #3785 

To be able to successfully delete categoryImagesActivity, I deleted:
- categoryImagesActivity reference from the manifest file
- categoryImagesActivity test that referenced this activity
- categoryImagesActivity import statement and reference in activityBuildModule

I want to delete other references to it in non-code items like comments, but I want to gauge from maintainers if that is necessary/ or allowed. 

**Screenshots (for UI changes only)**
placeholder image will replace with more useful tests that show app does not crash with this change.
image

### CODE REVIEW

**Comment by FawziyahAlebiosu** [comment]
@macgills and any maintainer i have the following questions I need clarifying on:

- how else would you recommend testing that this doesn't break anything? I understand that this activity is responsible for displaying images of a particular category. However, I cannot seem to find an explicit path to testing this on the emulator. 
So far, I've tried the following: checking that categories still work when uploading images and submitting them. I also checked that featured images work well (not sure if that is a category??) Are there any other features I should check?
- do you want me to delete non-code related references like in comments, and its xml layout file (see here: https://github.com/commons-app/apps-android-commons/blob/69e7161c61472ee4a175db9672c0086545b37d81/app/src/main/res/layout/layout_category_images.xml#L1
it does not reference this activity at all so it might not be necessary?

**Comment by macgills** [comment]
Sorry @FawziyahAlebiosu but I am no longer on this project

**Comment by ashishkumar468** [comment]
@FawziyahAlebiosu  Sorry for the delayed response, the tests were failing for a different issue, Please sync your branch with master. The changes look fine to me, happy to merge post verifying the changes

**Review by neslihanturan — APPROVED** [review]
Thanks @FawziyahAlebiosu :) Sorry for the delay, your PR does the job thanks :)

**Pull request merged**
