### PR TITLE
Shows "Location not available" despite GPS being on in Nearby tab( #3924)

### LINKED ISSUE #3924: Shows "Location not available" despite GPS being on in Nearby tab
**Summary:** 

The app shows "Location not available" in the Nearby tab, even though location is enabled for the app and the precise location is also available (another app can display the exact position).

**Steps to reproduce:** 

1. Make sure that you have accurate location enabled and available, e.g. by starting a navigation on osmand.
2. Clear data of the app, start it.
3. Go through introduction screens.
4. Log in.
5. Click on "Nearby".
6. "Allow Commons to access this device's location?" → Allow
7. See the toast "Nearby might not work properly, Location not available"

**Device and Android version:** 

Nexus 5X, Android 8.1.0, LineageOS 15.1, without Google Play Services and MicroG.
 
**Commons app version:** 

2.13.1~917a94472 via F-Droid.

**Would you like to work on the issue?**

No.

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #3924

What changes did you make and why?

**Their is not an need to show an Toast message -"Nearby might not work properly, Location not available " Becouse it location work fine.**

**Tests performed (required)**
Android Device :Redmi Y3
API:29

**Screenshots 

(for UI changes only)**

### CODE REVIEW

**Comment by ashishkumar468** [comment]
Hi, the if else seems to be a valid case when the lastKnownLocation is null, can you explain why are we removing this?

**Comment by Prince-kushwaha** [comment]
When I test the app on different phone i see it work fine show that i remove toast message **Nearby might not work properly, Location not available**

**Comment by Prince-kushwaha** [comment]
@ashishkumar468

**Comment by heinrich5991** [comment]
I don't think that this will fix my issue. The problem wasn't that a toast appears, but rather that location is never updated. This seems to remove the error message, but not the actual problem.

**Comment by Prince-kushwaha** [comment]
@heinrich5991 it work fine in my device

**Comment by ashishkumar468** [comment]
` java.lang.IllegalArgumentException: provider doesn't exist: network`, this is the issue, agree with @heinrich5991, removing the toast would clearly not help.

**Comment by Prince-kushwaha** [comment]
ok i understand the issue 
i try to solve this issue

**Comment by neslihanturan** [comment]
Since everyone agrees this wont solve the issue, closing.

**Pull request closed without merging**
