### PR TITLE
[GSoC] Full Screen Mode

### PR DESCRIPTION
**Pull request by Ayan-10**
**Tasks**

- [x] Detect swipe gestures
- [x] Swipe left to view the previous image
- [x] Swipe right to view the next image
- [x] Swipe up to select the picture (the equivalent of tapping it in non-fullscreen mode) and show the next picture (the picture that follows in the folder view, skipping pictures that have either already been uploaded or ignored).
- [x] Swipe down to immediately mark that picture as "Not for upload" (the equivalent of selecting it then tapping "Mark as not for upload" in non-fullscreen mode), and show the next picture.

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Can you please resolve the conflicts, so that I can merge this into gsoc22 and review the whole feature? Thanks!

**Comment by nicolas-raoul** [comment]
Wonderful, thanks for the fast fix!

**Comment by Ayan-10** [comment]
There are some changes left to do. I will commit those soon.

**Comment by nicolas-raoul** [comment]
Understood, thanks!

**Comment by nicolas-raoul** [comment]
I get build errors indeed, such as `Conflicting overloads: public abstract suspend fun findByImageSHA1`

**Comment by Ayan-10** [comment]
Yeah, I have seen that. I will create a new PR with required changes,
merging FS Mode and Hide/Unhide feature, I will solve this build issue on
that PR.

**Pull request merged**
