### PR TITLE
Simplify if statements in Utils and ExistingFileAsync

### PR DESCRIPTION
**Pull request by Deskana**
This patch simplifies a few if statements by replacing them with returns, which helps improve code readability and simplicity.

### CODE REVIEW

**Comment by misaochan** [comment]
It does make it shorter, but is it truly more readable? As a newbie I would have found the proposed changes confusing, but that might be just me. What do you guys think?

**Comment by nicolas-raoul** [comment]
I always favor readability over concision, but these two changes look positive to me.

**Comment by Deskana** [comment]
I believe that generally if you crunch if statements like this and find it less readable, it's indicative of another issue. For example, the change in Utils would be more readable if the dark theme wasn't called "theme"... but that confusion was present in the if statement too.

I think it's more readable this way, but I won't be offended if you decline the pull request. :-)

**Comment by whym** [comment]
A somewhat old document, but I think this shows that people do prefer this style when returning a boolean flag: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-137265.html

**Comment by misaochan** [comment]
Thanks for your input everyone!

(BTW now the Travis tests are failing again. Odd.)

**Comment by tobias47n9e** [comment]
I had to restart some tests 2 times for them to run. I wonder why there are so many issues with the virtual machines.

**Pull request merged**
