### PR TITLE
[WIP] Add Media legend using the title typed by user

### LINKED ISSUE #1831: Fill P2096 (media legend) of P18 image using metadata typed by user
Insert image descriptions (or title? or both?) into Wikidata as qualifiers.
This is quite often done using property P2096.

Example:
screenshot from 2018-08-16 17-33-36

Infoboxes could then read this description when transcluding images from Wikidata.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #1831 

What changes did you make and why?

**Tests performed (required)**

WIP

**Screenshots showing what changed (optional - for UI changes)**

WIP

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @maskaravivek , I was wondering if we should create a feature branch for this due to the https://github.com/commons-app/apps-android-commons/issues/1831#issuecomment-575771417 blocker. So we can merge your PR when it's ready, but it won't go into master until #3222 is fixed. What do you think?

**Comment by prince-09** [comment]
Is there any slack or community group link?

**Comment by maskaravivek** [comment]
> Hi @maskaravivek , I was wondering if we should create a feature branch for this due to the [#1831 (comment)](https://github.com/commons-app/apps-android-commons/issues/1831#issuecomment-575771417) blocker. So we can merge your PR when it's ready, but it won't go into master until #3222 is fixed. What do you think?

Yes, sure @misaochan. To which branch should I base my PR?

**Comment by misaochan** [comment]
@maskaravivek I just made https://github.com/commons-app/apps-android-commons/tree/media-legend from master, you can base on that one. :)

@prince-09 we don't use Slack, sorry. We do have a Hangouts community that you can request to join via https://hangouts.google.com/group/YAC3Cso3QPnGopM66

**Comment by maskaravivek** [comment]
@misaochan Should I base my PR to `structured-data` instead of `media-legend`?

**Comment by misaochan** [comment]
I don't think so, as it is a separate feature, right? The idea is that `structured-data` should be merged into master before `media-legend` is.

**Comment by macgills** [comment]
I think targetting structured data makes sense here from just glancing at the code

**Comment by maskaravivek** [comment]
I have rebased my PR on the structured data branch.

**Comment by misaochan** [comment]
Remind me to test this again when the SDC branch uploads work for me. :)

**Comment by misaochan** [comment]
Once conflicts are fixed we can test and merge this. :)

**Pull request closed without merging**
