### PR TITLE
Open external links in same activity

### PR DESCRIPTION
**Pull request by sivaraam**
### Description (required)
It's common for users to expect that re-opening the app would
allow them to "continue where they left off". This also applies
for the case where they leave the app after opening an
external link. It's natural for them to expect that they would
see the webpage they left open when they re-open the app. This
doesn't happen for our app as we open custom tabs in a separate
activity. As a consequence, this makes the experience
un-intuitive.

Fix this by opening custom tabs in the same activity.

Fixes: #2944

### What changes did you make and why?
Made the links opened in custom tabs open in the same activity.

### Tests performed (required)
Tested betaDebug on Samsung SM-J111F with API level 22

### CODE REVIEW

**Comment by sivaraam** [comment]
> Seems to work, but not sure if this is behaviour we actually want (also see [#2944 (comment)](https://github.com/commons-app/apps-android-commons/issues/2944#issuecomment-492020384)).

I actually gave [a counter-argument](https://github.com/commons-app/apps-android-commons/issues/2944#issuecomment-492161825) to the comment you mentioned and didn't receive any objections.

> I think it's more of a preference thing, but all major apps I use follow the current behaviour (e.g. Gmail, Google Calendar, Spotify, Telegram, Slack)

Can you confirm that by "current behaviour" you mean the app opening the tabs in a separate activity?

Anyways, I'll share my view. I'm inclined to keep the webpages opened from the app in the same activity as that felt like the natural behaviour to me. I just want to pickup where I left off (the web page that I last opened) when I tap on the app icon. This expectation might be influenced by the experience I have from the apps I've used. They open the web page in the same activity. Examples are GitHub, Gmail (?), Markor. Actually, the Commons app is the first app that I've ever seen open a custom tab in a separate activity! So, assuming you meant that the apps you mentioned open the custom tabs in a separate activity I tried to use some of them and see if I could get a different perspective. Unfortunately, I couldn't:
* Spotify just outright opens the tabs in the old style (opening them in the browser itself without custom tabs). I'm not sure for what links they use custom tabs.
* Gmail opens the links in the same activity.
* Google also opens the links in the same activity.

Correct me, if I'm wrong somewhere. To conclude, I still find it odd that the Commons app opens the tabs in a new activity 🤷‍♂

**Comment by domdomegg** [comment]
> I actually gave [a counter-argument](https://github.com/commons-app/apps-android-commons/issues/2944#issuecomment-492161825) to the comment you mentioned and didn't receive any objections.

Yeah sorry about this - I've only been going through PRs recently.  I saw the comment, but thought it was mainly about implementing it.

> > I think it's more of a preference thing, but all major apps I use follow the current behaviour (e.g. Gmail, Google Calendar, Spotify, Telegram, Slack)

Whoops, I've spent more time testing this and you're right most of them actually do reopen the web browser. I think my phone was just being really strict with background apps and their memory usage, and I'm dumb for not checking more closely 🤦‍♂️

**Comment by sivaraam** [comment]
> Yeah sorry about this - I've only been going through PRs recently.

Oh, you don't have to be sorry. It's fine. You've really been doing a lot of work with the PRs. Great job! 🙂

**Comment by misaochan** [comment]
Thanks @domdomegg and @sivaraam !

**Pull request merged**
