### PR TITLE
Localization: fix incorrect Unicode for space after bullet points in French language

### LINKED ISSUE #5821: Tutorial display unicode error in french
### Summary

When displaying the tutorial in the french version of the app, the bullet lists don't show well : `•&#32;` instead of `• ` is shown.

See the screenshots for more information.

### Steps to reproduce

1. Change the app user interface language to french in the settings
2. Quit the settings and open the tutorial
3. Slide right and observe

### Expected behaviour

Only a bullet is shown : `• `

### Actual behaviour

A bullet and some other caracters are shown : `• &#32;`

### Device name

Samsung A40

### Android version

Android 11

### Commons app version

4.2.1

### Device logs

_No response_

### Screen-shots

Screenshot_20240907-172204_Commons
Screenshot_20240907-172536_Commons

### Would you like to work on the issue?

Prefer not

### PR DESCRIPTION
**Pull request by rohit9625**
**Description (required)**

Fixes #5821

What changes did you make and why?
Just a small fix for Unicode of space character

**Tests performed (required)**

Tested prodDebug on Samsung A14 with API level 34.

**Screenshots (for UI changes only)**
None

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Just a small piece of advice: I would recommend creating branches on your local repository, such as `issue5821_bullets`, that would allow you to work on several tasks in parallel, as well as prevent possible confusion (for instance I already have a `rohit9625-main` branch on my local repository but it contains a different fix). Thanks a lot! 😃

**Comment by nicolas-raoul** [comment]
This pull request solves the issue:
Screenshot_20240909-165822_Commons

However, this file will get overwritten the next time translations are pulled from TranslateWiki.

**Comment by rohit9625** [comment]
> Just a small piece of advice: I would recommend creating branches on your local repository, such as `issue5821_bullets`, that would allow you to work on several tasks in parallel, as well as prevent possible confusion (for instance I already have a `rohit9625-main` branch on my local repository but it contains a different fix). Thanks a lot! 😃

I will keep that in my mind next time. Because this was a small fix, so I just add push it to main directly.

**Comment by rohit9625** [comment]
> However, this file will get overwritten the next time translations are pulled from TranslateWiki.

So, I need to make a change on Gerrit also. Right?

**Review by nicolas-raoul — APPROVED** [review]
Tested in both French and English, works great.
Thanks a lot!

**Pull request merged**
