### PR TITLE
[Enhancement] Make custom image selector available from Nearby

### LINKED ISSUE #4611: Make custom image selector available from Nearby
**Summary:** 

In the current state of the app, custom image selector is only available from contributions fragment. We also upload images from Nearby. What about making the custom image selector available from Nearby too ( If that has no disadvantages).

### PR DESCRIPTION
**Pull request by Eric-peng111**
**Description (required)**

As the nearby functions needs to be modified and add up a component of buttons
Both Activity and XML files which are corresponding to each other need to be changed and modified

Fixes #4611 

***What changes did you make and why?***

**Activity parts**

Since the issue is to add up a component of button to provide an extra path towards the custom image selector, what I did is to find and target the two existing buttons that worked in this java file of the nearby activity:

I.First is to add up this button to @BindView to create an object to manage in the methods 
image

II.showFB() to add up a fabCustomGallery
image

III.Add startAnimation of fabCustomGallery button to expandFABs() 
image

IV.Add hide function to fabCustomGallery button from the method: 
image

V.Add collapse function to fabCustomGallery button when the button is collapse sfrom the method collapseFABs(): 
image

VI.Add button click on listener to passInfoToSheet()
image

XML parts
It is not easy to manually draw the new button and setup design pattern in the Design
Since all the parameters need to be added up which are hidden and unknown(needs to be on trails for a few times to design)
By looking at the XML code:
I.The two existing buttons are setup in each empty view:
image

So the third extra button need to be included in a new view:
image

II.The extra floating button need to add up in xml code with different attributes:
image

**Tests performed (required)**

Tested on {Pixel 3 XL API 32} with API level {32}.

**Screenshots (for UI changes only)**
Before:
image

After:
image

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by u7253519** [comment]
student review, it seems to be ok on my side
MicrosoftTeams-image

**Comment by Eric-peng111** [comment]
> student review, it seems to be ok on my side
> MicrosoftTeams-image

Thanks, Jack. gonna do the test and try to figure out how to run and pass CI

**Comment by Eric-peng111** [comment]
> Hi @Eric-peng111 , have you tested this on the prodDebug build variant, all the way up to a successful upload? If you have, it would be great to have a video of it. In particular, I'm concerned about whether the autofill of caption, description, categories etc that usually occur with a Nearby upload, would still apply to a custom upload.

yes , currently working on it. Truly as @nicolas-raoul said: it gonna take a while to fix this issue

**Comment by ShashwatKedia** [comment]
@nicolas-raoul could this PR be closed, as the issue #4611 has already been solved by #5655?

**Pull request closed without merging**
