### PR TITLE
Fix #5182 Switch From Mapbox to MapLibre

### LINKED ISSUE #5182: Switch from Mapbox to MapLibre
### What is the user problem or growth opportunity you want to see solved?

As discussed in #4994, Mapbox includes a licensed library GMS. MapLibre is an open-source alternative to Mapbox that does not include GMS dependency from v10.0.0.

### How do you know that this problem exists today? Why is this important?

_No response_

### Who will benefit from it?

_No response_

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by kartikaykaushik14**
**Description (required)**

Fixes #5182

What changes did you make and why?

Migrated from Mapbox to MapLibre

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Meanwhile any idea why the unit tests testOnMapReady and testShowDetail fail?

**Comment by nicolas-raoul** [comment]
I am getting this crash:
```
03-23 19:49:07.328 26593 26593 E AndroidRuntime: java.lang.IllegalArgumentException: Could not find layer Outdoor
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.Style.getPredefinedStyle(Style.java:1430)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.lambda$onViewCreated$2$NearbyParentFragment(NearbyParentFragment.java:319)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at fr.free.nrw.commons.nearby.fragments.-$$Lambda$NearbyParentFragment$LW_iO-h3e6OvgddLCQ2oE4vXWAc.onMapReady(Unknown Source:2)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1322)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1308)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:203)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:65)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:355)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-23 19:49:07.328 26593 26593 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by nicolas-raoul** [comment]
Deleting the app's data solved the crash.
Maybe a kind of migraton is needed?

**Comment by nicolas-raoul** [comment]
I can consistently crash by switching from dark mode to light mode in the app's settings menu and coming back to the map. Can you reproduce?

**Review by Ayan-10 — COMMENTED** [review]
**It's having some issues with the dark UI. Screenshots are attached below.**


Screenshot_2023-03-24-01-17-26-54_d5db3f3edc380047609fe9c266f7c566
Screenshot_2023-03-24-01-17-08-67_d5db3f3edc380047609fe9c266f7c566
Screenshot_2023-03-24-01-17-17-84_d5db3f3edc380047609fe9c266f7c566

**Comment by kartikaykaushik14** [comment]
@Ayan-10 I'm able to reproduce the issue. Still trying to figure out what could be the root cause since I'm using Mapbox's predefined style for "Dark" just like "Outdoors" and "Streets".

MapLibre offers us the option to use Mapbox Configuration so I continued with it to maintain consistency. I checked the URL being called for the Dark Style and it is "mapbox://styles/mapbox/light-v10" which is consistent with that being called in the case of mapbox-sdk.

**Comment by nicolas-raoul** [comment]
Great, no more crash in Contributions now.

However, in addition to the visual issues reported by Ayan, I observe a crash in Explore: tap any picture, then tap the pen icon at the right of the latitude/longitude:
```
03-24 14:56:06.218 27280 27280 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.LocationPicker.LocationPickerActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:402)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.onCreate(LocationPickerActivity.java:147)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8341)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8320)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
03-24 14:56:06.218 27280 27280 E AndroidRuntime: 	... 12 more
```

If possible, would you mind using normal push instead of force-push, unless really necessary? Thanks! :-)

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could you please check if the issue still persists?

Meanwhile, I'm trying to fix the dark mode issue.

**Comment by Ayan-10** [comment]
The crash is not occurring for me anymore.

**Comment by nicolas-raoul** [comment]
No crash anymore indeed, thanks!

**Comment by kartikaykaushik14** [comment]
@Ayan-10 I Just pushed some changes for the "About" and "Settings" screens on dark mode. Please let me know how to get to the 3rd screen with achievements and leaderboard. I can apply a similar fix and test.

**Comment by nicolas-raoul** [comment]
To see achievements, you must be logged-in, tap the app's hamburger menu, then tap the cup icon with your usename at the top of the menu.

I will test this branch from now, thanks!

**Comment by nicolas-raoul** [comment]
UI that appears bright in dark mode:
- Achievements
- Leaderboard (right tab next to achievements)
- Review, also known as Peer Review, accessible from the hamburger menu
- Background of the upload wizard, when the picture does not take the full space (not sure whether this works in master, so no need to worry if not related to your PR)

**Comment by kartikaykaushik14** [comment]
I'm able to sign up and create an account on the app. I've been able to log in via web but not through the app. Do we have a dummy account created whose credentials I could use?

**Comment by nicolas-raoul** [comment]
I guess you have found out that the app has two flavors, beta and prod, matching https://commons.wikimedia.beta.wmflabs.org and https://commons.wikimedia.org.
We usually use prod even for development, unless we need to perform test uploads.

**Comment by nicolas-raoul** [comment]
Sorry I noticed a few more places with bright elements in dark mode:

Upload wizard license selection step:
Screenshot_20230328-165650

Upload wizard location selection step:
Screenshot_20230328-165607

Upload wizard first step:
Screenshot_20230328-165550

Custom picker:
Screenshot_20230328-165435

Hamburger menu → Feedback:
Screenshot_20230328-165311

Nearby location alert:
Screenshot_20230328-165251~2

**Comment by kartikaykaushik14** [comment]
1. Upload Wizard Media License - Working on it
2. Upload Wizard Location Selection Step - Looks the same in master
3. Upload Wizard First Step - Working on it
4. Custom Picker - Working on it
5. Feeback - Looks the same in master
6. Nearby Location Alert - Unable to verify this.

**Pull request merged**
