### PR TITLE
Improved Result of the quiz activity for smaller screens(#2010)

### LINKED ISSUE #2010: Result of the quiz activity could be improved for smaller screens
**Summary:** 
When the user is shown the result of the quiz activity at the end of taking the quiz, Some parts of the sentence are hidden by the button.

*A side note*: The 2nd picture never showed up in the quiz as a consequence of which I had to quit it in the middle. The progress bar for the second picture went close to the end but the picture never showed up. The mobile network was a little wavery but it wasn't that bad at that time.

**Steps to reproduce:** 
1. Go to the quiz activity (One way: have more than 50% of the uploaded images deleted in your account. Then log-in to the app. I got a pop-up to take the quiz)
2. Complete the quiz to get the results

Expected: The sentence in the Results activity is readable.
Actual: Some part of the sentences are hidden behind the 'Continue' button making it unreadable.

**Device and Android version:** 
Samsung Galaxy J1 Ace, Android 5.1.1 (stock)

**Commons app version:** 
2.8.6

**Screen-shots:** 
screenshot_2018-10-21-14-14-19

**Would you like to work on the issue?**
No for now. Maybe when I get some free time, I can.

### PR DESCRIPTION
**Pull request by sp2710**
Fixes #2010 Result of the quiz activity could be improved for smaller screens

What changes did you make and why?

Some minor changes in activity_quiz_result.xml

Before
screenshot_1547564175

Now
device-2019-01-15-204647

### CODE REVIEW

**Comment by maskaravivek** [comment]
@sp2710 Can you attach a screenshot.

**Comment by sp2710** [comment]
@maskaravivek I tried another device and saw that it was not solving the issue so made some more changes to it.Now it is solving the issue.
I had attached the screenshots

**Comment by maskaravivek** [comment]
Can you attach screenshots from either an emulator or a real device

**Comment by sp2710** [comment]
Done.

**Pull request merged**
