### PR TITLE
Fixes #1518  (fixed Featured image back button bug)

### LINKED ISSUE #1518: Back from featured image's details: loading forever
Steps:
1. Go to featured images
2. Touch one feature image
3. Press "Back"
4. Loading forever:
screenshot_20180515-213739

logcat:
```
05-15 21:38:30.223  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:30.769  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:31.297  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:31.893  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:32.677  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:33.291  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:33.990  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:34.519  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:35.132  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:35.763  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:36.462  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:37.042  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:37.673  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:38.303  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:38.917  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:39.514  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:40.110  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:40.741  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:41.372  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:41.951  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:42.582  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:43.230  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:43.777  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:44.441  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:45.020  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:45.651  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:46.282  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:46.913  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:47.612  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:48.362  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:49.045  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:49.760  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:50.391  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:51.891  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
05-15 21:38:52.556  9434  9434 W View    : requestLayout() improperly called by android.widget.ProgressBar{707b2a0 V.ED..... ......ID 468,696-612,840 #7f0f0100 app:id/loadingImagesProgressBar} during layout: running second layout pass
```

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
## Fixed Featured image back button bug

Fixes #1518 (Back from featured image's details: loading forever) 

## Description 

- overrided onresume on CateoryImageListfragment as it will be called on back press and setted gridadapter.

## Tests performed (required)

Manually tested on [API 25 Motog5S+] with ProdDebug

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Ah, how about a short Javadoc comment on the added method?

**Comment by ujjwalagrawal17** [comment]
Ok @nicolas-raoul I will add it.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Is it fine now?

**Comment by neslihanturan** [comment]
Thanks @ujjwalagrawal17 works great and it is also great you are still involved with other issues on the project while working on your GSoC task.

**Pull request merged**
