### PR TITLE
Update wiki page links

### PR DESCRIPTION
**Pull request by sivaraam**
We've moved the documentation to a separate repo.

So, change the old links to point to the corresponding
places in the documentation repo.

**Note**: I haven't updated _all_ the links yet. I've only updated the links used within the app.

### CODE REVIEW

**Comment by 6point022** [comment]
In `ISSUE_TEMPLATE.md`, we have a link that can also be changed to https://github.com/commons-app/commons-app-documentation/blob/master/android/Getting-app-logs-from-Android-Studio.md

**Comment by sivaraam** [comment]
Yeah. I forgot mention that I haven't updated _all_ the links yet. I've only updated the links used within the app :)

I'll update the description to mention this.

**Comment by 6point022** [comment]
Okay, I'll create a separate issue for this. :)

**Comment by sivaraam** [comment]
FYI: I've changed the base to 2.13-release to ensure the link to the Privacy policy isn't left broken.

A general doubt: what happens to the commits that are only present in the `2.13-release` branch? Is the branch merged with `master` after release?

**Comment by misaochan** [comment]
Thank you! The 2.13-release branch is merged into master periodically, preferably after every commit but occasionally I batch them. Definitely after every release.

**Pull request merged**
