### PR TITLE
Fixes #3879

### LINKED ISSUE #3879: Other pictures flickers when a media is selected from contributions list
**Summary:** 
I always knew I was seeing flickering images when I choose an item from contrib list and trying to go to Media Details Fragment. While I was testing another bug, I recognized on click to an object from contrib list, rebuildCatList method from MediaDetailsFragment is called for previous images too. And I see previous image is appeared during my debug steps. 

This issue should be investigated.

### PR DESCRIPTION
**Pull request by vinayak0505**
Fixes #3879 

solved this issue also added a little animation when opening detail screen and going back (because it looks like that was the developer trying to do while adding delay) and also minor optimization to code repetition and if else statement

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
After merging this PR, I observe two side-effects:
1) When opening the app, the contributions appear from the right. While animation can be good sometimes, making the main content appear from the side when starting the app is not good: the content should appear immediately. Would you mind removing animations from this screen. Thanks!
2) Whenever I tap a picture in the contributions screen, I get this crash:
```
04-07 09:05:07.422  6004  6004 E AndroidRuntime: FATAL EXCEPTION: main
04-07 09:05:07.422  6004  6004 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 6004
04-07 09:05:07.422  6004  6004 E AndroidRuntime: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 60, found: 70 Pager id: fr.free.nrw.commons:id/mediaDetailsPager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:992)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.View.measure(View.java:24967)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3266)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1993)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2295)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-07 09:05:07.422  6004  6004 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
While it might be due to an existing bug, it was not (or maybe very rarely) happening before, and after merging this PR it is happening every time I tap an image. Maybe you are testing with too few images? If you are testing using the BetaDebug flavor (which is default), please upload like 80 pictures of a pen (not copyrighted images) and test again before judging that your testing is complete.

Also, could you please follow the [PR template](https://github.com/commons-app/apps-android-commons/blob/master/PULL_REQUEST_TEMPLATE.md)? That would allow us to see what tests you performed, for instance.
You have a lot of potential, but GSoC candidate selection is based on PR quality, for which PR description and absence of bugs (including side-effect bugs) are very important factors. Thanks :-)

**Comment by vinayak0505** [comment]
1. That is weird  beacause I didn't apply animation when the app starts
only , when you press back and click for the detain screen , so number
should be the problem
2. Bug I think is because the adapter loading time and i made call it in
the beginning , so it crashes  , I'll fix that
Even though animation might not be the one causing error I am still
removing it

**Comment by nicolas-raoul** [comment]
About 1: Yes sorry I edited my post a few minutes after posting it, since I realized it is a problem that recently appeared in master, sorry for thinking it was because of your pull request. Thanks for your understanding! :-)

**Comment by vinayak0505** [comment]
No worries, thanks for the update!

**Pull request closed without merging**
