### PR TITLE
Resolved progressbar overlapping issue while scrolling in explore activity

### LINKED ISSUE #2740: Progressbar Overlaps images in Explore
**Summary:** 
In explore activity Progressbar overlaps the images.  It should be displayed at the bottom when scrolling down the images

**Steps to reproduce:** 
- Go to explore
- Scroll down to the bottom 

**Screen-shots:** 

WhatsApp Image 2019-03-24 at 10 19 21 PM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**

Fixes #2740 Progressbar Overlaps images in Explore

### Changes made
- Modified fragment_category_images.xml
- Modified CategoryImagesListFragment.java

**Screenshots showing what changed (optional - for UI changes)**
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by neslihanturan** [comment]
@vanshikaarora can you please explain what does this PR fixes? What is the difference between having progress bar on middle or bottom and why do we have multiple progressbars?

**Comment by vanshikaarora** [comment]
@neslihanturan Earlier the prgressbar in the middle overlaps the images int the middle while loading like this
WhatsApp Image 2019-03-24 at 10 19 21 PM

In the current PR while scrolling to the bottom Progreebar doesn't overlaps the views instead while scrolling progressbar is visible at the bottom of the layout

**Comment by neslihanturan** [comment]
But If you scroll a little more, it will overlap with bottom progressbar too, won't it? Does it matter overlapping at the middle or at bottom?

**Comment by vanshikaarora** [comment]
>But If you scroll a little more, it will overlap with bottom progressbar too

@neslihanturan It won't overlap I have checked it in my PR It won't overlap the views loading from the bottom :)

**Comment by neslihanturan** [comment]
@vanshikaarora can you explain more, how it won't overlap when we scroll? I couldn't imagine

**Comment by neslihanturan** [comment]
Sorry I still can't understand the real benefit of this PR, closing for now. Please feel free to reopen if you want to

**Pull request closed without merging**
