### PR TITLE
issue #2285 resolved

### LINKED ISSUE #2285: Fresh clone fails build in latest Android studio
**Summary:** 

Fresh clone fails build in latest Android Studio/SDK

**Steps to reproduce:** 

How can we reproduce the issue? 
- Fork project and go through quick start guide
- Fresh Android Studio install: I have 3.2.1. It setup with SDK 28
- Setup project via 'import from version control'

What did you expect the app to do, and what did you see instead?

Expected:
- Project syncs and builds
Actual:
- Sync/build failed. Checked Android Studio and saw references to android-27. Installed that in Sdk manager. Still had issues. Logs showed that I needed buildtools 27.0.3. Installed those specific tools as described in: https://stackoverflow.com/questions/47721952/how-to-solve-failed-to-find-build-tools-revision-26-0-2

This is more an Android Studio project setup issue. I noticed that root gradle.properties contains:
buildToolsVersion=27.0.3

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**

Fixes #2285 Fresh clone fails build in Android Studio

What changes did you make and why?

Updated the build tools version to 28.0.3 and classpath to 3.2.0

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Actually, the .travis.yml file is configured for build tools version 27.0.3, I think that's why the Travis CI build is failing on updating the build tools version.

**Comment by vanshikaarora** [comment]
Yes but issue with fresh clone was due to the build version. Because it's not apt with the latest version of Android Studio/ SDK hence i had to modify the file

**Comment by maskaravivek** [comment]
@vanshikaarora Can you check the build failure. 
screen shot 2019-01-24 at 11 02 54 pm

**Comment by vanshikaarora** [comment]
@maskaravivek 
I'll do that

**Comment by maskaravivek** [comment]
Also, you might have to update `.travis.yml` with the latest versions. right now it uses 27.

**Comment by vanshikaarora** [comment]
> Also, you might have to update `.travis.yml` with the latest versions. right now it uses 27.

I have updated the buildToolsVersion in travis.yml from 27 to 28.0.3
Shall I also modify the `compileSdkVersion=android-27`?

**Comment by maskaravivek** [comment]
> > Also, you might have to update `.travis.yml` with the latest versions. right now it uses 27.
> 
> I have updated the buildToolsVersion in travis.yml from 27 to 28.0.3
> Shall I also modify the `compileSdkVersion=android-27`?

Yes.

**Comment by maskaravivek** [comment]
Build failed because of some Travis error. Restarting the build again.

**Comment by vanshikaarora** [comment]
> Build failed because of some Travis error. Restarting the build again.

@maskaravivek How do I restart the build at travis?

**Comment by maskaravivek** [comment]
> @maskaravivek How do I restart the build at travis?

Does travis show restart option to you? https://travis-ci.org/commons-app/apps-android-commons/builds/484266184

Am not sure, but maybe this option is visible only to collaborators and members.

**Comment by whym** [comment]
[A page I found via Google](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#fix-travis-log-too-long-error) suggests adding ``VERBOSE=0`` to the env entries in travis.yml. (Actually, I don't really if it works, and even if it does, it might be just a workaround without solving the root cause.)

**Comment by vanshikaarora** [comment]
@whym So should i add `VERBOSE=0` to the env entries in travis.yml file?
Also `VERBOSE=0` is this related to the issue itself or just to solve the issue with travis-ci?

**Comment by domdomegg** [comment]
Not really sure what is it. Comparing master's logs it seems there are a lot more "Maybe this is program method"/"Maybe this is library method" lines. Looks maybe related to the updated androidx testing libraries?

Also a reminder that there's PR #2175 which tidies up gradle.properties a bit - maybe it could be absorbed by this PR?

**Comment by vanshikaarora** [comment]
@domdomegg Keeping the travis-ci aside can you find any other problem with the changes that I had made that which you feel might be wrong or might affect the master branch?

**Comment by maskaravivek** [comment]
> Not really sure what is it. Comparing master's logs it seems there are a lot more "Maybe this is program method"/"Maybe this is library method" lines. Looks maybe related to the updated androidx testing libraries?

These seem to be proguard warnings. 

```
-dontnote
```

Ref: https://stackoverflow.com/questions/6068902/how-to-suppress-maybe-this-is-program-method-warnings-from-proguard

> Also a reminder that there's PR #2175 which tidies up gradle.properties a bit - maybe it could be absorbed by this PR?

Am happy merging #2175 and let alpha users test it. :)

**Comment by vanshikaarora** [comment]
>These seem to be proguard warnings.

@maskaravivek which class do you feel is conflicting with the progaurd

**Comment by vanshikaarora** [comment]
>You can try excluding warning for android packages.

-dontnote android.**


OK I'll try this

**Comment by maskaravivek** [comment]
@vanshikaarora Can this PR be closed now?

**Comment by vanshikaarora** [comment]
>@vanshikaarora Can this PR be closed now?

Yes, Let' close this now

**Pull request closed without merging**
