### PR TITLE
Feature: Show where file is being used on `Commons` & `Other wikis`

### LINKED ISSUE #4997: Show where a picture is in use
### What is the user problem or growth opportunity you want to see solved?

A big motivation for users is to see that their uploads are useful, being embedded into Wikipedia articles etc.

### How do you know that this problem exists today? Why is this important?

Important to retain users and encourage them to upload more useful pictures.
Can also teach what kind of pictures are well-received.

### Who will benefit from it?

Wikipedia etc

### Anything else you would like to add?

The website has this feature already:
Screenshot from 2022-06-20 14-07-32

### PR DESCRIPTION
**Pull request by parneet-guraya**
Fixes #4997 

WIP

- Show where the file is being used whether on `Commons` or `Other wikis`
- Uses `paging` to load data lazily.
- Showing appropriate indications when loading pages for eg. showing loading indicator when loading subsequent items & error message when there's an error. 
- Proper state handling for eg. showing button to retry when initial request fails.
- Click on the item to open the page in browser.
- Wiki style UI.

## Demo: 

https://github.com/user-attachments/assets/457e67b2-4b4d-417b-8863-70f91247a6f4

### Dark Theme:

<p float="center">
  
   
  
</p>

### Light Theme:

<p float="center">
  
  
  
</p>

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks a lot!

I am very sorry for mentioning this only now, but I think the feature would be more used if the UI was like this:

- In the Media Details, rather than in Contributions
- Querying and displaying results immediately, rather than having to tap a button. I suggest listing the results between the discussion and the buttons, whereI drew the green arrow:



If you do not want (or do not have time) to modify the UI, that's totally fine, if that's the case then I will create a different issue for that. 🙂

**Comment by nicolas-raoul** [comment]
By the way, most files have very few usages, so don't worry about the list taking too much vertical space. 🙂

**Comment by parneet-guraya** [comment]
@nicolas-raoul  It's fine by me, I can make the change. Also, as in `MediaDetails` page there will be limited space, do we want to also show the entire list in another screen as well? I know you mentioned most of the files won't have that long list but do we want to keep the option for the longer ones?

**Comment by parneet-guraya** [comment]
Closing this one and will create a new one with requested changes :)

**Pull request closed without merging**
