### PR TITLE
667 fix categories

### LINKED ISSUE #667: Category search sometimes hangs
The spinner spins forever. I can continue typing or even delete the whole field's text, it does not stop spinning and zero suggestions appear.

Second time today.

### PR DESCRIPTION
**Pull request by akaita**
This PR aims to resolve #667 

I migrated the logic to RxJava trying to make it more deterministic.
So far my tests show it to be the new code really reliable and no trace of the issue is left (it also feels easier to read to me).

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @akaita , I am very happy for #667 is fixed finally. As a user of app, it was the most annoying bug. But it is very long and I may need one or two days to test it completely.

**Comment by akaita** [comment]
Yeah, it took me quite a while to rewrite... I would expect to need a while to review and test it.
I tried to be as clear as possible, but please feel free to ask about any details of the implementation.

note: this look like the most complex stream of events in the app, the rest should be quite simpler.

**Comment by neslihanturan** [comment]
According to my tests, there is no functional problem. Happily, our famous bug is solved finally. Thanks @akaita .

However there is small differences between expected behaviour and found. Currently (on master) category search works as:

before_patch
  
On this branch : 

after_patch

- So, "No input yet case" is same in both branches.
- In "Random input case" there is two differences
    - "No categories matching xxxx found" warning is missing
    - We don't see previous categories on master, only selected categories. And "previously used category suggestion" is somehow added twice.
- When we clean all text filter, is displays only selected and previous items on master. But on this branch, it displays something else.

**Comment by akaita** [comment]
It looks like after deleting the random input, this branch was still searching for "g". I'll check it out 👀

**Comment by akaita** [comment]
I fixed three issues:

- default suggestions (gps, title, recent) where shown when a search returned no suggestions
- the "no suggestions found" text would never show
- repeated suggestions could appear when using the default suggestions (gps, title, recent)

I used one more RxJava operator, but I could also remove one... it is probably simpler now :)  
Thanks for testing it @neslihanturan 🙆  It is very helpful!

**Pull request merged**
