### PR TITLE
Disabled review buttons while an image is being loaded

### LINKED ISSUE #2753: Disable the answering buttons in Review Activity until image is loaded
**Summary:** 

Disable the yes and no buttons in Review activity until image is loaded

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by yashk2000**
**Description (required)**

Fixes #2753  Disable the answering buttons in Review Activity until image is loaded

What changes did you make and why?
The buttons for submitting reviews have been enhanced so that they are enabled only when an image has loaded. This will help provide a better experience as now a user cannot click on a review option without an image being loaded.

**Tests performed (required)**

Tested betaDebug on Nokia 7 Plus with API level 28.

**Screenshots showing what changed (optional - for UI changes)**

1) Before image loads:

screencap

2) After image loads:

screencap

### CODE REVIEW

**Comment by yashk2000** [comment]
@misaochan could you please guide me with the Travis build? 
The Travis build is failing due to an invalid resource file name in `values-tt-cyrl`. 
I faced the issue on my laptop too, but for testing the app, I temporarily removed this file. How can I make the Travis build pass here?

**Comment by misaochan** [comment]
Hey @yashk2000 , it looks like the Travis build is failing on master too. So it's fine for yours to be failing for the same reason - once we fix it on master you can just rebase and that will fix the build on your side too.

We will try to test and review your PR as soon as we can. Sorry, we are working on a bit of a backlog at the moment. :)

**Comment by yashk2000** [comment]
@misaochan thanks for the response :)
I am interested in contributing to this app. I will continue working on other issues in the meantime.

**Comment by yashk2000** [comment]
@misaochan @ashishkumar468 I have rebased the pr to make it up to date with master. Please review it :)

**Comment by yashk2000** [comment]
@neslihanturan thanks for the review :)
 I have added the javadocs for the new methods.

**Comment by yashk2000** [comment]
@neslihanturan the build is failing due to 
`/home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-tt-cyrl: Error: Invalid resource directory name`

How to fix this error? I renamed the file to its correct name in a previous pr, but translatewiki added it again due to which the build is failing again.

**Comment by neslihanturan** [comment]
This is irrelevant with your PR, don't worry.

**Pull request merged**
