### PR TITLE
Fix - zero quantity in messages doesn't work in English #343

### PR DESCRIPTION
**Pull request by uditverma5602**

### CODE REVIEW

**Comment by uditverma5602** [comment]
@whym please review

**Comment by uditverma5602** [comment]
Fix for #343

**Comment by whym** [comment]
Thanks for your work on this. I wonder if anything can be done for languages other than English. To be fair, the report was only about English, though.

**Comment by uditverma5602** [comment]
@misaochan Thanks for approving.

@whym I agree, a language independent fix would have been better and I thought about it too.
Could not come with a generic solution. If anyone has any possible approach in mind, I'll be happy to know.

Resolved conflicts in strings file.

**Comment by whym** [comment]
We can continue discussing at the issue (or maybe a new one), I guess.

@uditverma5602 would you like to remove "WIP - " from the title?

**Comment by uditverma5602** [comment]
@whym Sure!

**Pull request merged**
