### PR TITLE
Day mode by default #825

### PR DESCRIPTION
**Pull request by mebr1416**
Resolve for issue where the default was Night Mode. Default is now NOT Night Mode.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks! almost there. This works whenever setting activity is created. Before user is clicked to the settings, shared preferences returns default value for theme decision (which is true, which means dark theme). If you uninstall the app, and re-install it, you will still have dark theme. To solve this issue, can you please replace all of the 

> .getBoolean("theme",true)

 occurences with 

> .getBoolean("theme",false)
There should be 5 occurences.

**Comment by mebr1416** [comment]
Ok.

**Comment by neslihanturan** [comment]
I have tested it but, it comes with dark theme on fresh install. Does it work in your tests @mebr1416 ?

**Comment by mebr1416** [comment]
@neslihanturan ok great. Any more fixes required or should we close this issue @nicolas-raoul?

**Comment by nicolas-raoul** [comment]
Thanks! :-)

**Pull request merged**
