### PR TITLE
Use data client for peer review calls

### LINKED ISSUE #2921: Optimize peer review, avoid unnecessary calls
**Summary:** 
As described here: #1544 Review needs some performance optimization. @maskaravivek seems familiar with the new implementation in ReviewHelper.java. 

Note: Please only see the last commit from the closed PR.

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #2921

This is the first PR where we start leveraging the data client library. 

The APIs were not defined in the library so as defined in the documentation, I have created a `ReviewInterface` for the API calls. 

Check out the documentation to go through the steps. 

https://github.com/wikimedia/wikimedia-android-data-client

### CODE REVIEW

**Comment by misaochan** [comment]
@neslihanturan , what manual tests did you perform with this?

**Comment by neslihanturan** [comment]
Hi @misaochan , since this looked like a basic refactor and all tests are included I played around peer review such as marking images as mis-categorized etc. But I can't say precise test steps, will definitely write next time. Now I remake a test too on master since this code is already on master (on beta cluster API 26 emulator), and mis-categorized thing works but others has no effect. Did you also experience this issue?

**Comment by maskaravivek** [comment]
> Hi @misaochan , since this looked like a basic refactor and all tests are included I played around peer review such as marking images as mis-categorized etc. But I can't say precise test steps, will definitely write next time. Now I remake a test too on master since this code is already on master (on beta cluster API 26 emulator), and mis-categorized thing works but others has no effect. Did you also experience this issue?

Did something break?

**Comment by neslihanturan** [comment]
yes @maskaravivek according to my beta cluster tests current master review questions has no effect except category one.

**Comment by misaochan** [comment]
Yes, same issue here. I think for PRs related to our backend overhaul, we need to manually test them a bit more rigorously than we would other PRs, due to the high potential for side effects.

**Comment by neslihanturan** [comment]
I agree, will be more careful next time. Do you think we should revert this merge?

**Comment by maskaravivek** [comment]
> I agree, will be more careful next time. Do you think we should revert this merge?

It would be great if we could keep the changes in master as my other changes are based on it. I can pick up the fixes for the issues immediately.

**Comment by neslihanturan** [comment]
Okay, thanks @maskaravivek !

**Comment by misaochan** [comment]
Sure, we can keep the changes in master, just link to this when you have your fix PR up.

**Comment by maskaravivek** [comment]
> Sure, we can keep the changes in master, just link to this when you have your fix PR up.

Sure. :)

**Pull request merged**
