### PR TITLE
Changed label of Limited Connection switch

### LINKED ISSUE #3986: Limited connection mode switch  needs a label
Limited connection mode switch  needs a label. Yes, I know there's no way to put a label there. However I challenge you to figure out what this switch is for without forcing yourself to toggle it to find out. What if there was a fire alarm button and nobody could figure out what the purpose of it was without having to push it to find out?
Version 811.

### PR DESCRIPTION
**Pull request by mrudultora**
**Description (required)**

Fixes #3986 (see https://github.com/commons-app/apps-android-commons/issues/3986#issuecomment-728790869)

What changes did you make and why?
Changed string label to "Limited Connection Mode" as suggested in the issue thread.

**Tests performed (required)**

Tested {build variant-betaDebug} on {Redmi Note 7S} with API level {API 29}.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Hi Mrudultora,
This issue is not marked as "bug".
Citing https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers :

> If you are a new contributor, please only ask to be assigned to issues with a "bug" or "good first issue" label. Issues labeled "enhancement" will usually only be assigned to contributors with more than 5 merged pull requests to this repo.

How many bugs have you fixed so far?
Cheers! :-)

**Comment by mrudultora** [comment]
Sorry @nicolas-raoul . I was not familiar with this part. I have opened PR for 4 issues till now. I will remember this from next time. Sorry !

**Comment by nicolas-raoul** [comment]
No problem! When you have 5 bugfixes merged, please reopen this :-) Thanks!

**Comment by mrudultora** [comment]
@nicolas-raoul Can this be reopened now ?

**Comment by nicolas-raoul** [comment]
Congratulations on [your 5 merged bugfixes](https://github.com/commons-app/apps-android-commons/pulls?q=is%3Apr+is%3Aclosed+author%3Amrudultora)! 
Yes thanks :-)

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
