### PR TITLE
Feature/bug fix#1793

### PR DESCRIPTION
**Pull request by ashishkumar468**
## Title (required)
Improve description language selector in ShareActivity
Fixes #{1793 and title (Improve description language selector in ShareActivity
) } 

## Description (required)
The spinner items in the ShareActivity were not showing up in certain devices. 
{Describe the changes made and why they were made.}
Changed the ration of the spinner to the recycler view for description from 3:7 to 4:6
## Tests performed (required)

Tested on {24 & Nexus s emulator}, with {build variant, e.g. betaD
device-2018-08-07-003007
ebug}.

## Screenshots showing what changed (optional)
 
{Only for user interface changes, otherwise remove this section. See [how to take a screenshot](https://android.stackexchange.com/questions/1759/how-to-take-a-screenshot-with-an-android-device)}

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by misaochan** [comment]
Looks good to me, happy to merge after tests succeed (please test with a small-size emulator as well). :)

**Comment by ashishkumar468** [comment]
@misaochan I have already tested on Nexus S (The attached screenshot is from the same), as well as on samsung s device. Seems to be working fine.

**Comment by misaochan** [comment]
Thanks, I missed that note on your screenshot! Btw, is there a reason why there is so much padding between the text and the dropdown arrow on the right? This feature is still usable in its current state, but was wondering about that. The dropdown menu takes up half of the screen width on small screens.

**Comment by ashishkumar468** [comment]
Actually, I have used the default spinner edit text layout which has the default padding. Let me see if I can figure out a way to somehow reduce the padding

**Comment by ashishkumar468** [comment]
@misaochan I believe the last commit will meet your requirements

**Comment by misaochan** [comment]
Thanks @ashishkumar0207 !

**Pull request merged**
