### PR TITLE
Fixed Issue 2311 for failed upload

### LINKED ISSUE #2311: Hide details of failed upload? Or fix them?
A failed upload happens when for instance Internet cuts in the middle of an upload.
In such cases, the image appears as a "failed" item in the home activity.

Unlike other images, tapping on this failed upload does not show the image's details activity. I guess this is intended?
Problem: If you tap the next unfailed image and swipe left, you can reach the failed image's details.

# Solution 1

Fix the details activity so that it shows correct information for a failed upload (for instance I believe the categories are stored so that they can be used when retrying?), and make it accessible by tap in the home activity, like all other images. Also, remove its download/share/date/copy/delete fields and all other fields that are not relevant.

# Solution 2

Make the the details of the failed image not accessible via swipe or any other mean.

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Issue: Image detail does not loads for failed images on clicking**

Fixes #2311 Hide details of failed upload? Or fix them?

### Changes made
Modified the ContrubtionListAdapter, View Holder and Contribution fragment to trigger call to media fragment when contribution image is clicked

### CODE REVIEW

**Comment by domdomegg** [comment]
I haven't reviewed it properly yet but can you remove the commented out code please.

**Comment by vanshikaarora** [comment]
>I haven't reviewed it properly yet but can you remove the commented out code please.

Sure, I'll update this PR immediately :)

**Comment by vanshikaarora** [comment]
>First time it opens the correct media, second time it opens the wrong one.

**Comment by vanshikaarora** [comment]
>First time it opens the correct media, second time it opens the wrong one.

Sorry :(  I didn't noticed it. I'll looking into the issue again

**Comment by vanshikaarora** [comment]
>Get toasts every time opening media, and also clicking some media doesn't always open that one any more. 
First time it opens the correct media, second time it opens the wrong one.

@domdomegg I have resolved both these Issues. Kindly review :)

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @domdomegg :)

**Pull request merged**
