### PR TITLE
Add pull down to refresh in Contributions screen 

### LINKED ISSUE #5131: Add pull down sync
Install the app on two different cell phones. Take some pictures and upload them on one cell phone, then do the same on the different cell phone.

Now back on the first cell phone pull down on the screen (refresh action), expecting to be able to see the pictures that one took on the other cell phone.

Not only does the screen not pull down to refresh, the other pictures don't suddenly arrive either.

### PR DESCRIPTION
**Pull request by parneet-guraya**
Fixes #5131

What changes did you make and why?

Add pull down to refresh in the contributions screen to fetch the latest data.

**Screenshots (for UI changes only)**

https://github.com/user-attachments/assets/a49cfc77-294a-45e0-a877-01c51a81cc7a

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
As you probably saw:
```
ContributionBoundaryCallbackTest > testFetchContributions FAILED
    java.lang.NoSuchMethodException at ContributionBoundaryCallbackTest.kt:100

ContributionBoundaryCallbackTest > testFetchContributionsFailed FAILED
    java.lang.NoSuchMethodException at ContributionBoundaryCallbackTest.kt:114
```

**Comment by parneet-guraya** [comment]
@nicolas-raoul Just so you know pull to refresh is only enabled in self contributions , not in other user contributions.

**Comment by nicolas-raoul** [comment]
Now it is working... I wonder what was the problem earlier. I will try again a few times tomorrow on various WiFi/mobile networks.

I also uploaded a picture using the web browser, and this feature made it appear, which is great!

**Review by nicolas-raoul — APPROVED** [review]
The problem I saw might have been a network issue. Otherwise working great, thanks!

**Pull request merged**
