### PR TITLE
Save more properties to Contribution database(Fixed #2547)

### LINKED ISSUE #2547: Some properties are lost in failed uploaded images
**Summary:** 

If image uploading failed, we can try later in CONTRIBUTIONS fragment. But some properties are not saved to Contribution database and they are lost. This caused the problem that these properties have to be manually added/edited after we successfully uploaded the failed image.

**Steps to reproduce:** 

Upload an image with location and categories, interrupt the uploading process, so the image appears as Failed in contribution list.

Re-uploading this image in contribution list.

The location and categories properties are lost in the re-uploaded image.

Expected:
Re-uploaded image has its previously set location and categories properties.

**Device and Android version:** 

Unrelated
 
**Commons app version:** 

current master

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by zhao-gang**
**Description (required)**

Fixes #2547 

What changes did you make and why?

Some useful properties of class Contribution are not saved to
Contribution database. This caused some inconvenience when re-upoading
falied images. Such that the image's date source, location and
categories are lost when re-uploading. These properties should also be
saved to database and reused when re-uploading failed images. By this
the user does not need to add/edit these properties manually.

**Tests performed (required)**

Tested master betaDebug on Nexus 6P with API level 27.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hi @zhao-gang , code overview looks good to me too. But on my test, I experienced and issue. I intentionally failed the upload and the app crashed:

```
2019-03-20 15:19:36.844 12066-12066/fr.free.nrw.commons.beta E/SQLiteLog: (1) duplicate column name: wikidataEntityID
2019-03-20 15:19:36.846 12066-12066/fr.free.nrw.commons.beta E/ContributionDao$Table: Exception performing query: ALTER TABLE contributions ADD COLUMN wikidataEntityID STRING;
    android.database.sqlite.SQLiteException: duplicate column name: wikidataEntityID (code 1): , while compiling: ALTER TABLE contributions ADD COLUMN wikidataEntityID STRING;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
        at fr.free.nrw.commons.contributions.ContributionDao$Table.runQuery(ContributionDao.java:377)
        at fr.free.nrw.commons.contributions.ContributionDao$Table.onUpdate(ContributionDao.java:320)
        at fr.free.nrw.commons.data.DBOpenHelper.onUpgrade(DBOpenHelper.java:39)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at fr.free.nrw.commons.contributions.ContributionsContentProvider.update(ContributionsContentProvider.java:160)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
        at android.content.ContentResolver.update(ContentResolver.java:1672)
        at fr.free.nrw.commons.upload.UploadService.onStartCommand(UploadService.java:174)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-03-20 15:19:37.038 12066-12066/fr.free.nrw.commons.beta E/ContributionsFragment: onFragment
```

Do you think this can be related @zhao-gang ?

**Comment by zhao-gang** [comment]
@neslihanturan I can't reproduce the crash so I can't say if it's related to this PR. As the crash log shows, it crashed when adding column `wikidataEntityID` to the database. As far as I know columns are only added when the database is being updated(in `ContributionDao#onUpdate`). I had seen some commits that are added to address the crash when updating database. I'm not sure this is the same problem.

**Comment by neslihanturan** [comment]
The error I got on your branch is: 
```
2019-03-21 12:23:59.761 18067-18074/? E/zygote: Failed sending reply to debugger: Broken pipe
2019-03-21 12:24:01.996 1451-1499/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2019-03-21 12:24:02.125 18067-18067/fr.free.nrw.commons.beta E/SQLiteLog: (1) duplicate column name: wikidataEntityID
2019-03-21 12:24:02.154 18067-18067/fr.free.nrw.commons.beta E/ContributionDao$Table: Exception performing query: ALTER TABLE contributions ADD COLUMN wikidataEntityID STRING;
    android.database.sqlite.SQLiteException: duplicate column name: wikidataEntityID (code 1): , while compiling: ALTER TABLE contributions ADD COLUMN wikidataEntityID STRING;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
        at fr.free.nrw.commons.contributions.ContributionDao$Table.runQuery(ContributionDao.java:377)
        at fr.free.nrw.commons.contributions.ContributionDao$Table.onUpdate(ContributionDao.java:320)
        at fr.free.nrw.commons.data.DBOpenHelper.onUpgrade(DBOpenHelper.java:39)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at fr.free.nrw.commons.contributions.ContributionsContentProvider.update(ContributionsContentProvider.java:160)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
        at android.content.ContentResolver.update(ContentResolver.java:1672)
        at fr.free.nrw.commons.upload.UploadService.onStartCommand(UploadService.java:174)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
```
I am able to reproduce this issue consistently with API 26 device. On the other hand, the app crashes with a different error as I reported #2696

But the error log we get on your branch about db. Since your edits are also about db, we should be careful to test this branch. To sum up, I think besides the issue on master, your PR also has an issue that causes e crash.

**Comment by zhao-gang** [comment]
@neslihanturan I think the error is related to commit 64eae8b. This commit made column `wikidataEntityID` will be added to the database every time the database is updated. But what if the database already has column `wikidataEntityID`, and is going to be updated(exactly the situation when update the app from master to my PR)? This will certainly emits the error you just encountered. Fortunately we catch this exception in method `runQuery`, so there will be no real harm to the app. 

Saying this, I also "blindly" added three columns just like column `wikidataEntityID` does. I have to say in next database update we will see three more errors like this :-(
https://github.com/commons-app/apps-android-commons/blob/d8fb0c0cd4e8164af0f5f9188a06c526958d13c2/app/src/main/java/fr/free/nrw/commons/contributions/ContributionDao.java#L319-L324

**Comment by neslihanturan** [comment]
@ashishkumar468 pinging you because the mentioned commit belong to you. Do you think the errors I have shared can be related with the commit?

**Comment by ashishkumar468** [comment]
@neslihanturan The logs you have attached, have been intentionally added. If the app is crashing for you, would it be possible for you to attach the logs which are caused due to the exception which is fatal ?

**Comment by neslihanturan** [comment]
@ashishkumar468 I am not sure if this line is safe or not:
```
    android.database.sqlite.SQLiteException: duplicate column name: wikidataEntityID (code 1): , while compiling: ALTER TABLE contributions ADD COLUMN wikidataEntityID STRING;
```

**Comment by nicolas-raoul** [comment]
Would you mind solving the conflicts? Thanks! :-)

**Comment by neslihanturan** [comment]
This PR seemed to me like sleeping for a while, thus I am going to close it. However, there are beneficial changes here. Anyone who claims the issue, please make sure you have inspired from the changes here.

**Pull request closed without merging**
