### PR TITLE
Issue #930 - Added localised screenshots for Turkish and Russian languages

### PR DESCRIPTION
**Pull request by ardovic**
#930 - Added localised screenshots for Turkish and Russian languages (2 folders in design/screenshots, 8 files each). All screenshots are ordered and follow the same pattern with the current English ones on the Google Play app page.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Cool, you got the branches right :-)

Sorry, could you please wait a bit until we refine the screenshot instructions? Thanks for your patience!

**Comment by ardovic** [comment]
Sure, why not. I'll look at other stuff needed in the meanwhile.

**Comment by neslihanturan** [comment]
I think these screen shoots looks nice, what does others think? If you also agree I will merge this.

**Comment by nicolas-raoul** [comment]
Sorry I forgot about this!

**Pull request merged**
