### PR TITLE
Fixes #3336 Hotfix: Coordinates of picture are not uploaded

### LINKED ISSUE #3336: Hotfix: Coordinates of picture are not uploaded
A user mentioned that since 2.11 (and still existing in 2.12.1), coordinates are not uploaded with his pictures. He confirms that he can see the coordinates in his stock gallery.

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
Add the value of location in managedExif tags so that location is not redacted by default (unless the user has manually chosen that)
Fixes #3336 Hotfix: Coordinates of picture are not uploaded

What changes did you make and why?
* Do not redact location by default
**Tests performed (required)**

Tested betaDebug on Samsung S7

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hey @ashishkumar468 , currently all exiif tags are non selected by default on a clean install. Is this what we want to achieve?

**Comment by ashishkumar468** [comment]
On a fresh install 
* Location should be selected by default

On existing installs
* Location state is maintained as per the existing state

**Comment by neslihanturan** [comment]
On fresh install, what I see is:
image

This is unexpected according to your answer then?

**Comment by ashishkumar468** [comment]
@neslihanturan I have pushed the fix, sorry for the trouble, somehow multiple keys were being used for managedExifTags and that's why the same did not reflect in the UI

**Comment by neslihanturan** [comment]
Thanks a lot @ashishkumar468 !

**Pull request merged**
