### PR TITLE
Fixed bitmap too large issue

### LINKED ISSUE #5387: Crash when editing some normal-sized pictures: RuntimeException Canvas trying to draw too large bitmap
### Summary

When image is shared to Commons app via Android built-in share functionality, the `Edit` button does not show image (and thus is useless) for many (but _not all_) of them. It is reproducible, i.e. pictures that fail always fail, and those which work always work.

<strike>However, the image is normally shown in  `Edit` (and can be rotated) if it has been opened from app (via `+` icon and the picture icon)</strike>

### Steps to reproduce

1. open Android image gallery and select picture
2. click `share` icon and choose `Upload to Commons`
3. Notice that `Step 1/4: Media details` opens normally with picture correctly shown in the background
4. click the `Edit image` button

### Expected behaviour

picture should be shown, along with `rotate` / `save` buttons

### Actual behaviour

only `rotate` / `save` buttons are shown, with rest of the screen being white 

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.2.1 ~14b6c455b (latest f-droid)

### Device logs

_No response_

### Screen-shots

small_Screenshot_20231117_133453_fr free nrw commons

### Would you like to work on the issue?

None

### PR DESCRIPTION
**Pull request by shankarpriyank**
Fixes #5387

Fixed the error by scaling down the images if it is too large to handle

### CODE REVIEW

**Comment by shankarpriyank** [comment]
the unit tests are failing due to some download issues

**Comment by nicolas-raoul** [comment]
In order to fix the unit tests, would you mind rebasing (or pulling) from main? Thanks :-)

**Comment by shankarpriyank** [comment]
> In order to fix the unit tests, would you mind rebasing (or pulling) from main? Thanks :-)

Done

**Review by nicolas-raoul — APPROVED** [review]
I just tested using https://mnalis.com/tmp/IMG_20231116_161908.jpg :
- On the main branch I get a crash
- On this branch I get the finne Edit UI, ad am able to rotate the picture then upload it: https://commons.wikimedia.org/wiki/File:Building_and_cars_in_Croatia.jpg (and the uploaded picture has the same number of pixels as the original, in other words it is not the scaled-down version that gets uploaded).

**Pull request merged**
