### PR TITLE
Adding username to Drawer

### PR DESCRIPTION
**Pull request by Nethermane**
This addresses issue #719.

Please let me know if I am doing something horribly wrong.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks for pr! I see nothing horrible:) Only lines are too long, maybe adding some breaks could work. Plus, I think you can use the default shared preferences instead, this could also shorten the code. Please let me test this in morning and others can also check it.

Note: Yes, there is some inconsistency about organization of shared preferences. But this should be solved on another pr.

**Comment by neslihanturan** [comment]
The functionality works nice according to my tests, but I think getting it on LoginTask might be a problem for the case: When user cleared data from settings of the phone, then go back to the app, somehow user is still logged in but username disappears. Does anyone have an idea to prevent this @nicolas-raoul @misaochan ? 

Plus, appearance of the text should be fixed. Maybe we can write it to bottom of the commons icon. Here current look:
device-2017-08-01-123455

**Comment by misaochan** [comment]
Thanks for the PR, @Nethermane !

Sorry, but I am not sure at the moment how we can prevent the loss of username when user clears data, while using sharedpreferences to store the username. Indeed that would be a drawback of that method. Hopefully someone else has an idea?

I agree with @neslihanturan re: the text. Personally I think it would be nice for the nav drawer to say "Welcome, [username]!" just above "Home".

**Comment by psh** [comment]
I've met this issue on previous projects - when you clear data it doesn't affect what the Android account manager has stored.  The trick is to ask the account manager for the current user's name and not store it in shared preferences.

Sadly the account manager is a little annoying to work with - all I can do is ask for an array of accounts of a particular type.  As we log in and log out what we need to do is flag which of those accounts is "live" and store any other additional data there that is pertinent to our account.  When we grab the array of accounts, we can look for the logged in flag and pull the name from that one.

**Comment by jorgecasariego** [comment]
I think the design could be something like this:

**Design 1**

idea1

**Design 2**

idea2

**Comment by neslihanturan** [comment]
My vote for design 1 with a different font (the font used on nav drawer). @psh thanks for the solution, but I couldn't understand where to save these flags. Maybe sample code can work tomorrow.

**Comment by psh** [comment]
I was playing around in the `LoginActivity` and added a quick log message to the `onResume()` to illustrate things:
```java
protected void onResume() {
    super.onResume();
    if (prefs.getBoolean("firstrun", true)) {
        WelcomeActivity.startYourself(this);
        prefs.edit().putBoolean("firstrun", false).apply();
    }
    Account currentAccount = app.getCurrentAccount();
    if (currentAccount != null) {
        Log.e("MW", "### Current account name = "+currentAccount.name);
        startMainActivity();
    }
}
```
What I noticed is that the `getCurrentAccount()` method that does a bunch of work for me - it queries the Android account manager and returns either the current logged in account, or null.  I think the `name` field is what we're looking for, right?

The log that printed out when I logged in said
```
### Current account name = Paul.hawke
```
Which is what I would be happy seeing on the navigation drawer.  Oh, and I vote "1" for the design.

**Comment by misaochan** [comment]
Design 1 looks good to me too. :)

**Comment by neslihanturan** [comment]
It works without a problem now, thanks @jorgecasariego :). But my last feedback is adding some space between the text and commons logo. Currently it looks like:
device-2017-08-08-143008

If you can fix Codacy and appearance, it can be merged immediately.

**Comment by Nethermane** [comment]
I am still unsure about how to get the font to look like the drawer items, but other than that it looks pretty good.
drawerlayout

**Comment by neslihanturan** [comment]
Thanks @Nethermane for adding this needed property!

**Comment by neslihanturan** [comment]
This branch failed on integration tests, and needs to be solved before being merged. Sorry for my confusion.

**Pull request merged**
