### PR TITLE
Resolves #5445 highlighting nearest place on clicking home nearby banner

### LINKED ISSUE #5445: Highliting nearest location on nearby map, when user clicks on home banner
### What is the user problem or growth opportunity you want to see solved?

_No response_

### How do you know that this problem exists today? Why is this important?

_No response_

### Who will benefit from it?

_No response_

### Anything else you would like to add?

Clicking on the nearby home banner opens the nearby map but doesn't display/highlight the nearest location, which the user would expect when he clicks. It will also help them know the name of the place since the name is usually cut short in the home banner. Also after clicking on the banner, it disappears when we go back to contributions fragment, which shouldn't happen.

### PR DESCRIPTION
**Pull request by ShashwatKedia**
**Description (required)**

Fixes #5445 

**What changes did you make and why?**
Added method to change marker icon if place is nearest, when user clicks on home nearby banner and also highlight the bottom sheet details of that particular place. Also fixed the home nearby banner to keep displaying even after clicks on it and comes back to it later (which wasn't happening earlier)

**Tests performed (required)**

Tested prodDebug on OnePlus Nord CE 2 Lite with API level 31 

**Screenshots (for UI changes only)**

Video showing functionality of app in dark and light mode:
https://drive.google.com/file/d/1ZmxEvQ05mT82A5uz1D4eEI2DmtSRpWCf/view?usp=share_link

### CODE REVIEW

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I added functionality for highlighting nearest place only when user clicks on banner, as I felt that, highlighting it always would make the home banner click redundant and would defeat it's purpose. If you feel otherwise, then I can modify it.

**Review by nicolas-raoul — COMMENTED** [review]
Unit test failing:

fr.free.nrw.commons.contributions.ContributionsFragmentUnitTests > testOnResumeCaseNullCaseIf FAILED

**Comment by ShashwatKedia** [comment]
@nicolas-raoul my apologies, I missed checking NPE while calling function in onResume

**Review by nicolas-raoul — APPROVED** [review]
Works great, thanks!
I changed the indentation a bit, see my commits above.
Merging now.

**Pull request merged**
