### PR TITLE
Fix TestCommonsApplication

### LINKED ISSUE #1068: TestCommonsApplication's compilation errors
It looks like since #1062 TestCommonsApplication has been broken. For example, it tries to override injector() which was removed by the patch.

To quote some of the errors:

```
/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/TestCommonsApplication.java:66: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/TestCommonsApplication.java:71: error: method does not override or implement a method from a supertype
                        @Override
```

### PR DESCRIPTION
**Pull request by whym**
Fixes #1068 - at least that's what I intended.

@maskaravivek can you please review this if you have time?

### CODE REVIEW

**Comment by whym** [comment]
NearbyActivityTest's
> assertNotNull(nearbyActivity.getSupportFragmentManager().findFragmentByTag("NearbyListFragment"));

keeps giving null. Has the timing of rendering fragments changed?

**Comment by whym** [comment]
I replaced schedulers per https://medium.com/@fabioCollini/testing-asynchronous-rxjava-code-using-mockito-8ad831a16877 and it seemed to work locally.

**Comment by maskaravivek** [comment]
LGTM. Merging it.

**Comment by maruthisundar** [comment]
LGTM.Merging it.

**Pull request merged**
