### PR TITLE
Fixes #4571 - Nearby: Save last known location and show it immediately without waiting for GPS

### LINKED ISSUE #4571: Nearby: Save last known location and show it immediately without waiting for GPS
Whenever I start Nearby, the map shows the whole world (used to be centered on London).
How about centering on the last known location instead?
It won't make the pins appear faster (unless we decide to also load pins at the last known location while waiting for a GPS fix), but it is less surprising for the user.

### PR DESCRIPTION
**Pull request by Pratham2305**
**Description (required)**

Fixes #4571 

What changes did you make and why?

- Saved the last known location in `applicationKvStore`, which will get updated each time when a user searches the new location

- Added condition for checking the last location, if available then the map will open at this location.

- Also resolved the issue of Mapbox getting null when using it without location permission.

**Tests performed (required)**

Tested betaDebug on Pixel 3 with API level 29.

### CODE REVIEW

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @Pratham2305 , thanks a lot. All looks good but if the lastKnownLocation is not empty, the zoom level was too far in my tests. Can you please take a look what it can be about?

**Comment by Pratham2305** [comment]
Thanks for the review, I have noticed the issue and I think it might be because the latitude and longitude are getting exchanged sometimes in the HashSet as it does not maintain the order of insertion. I have made the changes. @neslihanturan  Can you please re-test the PR. Thanks!

**Comment by neslihanturan** [comment]
Sure @Pratham2305 , would you mind fixing the conflicts first?

**Comment by Pratham2305** [comment]
@neslihanturan Done!

**Review by nicolas-raoul — APPROVED** [review]
Worked great, thanks!

**Pull request merged**
