### PR TITLE
Progressbar in category and media fragment now doesn't overlaps the views

### LINKED ISSUE #2378: Progressbar overlaps views in category and media fragment
**Summary:** 
In the category tab of Explore while loading list of items upon scroll, progressbar  overlaps the listview items.

**Steps to reproduce:** 

- Go to Explore
- Search by any name
- Go to the categories fragment
- Scroll down

### Expected
The Progressbar should be visible at the bottom of the ListView
While it is overlaps the ListView

**Device and Android version:** 
vivo 1713 Android version 7.0

**Screen-shots:** 
whatsapp image 2019-01-31 at 11 00 05 am

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Fixed the location for progressbar in media and category while loading the the list of items**

Fixes #2378 Progressbar overlaps views in category fragment

**Tests performed (required)**

Tested  on vivo 1713 with API level 24.
ezgif com-video-to-gif 4

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
That's an improvement, thanks!
Note to reviewers: The "Error occurred while loading images" already exists in master and is the topic of another issue: https://github.com/commons-app/apps-android-commons/issues/2410

**Comment by vanshikaarora** [comment]
>That's an improvement, thanks!
Note to reviewers: The "Error occurred while loading images" already exists in master and is the topic of another issue: #2410 

Good to see that you have liked the improvement :)

**Comment by maskaravivek** [comment]
Works for me.

**Comment by vanshikaarora** [comment]
Thanks @maskaravivek and @nicolas-raoul :)

**Pull request merged**
