### PR TITLE
Remove attribution for mapbox

### LINKED ISSUE #1064: Switched to Wikimedia maps server instead of Mapbox ??
The release notes of v2.6.5 does say that the app has switched to using the Wikimedia maps server instead of the Mapbox. But, I still see the Mapbox watermark in the Nearby screen. So, hasn't Mapbox been removed completely?

screenshot_2018-01-14-19-01-14

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #1064. 

Attached screenshot. 

no_attribution

### CODE REVIEW

**Comment by misaochan** [comment]
Looks good to me. @nicolas-raoul you can confirm that removing attribution is OK, right?

**Comment by misaochan** [comment]
Edit: I just re-read #1083 . I think we need to attribute them in our code, even though we can remove the logo? Perhaps add them to our credits.md?

**Comment by whym** [comment]
@nicolas-raoul I'm not sure exactly what was requested. Does the entire content of their LICENSE.md have to be copied to our credits.md? Would a hyperlink be insufficient?

**Comment by nicolas-raoul** [comment]
This is my understanding of what the rules at https://github.com/mapbox/mapbox-gl-native/edit/master/LICENSE.md require us to do: https://github.com/commons-app/apps-android-commons/pull/1105

**Comment by maskaravivek** [comment]
@nicolas-raoul Thanks for adding the license info. With your changes merged, I guess we should be good to merge this too.

**Pull request merged**
