### PR TITLE
Improve the algorithm for detecting unwanted images.

### LINKED ISSUE #1767: "Too dark" for picture with black background
I got the "too dark" message:

screenshot_20180725-135401

... for this picture:

_at_ _

I don't remember the specifics of the algorithm, but maybe it divides the picture into zones, and focused on the top part of the picture too much?
The algorithm should be improved to allow such pictures where only the background is very dark.

(recent master)

### PR DESCRIPTION
**Pull request by Mansi449**
## Modified ImageUtils.java

Fixes #1767 "Too dark" for picture with black background 

## Description (required)

Fixes #1767 "Too dark" for picture with black background
ImageUtils.java: algorithm used previously gave the 'TOO DARK' message even for the images that were perfectly valid.

The modified algorithm solves this problem. It is as follows:

- Count the number of pixels with high brightness

- Count the number of pixels with medium brightness

- If numberOfBrightPixels is below 2.5% AND numberOfMediumBrightnessPixels is below 30%, then the picture is too dark.

## Tests performed (required)
Tested on device Motorola Moto G(5) (Android 7.0, API 24), with build variant betaDebug.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@Mansi449 Can you elaborate upon the test plan. Based on that anyone who doesn't have the full context about the "dark" images issue would be able to test it. :)

**Comment by Mansi449** [comment]
@maskaravivek Can you please provide some clarification for the kind of 'test plan' that you want me to provide?

**Comment by Mansi449** [comment]
@maskaravivek Thanks for the clarification!

The following images (all of which are perfectly valid) pop up the warning when being uploaded from the `master` branch but not when being uploaded using my PR:

https://drive.google.com/open?id=1UzxErrFyWf4Bvvad9lomFXybQxbRG1e0
https://drive.google.com/open?id=1DeVSbWRoRXHSWn8IHpjCZOWN8A3sZqvw
https://drive.google.com/open?id=1jozlI1XMmgxb29qkLZEFu4WnlK6uSufE
https://drive.google.com/open?id=1ZZy4B5pZJ8XIrldACfJwRXeqwqvn9W3u

**Comment by nicolas-raoul** [comment]
Could you please also test with pictures that would definitely be considered too dark?
Here are a few ones:
img_20180807_124651
img_20180807_124622

**Comment by Mansi449** [comment]
@nicolas-raoul @maskaravivek Are there any changes that you think I should do?

**Comment by neslihanturan** [comment]
I think this PR does what it should do:) Being dark or valid can be very variable. But with this PR, we let night photos too. I tested with example images above, and didn't distracted as a user, so merging as soon as you fixed Travis Cl fail. Thanks @Mansi449 !

**Comment by Mansi449** [comment]
@neslihanturan the Travis CI fail has been fixed. The PR can be merged now.
Thanks!

**Pull request merged**
