### PR TITLE
Develop ui featured images

### PR DESCRIPTION
**Pull request by neslihanturan**
This PR includes UI for featured images (last pic of the days) as discussed here #324 
I thought I have added screenshots already, @misaochan , here they are:
screenshots

### CODE REVIEW

**Comment by misaochan** [comment]
@neslihanturan Nice! Do you think we could get screenshots for the PR? :)

**Comment by misaochan** [comment]
Hi @neslihanturan , sorry it took so long for me to go through this. The screenshots you posted look good to me, with one minor issue: there needs to be an "Author" field in the detailed (individual) view, as mentioned at #324 . :)

Will also ping @psh for feedback.

**Comment by neslihanturan** [comment]
Thanks for feedback  @psh , this was one of my concerns while implementing it. But I thought it can be too much for this PR (I mean refactoring ContributionActivity also). But I totally agree that we need to reuse these codes.

Besides, what would you think if featured images UI wouldn't be incredibly similar to ContributionActivity? We should make user feel she is on a different activity (the only disciriminator is activity title currently).

**Comment by neslihanturan** [comment]
Added author field @misaochan , and tested. It worked fine for me on 4.4.2, for both activities (No author field on Contribution), orientation changes included.

**Comment by misaochan** [comment]
Thanks @neslihanturan ! I agree that refactoring the code to prevent duplication would be great. However, I will go ahead and merge this PR first, please feel free to submit the refactoring in another PR. :)

**Pull request merged**
