### PR TITLE
fix :Back Pressed Event not work in Explore tab when user not login

### LINKED ISSUE #4403: Back Pressed Event not work in Explore tab
**Summary:** 

Open the App without login  and go to Explore tab  and press back button then back press event not work 

**Steps to reproduce:** 
- Open an App without Login
- Go to Explore Tab 
- Press the Back button then nothing happens

**Device and Android version:** 
Android Device:Redmi y3

**Commons app version:** 
Latest master
**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**

Fixes #4403

What changes did you make and why?
Make some conditional statement changes 

**Tests performed (required)**
Android Device:Redmi y3,Redmi 4
API Level:25,29

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul please review this one

**Comment by Prince-kushwaha** [comment]
@madhurgupta10 please review this one

**Comment by Prince-kushwaha** [comment]
@neslihanturan @ashishkumar468 up for review

**Comment by nicolas-raoul** [comment]
Sorry for the delay!
Would you mind fixing the conflict?

**Review by nicolas-raoul — APPROVED** [review]
It indeed fixes the bug, thanks!

**Pull request merged**
