### PR TITLE
solves issue #3346 now the upload limit value is assigned to 100 if the edit text is empty

### LINKED ISSUE #3346: Upload limit is working even if I leave the upload limit edittext blank or if I press Cancel button
**Summary:** 
Upload limit is taking the first digit of last entered number a the upload limit if I am leaving upload limit edittext blank.

What did you expect the app to do, and what did you see instead?
I wanted app to show an toast displaying an error that upload limit edittext is empty.

**Screen-shots:** 

todayfifd

**Would you like to work on the issue?**

I want to work on this issue.
@nicolas-raoul @maskaravivek

### PR DESCRIPTION
**Pull request by vibhusharma101**
Fixes #3346

What changes did you make and why?
I changed the Settings Fragment activity and made changes in uploadLimitEdittext event listener

### CODE REVIEW

**Comment by vibhusharma101** [comment]
@madhurgupta10 sir I have created the new pull request with the changes you suggested.

**Comment by vibhusharma101** [comment]
@ashishkumar468  @maskaravivek  sir please review

**Comment by neslihanturan** [comment]
Hi @vibhusharma101 can you please inform us about what does this changes exactly do? In issue discussions you said it is expected to display a error dialog if the text is empty, but these changes seems irrelevant. Can you explain it in more details please?

**Comment by madhurgupta10** [comment]
@vibhusharma101 Any updates on this issue?

**Comment by macgills** [comment]
fixed in #3521

**Pull request closed without merging**
