### PR TITLE
Fixes #3508: Replaced Heightlimitedrecyclerview 

### LINKED ISSUE #3508: Remove HeightLimitedRecyclerView
**Summary:** 

I can see no reason why this should exist. It should be removed and the UploadMediaDetailFragment tested with a standard Recyclerview

**Would you like to work on the issue?**

Anyone feel free to take, otherwise I'll get to it

### PR DESCRIPTION
**Pull request by hudlerr**
Fixes #3508

Replaced Heightlimitedrecyclerview with standard recycler view

**Screenshots (for UI changes only)**
Screen Shot 2020-03-25 at 14 55 00

Screen Shot 2020-03-25 at 14 55 32

### CODE REVIEW

**Comment by maskaravivek** [comment]
@hudlerr Can you add a screenshot with 5-6 description items.

**Comment by hudlerr** [comment]
Screen Shot 2020-03-26 at 08 42 24

**Comment by macgills** [comment]
@hudlerr you need to sync your branch with the upstream master. This crashes when you try to add a description for an image that has a location

**Comment by macgills** [comment]
image

This scenario is also possible. So the original intention of HeighLimitedRecyclerview I am seeing now, the image should always be in view while you are adding descriptions. Recylerview is annoying and doesn't respect `maxHeight`.

We can work around this by just wrapping the recyclerview in a ConstraintLayout with a `maxHeight`, [docs](https://developer.android.com/reference/android/support/constraint/ConstraintLayout#minimum-dimensions-on-constraintlayout)

**Comment by macgills** [comment]
This PR also does not delete the HeightLimitedRecyclerView and was based off your previous PR so has unnecessary changes

**Comment by hudlerr** [comment]
> This PR also does not delete the HeightLimitedRecyclerView and was based off your previous PR so has unnecessary changes

Should I just create a new branch, since I dont want them commits?

**Comment by macgills** [comment]
You should when starting a new ticket, sync your fork's master with this repo's master and then branch off of that

**Comment by sivaraam** [comment]
> You should when starting a new ticket, sync your fork's master with this repo's master and then branch off of that

Alternatively you could just fetch the repo's master and branch off directly from that. Like:

```commands
git fetch origin
git checkout -b feature_branch_for_3508 origin/master
```

**Comment by macgills** [comment]
@sivaraam you have configured the upstream repo as `origin`? I thought [upstream](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) was the convention but I have rarely worked on forks

**Comment by hudlerr** [comment]
Im trying to git reset --hard COMMIT_ID, to get rid of unwanted commits on this branch, but its not working so well. Am I okay to delete this branch and open a new pull request?

**Comment by macgills** [comment]
It is your fork, go wild.

It is not best practice so try not to create excessive activity on this repo in the future but I'll allow it for now.

**Comment by hudlerr** [comment]
Kay! Ill just know to triple check what commits are getting onto my pull requests :)

**Comment by sivaraam** [comment]
> @sivaraam you have configured the upstream repo as `origin`?

Yeah. I always keep the upstream as `origin` and name the remote associated with my fork as ... `fork` :slightly_smiling_face: 

> I thought [upstream](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) was the convention but I have rarely worked on forks.

I haven't heard of this convention before. Now that I am aware of it, I see how there's a possibility of misinterpretation in my comment, sorry about that. To be clear, I did refer to the upstream repo as `origin` in the following commands:

```
git fetch origin
git checkout -b feature_branch_for_3508 origin/master
```

**Pull request closed without merging**
