### PR TITLE
Refactoring the API calls

### PR DESCRIPTION
**Pull request by psh**
In the process of refactoring related to the networking stack, I introduced a class `ApacheHttpClientMediaWikiApi` and felt the need to at least _smoke test_ a few API calls to make sure that requests and responses are correctly handled.  I used the `MockWebServer` (from OkHttp) to serve up canned responses and assert that requests are well formed at a unit-test level.  This was already a transitive dependency from the mapbox library, made explicit in the `build.gradle` file.

My refactor pulls all of the API calls into a single place so that the body of the app depends on a `MediaWikiApi` interface returning application specific models, with a concrete `ApacheHttpClientMediaWikiApi` class that hides the implementation.  This makes the code more _testable_ (isolating the networking tests to a single class) and makes it easier to use mocks in the rest of the app if you want to unit test just the interactions later.

Although the testing isn't yet complete, I wanted to get the code into your hands as (IMO) it forms a solid basis to address your high-priority item #705 (upload tests).  This PR doesn't include those tests, but it does aim to _set you up for success_ in this endeavor.  :)

### CODE REVIEW

**Comment by psh** [comment]
Well, that's disappointing - Travis CI [timed out starting the emulator](https://travis-ci.org/commons-app/apps-android-commons/builds/250583143?utm_source=github_status&utm_medium=notification).

I notice in the build history this is happening a lot.

Want to maybe look at using a tool like [Robolectric](http://robolectric.org/) to be able to run the tests locally without an emulator?

**Comment by misaochan** [comment]
Thanks for the PR, @psh ! It's huge, please give us some time to look through it. ;)

**Comment by misaochan** [comment]
Hi @psh ,

I've tested this and it works well except for one (significant) problem - it crashes each time it attempts to finalize an upload. When the loading bar has completed, the app crashes with the error log:

```
07-10 19:36:21.971: E/AndroidRuntime(2252): FATAL EXCEPTION: UploadService
07-10 19:36:21.971: E/AndroidRuntime(2252): Process: fr.free.nrw.commons, PID: 2252
07-10 19:36:21.971: E/AndroidRuntime(2252): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:248)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:130)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:38)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:25)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at android.os.Looper.loop(Looper.java:154)
07-10 19:36:21.971: E/AndroidRuntime(2252): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

The image upload actually does go through, e.g. https://commons.wikimedia.org/wiki/File:Fog_in_Brisbane.jpg , but it displays erroneously in the contributions view as a failed upload:

screenshot_20170710-194041

**Comment by whym** [comment]
It looks like my last patch #738 brought some conflicts here. Please free to ping me if you need help.

**Comment by misaochan** [comment]
Sorry, @psh , I missed your comment from 2 days ago. Should I go ahead and re-test the upload issue?

**Comment by psh** [comment]
The branch is now up-to-date with _master_.  The conflicts were trivial (just imports) I deal with much worse on my team in work!

@misaochan - I gave uploading a quick smoke test, the NPE is fixed for the images I tried - please retest.

**Comment by misaochan** [comment]
Works great for me now, thanks @psh ! :)

**Pull request merged**
