### PR TITLE
[WIP] Implemented Espresso tests for upload with multilingual descriptions

### LINKED ISSUE #2817: Espresso tests for testing upload with multilingual descriptions
**Summary:** 

It would be nice to automatically test uploads with multilingual descriptions. The user can click on the (+) button to add a description in another language. 

device-2019-03-30-173139

IMO, there are two things that need to be tested here. 

- test that verifies that the user is able to enter descriptions in multiple languages.
- test that verifies that an image with multiple descriptions is queued for upload.

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #2817 

All tests pass. 

Screen Shot 2019-04-01 at 11 57 35 PM

### CODE REVIEW

**Comment by domdomegg** [comment]
Here's a GIF of testUploadWithDescription, with the login part removed (as that seems to work fine + would reveal my login details)

withDescription

And here are the exact logs for that GIF:

```
androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: fr.free.nrw.commons.beta:id/bottom_card_next'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:84)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:85)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:57)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:316)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:177)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:118)
at fr.free.nrw.commons.UploadTest.testUploadWithDescription(UploadTest.kt:158)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user.
Target view: "AppCompatButton{id=2131296370, res-name=bottom_card_next, visibility=VISIBLE, width=176, height=96, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@56b4bf0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=528.0, y=350.0, text=Next, input-type=0, ime-target=false, has-links=false}"
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:248)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:64)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:157)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:154)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by neslihanturan** [comment]
Is this Pr active?

**Comment by maskaravivek** [comment]
I will try to make the fixes soon. :)

**Comment by neslihanturan** [comment]
Ping me for review @maskaravivek :)

**Comment by domdomegg** [comment]
Closing stale PR for now, reopen if more work happening on it.

**Comment by misaochan** [comment]
Ah, this PR is kind of important actually. :) @maskaravivek are you still working on it? If not, maybe someone would like to take up fixes for the issues that @domdomegg mentioned above?

**Comment by maskaravivek** [comment]
@misaochan I wasn't working on it from quite some time but let me fix the issues and get it merged. It would be nice to have these tests in place.

**Comment by maskaravivek** [comment]
@domdomegg @misaochan I have fixed the tests.

**Comment by macgills** [comment]
I am morally opposed to an automated test that touches a non app resource like an endpoint but I am a bit late coming to this race.

```
> Task :app:connectedBetaDebugAndroidTest
Starting 30 tests on Nexus 5X - 8.1.0

fr.free.nrw.commons.LoginActivityTest > testLogin[Nexus 5X - 8.1.0] FAILED 
        androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 539, 1053 and precision: 16, 16' on view 'with id: fr.free.nrw.commons.beta:id/login_password'.
        at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)

fr.free.nrw.commons.UploadTest > testUploadWithMultilingualDescription[Nexus 5X - 8.1.0] FAILED 
        androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 947, 1659 and precision: 16, 16' on view '(with id: fr.free.nrw.commons.beta:id/fab_plus and is displayed on the screen t
o the user)'.
        at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)

fr.free.nrw.commons.UploadTest > testUploadWithoutDescription[Nexus 5X - 8.1.0] FAILED 
        androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 539, 1053 and precision: 16, 16' on view 'with id: fr.free.nrw.commons.beta:id/login_password'.
        at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)

fr.free.nrw.commons.UploadTest > testUploadWithDescription[Nexus 5X - 8.1.0] FAILED 
        androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 947, 1453 and precision: 16, 16' on view '(with id: fr.free.nrw.commons.beta:id/fab_gallery and is displayed on the scree
n to the user)'.
        at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
```

I have failures running on my device.

The tests could be using PageObjects/Robots pattern.

Raw Espresso is hideous to the eyes, Kakao, Kaspresso are libraries out there to soften the usage. I am sure there are others which are much nicer too, just slipped my mind.

I don't think UI tests are running on travis? If they aren't being run they have zero value to me.

These are all just thoughts, feel free to go ahead with the merge, I am not overtly familiar with the project yet.

**Comment by domdomegg** [comment]
> I am morally opposed to an automated test that touches a non app resource like an endpoint but I am a bit late coming to this race.
> 
> I have failures running on my device.
> 
> Raw Espresso is hideous to the eyes, Kakao, Kaspresso are libraries out there to soften the usage. I am sure there are others which are much nicer too, just slipped my mind.
> 
> I don't think UI tests are running on travis? If they aren't being run they have zero value to me.

Haha the UI tests are erm... not the strongest part of the app. It would be good to mock the calls to the external endpoints, but there's a lot more wrong with them that that tbh.

There's been many attempts to get them running on Travis, unfortunately with no consistent success - see #2226 #2897 #3279 #3298 (getting them to run locally is a big enough challenge already...)

If you could manage to fix all them to work consistently and easily (even if it meant ripping out what's there so far and redoing it) I think it would be highly valuable.

**Comment by macgills** [comment]
> Haha the UI tests are erm... not the strongest part of the app.

Show me an app where they are 😞 .


@domdomegg perhaps that should be a ticket then? My knowledge of everything is a little light right now as I wade through the `depiction`s branch.

If that is what I am pointed at next I'll go at it.

**Comment by domdomegg** [comment]
> @domdomegg perhaps that should be a ticket then? My knowledge of everything is a little light right now as I wade through the `depiction`s branch.

Yea, feel free to create one (there may already be one in the backlog of issues).

> If that is what I am pointed at next I'll go at it.

I'd be happy for you to pick this up, but there are also lots of other valuable issues I'd be happy for you to work on (several you've raised recently) - up to you to work on what you think is most valuable and you'd be most effective at :)

If you do need a hand with anything do let me (no guarantee I'll be any help though :P) or others know.

**Comment by maskaravivek** [comment]
@macgills Did you put test credentials in `app/build.gradle` before running the tests? On Travis it picks from the `env` variables and when ran locally, we are supposed to put test user name and password in the gradle file.

**Comment by macgills** [comment]
@maskaravivek yes I put in credentials. The tests thrown a helpful exception telling you to go there and fill them out.

**Comment by maskaravivek** [comment]
@macgills I ran the tests on the device that you were using ie. "Nexus 5X - 8.1.0" and didn't encounter the same issues. However I ran into a few other issues which I have fixed in my last commit. 

I agree that our tests are flaky as of now and as of now it won't run on all android devices smoothly. The idea is to have the basic tests in place and move towards stable UI tests which can ideally run on multiple Android platform using Travis CI. 

Couple of issues worth highlighting are: 

- Most of the tests use `Thread.sleep`. Ideally `IdlingResource` should be used 
- Permission, warning and other dialogs are not handled properly by the tests.

**Comment by macgills** [comment]
Stupid IdlingResources "Hey why don't you alter your code so your test code can work?" A+ design work by google there or the even more infuriating "Write a testwrapper around every component that is asynchronous to awkwardly shove an IdlingResource in, isn't this a fun development flow!"

Anyway I am ranting, I am fine with this being merged, it already has approval so if you are postponing merging on my account I wouldn't worry

**Comment by maskaravivek** [comment]
Going ahead and merging the PR.

**Pull request merged**
