### PR TITLE
Making text a link

### PR DESCRIPTION
**Pull request by mithlesh4257**
Fix for issue #1037
Explicitly show that the license text is a link.

### CODE REVIEW

**Comment by neslihanturan** [comment]
@mithlesh4257 thanks for your contribution:) But I couldn't see any difference on m tests. If it works for you, can you share a screen shot please? I think you may need to use Htlm.fromHtml method to make it work for all devices.

**Comment by mithlesh4257** [comment]
Thanks @neslihanturan, Well Nothing I have change instead of 2 word code. Earlier it was explicitly link. But now there is one underline down the Attribution 3.0 or whatever option is selected.

**Comment by mithlesh4257** [comment]
Does it need more work? If yes, kindly guide me @neslihanturan.

**Comment by neslihanturan** [comment]
Hi @mithlesh4257 , yes it requires a little more work. Firstly can you please share a screen shot of your successful result from your device or emulator. Secondly, I suspect we need to do some extra steps to make TexView understand <u> tags. Here are some advices, https://stackoverflow.com/questions/8033316/to-draw-an-underline-below-the-textview-in-android and I think Html.fromHtlm(string) is the thing we might need. 

Sorry if my english in previous comment isn't understandable, this happens sometimes:)

**Comment by mithlesh4257** [comment]
screenshot_20180114-163128


Now it will look like this.

**Comment by neslihanturan** [comment]
Yes, I expected the same. But it doesn't worked for me. So some additional steps (which I mentioned above) are required.

**Comment by mithlesh4257** [comment]
Okay I'm fixing it. Thanks @neslihanturan.

**Comment by mithlesh4257** [comment]
Hi @nelishanturan, see this.

https://stackoverflow.com/questions/2394935/can-i-underline-text-in-an-android-layout

I think this might be good. Right?

**Comment by mithlesh4257** [comment]
I have opened another PR. 
Kindly review
Thanks @neslihanturan.

**Pull request closed without merging**
