### PR TITLE
5191: Fix UI elements not conforming to dark mode

### LINKED ISSUE #5191: Dark mode: Some UI elements not conform
# Upload Wizard Location Selection Step (when uploading a picture, tap the map icon on the screen when description can be entered)
The map should be dark (like the Nearby activity's map):
Screenshot_20230328-165607

# Feedback (in the app's hamburger menu)
The black font is not great for dark mode.
Screenshot_20230328-165311

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #5191 

What changes did you make and why?
Changed the map in the upload wizard at the location selection step and black font in the feedback dialog to conform to the dark mode.

**Tests performed (required)**

Tested ProdDebug on Redmi 5A with API level 27.

**Screenshots (for UI changes only)**

### Dark Mode:

| Before | After |
|----|----|
| Map | |
| map_before | map_after
| Feedback Dialog | |
| feedback_before | feedback_after 

The light mode still remains the same:

### Light Mode:

| Before | After | 
| ---- | ---- |
| Map | |
| light_map_b4 | light_map_after 
| Feedback Dialog | | 
| light_feedbback_before | light_feedback_after

### CODE REVIEW

**Comment by kartikaykaushik14** [comment]
@RitikaPahwa4444 You might have to make a few changes after rebasing with the latest version of Master. After the changes for moving from Mapbox to MapLibre, we now have the option to get a predefined style based on the type of configuration we choose. It could be Mapbox, MapLibre, or MapTiler. 

In order to retain the original configuration, we chose to retain the configuration type Mapbox. For ex: Style.DARK would now be used as Style.getPredefinedStyle("Dark")

**Comment by nicolas-raoul** [comment]
Indeed, Rikita would you mind rebasing and writing setStyle like on this line: https://github.com/commons-app/apps-android-commons/pull/5184/files#diff-b503ac9d99a74afbbde1ec04f8f774fd92a69b3a7e940233b82df7b9c3db59f0L319

By the way, do not hesitate to create constants or otherwise factorize the first argument of `setStyle` with other usages, if you think it makes sense.

Thanks both!

**Comment by RitikaPahwa4444** [comment]
I just checked out the latest master. Thank you @nicolas-raoul for giving the example; I will make the necessary changes.

**Comment by RitikaPahwa4444** [comment]
Seems like the unit tests have changed too in the latest master. They are failing because of the constants I added in the `LocationPickerConstants` file and need to be modified. Will update after fixing the tests🙂

**Comment by nicolas-raoul** [comment]
Ah sorry, thanks for noticing!

**Comment by RitikaPahwa4444** [comment]
I have added an additional target exception in the unit test caused by the introduction of constants in the code.

**Review by nicolas-raoul — APPROVED** [review]
Works great, special thanks for also fixing the unit tests!
I guess `Style.DARK:Style.OUTDOORS` could be used in more places, they probably got overwritten by the rebase, feel free to modify in another pull request if you want. :-)

**Comment by RitikaPahwa4444** [comment]
Thank you for confirming. I'll make the changes and create another pull request soon.

**Pull request merged**
