### PR TITLE
Feature #1756 : Bookmark System

### LINKED ISSUE #1756: Add a bookmark option in media Details
**Summary:** 
When exploring feature will be available to everyone. A lot of people will download images uploaded by others. But they users will not get the same in an Organised manner. It would be nice if we can have a bookmark option in media details menu and store the bookmarked filenames in the local history and show a list of bookmarked images later may be in the drawer of somewhere.

### PR DESCRIPTION
**Pull request by Victor-Bonin**
## Bookmark System

Fixes #1756   

Creation of a new section Bookmarks in the navigation drawer, divided in 2 tabs.
Those tabs list the user's bookmarked media and places using the previsouly used display.
When clicking a media or a location you can access its details. From the details screen you can now save the picture or place, or unsave it if it is already bookmarked.

Creation of a new package : **bookmarks** including both subpackages **locations** and **pictures**
The subpackages have their own DAO, ContentProvider, Controller and Fragment.
Creation of corresponding tests.

## Tests performed (required)

Tested on API level 24 (Samsung Galaxy S6) & 28 (Emulator Pixel 2), with betaDebug & betaRelease.

## Screenshots : 

#
screenshot_20181012-152337
screenshot_20181012-152411
screenshot_20181012-152442
screenshot_20181012-152446

### CODE REVIEW

**Comment by maskaravivek** [comment]
@R0ma1nG Thanks for the PR. I tried testing it and the app crashes as soon as I click on bookmarks. Here are the logs: 

```
2018-10-14 23:15:19.303 19638-19638/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 19638
    android.database.sqlite.SQLiteException: no such table: bookmarks (code 1): , while compiling: SELECT media_name, media_creator FROM bookmarks
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1392)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesContentProvider.query(BookmarkPicturesContentProvider.java:46)
        at android.content.ContentProvider.query(ContentProvider.java:1063)
        at android.content.ContentProvider.query(ContentProvider.java:1155)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:154)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:137)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:127)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.getAllBookmarks(BookmarkPicturesDao.java:42)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesController.needRefreshBookmarkedPictures(BookmarkPicturesController.java:53)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesFragment.onResume(BookmarkPicturesFragment.java:89)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:22105)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:22105)
        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1059)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
2018-10-14 23:15:19.305 19638-19638/fr.free.nrw.commons.beta E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2462)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1544)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1801)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1432)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

Note: I didn't do a fresh install. If the user already has the app installed, you should handle it using sqlite migrations ie `onUpgrade`

**Comment by maskaravivek** [comment]
Great work @R0ma1nG!!

I tested the feature on a fresh install and it works like a charm. I tried the following things: 
- Bookmarked a media item
- Removed a media item from bookmarks
- Bookmarked/removed a nearby item
- Tried uploading an image using the bookmarked item, and ensured that the corresponding wikidata edit is also attempted. 

Am happy to do a code review and merge this PR once the upgrade thing is fixed. :)

**Comment by nicolas-raoul** [comment]
Looks great!
This feature will be extremely useful to me, as I look for nearby places using Android, usually shoot them with an unconnected DLSR camera, and link them to Wikidata later.
Insalien ? :-)

**Comment by R0ma1nG** [comment]
Hey @maskaravivek 
I fixed the database upgrade :) 
Yes @nicolas-raoul from INSA Lyon.

**Comment by misaochan** [comment]
Wow, fantastic PR! Merging, thanks for the great job @Victor-Bonin and @R0ma1nG . :)

**Pull request merged**
