### PR TITLE
Bug#954 Take latitude/longitude from picture taken seconds after

### PR DESCRIPTION
**Pull request by harisankerPradeep**
Fixes bug #954

### CODE REVIEW

**Comment by neslihanturan** [comment]
I checked your code and looks good to me. However I don't have such photos to test unfortunately. @misaochan @nicolas-raoul do you have photos that matches criteria of related issue?

**Comment by harisankerPradeep** [comment]
@neslihanturan one way to get samples is to click pictures by turning geotagging on and off. Open Camera let's you do that.

**Comment by neslihanturan** [comment]
Thanks for the great tips, will collect some samples today

**Comment by neslihanturan** [comment]
@harisankerPradeep it works grreat, and I really liked using this feature while playing with it for test purpose. Thank you for implementation and @nicolas-raoul for the idea.
Some minor questions:
- User is able to dismiss the question by clicking outside (and does not copy location info as expected). Do we want to let this happen, or force the user to answer. 
- If user says no, code re-asks the question on category screen also (same thing happens if user clicks outside of the screen also). Is this a bug or a feature? It seems like our code doesn't accept "no" as an answer:D

**Comment by harisankerPradeep** [comment]
@neslihanturan  I personally don't think the user should be forced to answer.
As for the second issue, I have fixed it in the last commit. Thanks for pointing it out! 👍

**Comment by neslihanturan** [comment]
Thanks @harisankerPradeep :)

**Comment by harisankerPradeep** [comment]
@nicolas-raoul @neslihanturan @misaochan  Thanks!

**Pull request merged**
