### PR TITLE
#747: Convert auth package to Kotlin

### PR DESCRIPTION
**Pull request by domdomegg**
**Description (required)**

Kotlin conversion (#747). Hoping to get more of the app in Kotlin, eventually so it'll all be one language and easier to standardize and reason about.

This converts the auth package to Kotlin

**Tests performed (required)**

Tested BetaDebug on Oneplus 6T with API level 29

### CODE REVIEW

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @domdomegg , thanks the refactor seems good in general. However, when it comes to test them I recognized a weird, reproducible problem. If I log out and in at master branch I can see all of my contributions as I should. On the other hand, if I log out and in on your branch, I only see some of my uploads (my uploads up to until a random date). I have 200 uploads, it may be hard to replicate this problem with less contributions I guess.

**Comment by neslihanturan** [comment]
hey @domdomegg , any luck with this PR regarding to my previous reviews?:)

**Comment by domdomegg** [comment]
Hi, sorry for the delay in getting back to you! I've been very busy this summer :)

I struggled to reproduce the bug you mentioned, despite having over 200 uploads. I'm going to keep digging (and I'll need to fix the merge conflicts anyways). Will convert this to a draft until that's fixed and if I get too stuck might ask if you could look into it again.

**Comment by neslihanturan** [comment]
This is one of the PRs that I don't know what to do :) The errors are not reproducible all the times unfortunately :/ Should we convert it to draft @domdomegg , what would you suggest?

**Comment by domdomegg** [comment]
Hi @neslihanturan I've merged in master and so I think it is now up-to-date. I'm not able to reproduce the errors - are you sure they are specific to this branch? This should reimplement the functionality exactly, and my hope is to get everything in Kotlin so we can move faster going forwards with just one main supported language.

**Comment by neslihanturan** [comment]
Hey @domdomegg thanks for merging to master. I think after the merge there are some build errors as:

```
LoginActivity.kt: (402, 25): Type mismatch: inferred type is String? but String was expected
LoginActivity.kt: (228, 22): No value passed for parameter 'p7'
LoginActivity.kt: (202, 63): Type mismatch: inferred type is <no name provided> but String was expected
SessionManager.kt: (120, 29): Expecting comma or ')';
```

**Comment by domdomegg** [comment]
Ah yep my bad, think I messed up the merge.

I think at this stage given the problems with the PR I'm just going to close it - possibly more effort to fix the merge than it would be to redo the PR :joy:.

One day (in my dreams) we'll get everything migrated to Kotlin, and I think that should be somewhat of a strategic priority to maximise future development velocity, both for us and new contributors with one consistent way of doing things :)

**Pull request closed without merging**
