### PR TITLE
Fix release

### PR DESCRIPTION
**Pull request by akaita**
I noticed #826 broke the `release` build, because it actually started to use some `debug`-specific resources which should actually have never been there.

Removed them and replaced the placeholder using the `tools` namespace.

### CODE REVIEW

**Comment by akaita** [comment]
It is odd. Instrumentation tests succeed if you already logged in with the app before running tests.
Not sure how it could work before. Not sure why it stopped working now either 🤔

**Comment by akaita** [comment]
I just noticed: #826 also broke integration tests by accessing Account in Drawer.
Could introduce Mockito into the testing suite to mock the Account, or mock the server to create one... Not sure which one we'd prefer. Any ideas?

**Comment by neslihanturan** [comment]
Ups, probably my bad to merge it. But actually I am pretty sure that it was done with integration test when I checked that branch. Anyway, I think it can be better if I revert merge @akaita , what do you think?

**Comment by neslihanturan** [comment]
So that we can solve integration test issues on that branch.

**Comment by akaita** [comment]
If you log into the app once, an account will be saved into Android's AccountManager and instrumentation tests will run ok. They also run ok for me, and then they failed in CI.

The thing is that CI runs in a clean emulator every time, so it never has put any credentials in the app, so there is nothing in AccountManager.
It took me a while to realise 😅 .

I think your idea is good. Revert and fix in that branch will be definitely best 👍

**Comment by neslihanturan** [comment]
Since, merge is reverted, can we close this PR @akaita ?

**Comment by akaita** [comment]
Yes, thanks.
I'll try to replicate the reverted PR and think about the best way to fix the instrumentation test for it.

**Pull request closed without merging**
