### PR TITLE
Added share button in navigation drawer

### LINKED ISSUE #1284: Add Share app option inside app
**Summary:** 

There should be an option to share the app.

**Steps to reproduce:** 

1. Add option to share in navigation drawer.
2. On Click of share option -
```
Intent sendIntent = new Intent();
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_TEXT, "sharetext");
sendIntent.setType("text/plain");
startActivity(Intent.createChooser(sendIntent, getString(R.string.share)));
```			
**Expected behavior:** 
There should be an option to share the app.

**Observed behavior:** 
There is no option to share the app.

 **Commons app version:** 
2.6.7

### PR DESCRIPTION
**Pull request by aniket1897**
## Description
Added share button 

Fixes #1284 

Allows the app to be shared among platforms like WhatsApp,Facebook ,Gmail,etc

## Tests performed

Tested on API Level 24 & Redmi Note 4 with betaDebug build variant.

## Screenshots showing what changed
 
screenshot
s2

### CODE REVIEW

**Comment by maskaravivek** [comment]
@aniket1897 can you update the PR based on the discussion in #1284.

**Comment by ujjwalagrawal17** [comment]
@aniket1897 are you working on this?

If not I can work on this.

**Comment by neslihanturan** [comment]
Hi @aniket1897 do you want to update this according to discussion?

**Comment by neslihanturan** [comment]
This PR seems like sleeping, if you want to give a try @ujjwalagrawal17 I think you can go ahead.

**Comment by ujjwalagrawal17** [comment]
Sure @neslihanturan I will work on it.

**Pull request closed without merging**
