### PR TITLE
# 930 - 9 Screenshots for Turkish - tr language.

### PR DESCRIPTION
**Pull request by ardovic**
tr1
tr2
tr3
tr4
tr5
tr6
tr7
tr8
tr9

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks Serj for the screenshots!
We are currently fine-tuning the process, and this PR gave us great insight.
Why do you want this to be merged into the "direct-nearby-uploads" branch instead of "master"?
Cheers!

**Comment by ardovic** [comment]
Hi Nicolas!

Believe it or not, I've spent about 1 hour trying to submit the
screenshots, however I was unable to do so and did just as.

Could you please guide me to do things the correct way? I have also made 9
Russian screenshots for your app, maybe with your help I would do the right
thing in the right place this time.

Regards,
Serj

**Comment by nicolas-raoul** [comment]
The easiest to avoid messing with branches:
- Clone the repository somewhere else on your computer
- Create the folder and add the files
- Commit, push
- Do the pull request, leave all options by default

**Comment by ardovic** [comment]
Nicolas, 

I did as you said, but when I try to push, I get the following error from the SourceTree: 

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/master 
Pushing to ssh://git@github.com/commons-app/apps-android-commons.git
ERROR: Permission to commons-app/apps-android-commons.git denied to ardovic.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Completed with errors, see above
```

I'm on half way doing this...

**Comment by nicolas-raoul** [comment]
I forgot to say, you have to clone from your own fork.

**Comment by nicolas-raoul** [comment]
Please delete all of your local repositories (of course keep your screenshot files somewhere though) before applying my instructions at https://github.com/commons-app/apps-android-commons/pull/940#issuecomment-342756191

I see you have not forked the repository, please do it now.

Please read the whole page at https://help.github.com/articles/fork-a-repo/ it will help you a lot.

**Comment by ardovic** [comment]
Nicolas, 

Thank you very much for your guidance. I did as you instructed and everything worked out just fine.

Regards.

**Comment by nicolas-raoul** [comment]
Hello Serj,

I have just finished writing the instructions now!
So, please follow them at https://github.com/commons-app/apps-android-commons/issues/960 with YOURLANGUAGE being `Turkish tr-TR`. Thanks a lot for your patience. :-)

Nicolas

**Comment by ardovic** [comment]
Nicolas,

Of course, though my language is Russian ru-RU, and I live currently in Russia. Yet, I'm bilingual, and my second language being Turkish, I can provide screenshots for both. However, my map/places screenshot will still reflect Moscow..

Serj

**Comment by nicolas-raoul** [comment]
How about Russian screenshots?

**Comment by ardovic** [comment]
Sure, Russian screenshots I'll provide later this day.

**Pull request closed without merging**
