### PR TITLE
Optimize imports

### LINKED ISSUE #3201: [GCI Ideas] Remove unused imports from classes
**Summary:** 

Currently, some classes contain unused imports. To improve code quality and make the app-building faster, these unused imports should be removed. 

A few files that contain unused imports are:

- SessionManager.java
- BookmarkPicturesController.java
- Bookmark.java
- CacheController.java
- CampaignsPresenter.java

Similarly, go through other classes and remove all unused imports. Unused imports show up in a dull gray color when the file is opened in android studio, unlike used imports which appear in white color.

**Would you like to work on the issue?**

Opening for GCI

### PR DESCRIPTION
**Pull request by m-alzam**
**Optimize imports**

Fixes #3201 [GCI Ideas] Remove unused imports from classes

I've optimized imports and removed unused imports with the `Code > Optimize imports` option

**Tests performed**
Gradle build finished successfully with default settings.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
@m-alzam Thanks!
Are you a CGI student?

**Comment by urbanecm** [comment]
@nicolas-raoul Yes, they are, cf https://codein.withgoogle.com/dashboard/task-instances/4981019858436096/

**Comment by yashk2000** [comment]
@m-alzam if you could remove the conflicts, that would be great. 
Rest looks good :+1:

**Comment by yashk2000** [comment]
@nicolas-raoul should I approve the task?

**Comment by m-alzam** [comment]
> if you could remove the conflicts, that would be great.
Rest looks good 👍

Are there any conflicts? I fixed them with a second commit.

**Comment by yashk2000** [comment]
Screenshot_20191205_205530

It shows three conflicting files here.

**Comment by m-alzam** [comment]
Sorry, I was using my mobile and it's not showed in mobile. I'm going to fix it

**Comment by yashk2000** [comment]
@m-alzam great :rocket:

**Comment by m-alzam** [comment]
It should be fixed

**Comment by nicolas-raoul** [comment]
Better merge this quickly, because such large refactorings become conflicting very quickly when more commits are merged.

**Pull request merged**
