### PR TITLE
Fixes 4740: Contacts permission

### LINKED ISSUE #4740: Commons app info lists "Contacts" permission, in "Not allowed" state but it should not be shown at all
I found out one of the optional permissions needed by this app, is Contacts.
Maybe if I turn it on, it will send messages to all my friends!?
So perhaps it isn't really needed anymore.
Or, have some explanation within the app...

### PR DESCRIPTION
**Pull request by vivek-gite**
**Description**

Fixes #4740 

**What changes did you make and why?**

- Removed Contacts Permission.
- Implemented Android Autofill Framework.

**App Permissions**
image

**Tests performed (required)**

Tested on Samsung A20 (API Level 30)

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
Thanks!
On what API levels have you tested the change?

**Comment by vivek-gite** [comment]
@nicolas-raoul I've tested this on API level 30 and it's working perfectly.

**Review by nicolas-raoul — COMMENTED** [review]
Great! How about API level 19? (per https://github.com/commons-app/apps-android-commons/blob/master/app/build.gradle#L163)

**Comment by vivek-gite** [comment]
Yeah, It's working fine.
apps-android-commons – C__Users_vivek_Screenshot_20220113_141922 png 13-01-2022 02_20_12 PM

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Hey @vivek-gite , thanks a lot for the PR. I am getting this error on a fresh install with Android 19 emulator:
```
Caused by: java.lang.SecurityException: caller uid 10058 lacks any of android.permission.GET_ACCOUNTS
        at android.os.Parcel.readException(Parcel.java:1465)
        at android.os.Parcel.readException(Parcel.java:1419)
        at android.accounts.IAccountManager$Stub$Proxy.getAccountsAsUser(IAccountManager.java:647)
        at android.accounts.AccountManager.getAccountsByTypeAsUser(AccountManager.java:447)
        at android.accounts.AccountManager.getAccountsByType(AccountManager.java:441)
        at fr.free.nrw.commons.auth.SessionManager.getCurrentAccount(SessionManager.java:83)
        at fr.free.nrw.commons.auth.LoginActivity.onResume(LoginActivity.java:212)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
        ```

**Comment by neslihanturan** [comment]
Hi @vivek-gite , is this PR still active:)

**Comment by neslihanturan** [comment]
Closing since it does not seemed active anymore :)

**Pull request closed without merging**
