### PR TITLE
5074: Fix cropped numbers in Leaderboard

### LINKED ISSUE #5074: Numbers cropped in Leaderboard
The first digit is not entirely visible when numbers have 4+ digits:
Screenshot_20221016-204532~2

### PR DESCRIPTION
**Pull request by RitikaPahwa4444**
**Description (required)**

Fixes #5074 

What changes did you make and why?

Fix without indentation changes:

Enabled auto-scaling of text

The numbers in the Achievements fragment are getting cropped as the app is currently using a hard-coded text size value of `9dp` and the text is of the form "xxx/xxx", that is, the circular progress bar can accommodate at most 6 digits and one '/' as of now. Increasing the size of the progress bar might disturb the nearby elements and so, I enabled auto-scaling of the text.

For defining the UI, Commons makes use of the dependency: com.dinuscxj:circleprogressbar:1.1.1 (Available [here](https://github.com/dinuscxj/CircleProgressBar.git)). 

Since this library does not handle larger numbers even in the latest version, they get cropped in the Achievements fragment. Even though we can programatically scale the text size, a more reliable method is to make use of the [official Android UI guide for autoscaling text](https://developer.android.com/develop/ui/views/text-and-emoji/autosizing-textview). Modifying the library might introduce an additional maintenance overhead for the app and so, I added a frame layout to make use of the official auto-sizeable TextView. Since the circular progress bar takes up a very small portion of the activity, the GPU considerations are negligible here. 

I also changed the unit for progress bar text size from`dp` to `sp` (for [text scaling](https://support.google.com/accessibility/android/answer/12159181?hl=en)) in the `dimens` file as this dimension would not impact any other component except the fix. 

**Tests performed (required)**

Tested ProdDebug on Redmi 5A with API level 26.

**Screenshots (for UI changes only)**

Since I haven't uploaded many pictures on the Commons app, I cannot reproduce the issue directly. However, this is how the XML design shows changes in Android Studio on adding large numbers:

achievements

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
Much easier now to read the diff, thanks a lot!

**Comment by RitikaPahwa4444** [comment]
I think the unit tests need to be updated too. Figured out from the failed check on GitHub. Will check and commit if there's any relevant change.

**Comment by nicolas-raoul** [comment]
Thanks for noticing the unit tests!

It looks great with 4 digits/4 digits.
Would you mind posting a screenshot showing how it looks with your numbers?

Screenshot_20230213-203107

**Comment by RitikaPahwa4444** [comment]
This is how it looks on my phone:
Commons_Achievements_Fragment

**Review by nicolas-raoul — COMMENTED** [review]
Thanks, the screenshot looks great!
Looking forward to the unit tests :-)

**Comment by nicolas-raoul** [comment]
Did you get a chance to check the unit tests? :-)
```
fr.free.nrw.commons.profile.achievements.AchievementsFragmentUnitTests > testHideProgressBar FAILED
    java.lang.reflect.InvocationTargetException at AchievementsFragmentUnitTests.kt:260
        Caused by: java.lang.NullPointerException at AchievementsFragmentUnitTests.kt:260

fr.free.nrw.commons.profile.achievements.AchievementsFragmentUnitTests > testSetAchievementsUploadCount FAILED
    java.lang.reflect.InvocationTargetException at AchievementsFragmentUnitTests.kt:273
        Caused by: java.lang.NullPointerException at AchievementsFragmentUnitTests.kt:273
        ```

**Comment by RitikaPahwa4444** [comment]
I am sorry for the delay; wasn't anticipating any interviews before my continuous exams when I had taken this issue up. Now that my exams have ended today, I will update you soon. Thank you for waiting for me to make the changes :)

**Review by nicolas-raoul — APPROVED** [review]
Working fine, unit tests passing. Thanks!

**Comment by RitikaPahwa4444** [comment]
Thank you for reviewing and approving the changes :)

**Pull request merged**
