### PR TITLE
Erosa issue 2874

### PR DESCRIPTION
**Pull request by Danejerosa1111**
**Description (required)**

Fixes #INSERT_ISSUE_NUMBER_HERE

What changes did you make and why?

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by sivaraam** [comment]
Hi! Looks like this PR is for an issue that has already been assigned to @arishta. Next time, make sure to ask before hand before stating to work on a issue so that we could get it assigned properly. Also, this PR seems to have a lot of changes unrelated to fixing #2874. So, that needs to be fixed before this could be reviewed. Let us know once that's done.

Also, update the description of the PR with more details as requested by the template.

**Comment by arishta** [comment]
@sivaraam This issue is a part of our software development lab project. Last week, we completed the design phase of the issue and now are discussing the implementation part. Since we are bound to move with the pace of the lab course, fixing this issue has taken a little bit of time. However, since we have reached the implementation part of this issue, we will submit a PR by the end of next week. I request you to allow us to keep working on it.
Thank you .

**Comment by neslihanturan** [comment]
Hey @arishta , please make sure you followed PR template. Also there are some conflicts, if you are still around can you please fix them so that I can test?

**Comment by sivaraam** [comment]
@neslihanturan As far as I remember #4000 has been sent as a follow-up of this PR. So, we can close this in favour of it.

As a general note, kindly avoid creating multiple PRs for the same issue unless there's a good reason to do so.

**Pull request closed without merging**
