### PR TITLE
Fix Some pins disappear after switching apps

### LINKED ISSUE #5482: Nearby: Some pins disappear after switching apps
... even though I didn't change location (using FakeGPS).

Observed on main branch at 96b2608eb11bbb3547c5b36a851beef90282d3a7, but might have started earlier. `git bisect` will most probably help.

https://github.com/commons-app/apps-android-commons/assets/99590/576a469c-ec87-4a3e-ab08-a94f1143c611

### PR DESCRIPTION
**Pull request by shashankiitbhu**
**Description (required)**

Fixes #5482 

What changes did you make and why?

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

https://github.com/commons-app/apps-android-commons/assets/126143257/b5632e35-a3fd-49eb-91a1-b5588bd8ca70

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
With this branch somehow no pins get loaded when I open the Nearby activity.
When I try with the main branch, pins load normally.

**Comment by nicolas-raoul** [comment]
Sorry for the delay!
Somehow I have not seen this in a while.
Now it seems that every time I switch apps I get more points lol

@shashankiitbhu Do you think it is still needed?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I think nearby has changed significantly since the time I made this PR. I don't think it's relevant anymore.

Do you want me to fix that Issue Instead? - More Pins appearing? , it could be due to a similar reason.

**Comment by nicolas-raoul** [comment]
The current behavior is good. Let's close this for now.

**Pull request closed without merging**
