### PR TITLE
Merge commons master to browse-commons-via-app branch

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
**Description**
I have updated my local master from commons master and merged it to a new branch taken out from browse-commons-via-app branch.

 It will update the browse-commons-via-app branch with the new code in master in main repository.

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul can you review this PR. I have updated this with master branch today.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul I am not sure about Travis fail. It is working fine in my local. Can you tell me what changes do I need to do?

**Comment by misaochan** [comment]
@ujjwalagrawal17 if you click on "Details" and scroll down, you can usually see what caused the Travis build error. In this case a test is failing. Failed Travis builds can indicate failing tests, they do not always mean the actual build is failing.

That being said, I personally think a simpler method of updating the branch would be for @nicolas-raoul or @neslihanturan to just pull from master when needed, as they have write access to the repo. :)

```
:app:kaptGenerateStubsBetaDebugUnitTestKotline: /home/travis/build/commons-app/apps-android-commons/app/src/test/kotlin/fr/free/nrw/commons/TestCommonsApplication.kt: (47, 15): Unresolved reference: Gson
e: /home/travis/build/commons-app/apps-android-commons/app/src/test/kotlin/fr/free/nrw/commons/TestCommonsApplication.kt: (47, 22): Unresolved reference: Gson
 FAILED
```

**Comment by nicolas-raoul** [comment]
I just tried, assembleDebug is successful at least.

**Comment by nicolas-raoul** [comment]
Would you mind also pulling from commons-app:browse-commons-via-app, in order to fix the conflicts?
Thanks! :-)

**Comment by ujjwalagrawal17** [comment]
I already did it and have fixed the conflicts.

**Comment by nicolas-raoul** [comment]
GitHub was warning about conflicts, but indeed doing it manually there was no conflict, thanks! :-)
And thanks for fixing the import too!
I will test now.

**Pull request merged**
