### PR TITLE
Fixed the Issue#1159 : Icon is cropped in LoginPage, while using the app in Landscape mode

### PR DESCRIPTION
**Pull request by SaiKrishna1827**
I have added FrameLayout inside RelativeLayout and ` android:fillViewport="true"` in Scrollview to fix the Issue. 

Apart from that `android:focusableInTouchMode="true"` is also added as it is blocking the whole view when the screen orientation is changed to landscape.

screenshot_20180216-182912

I have also removed `android:layout_marginTop="@dimen/small_gap"` from FrameLayout as it has no significance there.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@SaiKrishna1827 Thanks for the PR. 

Can you add screenshots for how the screen looks both in landscape and portrait mode.

**Comment by SaiKrishna1827** [comment]
**Portrait mode :** 
device-2018-02-18-224702

**Landscape mode**
device-2018-02-18-224737

**Comment by maskaravivek** [comment]
@SaiKrishna1827 can you resolve the merge conflicts. We can merge it then. :)

**Comment by neslihanturan** [comment]
Besides conflicts, I am not sure if it is necessary to merge this PR. Since according to screen size, it is still cropped. @maskaravivek do you think it is a good practice to make these changes?

**Comment by maskaravivek** [comment]
@neslihanturan  Sorry, I didn't understand this bit 

> Since according to screen size, it is still cropped.

I would prefer the fix if it fixes at least for a few screen sizes. Moreover I believe it should be possible  to fix it for all screen sizes.

**Comment by neslihanturan** [comment]
Okay then @SaiKrishna1827 after conflicts are resolved, I will merge this.

**Comment by neslihanturan** [comment]
Okay then @SaiKrishna1827 after conflicts are resolved, I will merge this. (Up:))

**Comment by neslihanturan** [comment]
Seems like this PR is sleeping, closing for now. We can always reopen it:)

**Comment by QuantumPineapple68** [comment]
Hi @neslihanturan @maskaravivek,
I would like to work on this.

**Comment by misaochan** [comment]
Hi @QuantumPineapple68 , this PR is very old and will contain a lot of outdated code. At this stage, it's better to submit your own PR than to try and fix the conflicts on this one.  You've already been assigned to the parent issue #1159 , so please feel free to submit a PR with that in the description. Thanks!

**Pull request closed without merging**
