### PR TITLE
About activity

### LINKED ISSUE #2165: App bar scrolls when it shouldn't
**Summary:** 

The toolbar scrolls when really it should be the contents of certain activities that scroll only. See GIF below demonstrating behaviour.

Most likely you will need to change files in `/res/layout/`

Places where this happens
- Achievements
- About
- other places I've forgotten to check?

Comment if you are working on this issue beforehand so we don't have two people working on the same thing. Feel free to submit one pull request that contains all changes, or many small ones. If it turns out to be kinda complex, go down the many small ones route. Do tag me (@domdomegg) if you need a review.

**Steps to reproduce:**

Open "About" activity and scroll up and down

**Screen-shots:** 

| Actual | Expected (toolbar stays fixed) |
| - | - |
| actual | expected |

### PR DESCRIPTION
**Pull request by vanshikaarora**
The issue was The toolbar scrolls when really it should be the contents of certain activities that scroll only. Which indicates that there is a slight issue with the layout files.

Fixes #2165  App bar scrolls when it shouldn't

I made changes to activity_about and activity_settings. To keep the layout of toolbar differnt from that of the remaning layout.

Tested on vivo 1713 with API level 24.

### CODE REVIEW

**Comment by domdomegg** [comment]
Thanks for the changes @vanshikaarora. I haven't read the full changes yet but I know these changes will need to be made:
- Merge master into this to resolve conflicts and ensure fix works when pushed to master.
- Remove the changes that aren't relevant to this PR (e.g. with the API, strings, some changes in aboutactivity, changes to gradle-wrapper.properties)

**Comment by sivaraam** [comment]
Just for the note, I guess the merge to local master is unnecessary is here. You could just do:

```
git fetch origin
git checkout -b new-feature-branch origin/master
```
Where `origin` is the upstream.

**Comment by nicolas-raoul** [comment]
Works great in latest alpha :-)

**Comment by vanshikaarora** [comment]
Thanks @nicolas-raoul :)

**Pull request closed without merging**
