### PR TITLE
Fixes #814 Added App Shortcuts

### LINKED ISSUE #814: Add app shortcuts
Android app shortcuts seem like a natural way to launch the app and go directly to 

* Nearby places
* Upload from gallery
* Take a picture

App Shortcut

It should be a matter of _configuration_ rather than large amounts of code - adding a `shortcuts.xml` and making sure that we can launch directly into the given activities.  I am so-so about "Upload from gallery" and think just taking a photo or going to the nearby list might be the most important.

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
Added App shortcuts for Bookmark, Settings, Explore and Reviews.

The app shortcuts are added for only the actions which can be done without the need to log in.

Fixes #814 Add app shortcuts

**Tests performed**

Tested betaDebug on Google Pixel 2 Virtual Device with API level 29 Android 10.

**Screenshots showing what changed**
Screenshot_1581054086
Screenshot_1581054102

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Actually "Nearby places" would probably be the most popular, I guess ^_^
It is the first one cited in the issue.

**Comment by madhurgupta10** [comment]
@nicolas-raoul Actually the problem is if the user is logged out then the app doesn't allow them to access nearby or upload activities.

**Comment by nicolas-raoul** [comment]
Oh about sending unlogged users to the login activity in that case? :-)

**Comment by sivaraam** [comment]
> Oh about sending unlogged users to the login activity in that case? :-)

Hopefully after educating them that Nearby can only be accessed after they log-in 🙂

**Comment by maskaravivek** [comment]
Yeah, I think Nearby would be the most popular item. I am quoting my comment from another issue where we discussed how the app should behave for not logged in users. 

https://github.com/commons-app/apps-android-commons/issues/1781#issuecomment-410423090

Probably we can start with the shortcuts @madhurgupta10 has added and then create a separate issue for modifying the login flow to accommodate for other shortcuts.

**Comment by madhurgupta10** [comment]
@maskaravivek Yes, I can work on the shortcuts which need login permission by creating a separate issue. I also think it is necessary to remove Review shortcut from this PR due to the recent change #3390

**Comment by madhurgupta10** [comment]
Screenshot_1581492636
Screenshot_1581492665

**Comment by ashishkumar468** [comment]
Hi @madhurgupta10 , are we adding the shortcuts by default?

**Comment by madhurgupta10** [comment]
@ashishkumar0207 I am sorry but I didn't understand your question 😅

**Comment by ashishkumar468** [comment]
@madhurgupta10 I wanted to know when exactly are we adding the app-shortcuts?

**Comment by madhurgupta10** [comment]
@ashishkumar0207 As soon as the user installs the updated app the shortcuts can be added by dragging and dropping from the list.

**Comment by madhurgupta10** [comment]
@maskaravivek Any updates on this PR?

**Comment by ashishkumar468** [comment]
@madhurgupta10  the PR looks good to me, can you attach a screenshot from one of the pre-oreo devices, AFAIR, shortcuts behavior/implementation had changed from the OREO devices

**Comment by madhurgupta10** [comment]
@ashishkumar0207 Sure I will add screenshots

**Comment by madhurgupta10** [comment]
Android 7.1

Screenshot_1582291009
Screenshot_1582291034

**Comment by sivaraam** [comment]
Excuse me for chiming in. Would it be possible to have a white background in the shortcut icons for the pre-Oreo devices just like the ones shown the PR description. I ask this because plain black icons [does not play well](https://github.com/commons-app/apps-android-commons/issues/868) with dark backgrounds.

**Comment by madhurgupta10** [comment]
@sivaraam I am unable to find the **explore** logo in the clip art, maybe it is removed or updated, can u confirm. I have fixed the other logos
Screenshot_1582376034

**Comment by sivaraam** [comment]
@madhurgupta10 Sorry, but I couldn't get what you're asking. Anyways, I could find the explore icon (without any background) at [app/src/main/res/drawable/ic_explore_24dp.xml](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/drawable/ic_explore_24dp.xml) if that's what you're asking.

Also, IIUC the app shortcuts and the pinned shortcuts would be available only in Android 8+ devices. Would it be possible to provide a way to add the pinned shortcuts on pre-Android 8 devices? I ask this as I use [an app](https://github.com/mtotschnig/MyExpenses) which allows me to add pinned shortcuts for specific actions via its Settings screen even though I use it on an Android 5 device. I find that very useful.

**Comment by madhurgupta10** [comment]
> @madhurgupta10 Sorry, but I couldn't get what you're asking. Anyways, I could find the explore icon (without any background) at [app/src/main/res/drawable/ic_explore_24dp.xml](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/drawable/ic_explore_24dp.xml) if that's what you're asking.
>
> Also, IIUC the app shortcuts and the pinned shortcuts would be available only in Android 8+ devices. Would it be possible to provide a way to add the pinned shortcuts on pre-Android 8 devices? I ask this as I use [an app](https://github.com/mtotschnig/MyExpenses) which allows me to add pinned shortcuts for specific actions via its Settings screen even though I use it on an Android 5 device. I find that very useful.
1. I mean to say that, to get the white background I need to generate the adaptive icons, I was using the Android Studio tool to get them but I was unable to find this specific logo.
Capture


2. Yes, it is possible, I guess it should be better if I do it in a separate PR.

**Comment by maskaravivek** [comment]
@madhurgupta10 Can you try one of these. 

https://blog.klinkerapps.com/android-o-adaptive-icons/
https://easyappicon.com/

I am sure you would find an online adaptive icon generator. It would be great if we could have white backgrounds for all shortcuts. 

I really appreciate your efforts in bringing this feature to completion. :)

**Comment by sivaraam** [comment]
> I mean to say that, to get the white background I need to generate the adaptive icons, I was using the Android Studio tool to get them but I was unable to find this specific logo.

Ah, I get it now. To add to the suggestions of @maskaravivek, I suppose you could try using the [explore icon image](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/res/drawable/ic_explore_24dp.xml) by choosing the asset type as "Image" instead of "Clip Art" in the tool.

> Yes, it is possible, I guess it should be better if I do it in a separate PR.

That would be better, indeed 🙂

**Comment by madhurgupta10** [comment]
@maskaravivek @sivaraam Thanks for the help, fixed!
Screenshot_1582665369

**Pull request merged**
