### PR TITLE
Fix for issue #701

### PR DESCRIPTION
**Pull request by mebr1416**

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @mebr1416 , thanks for submitting this! Sorry I wasn't in time to post on #701 , but I personally preferred your first screenshots that used a Toast instead of an AlertDialog. This might be a personal preference, but I feel that AlertDialogs are a bit too disruptive for this, where we want something displayed to the user but it's not really an "Alert! Action needed now!" kind of thing. :) That's why I'd prefer a Toast (at the bottom of the screen, exactly like your first screenshot on #701 ). Possibly make the Toast timer long, so the user would have time to read.

Would anyone else like to weigh in?

I like the text in your current PR. There are merge conflicts that need resolving, though.

**Comment by janpio** [comment]
The user specifically asked for something to happen by tapping the (i), so it going away automatically wouldn't feel right to me. I often tap stuff, am then sidetracked by the real world, and come back 15 minutes later... 

So I prefer the Alert here. 

(Although a kind of tooltip would also be fine, a kind of speech bubble coming from the (i) - but that is just cosmetics and non standard)

**Comment by mebr1416** [comment]
I agree with @janpio. Plus Alert dialogs are just easier to manage for the issue you stated. An alert dialog can also be quickly dismissed by the user....On the conflicts, I'll resolve them.

**Comment by misaochan** [comment]
Good point, guys. Happy to merge after the conflicts are resolved. :)

**Comment by mebr1416** [comment]
I've made the necessary changes but still facing a conflict. Any ideas?

**Comment by misaochan** [comment]
@mebr1416 I've resolved the conflicts via the GitHub "Resolve conflicts" option (it can be very handy for resolving simple conflicts like this one, some documentation [here](https://help.github.com/articles/resolving-a-merge-conflict-on-github/)). Will merge shortly if the Travis build succeeds.

**Comment by misaochan** [comment]
Merged, thanks @mebr1416 . :) We'd like to add your name to the CREDITS.md, if you're okay with that. If so, what name would you prefer us to use?

**Comment by mebr1416** [comment]
Josephine,

First Name: Bruke Mekuria
Last Name: Mulugeta

Thank you for asking.

Bruke

**Pull request merged**
