### PR TITLE
Fixed issue #1395

### LINKED ISSUE #1395: Map orientation button gets overlapped by recenter button
The directions symbol appears when the map is zoomed in or rotated , that symbol is overlapped by the recenter button.

alt link

**Expected behavior:** 

The directions symbol not appearing at all or the recenter button has to be moved down

**Device and Android version:** 
Android 6.0.1

### PR DESCRIPTION
**Pull request by wanderlustyc**
## Description

Fixes #1395 

Re-submitting PR #1422

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks for PR @wanderlustyc it is always good to share screen shots with UI related issues. Here is my test result:
device-2018-04-04-103503
Doesnt look very natural

**Comment by misaochan** [comment]
The screenshot was posted in #1422 , so I think it did work for their screen. It's likely that the fixed dimensions did not translate well to a larger screen size though, so that does need to be fixed. :)

**Comment by neslihanturan** [comment]
```
.compassMargins(new int[]{12, 24, 0, 0})
.compassGravity(Gravity.START)
```
or 
`.compassMargins(new int[]{0, 150, 26, 0})`
Worked nice on big screens, what about your screen?

**Comment by wanderlustyc** [comment]
@neslihanturan According to MapboxMap API the margins are in pixels. I think that's why it behaves differently on different devices. If we want to stick to this design (with compass button below the recenter button) we definitely need to get the device's display metrics and the recenter button's layout parameters at runtime. Or, maybe easier, we can move the compass button to some other corners of the screen. What do you think?

**Comment by neslihanturan** [comment]
Two bottom corners are not usable due to bottom sheets, but I think it can be ok if bottom sheets overlap c ompass icon. In this case I would suggest bottom left corner.
Left top corner is also not usable since they should look symmetrical in this case. 

Bottom left corner seems like the best solution if bottom sheets overlap compass icon, otherwise we should go through hard way unfortunately.

**Comment by wanderlustyc** [comment]
@neslihanturan I tried the bottom-left corner and fortunately, the bottom sheets do overlap. Seems that we can go with bottom-left.

**Comment by neslihanturan** [comment]
Great @wanderlustyc :)

**Pull request merged**
