### PR TITLE
Converted nearby list to recycler view

### PR DESCRIPTION
**Pull request by psh**
Changes on this PR

* Converted the "nearby" list to use a `RecyclerView` utilizing the excellent ["Renderers" library](https://github.com/pedrovgs/Renderers) (Apache 2.0 license).
* Unit tested the new list implementation using [Robolectric](http://robolectric.org/),
* Ran static code analysis on the "nearby" package and cleaned up the small issues noted.
* Deleted dead code.

This PR covers one step for Issue #743 (replace listviews)

### CODE REVIEW

**Comment by misaochan** [comment]
Looks good to me! Assuming the others are okay with the new library? @whym @nicolas-raoul

**Comment by nicolas-raoul** [comment]
At 16 KB it sounds acceptable :-)
https://mvnrepository.com/artifact/com.github.pedrovgs/renderers/3.3.0

**Comment by whym** [comment]
> At 16 KB it sounds acceptable :-)
> https://mvnrepository.com/artifact/com.github.pedrovgs/renderers/3.3.0

Does this number include the size of its transitive dependencies?

Anyway, when I checked the change in the size of the release APK, it was from 19350346 to 19354766 - so size-wise it seems actually fine.

**Comment by misaochan** [comment]
Thanks guys! I tested this and it works well for me. Will merge soon if no one has any issues with it.

**Pull request merged**
