### PR TITLE
Upload bottom card retains title even on rotation

### LINKED ISSUE #2369: Rotating screen erases title
1. select image for upload
2. enter title
3. rotate screen
4. title field is now empty 😱

even on the categories selection screen, rotating takes you back to step 1.

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Title written in edit text does not vanishes now on rotation**

Fixes #2369 Rotating screen erases title

### Changes made

- On changing screen orientation saved the data written in edit text to `savedInstanceState` 
- When the activity is recreated retrieved the `editText` text from `savedInstanceState` 
- Updated the EditText with the new text retrieved

**Tests performed (required)**

Tested on vivo 1713 with API level 24

ezgif com-video-to-gif 7

### CODE REVIEW

**Comment by maskaravivek** [comment]
@vanshikaarora The basic thing works for me but there's still an issue. If I add a description in multiple languages, only the first description is retained. Can you try fixing that too?

**Comment by vanshikaarora** [comment]
>@vanshikaarora The basic thing works for me but there's still an issue. If I add a description in multiple languages, only the first description is retained. Can you try fixing that too?

Sure thing :)

**Comment by vanshikaarora** [comment]
A gentle reminder for review :)

**Comment by maskaravivek** [comment]
> @vanshikaarora The basic thing works for me but there's still an issue. If I add a description in multiple languages, only the first description is retained. Can you try fixing that too?

Have you fixed this? I was hoping to have it fixed in the same PR. :)

**Comment by vanshikaarora** [comment]
@maskaravivek I am sorry for that :(
I have raised another PR [here](https://github.com/commons-app/apps-android-commons/pull/2516) that solves both the issues. 
Kindly review :)

**Comment by maskaravivek** [comment]
@vanshikaarora Is this PR not needed then?

**Comment by vanshikaarora** [comment]
>@vanshikaarora Is this PR not needed then?

Not needed

**Pull request closed without merging**
