### PR TITLE
Changed Facebook Icon color on About activity

### LINKED ISSUE #4599: Change Facebook Icon color on About activity
**Summary:** 

In the About activity of the app, the Facebook icon is black. If it were changed to the official color of Facebook, it would enhance the user interface.

May be Fixed on: #4600.

**Steps to reproduce:** 

Click More > About.

**Device and Android version:** 

Device Model: Realme XT
Android Version: Android 9.0 (Pie).
Stock from the Manufacturer.
 
**Commons app version:** 

Version: 3.0.2-debug-master.

**Screen-shots:** 

**Current About activity:**

WhatsApp Image 2021-08-31 at 9 10 48 PM

**Would you like to work on the issue?**

Yes, I would like to work on this Issue.

### PR DESCRIPTION
**Pull request by jaimehta1912**
**Description**

Fixes #4599.

Changed the Facebook Icon tint in About activity to enhance and improve the user interface.

**Tests performed**

Tested 3.0.2-debug-master on Realme XT with API level 28.

**Screenshots**

**Current About activity:**

WhatsApp Image 2021-08-31 at 9 10 48 PM

**Improved About activity:**

WhatsApp Image 2021-08-31 at 9 10 48 PM (1)

### CODE REVIEW

**Comment by jaimehta1912** [comment]
@madhurgupta10 @prtksxna @whym @mikehc Please review my  PR

**Comment by nicolas-raoul** [comment]
Thanks for suggesting!
This color is on purpose, though, to improve coherence between the 3 icons.

**Comment by madhurgupta10** [comment]
@jaimehta1912 It seems like you have configured wrong git username/email. Do make sure that you are using your own username/email when adding commits.

image

If you don't know how to modify it, here is a good article - https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

**Comment by jaimehta1912** [comment]
@madhurgupta10 Yes, Sorry for the mistake ,I will rectify it soon.

**Pull request closed without merging**
