### PR TITLE
Fix: Location update in nearby activity

### LINKED ISSUE #973: "No nearby places found" in NearbyActivity (pre-release)
While currently testing master, after loading NearbyActivity, I get the "No nearby places found" error. Tapping refresh does not solve the problem.

This happens consistently on my phone (Samsung Galaxy S7 running Android 7.0). I am never able to get the Nearby list/map on my phone in the current master. I have GPS on, which is currently displaying appropriately in other apps (E.g. Google Maps, Zomato, Foodora).

On an emulator (Nexus 7 API 25), Nearby works only after sending the coordinates through, then closing the app manually and re-launching it. Refresh button does not work. Switching activities does not work.

This used to happen occasionally for me on our current Play Store beta version, but the prevalence seems to have increased significantly on our current master. We will probably have to delay our planned release until the issue is solved.

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #973.

### CODE REVIEW

**Comment by maskaravivek** [comment]
Task `:app:connectedBetaDebugAndroidTest` is failing on travis, but the same task runs for me locally. Seems travis is facing some issue in connecting to the device.

**Comment by misaochan** [comment]
Experiencing some issues with this PR, mentioned it in the review.

**Comment by maskaravivek** [comment]
@misaochan  As I am listening for location update, the refresh happens every time location changes. There are two ways to handle it. 
1. Lock the view after it has been loaded once. 
2. Refresh the list only if the location changes significantly(say 100m or more). This approach can be beneficial as this would result in the list being updated automatically when the user is travelling.

**Comment by misaochan** [comment]
I think option 2 would be preferable.

I do wonder how other apps handle this. Do we necessarily need to couple user location updates with the map refreshing? As we are already displaying items within a fairly large radius. 

Regardless, I think if we implement option 2 with, say, 200m and that fixes the problem, we can go ahead with merging this and doing the release, then discuss this further in the issue. :)

**Comment by nicolas-raoul** [comment]
I believe that in some other apps, a pin representing you moves with your location. If the pin exits the screen, you move the app and new objects load at that time. Some apps have a "recenter" button, which is useful when you don't know anymore where you are.

**Comment by maskaravivek** [comment]
Considering @nicolas-raoul comment should we lock the view for now and then implement the pin moving thing later?

**Comment by misaochan** [comment]
Yeah, I would be good with locking the view, as long as it refreshes when the refresh button is tapped and onResume.

**Comment by maskaravivek** [comment]
@misaochan Have incorporated the changes. Will update the list only on clicking refresh button or activity `onResume`

**Comment by misaochan** [comment]
Works well for me. I have taken the liberty of resolving the conflicts so we can merge. Great job @maskaravivek , thanks!

**Pull request merged**
