### PR TITLE
Nearby places icons localization bug fix

### PR DESCRIPTION
**Pull request by Rulino**
## Title (Nearby places icons localization bug fix)

Fixes #{Icons in Nearby list showing up when phone is set to English but not when set to Czech #1852 } 

## Description (required)

Fixes #{Icons in Nearby list showing up when phone is set to English but not when set to Czech #1852}

Place.java: Enum Label was changed from using English word identifiers to QID identifiers. These are obtained from link sent within the query in NearbyPlaces.java. Few identifiers were added to the enum but still there are plenty of them missing and showing as unknown but they are actually set. New issue should be opened to add more identifiers to the enum in the future. 

## Tests performed (required)

Tested on Samsung Galaxy J5, API 25

## Screenshots showing what changed (optional)
 
**Nearby places for English locales:**
screenshot_20181023-083714

**Nearby places for Slovak locales before fix:**
screenshot_20181023-083806

**Nearby places for Slovak locales after fix:**
screenshot_20181023-083819

### CODE REVIEW

**Comment by Rulino** [comment]
Can somebody review this request?

**Comment by misaochan** [comment]
Hi @Rulino , sorry about the wait. @neslihanturan usually does PR testing, and I think she is away at the Netherlands techstorm at the moment. :) Will check in again with you soon...

**Comment by misaochan** [comment]
Thanks for testing, @domdomegg . :)

Happy to merge after the requested changes are made.

**Comment by domdomegg** [comment]
Test results: all tests passed

Tested home, nearby, in en-GB
Tested home, nearby, in cs-CZ

`2.8.5-debug-pr-1947~492ea591` on `Samsung Galaxy S6` with API level `25`.

Ready to merge.

**Pull request merged**
