### PR TITLE
Potential step 1 prototype for issue #175

### LINKED ISSUE #175: Custom picture(s) selector which indicates what pictures have been uploaded already
Users can upload images from the app by tapping the "+" button of the main activity and tapping the "gallery" button which calls Android's built-in picture selector.
This issue would introduce a custom picture selector, which shows whether each picture has been uploaded to Commons already or not.
This is useful because after a long trip it is difficult to remember what pictures you have uploaded already.

The custom selector would show a gallery of thumbnails where already uploaded pictures are faded out and have a [Commons logo](https://commons.wikimedia.org/wiki/File:Commons-logo.svg) overlay.

# Sketch UI

New button to select the custom picture selector:

commons-custom-picker

Custom selector:

pictures-browser-with-commons-overlay svg

In the example above, you can see that I have already uploaded the 4 pictures on the right, but not the two pictures on the left. Seeing this, I can decide whether I want to upload the first picture or not, given I have arguably already uploaded a better picture (with less cars).

# Requirements
- Show thumbnails.
- Let the user switch to another folder.
- Scrolling must be smooth, so that I can skip 100 pictures without waiting much
- Show differently images that have been uploaded already.
- To check whether a picture has been uploaded already or not, use the API (see below), as pictures may have been uploaded via a different device, or the user may have uninstalled/reinstalled the app.
- Results from the API must be cached, so that when I open the picture selector again the same API requests are not called again.
- API calls must not prevent scrolling (asynchronous).

# Bonus
Would be nice, but not strictly required:
- Long-press to preview the image fullscreen.
- Also show a "<strike>GPS</strike>" overlay icon for pictures that do **not** have EXIF latitude/longitude.

# Strategies
- You could reuse an open source gallery like https://github.com/nostra13/Android-Universal-Image-Loader which is reused by many applications, but please make sure that:
  - The library's license is compatible with our app's license.
  - Our app's APK size does not grow by more than 1 MB (in other words, the library is not too big).
  - The library is either maintained, or has less than 10.000 lines of code, reasonably well-written.
  - It allows the customization described above.
- Or you could implement a simple picture selector from scratch (it might be the only solution if no suitable library is found).

# API

Commons has a simple API to check the presence or not of a file, it works by sending the SHA1 checksum to the URL `https://commons.wikimedia.org/w/api.php?action=query&list=allimages&format=xml&aisha1=<put SHA1 here>`. Examples:

- https://commons.wikimedia.org/w/api.php?action=query&list=allimages&format=xml&aisha1=579330b110c605f7984f7ef6161e3ef8a417ef96 : We see that this image has been already uploaded.
- https://commons.wikimedia.org/w/api.php?action=query&list=allimages&format=xml&aisha1=da39a3ee5e6b4b0d3255bfef95601890afd80709 : We see that this image has not yet been uploaded.

The API is quite slow (around 1 second per request), which is why caching and asynchronous loading is needed. The selector must be usable even if Internet is extremely slow or disconnected.

### PR DESCRIPTION
**Pull request by vinayak0505**
**Description (required)**
https://photos.app.goo.gl/zyovRiBvaK8jXXSbA

as you can see in this video you can now upload the image using Imagepicker, for know it does not uploads it just get data for images which are selected,
store them in a database(made using room and the process happens in the background),
then when you open it again the data is fetch from that database(again room and background thread),
so the images which are in database , the user will not be able to select them again and a toast will appear(we can change that text - easy),
the images turn little darker for disabled in video but in final version i have made them litter as needed,
Please please take some time out and check it, 
I didn't made the upload part because the code is little messy and it is difficult to understand and also don't want to disturb other feature, some help with the mentor, then I think I might able to do it,
the table name is "upload_images" so therefor I also have to change the database version to 8 , i think there is no migration file even though no changes have made to previous schema so it should be a problem,
also I have added "ImagePicker: as module and added a feature as mention in a commit by me,
I have explained every thing i have did i think still if something left you found the code disturbing let me know

**Tests performed (required)**
I didn't add testing method but i have done manual testing from my side
If you think the idea where i am going with this is fine then let me know ill added the testing for database also

**Screenshots (for UI changes only)**

Screenshot_20210406-010148

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
It is great to see your enthusiasm and quick implementation :-)

As you know, issue 175 is far from fixed, though:
1) Calling the Commons API is necessary, because many users transfer pictures across devices, reinstall the app, etc, so we have to check the API. Your idea of storing upload status upon local upload is great, I suggest checking using a combination of both approaches, that will show a large part of the overlays faster.
2) We need a solution where overlay icons can see set (Commons logo overlay, in the future a "GPS" overlay, etc). I guess that feature could be added to the ImagePicker library.

By any chance, are you eligible/interested in participating in GSoC? If so, please have a look at how to apply and how we choose candidates: https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md As you can see, we choose the students who submitted the best [bugfix](https://github.com/commons-app/apps-android-commons/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Aassigned+-label%3Adebated+label%3Abug), that's important.

If using your ImagePicker fork for a GSoC, the biggest task would be to modify your ImagePicker fork to allow 1) asynchronous disabling 2) overlay icons. That sounds doable in the length of a GSoC, given your skills.

Cheers!

**Comment by vinayak0505** [comment]
can you elaborate point 1 and 2 
what i have understand from reading this is
solution for 1 - yes every one upload across the devices but the pictures would be very different so even making a common API would be useless and also it would be impossible as different device would have different path for each stored image , so keeping the database at the local site would me most optimized way(this is what i think and i can be completely wrong)

solution for 2 - you just want to add an image to each disabled image and that image may change. Right??

Yes i am eligible/interested in participating in GSoC.

**Comment by nicolas-raoul** [comment]
# About point 1

Let's say I take 100 good pictures with an Android smartphone. I upload 20 of the pictures to commons.wikimedia.org, then I move all pictures to my Android tablet (because it is more comfortable for instance). On the Android tablet, the app must show disable the 20 pictures that already exist on Commons. As you say the different device has a different storage path, but the picture's SHA1 checksum is the same on all devices.

# About point 2

See https://tortoisehg.readthedocs.io/en/latest/explorer.html#overlay-icons for an example of overlay icons. Overlay icons are small symbols displayed at the bottom-left of a file's representation. There can be several for one file. They can also be thought of as "badges".

**Comment by vinayak0505** [comment]
point 1 - as we have already created a table for storing the table , if backend is ready then creating a retrofit API would take much time then well also add a repository class so that database can be updated while app is not running ,main Problem would be we have to change to storage path to picture's SHA1, honestly i don't now how this is works so ill need some time to do some R&D on it,
Point 2 - okay no issue ill create a new feature for this in imagepicker library so that we can pass an image an it would be loaded using glide(do image type can be Int or URL as well)
ill take some time as i have to fix an issue first so that i can get selected for GSoC, so till then i anyone want's to add something , please feel free to copy my repo.

**Pull request closed without merging**
