### PR TITLE
Add in-app screenshots for Polish pl-PL

### PR DESCRIPTION
**Pull request by divadsn**
See issue #960.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
The building picture is really great!

About the restaurant picture: Is there any way you could take a picture where the subject is not in the dark, and not with a car hiding part of it? That would be wonderful :-)

About gallery.png and drawer.png: We have a problem with many of our users uploading screenshots of proprietary apps, which is contrary to Wikmedia rules for copyright reasons. So in general we really want to discourage people from uploading screenshots. Even though technically riot.im and rocket.chat are open source, most people don't know this, so by seeing this they would think "Oh it is OK to upload screenshots let's do that and screenshot all of my apps".
So, sorry about that, but would you mind taking screenshots of gallery.png and drawer.png after scrolling to hide screenshots and show some picture, preferably centered on your building picture? Thanks a lot! :-)

**Comment by divadsn** [comment]
@nicolas-raoul there was a problem that I had to upload a picture twice as the app crashed once when I was in the categories section because my networks were switching too fast.

**Comment by divadsn** [comment]
I couldn't find another photo of the restaurant in my photo library and couldn't find any other photo of another restaurant.

**Comment by nicolas-raoul** [comment]
Feel free to take picture of any other public building, for instance a
library, a town hall, a community center, etc.
Or even any bridge or statue :-)

**Comment by divadsn** [comment]
I found a picture of a church in my photo library, hope it fits well.

**Comment by divadsn** [comment]
The Travis-CI build is failing due to #1059

**Comment by nicolas-raoul** [comment]
Wonderful picture, thanks for your patience!
Yes, don't worry about Travis and Codacy.

**Pull request merged**
