### PR TITLE
Pasted text should have fonts unified (for Caption/Description)

### LINKED ISSUE #4514: Pasted text should have fonts unified
The fonts should become the same upon pasting. (We just pasted three words and added two words on the back.)
Latest beta.
All five words should be like the final two words.

### PR DESCRIPTION
**Pull request by dado1111**
**When adding picture and asking for Caption/Description, pasted text isnt formatted**

Fixes #4514

I created a subclass of "TextInputEditText" called "PasteSensitiveTextInputEditText", which has its own attribute saved in attrs.xml named "allowFormating", and so you can add atribute directly in xml file and decide whether to allow or forbid pasted formatting.

Given "PasteSensitiveTextInputEditText" can decide, when Paste option is selected from context menu of Cut/Copy/Paste
and interfere with pasting in two ways:
1.) API >= 23
     - uses "Paste it as a simple text" instead of regular Paste, 
2.) API < 23
     - after pasting it extracts given text, turns into String and sets it back on
     - then just moves cursor to front (after settingText its stuck at the start)

PS: also i could just use more general name for PasteSensitiveTextInputEditText and later on maybe some other 
attributes would come to play, but for now i guess this is fine and simple solution.

PS*: i did not change any other TextInputEditText-s to my new PasteSensitive class, so text formatting upon pasting is only disabled for "row_item_description.xml" file which contains both Caption and Description as one component (which means: pasting text, when searching for category for example will not remove formatting for now)

### CODE REVIEW

**Comment by madhurgupta10** [comment]
> Yes, i can.
> 
> I did not do it in cotlin, because i saw one more test in java, dont know which one, so i decieded to keep it in java, but can remake it

@dado1111 Converting the test to kotlin using `Android Studio` should be okay, let us know if you face any issue :)

**Comment by dado1111** [comment]
Well, i just converted TestClass to Kotlin and now it doesnt go through any check :/

**Comment by dado1111** [comment]
Well okay, now im unsure.

 I tried to include more lines of code in my test, but even tho id say my test does cover them, the report shows those lines as misses - as if not covered. Is there any possibility to solve this? I am not intending to get 100% coverage, but there are definitely misses, which my test covers.

Anyway, i think this can be merged even with these subtle problems.
Would like to hear your opinion on this also :)

**Review by neslihanturan — APPROVED** [review]
Thanks for fixing the reviews @dado1111 :)

**Pull request merged**
