### PR TITLE
Fixes to some errors found by lint ("Inspect code" on Android Studio)

### PR DESCRIPTION
**Pull request by whym**
@misaochan: please take a look at the changes in NearbyPlaces.java.

See also #171.

### CODE REVIEW

**Comment by misaochan** [comment]
Tested NearbyPlaces.java and it works well for me.

**Comment by whym** [comment]
Thanks - I was not completely sure if the duplicate was intentional or not.

**Comment by misaochan** [comment]
Yeah, it wasn't intentional, I'd just overlooked it. :)

BTW, would you like to be added to the credits.md file? I can add either your username or name, whichever you prefer.

**Comment by whym** [comment]
Thanks for the offer. I would prefer "Yusuke Matsubara".

**Comment by misaochan** [comment]
Done :)

**Pull request merged**
