### PR TITLE
Share file with camera using cache and FileProvider (for API 24)

### PR DESCRIPTION
**Pull request by whym**
Attempted fix for #457.

EDIT: since this PR became rather long, here is a quick summary.
* What this is about: it changes the way files shared between the camera and the app, and the timings of when storage permission is requested.
* What needs to be done: testing photo-capturing and sharing from the gallery on (ideally, physical) devices with across different versions of Android, and code review of the rather large changes of [ShareActivity.java](https://github.com/commons-app/apps-android-commons/pull/727/files#diff-a83ce591f5495a6097b96f65d03c9a4c) and other files.

API 22 (emulator), API 23 (real device) and API 25 (emulator) have been covered my (manual) tests - taking and sharing a photo, sharing from gallery and EXIF extraction.

Anyone willing to do it for API 24 and API 26 preferably on physical devices?

### CODE REVIEW

**Comment by misaochan** [comment]
It works well all the way through taking the camera photo and confirming it. But in ShareActivity, when I grant the necessary permissions to access storage as usual, this error will always occur:

```
06-08 18:07:22.890: E/AndroidRuntime(2983): Process: fr.free.nrw.commons, PID: 2983
06-08 18:07:22.890: E/AndroidRuntime(2983): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
06-08 18:07:22.890: E/AndroidRuntime(2983): 	at fr.free.nrw.commons.upload.FileUtils.getDataColumn(FileUtils.java:108)
06-08 18:07:22.890: E/AndroidRuntime(2983): 	at fr.free.nrw.commons.upload.FileUtils.getPath(FileUtils.java:76)
06-08 18:07:22.890: E/AndroidRuntime(2983): 	at fr.free.nrw.commons.upload.ShareActivity.getFileMetadata(ShareActivity.java:384)
06-08 18:07:22.890: E/AndroidRuntime(2983): 	at fr.free.nrw.commons.upload.ShareActivity.onRequestPermissionsResult(ShareActivity.java:337)
```

**Comment by misaochan** [comment]
To get that error, you need to set the target SDK to 25 (which I did locally after pulling your branch).

**Comment by whym** [comment]
Yeah that was as far as I tested. I should have mentioned, sorry.

Could you try it again? The new commit should make it significantly closer to solution. At least I was able to use camera and upload a picture from an API 25 device. (*)

It changes the part of the code I was not familiar with. More tests are welcome. I suspect there might still be bugs related to permission and/or EXIF/metadata and/or older devices.

(*) To be exact it was rejected by abuse filter, which is almost "done" from the app's perspective. https://commons.wikimedia.org/w/index.php?title=Special:AbuseLog&wpSearchUser=Whym+test0

**Comment by misaochan** [comment]
@whym This works all the way to complete upload in my API 24 real device, nice. :)

Testing on API 23 (emulator) seems to still be problematic though. I can take the picture, but cannot confirm it in order to move on to the title/desc screen. It doesn't crash, but is stuck in the camera confirmation screen.

Error report:

```
06-09 17:04:25.738: E/ContributionController(4285): Could not create file: /storage/emulated/0/Commons/images/1496991865737.jpg
06-09 17:04:25.738: E/ContributionController(4285): java.io.IOException: open failed: ENOENT (No such file or directory)
06-09 17:04:25.738: E/ContributionController(4285): 	at java.io.File.createNewFile(File.java:939)
06-09 17:04:25.738: E/ContributionController(4285): 	at fr.free.nrw.commons.contributions.ContributionController.reGenerateImageCaptureUriInExternalStorage(ContributionController.java:44)
06-09 17:04:25.738: E/ContributionController(4285): 	at fr.free.nrw.commons.contributions.ContributionController.startCameraCapture(ContributionController.java:74)
06-09 17:04:25.738: E/ContributionController(4285): 	at fr.free.nrw.commons.contributions.ContributionsListFragment.onOptionsItemSelected(ContributionsListFragment.java:123)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2314)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3029)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.view.View.performClick(View.java:5198)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.view.View$PerformClick.run(View.java:21147)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.os.Handler.handleCallback(Handler.java:739)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.os.Looper.loop(Looper.java:148)
06-09 17:04:25.738: E/ContributionController(4285): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-09 17:04:25.738: E/ContributionController(4285): 	at java.lang.reflect.Method.invoke(Native Method)
06-09 17:04:25.738: E/ContributionController(4285): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-09 17:04:25.738: E/ContributionController(4285): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 17:04:25.738: E/ContributionController(4285): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-09 17:04:25.738: E/ContributionController(4285): 	at libcore.io.Posix.open(Native Method)
06-09 17:04:25.738: E/ContributionController(4285): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-09 17:04:25.738: E/ContributionController(4285): 	at java.io.File.createNewFile(File.java:932)
06-09 17:04:25.738: E/ContributionController(4285): 	... 28 more

```

**Comment by whym** [comment]
Doesn't it happen with master? Anyway, I seem to reproduce the issue and  I'll try solving it, too.

**Comment by whym** [comment]
I decided to try eliminating the use of external storage as much as possible. Tested with:
API 22 (emulator)
API 23 (real device)
API 25 (emulator)

Please make sure resetting permission settings before testing.

**Comment by whym** [comment]
@misaochan 
> I can take the picture, but cannot confirm it in order to move on to the title/desc screen.

I have been working on this with the patch I just have updated. I still see a similar issue, but it proceeds after waiting one minute or two. Is it the same for you? For me it only happens with debug builds and API 23. (Release builds are fine for API 23 too.)

**Comment by whym** [comment]
Travis failed with this error, but I couldn't reproduce it on my machine.

 > Execution failed for task ':app:transformClassesWithDexForDebug'.
 > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/travis/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar' to '/home/travis/build/commons-app/apps-android-commons/app/build/intermediates/pre-dexed/debug/guava-19.0_4125dcfa4f861863282b818bae4a32a93b7a0016.jar'

**Comment by misaochan** [comment]
I restarted the Travis build, but it throws the same error. I agree, builds fine on my machine as well. :/

What is the easiest way of testing a release build with the emulator? Do I actually need to sign it and load it manually into the emulator?

**Comment by whym** [comment]
> actually need to sign it and load it manually into the emulator

This is how I did it.



2017/06/11 午後6:26 "Josephine Lim" <notifications@github.com>:

I restarted the Travis build, but it throws the same error. I agree, builds
fine on my machine as well. :/

What is the easiest way of testing a release build with the emulator? Do I
actually need to sign it and load it manually into the emulator?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/commons-app/apps-android-commons/pull/727#issuecomment-307616721>,
or mute the thread

**Comment by whym** [comment]
Actually, the issue with API 23 doesn't happen for me anymore with the latest set of commits. Hopefully for you, too?

**Comment by misaochan** [comment]
Oh, cool, the debug build on API 23 works for me now, too. :)

Would anyone else like to test this if possible? Sorry for the long merge delay @whym , just being a bit cautious since this is core functionality.

**Comment by misaochan** [comment]
I will just take a leap and merge this. :)

**Pull request merged**
