### PR TITLE
Fix#1650 Category search does search for my whole string

### LINKED ISSUE #1650: Category search does search for my whole string
1. I typed "apple"
2. I got the results for "app"
3. The "MEDIA" tab is OK, though, showing pictures of apples.
4. Adding another letter then removing it solves the problem

Difficult to reproduce. 

screenshot_20180621-221817

### PR DESCRIPTION
**Pull request by DeepaMalani**
**Description (required)**

Fixes #1650 {Category search does search for my whole string}

What changes did you make and why?
Here is the reason for this issue :

When data fetching starts for half string and immediately user changes the string before finishing the fetching for half string, it generates the wrong results.  

I added below lines to solve this issue
1. Added one boolean variable and the value for this variable will be **true** when data fetching will start.
Set this variable's value **false** once fetching is done.

2. Fetch results for full string once data fetching for the previous half string is done. 

**Tests performed (required)**

I did manually testing.

**Screenshots showing what changed (optional - for UI changes)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks for the pull request!
I can not test right now, but hopefully someone will check soon :-)

**Comment by vvijayalakshmi21** [comment]
Hi,
I observed the same issue for Media as well on the latest app version on Google Playstore. 
Are these changes merged and available in that version?

**Comment by macgills** [comment]
@DeepaMalani there are conflicts which need to be resolved and potentially a simpler way to solve this would be the debounce operator of Rx, I skimmed [this article](https://blog.mindorks.com/implement-search-using-rxjava-operators-c8882b64fe1d) and it should give you all the information you need but don't hesitate to ask for any clarification.

**Comment by madhurgupta10** [comment]
@DeepaMalani Let us know if you are still working on this

**Comment by DeepaMalani** [comment]
Hi @madhurgupta10  
I'm not working on this issue.

**Comment by madhurgupta10** [comment]
> Hi @madhurgupta10
> I'm not working on this issue.

Thanks for the confirmation @DeepaMalani I am closing the PR. Feel free to comment on the issue thread if you would like to work on it again :)

**Pull request closed without merging**
