### PR TITLE
Fixes 4544 : Language selection: history

### LINKED ISSUE #4544: Language selection: history
The app has 3 places where a language can be selected: `App user interface language` and `Default description language`in Settings, ` and the Upload Wizard's Media Details dropdown. There are about a hundred languages, so it takes a long time to find the one you want.

Since a user probably uses only a handful of languages, it would be great if we could show in a first sub-list the most-recently selected 5 (or 10) languages. They could be separated from the rest of the list by a simple separator.

### PR DESCRIPTION
**Pull request by Ayan-10**
**Description (required)**

Fixes #4544

What changes did you make and why?

- Created a database for storing recently used languages
- Created Dao and Content Provider for operations
- Maintained 5 entries in the database
- Saved and populated those recently used languages on `App user interface language` and `Default description language` in  Settings, ` and the Upload Wizard's Media Details dropdown.
- Added tests

**Tests performed (required)**

Testedlastest master ProdDebug on Pixel 3 with API level 30

**Screenshots (for UI changes only)**

### CODE REVIEW

**Comment by Ayan-10** [comment]
@nicolas-raoul Can you review it once?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Thanks a lot, it is working great!
Would you mind adding more unit tests?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
I just noticed what I think is a bug:

I typed a caption, but want to change its language from Japanese to English. However, both Japanese and English are untappable (disabled) in the UI:
adb

**Comment by Ayan-10** [comment]
@nicolas-raoul Can you confirm the English caption is already added or not. If an English caption is already added earlier and you are trying to change the language in English then this will be not possible. Can you give some more information about the bug so that I can diagnose the issue?

Thanks.

**Comment by nicolas-raoul** [comment]
Ah yes thanks it might have been the problem, apologies for the false alarm!

**Comment by Ayan-10** [comment]
@nicolas-raoul Adding unit tests for the `RecentLanguagesContentProvider` methods seems not possible, we need a real device to test those as each of the methods has `getContext` in it so some errors will occur while unit testing. I added tests for other requested lines.

**Comment by nicolas-raoul** [comment]
Understood, thanks! :-)

**Pull request merged**
