### PR TITLE
Replace images for vectors

### PR DESCRIPTION
**Pull request by akaita**
This PR just replaces a bunch of icon images with their svg counterpart, and removes a couple of unused icon images.

| Before | After |
| - | - |
| screenshot_1500680916 | screenshot_1500681136 |
| screenshot_1500680920 | screenshot_1500681157 |
| screenshot_1500680937 | screenshot_1500681222 |
| screenshot_1500680944 | screenshot_1500681231 |
| screenshot_1500681080 | screenshot_1500681270 |

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks for this really fast patch! This was really needed. I am checking it very quick.

**Comment by neslihanturan** [comment]
I have found a small issue:
- Take photo icon is black on main screen

**Comment by akaita** [comment]
Very true. Fixed it to avoid confusion.
Thanks for catching it!

**Comment by neslihanturan** [comment]
Thanks for fast fix @akaita . I think there is no other issue for this pr. Nice work, thanks!

**Comment by misaochan** [comment]
Lovely, thanks @akaita !

**Pull request merged**
