### PR TITLE
Merge gamification branch with master

### PR DESCRIPTION
**Pull request by maskaravivek**
*  Layout inflated

*  Layout for mcq added

*  Inflated Basic Layout

*  Implemented basic flow

*  Added the basic implementation pf score

*  Added the result layout

*  Added the result layout

*  Added functionality to set result

*  Changed the launcher intent to Quiz Activity for testing purpose

*  Explanations of answers added

*  Improved the layout of quiz result a bit

*  Fixed some minor issues

*  Fixed build issues

* Api Added and basic structure for calling implemented

* Added intents

*  Added the title

*  Fixed image error and improved quality of pr

*  Made separate class for checking quiz

*  Added counter

* Implemented back and next for quiz result

*  Added back functionality to quiz

*  Added progressBar

*  Fixed bugs

*  Improved code quality

*  Imporved code Quality

*  Updated strings

*  Added share screenshot function

*  Added checks and improved UI

*  Removed unused string

*  Removed unused string

* Adding checks and improving code quality

* Changed string

* Improved code quality

### CODE REVIEW

**Comment by maskaravivek** [comment]
The build was failing due to some string duplication. Have fixed it now.

**Comment by tanvidadu** [comment]
Thanks! @maskaravivek :)

**Comment by maskaravivek** [comment]
All checks are passing. Have also tested the quiz on my android device. I had lots of reverted images so the quiz popped up immediately. :D

The feature works quite well. 🎉

**Comment by domdomegg** [comment]
Can this branch be deleted now?

**Pull request merged**
