### PR TITLE
Upload overhaul

### PR DESCRIPTION
**Pull request by ilgazer**
Based on designs shared in #1128, this code introduces a new UploadActivity that aims to replace the old Share / Multi-Share activities. The basic categorization and upload functionalities are working but many features are still WIP. Also, anything and everything could be broken in the old ShareActivity but they will be gone soon anyway.

### CODE REVIEW

**Comment by ilgazer** [comment]
I made some more progress, too dark picture detection and copying files to a directory are now working. Also, could you guys enable Codacy for the branch?

By the way, why is blur detection not implemented in the DetectUnwantedPicturesAsync class? There are some indications of the feature being planned but they seem abandoned.

**Comment by maskaravivek** [comment]
Wow, this works as a charm for me! I uploaded 2 sets of multiple pictures using the app and didn't find any glitches in the whole upload flow. I am happy merging this PR after at least one more person is able to test the whole flow. :)

@ilgazer I see that you have already listed down possible enhancements for the upload overhaul. Can you help in listing down things that are missing as compared to the existing multiple upload flow? Once we have feature parity, we can probably merge this to the main branch. 

Moreover, can this flow be reused for the upload flow that is triggered when uploading pictures from within the app? That would make the in-app upload flow a lot more aesthetic.

**Comment by ilgazer** [comment]
Yeah, I haven't looked at how the internal buttons call the old upload
screen but switching it to the new one definitely should be doable! By the
way, the only 2 features missing AFAIK are zoom, location map and the new
description language selector but tell me if there are any features that I
missed on the old screen.

**Comment by neslihanturan** [comment]
Photos or it didn't happen... Screenshots please @ilgazer :)

**Comment by maskaravivek** [comment]
I found one issue with the images that I uploaded. I gave the same title to all the images I was uploading and the app shows 6 different images(as I uploaded 6 images at a time) in my recent uploads. 

device-2018-08-05-191334

But my contribution list shows that the same image was overridden 5 times. Moreover, the image shown in the screenshot is the actual version of that image. 

- Maybe it makes sense to show a warning or have a validation that prevents users from entering the same title for multiple uploads. 
- Otherwise as done in the current in-app upload flow, the app checks for duplication and appends numbers 1, 2, 3.. to the file name if a file with the same name already exists on Commons. 

https://commons.wikimedia.org/wiki/Special:ListFiles?limit=50&user=Maskaravivek

**Comment by ilgazer** [comment]
Hmm, I'll look into that once I finish with the map and zoom stuff. Also, loads of pictures:

image
image
image
image
image
image
image

**Comment by maskaravivek** [comment]
@ilgazer Let us know when this PR is ready for testing/review :)

**Comment by ilgazer** [comment]
> @ilgazer Let us know when this PR is ready for testing/review :)

This branch is ready for testing. It has all the features of the old ShareActivity except for receiving title etc. from Nearby but implementing that should be fairly self-contained. As such, I think you guys can start testing it :)

The only issue I encountered was that my 7.0 Genymotion emulator kept running out of memory. Hopefully, that is because of me having an emulator, android studio and 74687 chrome tabs open at the same time. It is working just fine on a smaller-screen Android 6.0 emulator.

**Comment by maskaravivek** [comment]
Thanks for bringing diff to completion @ilgazer. Will review the changes soon.

**Comment by maskaravivek** [comment]
Upload is failing for me with this error. 

```
2018-08-10 10:41:31.942 7732-7800/fr.free.nrw.commons E/WTF: Result: org.mediawiki.api.ApiResult@4f7715e
2018-08-10 10:41:31.962 7732-7800/fr.free.nrw.commons E/ApacheHttpClientMediaWi: verification-error
```

@ilgazer Can you rebase your branch with master as it has fixes for upload failures.

**Comment by ilgazer** [comment]
> @ilgazer Can you rebase your branch with master as it has fixes for upload failures.

Merged master and also fixed some not logged in bugs. Rebase was nearly impossible because the earlier commits had tons of conflicts.

**Comment by maskaravivek** [comment]
@ilgazer Am not sure if the PR is ready for review but just out of curiosity I was trying it out today and had trouble when I chose a photo from Google Photos. It kept showing "Receiving shared content, this may take a moment or two" and never proceeded. 

When I clicked a photo from the camera, it worked well.

**Comment by ilgazer** [comment]
@maskaravivek I failed to duplicate the bug, but this is after I made some changes to the received file caching mechanism. Could you please test again?

Also, as the new UI has achieved feature parity with the old one at this point, should I finally delete the old upload activities and their dependent classes? I have hit the MultiDex method limit already and had to exclude the old Activities from the build as a workaround. Deleting the old activities at this point would allow more flexibility in modifying stuff like FileProcessor and moving some upload stuff to more logical places.

**Comment by maskaravivek** [comment]
Thanks for the update @ilgazer. I will try to test the PR tonight. 

> Also, as the new UI has achieved feature parity with the old one at this point, should I finally delete the old upload activities and their dependent classes? 
Yes, you can delete the old classes. Just make sure to keep your branch updated with master so that large merge conflicts can be avoided.  

If the PR has achieved feature parity with master, should I test it extensively and list down any issues that I come across?

**Comment by ilgazer** [comment]
> If the PR has achieved feature parity with master, should I test it extensively and list down any issues that I come across?

I would love that!

**Comment by ilgazer** [comment]
> The plus (+) button is not aligned properly when the view bottom view is collapsed

It was supposed to be hidden. Fixed!

>While trying to share from the Google photos app/gallery, the app immediately closes after clicking on Submit in the final step. For one moment I thought that the app crashed but upon checking the logs it became apparent that images have been queued for upload. It might be helpful to show a toast if queuing of uploads is successful.

Added a toast. 

>On the final screen where the user selects the license, the description below it should have a link(according to latest master) to the license.

Done!

>Title edit text should have(according to latest master) a info(i) button that shows a popup

Added!

>The map view button at the middle of the screen wasn't intuitive for me. For most of my uploads, nothing was happening on clicking it. Finally, for one of the images, it opened the map. Am not sure what coordinates it shows on opening the map. Am unable to recollect what was its purpose earlier.

The map view button shows the EXIF coordinates obtained from the file. The same feature was present under the expanding FAB in the Single Share activity. I will make it so that if there are no coordinates attached to the picture, the button will be hidden. Other than that, how could I make it more intuitive?

**Comment by ilgazer** [comment]
I'm failing to duplicate the HEIC bug as the HEIC image isn't even recognized as an image. Could you tell me the steps you took between taking the photo on an iphone x and uploading them to commons?

**Comment by maskaravivek** [comment]
Thanks, @ilgazer. The above fixes work well for me. 

Just one more feedback. Right now, there is no check for an empty title while uploading. This check is there on the master. Can you add it?

Also, it would be nice if you can include the latest changes from the master and make the PR up to date. This PR might stay open for a while before it is finally merged with master. :)

**Pull request closed without merging**
