### PR TITLE
Fixes #3414:  For v2.13, Handle zoom in media details view

### LINKED ISSUE #3414: Handle zoom in media details view
App review:

> The "Contributions" section is terribly designed: full-width images with title text over them instead of thumbnails. Tapping to open one instead shows a full-height portion of the image that can't be scrolled across nor zoomed out of. Basically, it's a pain to see what you've uploaded and impossible to see a whole image unless you open it in the browser.

I actually thought that we had redesigned media details to fix this - I recall @ujjwalagrawal17 was working on it during the hackathon, and had a branch going that handled zoom and scrolling appropriately. I also recall we were close to merging, but I can't actually find the PR now. @maskaravivek any idea?

### PR DESCRIPTION
**Pull request by kbhardwaj123**
Handle zoom in media details view

Fixes #3414  Handle zoom in media details view

What changes did you make and why?
Extended Fresco **SimpleDraweeView** to implement zoom into the view **ZoomableDraweeView**

**Tests performed**

Tested on Honor Play with API level 28.

**Screenshots showing what changed (optional - for UI changes)**
GIF-200220_173926 1

### CODE REVIEW

**Comment by kbhardwaj123** [comment]
I have created controller's for ZoomableDraweeView rather than using photo view because it takes 3 fold time to load zoom view and it creates problem handling jpg files(it's good with bitmap only) and the thing is that all pictures on server are in jpg format

**Comment by neslihanturan** [comment]
Thanks for the PR @kbhardwaj123 :) I actually have sent this review a few days ago, but can't understand why it didn't appeared under the issue.
1- MediaDetails changes image dimensions, please see:
image
2- When I click on an image, I get this error:
```
2020-02-24 13:34:32.602 32736-32736/fr.free.nrw.commons E/ACRA: ACRA caught a ActivityNotFoundException for fr.free.nrw.commons
    android.content.ActivityNotFoundException: Unable to find explicit activity class {fr.free.nrw.commons/fr.free.nrw.commons.media.ZoomableActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1932)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
        at android.app.Activity.startActivityForResult(Activity.java:4472)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:657)
        at android.app.Activity.startActivityForResult(Activity.java:4430)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:644)
        at android.app.Activity.startActivity(Activity.java:4791)
        at android.app.Activity.startActivity(Activity.java:4759)
        at fr.free.nrw.commons.media.MediaDetailFragment.launchZoomActivity(MediaDetailFragment.java:206)
        at fr.free.nrw.commons.media.MediaDetailFragment_ViewBinding$1.doClick(MediaDetailFragment_ViewBinding.java:46)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by kbhardwaj123** [comment]
@neslihanturan thanks for pointing out it slipped off my mind to keep the Aspect Ratio intact, anyways i have fixed both the issues
GIF-200224_202446 1

**Comment by madhurgupta10** [comment]
@kbhardwaj123 @neslihanturan 
With the new Android 10 update, the swipe from the edges of the screen is the default way for the back gesture.
When I zoom the photograph and try to scroll from the edges I accidentally trigger the back gesture. This is very well explained in - https://www.youtube.com/watch?v=Ljtz7T8R_Hk

**Comment by kbhardwaj123** [comment]
@madhurgupta10 hmm thanks for bringing that to perspective, I think this won't be a big issue since my android device also has this gesture **But** zoom scroll or any horizontal scroll for that matter will be interpreted as a back gesture if you do it from the very edge (however one usually scrolls using thumb which naturally approaches center of the screen so its not a big problem). What I mean is that it's a tradeoff between convince and accidently triggering back that this gesture brings with itself

**Comment by madhurgupta10** [comment]
> @madhurgupta10 hmm thanks for bringing that to perspective, I think this won't be a big issue since my android device also has this gesture **But** zoom scroll or any horizontal scroll for that matter will be interpreted as a back gesture if you do it from the very edge (however one usually scrolls using thumb which naturally approaches center of the screen so its not a big problem). What I mean is that it's a tradeoff between convince and accidently triggering back that this gesture brings with itself

Take an example of LinkedIn, they have the same zoom feature. When I am using the phone with a single hand it is sometimes difficult to get the gesture right. You can see the gif to understand my point.

ezgif com-optimize

**Comment by kbhardwaj123** [comment]
@madhurgupta10 i tested it on my phone it didn't scroll on back gesture which means that the controller are fine i think it might have to do some issue with the Android 10's gesture ,see:
GIF-200228_155537 1
@neslihanturan what are your views on this

**Comment by neslihanturan** [comment]
Hey @kbhardwaj123 , thanks for your fast responses :) I tested it again, the crash is solved and zoom works with no problem, congratz:) But it still resizes the image:
image
Bottom sheet can overlay on top of the image. Just like we do now.

**Comment by kbhardwaj123** [comment]
@neslihanturan sure I'll fix that as soon as my exams are over :)

**Comment by kbhardwaj123** [comment]
@neslihanturan  i need a bit help, actually i have tested resizing image issue but was not able to reproduce it
kindly take a look at the screenshots below:

**For Wide Aspect Ratio image**
Screenshot_20200307_151954_fr free nrw commons beta 1


**For Tall Aspect Ratio image**
Screenshot_20200307_151958_fr free nrw commons beta 1

**Comment by neslihanturan** [comment]
You can use this image to test my issue, https://commons.m.wikimedia.org/wiki/File%3AGuitar_head.jpg

Please do not finalize the upload process to prevent duplicates:)

**Comment by kbhardwaj123** [comment]
@neslihanturan after a lot of debugging i realised that the setAspectRatio method of SimpleDraweeView was not working correctly, anyways i have applied a workaround and it should work this time :)

**Comment by neslihanturan** [comment]
Thanks @kbhardwaj123 , now the issues are fixed. After I tested this Pr here are some reviews:
- When it is a DSLR image with a big size, it took some time for it to be displayed of course. But user is looking at a black screen during this time. Instead there should be an progressbar. 

My suggestion is merging this PR as is and having progressbar as another PR. Because current implementation improved my user experience significantly. Thanks for the great job! Let me check the code one more time before merge

**Comment by misaochan** [comment]
Thanks @kbhardwaj123 and @neslihanturan ! :)

**Comment by kbhardwaj123** [comment]
@misaochan my pleasure :)

**Pull request merged**
