### PR TITLE
Update issue and PR templates

### PR DESCRIPTION
**Pull request by domdomegg**
**Description**

Update issue and pull request templates to be more useful to users, use more consistent formatting and simply language throughout.

Would appreciate other's feedback on what else could be done to improve the templates

### CODE REVIEW

**Comment by domdomegg** [comment]
Also I'm considering removing the issue and PR templates from the wiki as they were out of sync with even the old ones and it's kinda a pain to keep two sets up to date.

https://github.com/commons-app/apps-android-commons/wiki/Issue-Template
https://github.com/commons-app/apps-android-commons/wiki/Pull-Request-Template

**Comment by neslihanturan** [comment]
Hi @domdomegg , thanks for your contributions. And sorry for long review time, hopefully after 2.9 is out, we all will be faster. Can you please explain main objective of you on this PR? 

- I see you fixed some typos (which is something I understood)
- You turned titles to bold text (which is something I want to hear more about)
- You removed title field (I agree requesting title twice is a duplicate, and agree about removing them. But want to hear from other parts of team to make sure)

**Comment by neslihanturan** [comment]
Since @nicolas-raoul approved changes (thanks!) I will merge this PR. Thanks for your contribution @domdomegg .

**Comment by domdomegg** [comment]
Thanks. To explain my rationale anyways:
- Turned titles in PR template to bold text just to match issue template. Didn't mind which that much, but thought they should be the same. Happy to change both to titles
- Removed title field as it's a duplicate, and Github PRs already have a title field
- Updated the screenshot link to the official Google Android guide as it's up to date with Android 9.0

**Pull request merged**
