### PR TITLE
Fixes #2843 New main screen UI in v3.0

### LINKED ISSUE #2843: New main screen UI in v3.0
This task was mentioned in our PG proposal and is slated for the end of our grant, but I forgot to create an issue for it. :) Copying over from the proposal:

After the new features have been completed, we would like to tie everything together in a new main screen UI. Since the creation of the app, the focal point of the main screen has been the user's past contributions. However, the app is now very different from what it was at the beginning - we have the Nearby feature, an Achievements screen with a level badge and upload stats, a Notifications screen with user talk messages, an Explore screen that lets users browse other Commons photos, and various other conveniences. At the end of 2018 we will be able to display news about an ongoing campaign. And at the end of this proposed grant, we will have a limited connection mode, the option to pause and resume image uploads, and a "to-do" system.

When the time comes, we will create a few different mockups and seek community feedback on which one they like best, before proceeding with implementation. However, as a rough guide, a possible plan for a new main screen UI is outlined below.

The action bar (the blue bar at the top of the screen) could have:

- Unread notifications as a bell icon
- Limited connection mode toggle

A bottom navigation bar could have:

- Home
- Nearby (nearby places that need pictures)
- Browse (the current "Explore" screen)
- My contributions

Home (which will be the new main screen) could contain:

- "Welcome back, username!" with level badge, upload stats and achievements displayed
- News about ongoing campaigns
- The nearest place that needs pictures
- The picture being uploaded currently (with option to pause/resume) and queue of other pending uploads. Or, if there is no picture being uploaded or in the queue, the most recent picture uploaded
- "To do list" of uploaded pictures with action needed
- Upload button

All of this will culminate in the release of v3.0 of the app at the end of the project.

### PR DESCRIPTION
**Pull request by neslihanturan**
**Description (required)**
Fixes #2843 . Migrated to use Bottom Nav Bar instead of drawer. 

Known issue, help needed:

Hey team, I need some help to solve an issue. You know after we migrated to new UI our fragment hierarchy is changed. 
Normally we had ExploreActivity, BookmarksActivity etc. 

Now we have MainActivity and inside ConstibutionsFragments, ExploreFragments etc.

Lets talk about ExploreFragment whcih has two child fragments as MobileImagesListFragment and FeaturedImagesListFragment. When one of the item from lists is selected we should display MediaDetailsFragment. So the structure is
```
MainActivity
|-------------------->ExploreFragment
                                  |-------------->MobileImagesListFragment
                                  |-------------->FeaturedImagesListFragment
                                  |-------------->MediaDetailsFragment
```
I used hide/show/add instead of replace fragment (to retain the list state and for efficiency). But the problem is our newly added visible fragment doesn't gain the focus. Do you have any suggestions?

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @neslihanturan , thanks for making the requested changes! I just tested this on a real device running Android 10. The bottom bar navigation was very smooth, great job. :)

There are a few minor changes that I would request before merging. Let me post the mockup for easy reference first:

toggleRedesign

And this is the Contributions screen that I see in the PR:

Screenshot_20201030-010250_Commons

- The first thing that I notice is the nearby place card. This needs a bit of tweaking to get it to look similar to the card in the mockup
- Also, I feel that the "person" icon in the bottom bar of the mockup fits Contributions more than the trophy icon, do you agree? When I was navigating back from Nearby I had a bit of trouble figuring out how to go back to Contributions because I assumed that the first icon was Achievements (since we have always used that icon for Acheivements)

Screenshot_20201030-010555_Commons

- After using the app for a while (I can't remember exactly which activities I visited, sorry), a bogus event card appeared too. The first problem with this is that the card appears even though there is no event running, and therefore the values are blank. The second problem is the design of the card

Screenshot_20201030-010450_Commons

- The action bar of a media detail fragment does not have back navigation

Screenshot_20201030-010200_Commons

- Notifications activity is missing an action bar

**Review by misaochan — CHANGES_REQUESTED** [review]
Requesting changes as per comment.

**Comment by neslihanturan** [comment]
Hey @misaochan , reviews are adressed. Please take a look at them again. Currently cards looks like this:

photo_2020-11-04_14-21-30

I liked when texts are blue instead of black. So kept them blue. If you disagree we can change them.

Note: Regarding to the limited connection, I agree it should be more obvious but could be better in another PR.

**Comment by misaochan** [comment]
Thanks for making the changes @neslihanturan ! I will go ahead and merge this PR, and make issues for any further items that need fixes. That way we can get this out to alpha users ASAP.

Nice work! :)

**Review by misaochan — APPROVED** [review]

**Pull request merged**
