### PR TITLE
Image downloading fixed

### LINKED ISSUE #1216: Image downloading fails
### Summary
Clicking the download button after going to My Recent Recent Uploads fails to download an image to the phone's storage even when the app has been granted Storage Permission.

### Screenshots

whatsapp image 2018-02-27 at 9 09 05 am 2
whatsapp image 2018-02-27 at 9 02 21 am 2

### System Logs
The log report can be found at this link:
[Log Report File](https://docs.google.com/document/d/1iFANGofxS37m9KHb7kZIQOdNAK3aybGCTXPTFY6m8vs/edit?usp=sharing)

### Device and Android version
Redmi Note 3
6.0.1 MMB29M
MIUI Version: MIUI Global 8.5
 
 **Commons app version:** 
2.6.7

### PR DESCRIPTION
**Pull request by gupta-meghna64**
### Description
Clicking the download button now downloads each image uploaded in future without any kind of failure. The PR fixes #1216. 
Changes were made to SingleUploadFragment.java where the title of the image was modified in a way so as to handle the incoming of spaces in the formed URL. The spaces was replaced by a '_' 
This works for all the newly uploaded images in the future and not for previously existing images, since their URL has already been formed while uploading them to the database.

### Testing
The changes have been tested on a real-time device and a few corner cases for image titles have been tried out as well.
Tried out test cases: 
1) ČSD ř. M 260.001 1939-02.17. 24.jpg
2) دمشق جبل قاسيون.jpg
3) A. b. c. d 1.2 . 3

Please review and give your inputs :-)

### CODE REVIEW

**Comment by gupta-meghna64** [comment]
@maskaravivek This is ready to be reviewed. Thanks :)

**Comment by maskaravivek** [comment]
This would fix the image download issue for future images. Can't we do something for existing images?

@nicolas-raoul @psh Do you guys have any feedback on this?

**Comment by nicolas-raoul** [comment]
If I understand correctly, this removes all non-alphanumeric characters from titles?
That would remove potentially valuable information. For instance I sometimes type my titles in Japanese only, so they would become blank, right?

In my opinion, the best fix is to first get the download URL using the Mediawiki API:
```
https://commons.wikimedia.org/w/api.php?action=query&format=xml&prop=imageinfo&iiprop=url&titles=File:ČSD ř. M 260.001 1939-02.17. 24.jpg
```
gives:
```
<api batchcomplete="">
<query>
<pages>
<page _idx="48443415" pageid="48443415" ns="6" title="File:ČSD ř. M 260.001 1939-02.17. 24.jpg" imagerepository="local">
<imageinfo>
<ii url="https://upload.wikimedia.org/wikipedia/commons/a/a6/%C4%8CSD_%C5%99._M_260.001_1939-02.17._24.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:%C4%8CSD_%C5%99._M_260.001_1939-02.17._24.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=48443415"/>
</imageinfo>
</page>
</pages>
</query>
</api>
```

The `url=` value is the safe download URL of the file :-)

**Comment by gupta-meghna64** [comment]
@nicolas-raoul @maskaravivek 
This fix is URL encoding the alpha numeric characters and replacing the spaces with _ 

So @ become %40 in URL, and % becomes %25 in the URL. It is not safe to use non alphanumeric characters in the URL as per the guidelines. 

For instance, I uploaded an image with title: ジンボはリンゴを食べる。
Then the download URL of the image generated is: https://upload.beta.wmflabs.org/wikipedia/commons/d/df/ジンボはリンゴを食べる.jpg

So yes, it doesn't become blank. The same has been tried for a title in Urdu language as well.

**Comment by nicolas-raoul** [comment]
Thanks for the research!
Still, I think that we should not modify the title entered by the user.

This code will probably be reused when we implement browsing from Commons, so it will be used for images that contain all sorts of characters. Thus I recommend the method described in my previous comment.

**Comment by maskaravivek** [comment]
I agree with @nicolas-raoul! It would be great if you could use the MediaWiki API suggested above to  make this fix. It would be a great way for you to get familiar with the APIs, and see how simple they actually are. :)

**Comment by gupta-meghna64** [comment]
I'll start working on this @maskaravivek @nicolas-raoul :-)

**Comment by gupta-meghna64** [comment]
Hi! I've written the code to send a request to MediaWiki API to fetch the safe download URL. The code runs on the image with the title ČSD ř. M 260.001 1939-02.17. 24.jpg successfully, but when I'm testing for the other uploaded images by me, the obtained JSON response states that the image is missing from here. 
For example: 
I uploaded the image named as Southern Valley
Browsing Link: https://commons.m.wikimedia.beta.wmflabs.org/wiki/File:Southern_Valley.jpeg

API Request Link: https://commons.wikimedia.org/w/api.php?action=query&format=xml&prop=imageinfo&iiprop=url&titles=File:Southern_Valley.jpeg

The response obtained shows that missing image repository. How do I proceed with the above error? 
Please guide me with this. Thanks :)

**Comment by gupta-meghna64** [comment]
@nicolas-raoul unfortunately I'm still having trouble understanding **use beta.wmflabs.org instead of wmflabs.org in the beta build** :( 
It would be really great if you could help me with this.

**Comment by ayushin78** [comment]
@gupta-meghna64 Hey, I guess you need to hit the beta API.
@maskaravivek  @nicolas-raoul  I think I found a fix for this. Can I create the PR for the same?

**Comment by gupta-meghna64** [comment]
Thanks @ayushin78 I'll give it another try :)

**Comment by gupta-meghna64** [comment]
@nicolas-raoul @maskaravivek Please review :-)

**Comment by gupta-meghna64** [comment]
@maskaravivek can I submit a new PR to this fix? I forgot to checkout the branch, and because this is still under review, I'm not able to work on any other claimed issue :( ?

**Comment by maskaravivek** [comment]
@gupta-meghna64 Testing this might need some time. You can surely submit a new PR if you want. But I have another solution for you. 
You created the PR from `master`. So your `master` contains 4 extra commits(belonging to this PR).

1. Check out a new branch from master. 
```
git checkout -b imageDownload
```

Now the `imageDownload` branch has all the commits that you need for this PR. 

2. Go back to master
```
git checkout master
```

3. Do a hard reset of your master
```
git reset --hard HEAD~4
```

Now your master is up to date with upstream master. You can freely work on it.

**Comment by gupta-meghna64** [comment]
I tried this, but I don't know why my new branch isn't getting updated :-( 
So, I'm closing this PR and will submit a new PR for this.

**Pull request closed without merging**
