### PR TITLE
Fix failed uploads

### LINKED ISSUE #1485: Upload fails often in 2.7
Report from user on googlegroups
He says "Very often: Upload failed"

And has logs attached. Unfortunately I can't share them here without permission, but anyone who has signed the NDA that allows them to access our private group is welcome to check it there.

There are two issues here:

1. The logs don't provide any meaningful information. It is completely cluttered by system logs, etc. This has been the case for logs provided by everyone else as well. Is it at all possible for us to filter for our app's logs programmatically in the "send logs" feature?

2. The upload failing very often. I plan to ask him where he is uploading from (sd card, etc), and for screenshots if he can provide them. What other information do you guys think would be useful to solve the problem? @maskaravivek @psh @nicolas-raoul @neslihanturan 

He isn't the only one with it - a recent Play Store review was from a user who encountered the same problem. So I would probably assign this issue a fairly high priority since this is our core functionality.

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

Fixes #1485 

Will add the description if this actually fixes the issue. :)

@nicolas-raoul @misaochan Can you help in testing this. 

For me:
- I was able to reproduce the issue where image upload started failing with `mustbeloggedin` error. 
- I kept tweaking a few things while retrying the same upload and was running into authentication issues. 
- Finally the retrial failed with a different error. I am assuming this is an unrelated error. 

```
<?xml version="1.0" encoding="UTF-8"?><api servedby="mw1284"><error code="verification-error" info="File extension &quot;.John's_National_Academy_of_Health_Sciences&quot; does not match the detected MIME type of the file (image/jpeg)."><details><detail>filetype-mime-mismatch</detail><detail>John's_National_Academy_of_Health_Sciences</detail><detail>image/jpeg</detail></details><docref xml:space="preserve">See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&amp;gt; for notice of API deprecations and breaking changes.</docref></error></api>
```

- I upload a new image and it uploads successfully.

### CODE REVIEW

**Comment by misaochan** [comment]
This works for me!!!!! Well done @maskaravivek , you have solved a bug that has stumped us for over a month!! 🥇 👏 👍

I experienced a couple of minor issues while testing:
- I think this needs to be rebased on `2.8-release` and submitted to 2.8-release. I noticed some bugs with new changes on master (the desc language selector) while testing it
- While the new uploads succeed, I don't get the usual upload progress bar in ContributionsActivity. It just says "Queued" until it succeeds, even if there is no other upload ongoing. However this might be due to a bug on master, so it would be worth doing the rebase first and then seeing if it persists

**Comment by misaochan** [comment]
Thanks for the fixes, @maskaravivek . I tested this again on a separate emulator, and the progress bar is fixed now. :) I am unable to test on the emulator with failed uploads due to the rebase - it requires an uninstall due to the recent contentprovider change, and I can't reproduce failed uploads if I uninstall.

So, I am in favour of merging this once the Travis build completes. :) Then we can release this to beta, and see if it fixes the issue for the users who are experiencing failed uploads.

If I'm not around when Travis completes, anyone please feel free to squash and merge.

**Comment by maskaravivek** [comment]
@misaochan The build was failing because of a test failure.

**Comment by maskaravivek** [comment]
Merging this as both checks are now passing. :)

**Pull request merged**
