### PR TITLE
Fixes #3303

### LINKED ISSUE #3303: Nearby Crashes when options  menu is clicked
**Summary:** 
USER_COMMENT=Navigated away from settings after toggling night mode on and off 

**Steps to reproduce:** 

Play with options menu

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.material.bottomsheet.BottomSheetBehavior.getState()' on a null object reference at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.listOptionMenuItemClicked(NearbyParentFragment.java:576) at fr.free.nrw.commons.contributions.MainActivity.onOptionsItemSelected(MainActivity.java:342) at android.app.Activity.onMenuItemSelected(Activity.java:3556) at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:371) at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:197) at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109) at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109) at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64) at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204) at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781) at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840) at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158) at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991) at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981) at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625) at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151) at android.view.View.performClick(View.java:6669) at android.view.View.performClickInternal(View.java:6638) at android.view.View.access$3100(View.java:789) at android.view.View$PerformClick.run(View.java:26145) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:193) at android.app.ActivityThread.main(ActivityThread.java:6898) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) IS_SILENT=false USER_EMAIL= USER_CRASH_DATE=2019-12-19T13:49:11.240+00:00 REPORT_ID=eefad64f-1834-48a3-97d5-003a5e275f8f

```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
Android 9
**Commons app version:** 
2.12.0.530 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
* Refactor Nearby to align lifecycle methods
Fixes #3303 Nearby Crashes when options menu is Clicked

What changes did you make and why?
Refactored methods from Presenter to View and Vice Versa
Removed NearbyMap Fragment and used a MapView instead
Updated version of MapBox
**Tests performed (required)**
Tested on Samsung S7, betaDebug

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @ashishkumar468 , in general works great:) Here are few things:
1- If permission is not given at first, and then user gives it, nothing happens.
2- If the user go to settings and change the theme and come back, here is what they will see:
image
I think presented should be nulled on destroy of activity to prevent this.

**Comment by ashishkumar468** [comment]
Hi @neslihanturan @maskaravivek @misaochan . I have addressed all the review comments from @neslihanturan. I have tested the feature at my side, and solved all the bugs mentioned by @neslihanturan. It would be great if you guys could help me test this

**Comment by neslihanturan** [comment]
Hey, @ashishkumar468 , I have just tested this one. On a clean installation, after requesting permission and I allowed it this happened.
```
    Process: fr.free.nrw.commons, PID: 8583
    java.lang.NullPointerException: Attempt to invoke virtual method 'double fr.free.nrw.commons.location.LatLng.getLatitude()' on a null object reference
        at fr.free.nrw.commons.utils.LocationUtils.commonsLatLngToMapBoxLatLng(LocationUtils.java:11)
        at fr.free.nrw.commons.nearby.presenter.NearbyParentFragmentPresenter.onCameraMove(NearbyParentFragmentPresenter.java:266)
        at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.lambda$onViewCreated$0$NearbyParentFragment(NearbyParentFragment.java:212)
        at fr.free.nrw.commons.nearby.fragments.-$$Lambda$NearbyParentFragment$uB0nwZ4mgg3hTk-4wo5Uazawk7Q.onCameraMove(Unknown Source:2)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.executeOnCameraMove(CameraChangeDispatcher.java:120)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.access$100(CameraChangeDispatcher.java:21)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$CameraChangeHandler.handleMessage(CameraChangeDispatcher.java:171)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to invoke virtual method 'double fr.free.nrw.commons.location.LatLng.getLatitude()' on a null object reference
        at fr.free.nrw.commons.utils.LocationUtils.commonsLatLngToMapBoxLatLng(LocationUtils.java:11)
        at fr.free.nrw.commons.nearby.presenter.NearbyParentFragmentPresenter.onCameraMove(NearbyParentFragmentPresenter.java:266)
        at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.lambda$onViewCreated$0$NearbyParentFragment(NearbyParentFragment.java:212)
        at fr.free.nrw.commons.nearby.fragments.-$$Lambda$NearbyParentFragment$uB0nwZ4mgg3hTk-4wo5Uazawk7Q.onCameraMove(Unknown Source:2)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.executeOnCameraMove(CameraChangeDispatcher.java:120)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.access$100(CameraChangeDispatcher.java:21)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$CameraChangeHandler.handleMessage(CameraChangeDispatcher.java:171)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
Does this seems related to you?

**Comment by ashishkumar468** [comment]
Looking into it @neslihanturan .

**Comment by ashishkumar468** [comment]
Hi @neslihanturan , I have tested the application to work in the following situations
* Current location point tracks users position when he is walking
* Map does not track current location when user is browsing the map (map target location is not same as current location)

Please verify the same at your end.

**Comment by neslihanturan** [comment]
Works like a charm @ashishkumar468 , thanks for the great job:)

**Comment by maskaravivek** [comment]
Nice work @ashishkumar468 :)

**Comment by ashishkumar468** [comment]
Thanks, @maskaravivek  & @neslihanturan  for your help with testing the PR  :)

**Comment by misaochan** [comment]
Nice work, thanks everyone! :)

**Pull request merged**
