### PR TITLE
Remove unused message "back"

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Sorry would you mind pulling (or rebasing) and rePRing?

**Comment by jayvdb** [comment]
no worries

**Comment by misaochan** [comment]
Hm, there appear to be merge conflicts?

**Comment by jayvdb** [comment]
Ah, another merge conflict. Ill rebase as soon as I get near a computer.

**Comment by jayvdb** [comment]
ping @misaochan , @nicolas-raoul .  would appreciate a merge before another merge conflict

**Comment by misaochan** [comment]
Thanks @jayvdb !

**Pull request merged**
