### PR TITLE
improvements for #655 issue

### PR DESCRIPTION
**Pull request by tised**

### CODE REVIEW

**Comment by misaochan** [comment]
Could we get a screenshot of the final result, please? So that people can decide if they like the new one better?

**Comment by neslihanturan** [comment]
I have tested this one, it looks like : 
device-2017-08-06-183553

So, yes. Problem is solved. On the other hand numbers should be invisible when pictures appear.

**Comment by maskaravivek** [comment]
@neslihanturan Does this PR solve the issue mentioned in #655. In that case we can probably solve the merge conflicts and get it merged.

**Comment by neslihanturan** [comment]
@maskaravivek Actually the result is as I shared above. The issue was numbers intersecting with file name bar. This PR solves this, however brings us a new problem. Numbers are always visible at the most top level even if after images are loaded.

**Comment by neslihanturan** [comment]
Yes, I am OK

**Comment by misaochan** [comment]
Thanks guys. Please feel free to re-submit if you return, @tised :)

**Pull request closed without merging**
