### PR TITLE
add parameters to sort featured images by order of recency

### LINKED ISSUE #1564: Featured pictures: Show in recency or random order, rather than alphabetical order
Currently, featured pictures are shown in alphabetical order.

As a consequence, users will always see the same pictures.
In particular, nobody will ever see all of the featured pictures that do not start with a quote or digit character.
This is boring for users, they will not scroll featured pictures twice. Even in one year the pictures show will be the same, with 1 or 2 exceptions maybe among hundreds of pictures scrolled.

Solution: Rather than displaying in alphabetical order, show in either (only implement one, whichever you find easiest or have a personal preference for):
- Order of recent upload
- Order of recent nomination
- Or random

The order must be passed in the API request. Ordering results after receiving a result page is not a good solution.

### PR DESCRIPTION
**Pull request by neoliteconsultant**
## Change order of featured images to recently uploaded

Fixes #1564 

## Changed the order of featured images by adding the *gcmsort* and *gcmdir* parameters in the api request

Fixes #1564 Featured pictures: Show in recency or random order, rather than alphabetical order

Added  *gcmsort* and *gcmdir* parameters in  **fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi#getCategoryImages**  method 

1. Made an api call on a browser and compared the timestamps returned by the query
2.Built a **prod** flavour for the app and observed the order of featured images before and after the change.

Tested on {API level 23, Samsung SM-G532F}, with  **prod** flavour.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Great!
So this shows the latest featured image first, right? :-)

Would you mind adding a comment to each line saying quickly what it does?
For instance, it took me 5 minutes to guess that "gcmdir" means direction and "desc" means "descending" haha

**Comment by neoliteconsultant** [comment]
@nicolas-raoul yes it does

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Can you tell me how do you test a feature before merging it. Do you clone every contributor's repo that has sent the PR and change branch and then test or any other shortcut? I also want to learn it.

**Comment by neoliteconsultant** [comment]
@nicolas-raoul If there no bugs, this PR should be merged

**Comment by ujjwalagrawal17** [comment]
Thanks, @misaochan. I also got to know 2 other ways. Everyone uses git in a different style.

**Pull request merged**
