### PR TITLE
Refactor: utils models

### PR DESCRIPTION
**Pull request by ben-mathu**
Part of an ongoing code refactoring to move all models to a common models package.

Fixes #4782

Moved utils models to data.models package.

Tested debug on Pixel 4 (Emulator) with API level 30.

### CODE REVIEW

**Review by neslihanturan — APPROVED** [review]
Thanks, will merge as soon as test issue on master is solved (not related with this PR)

**Review by neslihanturan — CHANGES_REQUESTED** [review]
Why we are seeing and empy file at top of all, the .jpg file I mean

**Comment by neslihanturan** [comment]
Hi, is this PR sleeping @ben-mathu ?:)

**Comment by psh** [comment]
Closing: 2 years old and looks abandoned.

**Pull request closed without merging**
