### PR TITLE
Mapped values-en-gb to values-en-rGB

### PR DESCRIPTION
**Pull request by LivingWithHippos**
While running for the first time in Android Studio the app I get the "Error: Invalid resource directory name" on the values-en-gb directory.
This file has been created with commit [dfe59c4034c58d829f107b715699eb1134375040](https://github.com/commons-app/apps-android-commons/commit/dfe59c4034c58d829f107b715699eb1134375040) by @translatewiki as with issues #1059 or #1135 .
I've opened a PR to rename the folder to values-en-rGB but I know someone like @Nikerabbit needs to edit the codemap in CommonsAndroid.yaml.
I've also noticed that some of the country+region values are encoded in ISO 639-1 (values-country-rRegion, like values-pt-rBR) while some in BCP 47 (values-b+country+region, like values-b+be+tarask). [According to google](https://developer.android.com/guide/topics/resources/providing-resources.html#LocaleQualifier) BCP 47 is available from API 24 and in the project we have minSdkVersion=19 but I don't know if that can be a problem.
Maybe the same standard should be used for all the values folders?

### CODE REVIEW

**Comment by Abijeet** [comment]
@Nikerabbit has [made this change](https://gerrit.wikimedia.org/r/c/translatewiki/+/542955) on translatewiki.net and it has been merged.

The next export from Translatewiki.net will be submitting en-rGB translations.

**Comment by nicolas-raoul** [comment]
Can this pull request be closed, then? Thanks! :-)

**Comment by misaochan** [comment]
I don't think we should close this, as AFAIK we need both the directory change as well as the mapping in order for the build to work. Currently master is failing Travis with the logs below, and this PR fixes the build. @maskaravivek @neslihanturan shall I merge this?

> Execution failed for task ':app:mergeProdReleaseResources'.
> > /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-en-gb: Error: Invalid resource directory name

**Comment by neslihanturan** [comment]
I agree @misaochan , this should be merged.

**Pull request merged**
