### PR TITLE
On Logout, fetch the CSRF token and then make the post logout call

### PR DESCRIPTION
**Pull request by ashishkumar468**
Fixes https://github.com/commons-app/apps-android-commons/pull/3150#discussion_r331743965

**Description (required)**
 * Fetch the CSRF token
 * use the CSRF token to make the logout post call
 * once both of these succeed, clear the local data

**Tests performed (required)**

Tested prodDebug on Samsung S7 API 27

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @ashishkumar468 ,

Testing logout and relogin with this PR causes me the same issues as the one that was solved by #3168 - the pictures displayed on my 2nd account actually belong to my 1st account. Could you check if the image cache is still cleared?

**Comment by ashishkumar468** [comment]
@misaochan  Sure JO, I will look into it :)

**Comment by ashishkumar468** [comment]
@misaochan , I tested this with a debugger attached, the image cache clear function is called. I do not have 2 accounts on prod, I am not able to check the issue produced by you, but as far as I understand, this should not have caused that problem.

**Comment by misaochan** [comment]
Multiple accounts on prod isn't illegal as long as you don't use it to break rules or deceive people. :) Try creating one and see?

**Comment by ashishkumar468** [comment]
@misaochan Last time I got blocked (of all the accounts :P), I will do it anyways and get back :-)

**Comment by ashishkumar468** [comment]
Okat, Sure @misaochan , I will try to reproduce this and get back asap :-)

**Comment by ashishkumar468** [comment]
@misaochan  Can you verify if it works now ?.

**Comment by misaochan** [comment]
Yes, problem is solved for me, great job @ashishkumar468 ! :)

**Pull request merged**
