### PR TITLE
Fixed issue where GPS data was not getting sent when uploading multiple images

### PR DESCRIPTION
**Pull request by Bluesir9**
This should take care of #896. I have tested it on my end by making a couple of uploads. Would request someone else to test the changes as well and also review the changes made.

### CODE REVIEW

**Comment by misaochan** [comment]
@neslihanturan Could we please get this tested? Thanks!

**Comment by neslihanturan** [comment]
Actually this works great, sorry for testing it so late @Bluesir9 I just learned how to create photos  with/without GPS information. And finally could test this. There are minor conflicts, if you can solve them I will immediately merge this time. 
Bonus: it works with group of photos with and without GPS information too.

**Comment by Bluesir9** [comment]
@neslihanturan Branch has been synced with master.

**Comment by neslihanturan** [comment]
@Bluesir9 did you managed to successfully upload after fixing conflicts?

**Comment by neslihanturan** [comment]
Well, I have tested. Still works as expected. Thanks a lot @Bluesir9 !

**Pull request merged**
