### PR TITLE
Bug fix [#1419]

### PR DESCRIPTION
**Pull request by ashishkumar468**
## Description

Fixes #{#1419}

-Added a ProgressBar in MediaDetailFragment to be shown while the media is being fetched
-Replaced android:text with tools:text in TextViews with MediaDetails values.

## Tests performed

Tested on {27 & Google Pixel}, with {build variant, debug}.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@ashishkumar468 there are some merge conflicts. Could you resolve it before the review? :)

**Comment by maskaravivek** [comment]
The travis build is still failing for task `:app:processBetaDebugResources`. Can you check the issue. @ashishkumar468

**Comment by neslihanturan** [comment]
@ashishkumar468 I think you misunderstood the issue at #1419 . This PR doesn't solve the issue for me. 
- Upload a picture
- Open another media detail when it is uploading
- You wont see informations of media. 

This is the problem we try to solve. You changes doesn't have any effect on this problem. I still able to reproduce the issue after your PR, here:
image

**Comment by misaochan** [comment]
> It seems like the issue is only seen while another upload is going on . And data does come in my case after the upload has finished. Seems like somehow the api call is queued and fired only when the upload call is finished

Yes, exactly. That is the issue we are trying to solve. ;) Both calls should be able to work in parallel.

**Comment by neslihanturan** [comment]
Do you still working on this @ashishkumar468 ?

**Comment by ashishkumar468** [comment]
@neslihanturan  Was actually busy into other things lately, will have a look tonight

**Comment by ashishkumar468** [comment]
@neslihanturan There is nothing which is holding the data to be fetched from the api [Atleast I could not find something]. As soon as MediaDetailsFragment is opened, api call is made to fetch the relevant data is fetched. I think it is a simple case of network latency.

**Comment by neslihanturan** [comment]
Hmm, since we all have no solution maybe closing this PR and waiting someone else to dig this issue is a good idea. What do you say @ashishkumar468 ?

**Comment by ashishkumar468** [comment]
@neslihanturan Yes, Sure go ahead

**Pull request closed without merging**
