### PR TITLE
Fix bugs in peer review flow

### LINKED ISSUE #3038: Some of the peer review functions does not work
**Summary:** 
This issue is introduced after #2937 is merged. Here is a brief explanation of problems in peer review.

| Operation  | Expectation | Reality |
| ------------- | ------------- | ------------- |
| Is this in scope - No, out of scope | Requests reason -> nominates for deletion with delete reason -> Brings first question with new image | Does nothing |
| Is this in scope - Seems fine  | Brings next question | Brings next question |
--
| Copyright? - No, copy right violation | Requests reason -> nominates for deletion with delete reason -> Brings first question with new image | Brings first question |
| Copyright? - Seems fine  | Brings next question | Brings next question |
--
| Category? - mis-categorized | Requests category check -> Brings first question with new image | Requests category check -> Brings next question |
| Category? - Seems fine  | Brings next question | Brings next question |
--
| Thanks? - yes, why not | Sends thanks -> Brings first question with new image | Brings first question with same image |
| Thanks? - Seems fine  | Brings first question with new image |  Brings first question with same image |

### PR DESCRIPTION
**Pull request by maskaravivek**
**Description (required)**

Fixes #3038

What changes did you make and why?

Had to made several minor changes to fix the peer review bugs. 

**Tests performed (required)**

Have tested on both betaDebug and prodDebug

- nomination for deletion works as expected
- category check works
- thanks works
- next image comes as expected
- skip image works

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @maskaravivek , it works in general. There are some small issues that I recognized.
- Tests failed.
- Yes, mis-categorized button brings us to next question instead of first question with new image
- Sending thanks says success but I didn't see any recent changes about thanks. Should I see?
- Category check notification never ends:
Screenshot from 2019-06-25 14-31-53

And I saw some weird pages on recent changes of beta:
Screenshot from 2019-06-25 14-33-04
Screenshot from 2019-06-25 14-32-51

**Comment by nicolas-raoul** [comment]
@neslihanturan I believe thanks are visible if you look at the image's history page **when logged as the user who sent the thank**:
Screenshot from 2019-06-26 11-29-27
Thanks are kind of private information so they are not visible by other people, I believe.

**Comment by neslihanturan** [comment]
After @nicolas-raoul 's help I recognized thanks is actually working.
- The notification issue is solved. (+)
- Tests are solved (+)
- Category question is still brings us to next question. But we don't ask for thank if category problem exists. (-)
Can you please re-check @maskaravivek ?

**Comment by maskaravivek** [comment]
@neslihanturan Yes, makes sense we should probably show the next image. In #3038 was it a typo? You had mentioned that: 

```
Requests category check -> Brings next question
```

**Pull request merged**
