### PR TITLE
`CommonsApplication` migrate to kotlin & some lint fixes

### PR DESCRIPTION
**Pull request by parneet-guraya**
From [comment](https://github.com/commons-app/apps-android-commons/issues/5698#issuecomment-2424314890)

What changes did you make and why?

- Migrate application class to kotlin
- some lint fixes

**Tests performed (required)**

tested `betaDebug` & `prodDebug` on Oneplus 9RT 5G , Android 14

### CODE REVIEW

**Comment by parneet-guraya** [comment]
CI failing due to some unit test. Will fix it

**Comment by nicolas-raoul** [comment]
I did a few uploads and tried most activities of the app with this branch. It works as usual. :-)

**Comment by parneet-guraya** [comment]
Actually just one test failing due to `lateinit` `instance` property in application class, not being initialised while other tests do use that property and works fine :( . I'm a little rusty on testing, I will figure out what's causing this.

**Comment by parneet-guraya** [comment]
This test was causing the issue `ThanksClientTest`

https://github.com/commons-app/apps-android-commons/blob/f1205c19be7dccefc2b65f4d4c95bfb36c06c23c/app/src/test/kotlin/fr/free/nrw/commons/actions/ThanksClientTest.kt#L42

 `when()`  started raising error that it needs a call to a method on mocked instance. Now, in this case we were calling instance on static, `CommonsApplication.getInstance()`  was working fine when the class was in java but not when converted to kotlin. I'm guessing it's due to how to kotlin generate java impl internally such as it by default make properties `final` (I tried using `open` keyword` though). 

Most likely this is library issue. Also, from my research on stackoverflow mocking statics is discouraged. Also I found out `mockito`   [mockk](https://mockk.io/) supports kotlin by design didn't try it though. 

So, at the end I refactored the function to take application as an argument rather calling it inside.

**Comment by nicolas-raoul** [comment]
Thanks! Would you mind fixing the conflict?

**Comment by parneet-guraya** [comment]
Done

**Comment by parneet-guraya** [comment]
Waiting for this one #5887

**Comment by parneet-guraya** [comment]
Now that we have #5887 , this one's finally good to go. Give it a look whenever you can. I will have #5698 solution up after this.

**Comment by nicolas-raoul** [comment]
Thanks a lot! :-)

**Pull request merged**
