### PR TITLE
[WIP] Fixes #1244 (When selecting category, show sample images)

### LINKED ISSUE #1244: Show images from category
It can be hard to know whether you have found the right category just by its name.

The category could be for a different thing that bears the same name (and no category exists yet for the thing you took a picture of). Or you might have chosen a spelling different from the one used on Commons and the category is about something else. Or you might have a typo.

Solution: Show a few sample pictures from within the category. They could show as a popup whenever you select a category.

### PR DESCRIPTION
**Pull request by ujjwalagrawal17**
## Description (required)
Fixes #1244 (When selecting category, show sample images)
- Updated Design of categorization page
- Linked categorization with CategoryDetails page 

## Tests performed (required)

ManuallyTested on MOTO G5S+, with ProdDebug variant,

## Screenshots showing what changed (optional)
screenshot_20180802-171822

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Rotating the screen uploads the picture again, it seems.

**Comment by maskaravivek** [comment]
@ujjwalagrawal17 Am curious if this page is the same screen that is used while uploading images?

**Comment by ujjwalagrawal17** [comment]
Thanks @maskaravivek . We will try to complete #66 also. It would be even more nice then.

**Comment by nicolas-raoul** [comment]
It works great, but there is still a bug when rotating the screen.
Could you have a look? Thanks!

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul can we have a separate fix for this issue as this PR focusses on changing UI and adding support to view category details?

**Comment by nicolas-raoul** [comment]
@ujjwalagrawal17 Yes, a separate fix branch (from current 2.8-release branch) is needed.
Thanks! :-)

**Comment by ilgazer** [comment]
Maybe this could be merged with the upload-overhaul, I checked the code on this commit and porting this to the new UI doesn't look too complicated. On the other hand, would merging this with the upload overhaul make everything harder to test?

**Comment by maskaravivek** [comment]
Personally, I like the font size @ujjwalagrawal17 has used. It would be nice to have more opinions about it.

**Comment by misaochan** [comment]
The screenshot in the first post looks similar to the existing size if I'm not wrong? I guess if we are wanting users to tap on it, keeping the larger size would make it easier for them.

**Comment by ujjwalagrawal17** [comment]
Yup I haven't changed the font size. Also I am liking bigger font size.

**Comment by nicolas-raoul** [comment]
I would like to merge this, but rotating the screen still tries to re-upload the image.

**Comment by misaochan** [comment]
What is the status of this PR, @ujjwalagrawal17 ?

**Comment by ujjwalagrawal17** [comment]
Umm, actually I am quite busy these days due to preparations for Campus placements. I will be completing it in free time. work is left on this PR. Can we please have it on hold for sometime. Thanks

**Comment by misaochan** [comment]
Cool, thanks for the update. :)

**Comment by neslihanturan** [comment]
Up @ujjwalagrawal17 :) We are excited for this PR.

**Comment by ujjwalagrawal17** [comment]
@neslihan yup this will be a nice feature. I will try to find time to complete it soon.

**Comment by nicolas-raoul** [comment]
If I remember correctly this issue was about this PR: https://github.com/commons-app/apps-android-commons/issues/1867

**Comment by neslihanturan** [comment]
@albendz , do you still interested with this issue?

**Comment by neslihanturan** [comment]
Like the #1712 PR, this one also requires some work. But in general, nicely implemented. _I decided to note that since currently we have several beginner contributors who are looking for some tasks. IMO completing partially done tasks can be an option for beginners._

**Comment by ilgazer** [comment]
>But in general, nicely implemented

Thanks :)

> IMO completing partially done tasks can be an option for beginners.

I agree! That's how I started as well. By the way, I had added support for
removing non-exif metadata but as far as I remember, it is completely
broken. It could be better to remove that part but there may be metadata
that is not removed even if we remove all exif.

On Mar 18, 2019 3:14 PM, "neslihanturan" <notifications@github.com> wrote:

Like the #1712
<https://github.com/commons-app/apps-android-commons/pull/1712> PR, this
one also requires some work. But in general, nicely implemented. *I decided
to note that since currently we have several beginner contributors who are
looking for some tasks. IMO completing partially done tasks can be an
option for beginners.*

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/commons-app/apps-android-commons/pull/1784#issuecomment-473885470>,
or mute the thread

**Comment by noahwalugembe** [comment]
Is rotating the screen still tries to re-upload the image. If yes can i put it in my to do list . Am currently trying to close of an issue an i would like to try this as a next thing.

**Comment by noahwalugembe** [comment]
Is rotating the screen still tries to re-upload the image. If yes can i put it in my to do list . Am currently trying to close of an issue an i would like to try this as a next thing.

**Comment by nicolas-raoul** [comment]
@noahwalugembe The first step would be to make a branch on your side (on latest master), pull from this PR to the latest master, solve the conflicts, test a bit and send a new PR towards the ujjwalagrawal17:feat_issues_66 branch mentioning the issues you found. Thanks! :-)

**Comment by noahwalugembe** [comment]
> @noahwalugembe The first step would be to make a branch on your side (on latest master), pull from this PR to the latest master, solve the conflicts, test a bit and send a new PR towards the ujjwalagrawal17:feat_issues_66 branch mentioning the issues you found. Thanks! :-)

Okay am going to work on this now

**Comment by noahwalugembe** [comment]
dear @nicolas-raoul  its like am not able to reproduce this error (Rotating the screen uploads the picture again, it seems.) but instead am getting th
Screenshot_20190322-225712
Screenshot_20190322-225739

is

**Comment by ujjwalagrawal17** [comment]
Closing the PR as it is very old and needs more work to resolve so many conflicts than to open a new one. Also, the design of the already existing category details page while uploading seems similar.

**Pull request closed without merging**
