### PR TITLE
Fixes #3567: Logos in "About" screen are hardly visible in dark theme

### LINKED ISSUE #3567: Logos in "About" screen are hardly viisble in dark theme
**Summary:** 
The logos in About screen were recently changed in #3444. But the new logos are hardly visible in dark theme. We should show appropriate logos which are visible well in dark theme.

**Screen-shots:** 
Screenshot_2020-03-21-21-46-41

### PR DESCRIPTION
**Pull request by isnirp**
**Description (required)**
Fixes #3567 
What changes did you make and why?
Introduced an attr for the fill color of the logos in about screen

**Screenshots (for UI changes only)**
dark
default

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by sivaraam** [comment]
@isnirp Can you revert the unrelated changes in this PR, which seem to be part of another PR? Thanks.

**Comment by isnirp** [comment]
> @isnirp Can you revert the unrelated changes in this PR, which seem to be part of another PR? Thanks.

Hello @sivaraam thanks for your help today. I'm new to this PR stuff... I've been able to revert the unrelated changes.

**Comment by sivaraam** [comment]
> I'm new to this PR stuff...

That's fine. Everyone's new to it at some point of time. You'll get the idea of it over time :)

You could read the following articles to get a little idea:
* [About collaborative development models - GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-collaborative-development-models)
* [About pull requests - GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

> I've been able to rever the unrelated changes.

Thanks.

A couple of things:
1. Apologies before hand for being pedantic. Have you ensured that the official logos (which are the ones we should be using) distributed by GitHub and Facebook use the same colors that you've used?

    If you wish, you could see https://github.com/commons-app/apps-android-commons/issues/3567#issuecomment-604582741 to find links to the official logos.
2. Format your description as `Fixes #3567` to ensure the issue is automatically closed when the PR is merged. Kindly do the same for your other PR too. For more information, see [Linking a pull request to an issue - GitHub Help](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by isnirp** [comment]
Hello @sivaraam thanks for the information and the materials shared... I changed the color to white per the comment below. 
https://github.com/commons-app/apps-android-commons/issues/3567#issuecomment-604891899

But I can have it changed to the official ones. I can't find that of facebook though.

**Comment by isnirp** [comment]
> Thanks @isnirp looks good to me now:)

Thank you @neslihanturan :)

**Comment by neslihanturan** [comment]
I edited the description accordingly. Please review the docs shared by @sivaraam for next PR. And congratz for your first contribution :fireworks: :)

**Comment by isnirp** [comment]
> I edited the description accordingly. Please review the docs shared by @sivaraam for next PR. And congratz for your first contribution 🎆 :)

Thank you :)

**Comment by sivaraam** [comment]
> But I can have it changed to the official ones.

It's fine. I just checked and the color used in the light versions of the official icons is `#ffffff`. So, we're good.

> I can't find that of facebook though.

For future reference, they could be found at https://en.facebookbrand.com/facebookapp/assets/f-logo/?audience=landing

You can download them after checking the "I have read and accept the guidelines for use." box which enables the "Download" button.

**Comment by isnirp** [comment]
> > But I can have it changed to the official ones.
> 
> It's fine. I just checked and the color used in the light versions of the official icons is `#ffffff`. So, we're good.
> 
> > I can't find that of facebook though.
> 
> For future reference, they could be found at https://en.facebookbrand.com/facebookapp/assets/f-logo/?audience=landing
> 
> You can download them after checking the "I have read and accept the guidelines for use." box which enables the "Download" button.

Thank you @sivaraam

**Pull request merged**
