### PR TITLE
Feature/fix unit tests for #5262 ("Remove location" button for new uploads)

### LINKED ISSUE #5291: Fix unit tests for pull request  #5262
https://github.com/commons-app/apps-android-commons/pull/5262 introduces a useful feature, but makes two unit tests fail.

The task here is to fix these unit tests. Any volunteer? :-)

### PR DESCRIPTION
**Pull request by TomerPacific**
**Description (required)**
https://github.com/commons-app/apps-android-commons/pull/5262 introduces a useful feature, but makes two unit tests fail.
The two units tests that are failing are:

- testOnClickModifyLocation
- testOnStyleLoaded

Fixes #5291 

What changes did you make and why?

Added a variable to mock the newly added removeLocationButton

**Tests performed (required)**

Tested unit tests on an emulated device with API level 29

**Screenshots (for UI changes only)**
N/A

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks a lot for fixing the unit tests!

I just performed more real-world tests, and realized latitude/longitude are not actually removed from the EXIF of the picture. Hopefully this will be fixed soon and I will be able to merge. :-)

**Comment by TomerPacific** [comment]
@nicolas-raoul - Do you mind adding the hacktoberfet-accepted label?

**Comment by nicolas-raoul** [comment]
@TomerPacific

I added the label.
Sure, that would be wonderful! Feel free to create another branch, and pull from this branch into it.

**Comment by TomerPacific** [comment]
@nicolas-raoul - Can you elaborate on what the statement you made means:

> I just performed more real-world tests, and realized latitude/longitude are not actually removed from the EXIF of the picture.

What exactly did you try and what exactly did you see (and how)?

Thanks

**Comment by nicolas-raoul** [comment]
Sure!
I just added reproduction steps at https://github.com/commons-app/apps-android-commons/pull/5262#issuecomment-1762778826

**Comment by nicolas-raoul** [comment]
Please do not hesitate to comment at https://github.com/commons-app/apps-android-commons/pull/5262#issuecomment-1763551171 🙂

**Pull request closed without merging**
