### PR TITLE
Add missing annotations

### PR DESCRIPTION
**Pull request by akaita**
We should make sure we don't loose the information provided by annotations. This will make it easier to avoid NullPointerExceptions and make the app more robust 💪

### CODE REVIEW

**Comment by akaita** [comment]
Codacy complains about method signatures being longer than 100 character.
I can see some should be refactored as builders, some should be split into multiple lines, ...
I don't think it should, but should this PR include a refactor to make Codacy happy?

**Comment by misaochan** [comment]
I don't refactor some of my 100+ char lines either, so I'm good with code not adhering to that, within reason. :)

**Comment by misaochan** [comment]
Thanks for the great PRs, @akaita ! We'd like to add your name to the CREDITS.md, if you're okay with that. :) If so, what name would you prefer us to use?

**Comment by akaita** [comment]
Oh, thanks so much for the offering @misaochan !
`Mikel Pascual` is the official name :)

**Comment by misaochan** [comment]
No problems. :) Done!

**Pull request merged**
