### PR TITLE
Product flavors for production and the beta-cluster Wikimedia servers

### PR DESCRIPTION
**Pull request by psh**
I was able to log in to both production and beta clusters with the appropriate accounts.  Uploading and other API functions all work _except for_ getting my upload count - I didn't manage to track down the beta cluster equivalent of https://tools.wmflabs.org

Any ideas?  Want to merge as-is with the known issue and fix it later / live with it?

### CODE REVIEW

**Comment by janpio** [comment]
Awesome work!

**Comment by whym** [comment]
>  Uploading and other API functions all work except for getting my upload count - I didn't manage to track down the beta cluster equivalent of https://tools.wmflabs.org

It sounds like it would be fine if MediaWiki has an API call to report the upload count. Here is an upstream task for that: https://phabricator.wikimedia.org/T174312

**Comment by misaochan** [comment]
Wow, this is really cool, thanks @psh ! I'm not too familiar with the Wikimedia beta servers, but I'm guessing that if we run the `beta` product flavour, all uploads will go to the "beta" servers, which will solve the problem of having to upload real acceptable Commons photos for tests?

I haven't had time to test the PR yet, but IMO the upload count feature isn't essential for test uploads (I assume that the feature isn't broken for the "production" product flavour, just for the "beta" one?). So if someone tests this and all the other features work for them as well, I would be in favour of merging. :)

**Comment by janpio** [comment]
Person for the tools.wmflabs.org upload count tool could probably be contacted and asked to provide a second instance for the beta servers if anyone knows who it is and how to reach them.

**Comment by psh** [comment]
@misaochan You are correct, when you have the "beta" product flavor installed all of the API calls (including logging in, uploading, getting details) will all run against the beta-cluster.

Since there is an upstream dependency for the upload count, perhaps we can create an Issue to track that (and collect the info from @whym so it doesn't get lost) as it has no adverse affect on the productions product flavor.

**Comment by psh** [comment]
Note: if this is merged, I think it makes PR #555 invalid & we can close it.

**Comment by misaochan** [comment]
Sorry for the delay, @psh , it has been difficult to find time for testing. Hopefully if IEG approval comes, Neslihan and I can free up some time to go through the PRs.

**Comment by neslihanturan** [comment]
Hi @psh , thanks for this great PR. This will be great for our testing uploads. I just created an LDAP account, to test this PR. However, when I run the program on betaDebug mode, I wasn't able to login by using my LDAP username and psswd. Did I make something wrong?

**Comment by whym** [comment]
@neslihanturan did you try using your account on https://wikitech.wikimedia.org/ ? I believe it's supposed to be https://commons.wikimedia.beta.wmflabs.org .

**Comment by neslihanturan** [comment]
Thanks @whym , after your reply I was able to log-in and do whatever I want. According to my tests this PR works great, thanks @psh , we don't need to use real commons for testing any more (tears in my eyes)!

**Comment by misaochan** [comment]
Wonderful, thanks everyone! :) We should also probably add this to the wiki - something like "Manual testing - how to" perhaps?

**Pull request merged**
