### PR TITLE
Converted all the PNG to WebPs to save space.

### PR DESCRIPTION
**Pull request by akm0012**

### CODE REVIEW

**Comment by janpio** [comment]
May I ask what process you used to do this? Might need that myself.

**Comment by akm0012** [comment]
Sure, in Android Studio right click on the Resources folder and at the bottom there is an option to "Convert to WebP"

**Comment by janpio** [comment]
Ok, that _IS_ easy. Thanks.

**Comment by misaochan** [comment]
A question - https://developer.android.com/topic/performance/network-xfer.html says that WebP is only supported by API 17 and above, whereas our minSDK is 15. Is this going to be an issue for those who are using 16 and below?

**Comment by neslihanturan** [comment]
I agree to your question @misaochan . So, I am not sure about merging this PR.

**Comment by misaochan** [comment]
I don't think this PR can be merged the way it currently is, as AFAIK there is no way around the limitation. However, we can discuss if we want to change the minSDK to 17 (4.2.x) instead - it may or may not be worth the tradeoff. 

According to our Google Play page, currently 1.6% of our users are using lower versions than that. So unless WebP brings HUGE benefits, I would go with no unless a workaround can be found.

**Comment by psh** [comment]
I did a little poking around - 

* https://developer.android.com/guide/topics/media/media-formats.html
* http://tools.android.com/tech-docs/webp

Both pages say that WebP is supported back to API 14 for _lossy_ images _without transparency_.  The converter in Android Studio should be sensitive to min API

> If the minSdkVersion is less than 18, the flag to "skip images with transparency" is selected by default, so if you just press OK it will run through the project and convert images that *aren't* transparent. 

Assuming the conversion was done with that in mind, I dont expect there would be a problem.

That said, there might still be a case to be made for nudging the project's min API, but I don't think the introduction of WebP is necessarily the trigger for it!  😺

**Comment by neslihanturan** [comment]
Weird thing is both  @psh and @misaochan referenced from https://developer.android.com. However one says min required API level is 17, while the other says 14. 

I think we shouldn't change our min API level yet. But if this is not the case I don't see any problem with merging this patch. If you have, please raise your hands until tomorrow :)

**Comment by misaochan** [comment]
@neslihanturan I think @psh means that API 14 should support WebPs for lossy images without transparency, whereas API 17 is needed for all types of images. I think the best way to proceed from here would be to test this PR with an API 15 emulator (our minimum) and merge if all the images work on that.

**Comment by psh** [comment]
Thanks @misaochan - that's a much better and more succinct summation of what I was trying to say!  👍

**Comment by neslihanturan** [comment]
I have tested it on API 16 (4.1.2) device and works fine.

**Comment by misaochan** [comment]
Sounds good to me then. Fingers crossed.... :)

**Pull request merged**
