### PR TITLE
fixes After click on the image app is crashed (#4072)

### LINKED ISSUE #4072: Crash after opening media from the explore search
**Summary:** 
click on the image then app is crashed

Screenshot_2020-12-04-21-47-33-116_fr free nrw commons beta

**Steps to reproduce:** 
->click on explore 
 ->click on search icon search something 
->click on the result image 
What did you expect the app to do, and what did you see instead?
App does not crash when you click on Medai image

**Device and Android version:** 
Android Device:Redmi Y3
API:29

**Commons app version:** 
2.13.1~debug-issue15 ~b24ed1cf6

**Screen-shots:** 

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
**Description (required)**
Fixes #4072 

What changes did you make and why?
add an function setSupportActionBar(toolbar) in searchActivity.java becouse getSupportActionBar() function in MedaiDeatailsPageFragment.java give null object reference this cause to crash
 
**Tests performed (required)**
android Device :Redmi y3
API:29

**Screenshots (for UI changes only)**

### CODE REVIEW

**Comment by Prince-kushwaha** [comment]
anyone view my pullRequest

**Comment by Prince-kushwaha** [comment]
@ashishkumar0207 Hi

**Comment by Prince-kushwaha** [comment]
please review my pull request so i make another PR of another issue

**Comment by misaochan** [comment]
Thanks @Prince-kushwaha !

**Pull request merged**
