### PR TITLE
Backend overhaul fetch media by filename

### PR DESCRIPTION
**Pull request by ilgazer**
Migrated fetchMediaByFilename to retrofit as per #3026 

Also, the classes MwParseResponse and MwParseResult really belong to wikipedia dataclient. Should we submit a pull request or keep the classes within the app?

### CODE REVIEW

**Comment by maskaravivek** [comment]
> Migrated fetchMediaByFilename to retrofit as per #3026
> 
> Also, the classes MwParseResponse and MwParseResult really belong to wikipedia dataclient. Should we submit a pull request or keep the classes within the app?

We should submit a PR in the data-client

**Comment by maskaravivek** [comment]
> Migrated fetchMediaByFilename to retrofit as per #3026
> 
> Also, the classes MwParseResponse and MwParseResult really belong to wikipedia dataclient. Should we submit a pull request or keep the classes within the app?

They can belong in our app. :)

**Comment by ilgazer** [comment]
> They can belong in our app. :)

However, most of the migrations I have left require me to add fields to MwQueryResult instead of implementing new classes. It seems somewhat wasteful to copy and paste classes just to change little things. On the other hand, submitting PR's to wikipedia dataclient might make everything take a lot longer.

**Comment by nicolas-raoul** [comment]
> submitting PR's to wikipedia dataclient might make everything take a lot longer

I don't know what you guys are talking about, but just a tip:
You can easily fork dataclient, modify it as you like, and use that version in build.gradle while waiting for the PRs to be merged. We already do that for some other libraries.

**Comment by ilgazer** [comment]
Does Travis failing with this error have anything to do with my PR?

Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000eefef000, 38871040, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 38871040 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/travis/build/commons-app/apps-android-commons/app/hs_err_pid6656.log
> Task :app:testProdDebugUnitTest FAILED
FAILURE: Build failed with an exception.

**Comment by ilgazer** [comment]
> and use that version in build.gradle

How can I do that? Do I deploy my own maven repository?

**Comment by nicolas-raoul** [comment]
No need, just open your build.gradle and see how I did for `com.github.nicolas-raoul:Quadtree:ac16ea8035bf07`, I did not deploy anything, I just pushed to my GitHub :-)

**Comment by ilgazer** [comment]
Ooh, that's cool :)

**Comment by maskaravivek** [comment]
> > They can belong in our app. :)
> 
> However, most of the migrations I have left require me to add fields to MwQueryResult instead of implementing new classes. It seems somewhat wasteful to copy and paste classes just to change little things. On the other hand, submitting PR's to wikipedia dataclient might make everything take a lot longer.

Yes, for any class that already exists in the data client, we should add attribute to the library itself instead of copying the class to our app. But if we are adding a completely new response, we can add the response in the app itself. :)

**Comment by maskaravivek** [comment]
Please add test cases for the PR. :)

**Comment by ilgazer** [comment]
> Please add test cases for the PR. :)

Done :)

**Comment by maskaravivek** [comment]
@ilgazer Can you resolve merge conflicts so that the PR can be merged :)

**Comment by maskaravivek** [comment]
@ilgazer reminder:)

**Comment by ilgazer** [comment]
I'm sorry for the delay, I am starting at a university this fall, and the preparation, the prep exam etc. along with other personal projects took up all my time. The conflicts are resolved :)

**Pull request merged**
