### PR TITLE
Remove CSV option for nearby places

### LINKED ISSUE #979: Remove option to load from CSV for Nearby
The "load from CSV" option is a relic of our initial Nearby prototype before we switched to using Wikidata queries. Personally, I think Wikidata is superior in all aspects and I have never used the CSV option after Wikidata implementation because the CSV takes about 5 minutes to load each time. Nobody that I have talked to currently uses the CSV either.

We were discussing removing the CSV entirely at #291 , and some were supportive of it. Benefits of removing the option in my opinion:
- Simplifies the implementation of further Nearby enhancements (e.g. direct uploads)
- Allows us to close all issues caused by the CSV without wasting developer time solving them
- Prevents potential cases of a user accidentally tapping that option in Settings and then wondering why Nearby takes forever to load for him
- Simplifies testing

What do you guys think? Is there anyone here who would prefer we keep the CSV option?

### PR DESCRIPTION
**Pull request by maskaravivek**
Fixes #979. 

Have simply made a PR for the discussion going on in #979. It can be merged if there's no opposition on removing the CSV.

### CODE REVIEW

**Comment by misaochan** [comment]
Looks good to me, happy to merge once it has been tested :)

**Comment by maskaravivek** [comment]
@neslihanturan I guess this can be merged.

**Comment by misaochan** [comment]
So sorry this has been left for so long, @maskaravivek . If you could kindly submit this to the `directNearbyUploads` branch instead, I can merge immediately and use your changes as the basis for our next steps in that feature branch.

**Comment by neslihanturan** [comment]
I guess travis issue is not related with this pr. So happy to merge it, thanks  @maskaravivek

**Pull request merged**
