### PR TITLE
Change item background according to the theme

### LINKED ISSUE #3474: Items in Place type list in Nearby become unreadable on unselecting
**Summary:** 

Background of items in Place type list in Nearby becomes white on unselecting. Since the text is also white, the item becomes unreadable. This only happens in the dark theme.

**How can we reproduce the issue?** 

Enable dark theme. Open Nearby. Tap on the search option in front of Place type. If you tap once on any item, the background becomes light grey. Tap the same item again, i.e., unselect it, and the background becomes completely white.

**What did you expect the app to do, and what did you see instead?**

I expected the item's background colour to change to what it was before I had selected it, i.e., black.

**Device and Android version:** 

Redmi Note 5 Pro
MIUI version 11
Android 9
 
**Commons app version:** 

2.12.3-debug
master and betaDebug

**Screen-shots:** 

_Default_

image

_Tap once to select item_

image

_Tap again to unselect_

image

**Would you like to work on the issue?**

Yes, I'd like to work on this.

### PR DESCRIPTION
**Pull request by 6point022**
**Description (required)**

Fixes #3474 - Items in Place type list in Nearby become unreadable on unselecting

**What changes did you make and why?**

Added a conditional operator that sets the background colour of the item based on the theme.

**Tests performed (required)**

Tested betaDebug on Redmi Note 5 Pro with API level 28.

**Screenshot**

_The item background is highlighted on selecting and becomes black on unselecting._

gif1

### CODE REVIEW

**Comment by maskaravivek** [comment]
@6point022 can you attach screenshots.

**Comment by 6point022** [comment]
@maskaravivek I have edited the PR description to add a gif that shows the change. :)

**Comment by macgills** [comment]
The text is nearly unreadable while selected, could you fix that as well, while we are changing things in this file?
Also the responsibility of handling color states in response to interaction is usually done via a `selector` in xml

**Comment by 6point022** [comment]
> The text is nearly unreadable while selected, could you fix that as well, while we are changing things in this file?

@macgills Here's how it looks after the change.

image

> Also the responsibility of handling color states in response to interaction is usually done via a selector in xml

I have replaced the colour values to use the values from xml. 

I also replaced a conditional operator with an if-else condition because two conditional operators in one line were getting too complicated.

**Comment by macgills** [comment]
@6point022 looks a lot better thanks.

When I mentioned xml I meant to use a selector xml file, example [here](https://developer.android.com/guide/topics/resources/color-list-resource)

**Comment by 6point022** [comment]
@macgills I have implemented XML selectors to change the background colours. Please review.

**Pull request merged**
