### PR TITLE
Removed telemetry - Bug #5154

### LINKED ISSUE #5154: [Bug]: Remove Telemetry due to app's privacy policy
### Summary

Telemetry is often used to monitor the performance of applications, track usage patterns, and gather other data that can help developers improve their products. This data can be used to identify and diagnose issues, track trends, and make informed decisions about product development. However, due to the app's privacy, we would want to remove Telemetry from the app.

The issue is created as advised in [this comment](https://github.com/commons-app/apps-android-commons/issues/4994#issuecomment-1432296875).

### Steps to reproduce

1. Have the app open
2. Go to More
3. Go to settings
4. Under the Privacy section, see Mapbox Telemetry

### Expected behaviour

There should be no trace of telemetry in the code and app.

### Actual behaviour

As of now, the users have an option to opt-in or out of telemetry but we want it to be removed. Currently, there are traces of telemetry in the code. 

### Device name

Pixel 6

### Android version

Android 33

### Commons app version

4.0.3

### Device logs

_No response_

### Screen-shots

_No response_

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by kartikaykaushik14**
**Description (required)**

Fixes #5154 

What changes did you make and why? 

Removed Telemetry dependency and its usages.

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
I am getting the following crash with this pull request when going to the Nearby activity, any idea why? It does not happen on master, it seems.
```
02-26 08:08:10.331  9097  9097 W ree.nrw.commons: Accessing hidden field Landroid/view/View;->mViewFlags:I (max-target-p, reflection, denied)
02-26 08:08:10.331  9097  9097 I ViewUtils: fetchViewFlagsField: 
02-26 08:08:10.388  9097  9097 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-26 08:08:10.388  9097  9097 W ree.nrw.commons: Accessing hidden method Landroid/widget/AutoCompleteTextView;->doBeforeTextChanged()V (max-target-p, reflection, denied)
02-26 08:08:10.388  9097  9097 W ree.nrw.commons: Accessing hidden method Landroid/widget/AutoCompleteTextView;->doAfterTextChanged()V (max-target-p, reflection, denied)
02-26 08:08:10.388  9097  9097 W ree.nrw.commons: Accessing hidden method Landroid/widget/AutoCompleteTextView;->ensureImeVisible(Z)V (max-target-p, reflection, denied)
02-26 08:08:10.402 18469 18469 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.api.credentials.internal_service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsInternalBoundBrokerService }
02-26 08:08:10.412  9097  9097 W ree.nrw.commons: Accessing hidden field Landroid/graphics/Typeface;->sSystemFontMap:Ljava/util/Map; (unsupported, reflection, allowed)
02-26 08:08:10.435 18469 18469 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.mdd.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
02-26 08:08:10.441  9097  9097 D AndroidRuntime: Shutting down VM
02-26 08:08:10.442  9097  9097 E AndroidRuntime: FATAL EXCEPTION: main
02-26 08:08:10.442  9097  9097 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 9097
02-26 08:08:10.442  9097  9097 E AndroidRuntime: java.lang.SecurityException: getDataNetworkTypeForSubscriber
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8593)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3035)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2999)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:165)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.onViewCreated(NearbyParentFragment.java:313)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-26 08:08:10.442  9097  9097 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by kartikaykaushik14** [comment]
This seems to be a permission issue for READ_PHONE_STATE. Can we try to retry again with the new changes?

**Comment by nicolas-raoul** [comment]
I am still getting the same crash, unfortunately. Not 100% sure it is because of this pull request, but not getting the crash on master, I tried again.

**Comment by nicolas-raoul** [comment]
Are you able to reproduce the crash?
It looks very similar to https://github.com/mapbox/mapbox-navigation-android/issues/3577 whose workaround was to add telemetry. This bug was apparently fixed so maybe we can fix it by updating Mapbox or something? Or maybe skip the whole thing and migrate directly to another solution?
Thanks! :-)

**Comment by kartikaykaushik14** [comment]
I was able to reproduce the crash. We can resolve this issue by using mapbox sdk version 9.4.0. Though, it calls the required version of telemetry as a transitive dependency. 

As of now, to comply with the app's privacy policy, I have disabled telemetry in the code. Earlier users had an option to opt-in or out of it, but post these changes it would be opted out always and users do not require the option to change it.

**Review by nicolas-raoul — APPROVED** [review]
Looks good to me!
Tested, the maps work fine in Nearby, Explore, upload wizard, media details location editor.

**Pull request merged**
