### PR TITLE
Fixed crashing in ExploreListRootFragment

### LINKED ISSUE #4224: App crashes in ExploreListRootFragment
**Summary:** 

On clicking the last image in **ExploreListRootFragment** the app crashes with **IndexOutOfBoundsException**

**Steps to reproduce:** 

• Go to Explore tab from Bottom Navigation Bar.
• Clicking on the last image in Featured tab causes the app to crash.

**System logs:**

> 2021-02-12 13:11:00.128 26125-26125/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 26125
    java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
        at androidx.paging.PagedStorage.get(PagedStorage.java:138)
        at androidx.paging.PagedList.get(PagedList.java:410)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getMediaAtPosition(PageableMediaFragment.kt:49)
        at fr.free.nrw.commons.explore.ExploreListRootFragment.getMediaAtPosition(ExploreListRootFragment.java:127)
        at fr.free.nrw.commons.media.MediaDetailFragment.onResume(MediaDetailFragment.java:293)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:363)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1197)

**Device and Android version:** 
• Device (Redmi Note 7S)
• Android (Android 10)

**Screenshots**

https://user-images.githubusercontent.com/65870389/107845041-8d9e1380-6dfe-11eb-897f-c0f3206af66b.mp4

**Would you like to work on the issue?**
I want to work on this issue.

### PR DESCRIPTION
**Pull request by mrudultora**
**Description (required)**

Fixes #4224 

What changes did you make and why?
I changed the **if** condition and added a check that whether the index passing to list is valid or not (i.e. index is less than the size of list). Also, if the index is invalid then prevented displaying the media details. 

**Tests performed (required)**
Tested {betaDebug} on {Redmi Note 7S} with API level {29}.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hmm, even if this looks like a valid solution to prevent the issue, I would rather prefer to find the root cause. Did you find anything about what may be causing that idex is not valid sometimes?

**Comment by mrudultora** [comment]
@neslihanturan I logged the indexes and let's assume you clicked on first image. (In the logs 5 indices were printed 0,0,1,0,0). So, here we can see that on clicking the image at zeroth position the index of image at second position was also called. Similarly if we click on the last image, index of **last+1** is called and its invalid i.e., causing the IndexOutOfBoundsException.

**Comment by neslihanturan** [comment]
> @neslihanturan I logged the indexes and let's assume you clicked on first image. (In the logs 5 indices were printed 0,0,1,0,0). So, here we can see that on clicking the image at zeroth position the index of image at second position was also called. Similarly if we click on the last image, index of **last+1** is called and its invalid i.e., causing the IndexOutOfBoundsException.
> This is not the exact explaination of root cause ;-)

Hmm what does these 5 indices indicates?

**Comment by mrudultora** [comment]
This indicates that `getMediaAtPosition` is called 5 times for a single image. And in this calling sometimes the value of **i** changes. And the value of **i** is coming from api. So, may be the problem lies there. I am unable to determine what causes `getMediaAtPosition` to be called 5 times.

**Comment by mrudultora** [comment]
@neslihanturan  Nicolas has closed the issue, but I think changes I made are better. They will prevent any such problem in future. And I guess, there are chances of this issue to happen in coming future. Your views ?

**Comment by neslihanturan** [comment]
Hey @mrudultora , thanks for the PR. However, I believe we should solve the root cause instead of silencing the alert. Anyway, your comments and investigation here will help to solve the issue. I will link them to issue page too.

**Pull request closed without merging**
