### PR TITLE
[WIP] Wikimedia hackathon 2018

### LINKED ISSUE #2253: Include previous hackathon work to our master
**Summary:**

We should include previous hackathon's task which is mostly ready to be merged to master, preferably before next hackathon :)

### PR DESCRIPTION
**Pull request by silkypriya**
Wikimedia hackathon 2018

Fixes #2253  Include previous hackathon work to our master

**What changes did you make and why?**

As per the discussion on #2253 

1. Added some explanation to emphasize what will happen if I click to Yes.

2. Added SKIP THIS IMAGE button.

3. Changed button text and colour. 

First question             |  Last question
:-------------------------:|:-------------------------:
scope | thanku

4. Added line to show the current categories on the same page while asking to review the categories.

If categorized            |  If not categorized
:-------------------------:|:-------------------------:
with category | without category

5. "Seems fine" leads the user to the next question. User can also swip to next or previous question using 
    pageindicator.

**Tests performed**

Tested betaDebug on Realme 2 pro (Android Version 8.1.0) with API level 27.

### CODE REVIEW

**Comment by silkypriya** [comment]
Hello @nicolas-raoul @neslihanturan @maskaravivek 

May I proceed for fixing following issues?

There are some issues related with this -

1. Fix night mode issues - Text and button colour does not change in dark mode making it hard to see.
                                                 
2. Fix landscape mode issues - Make scrollable layout for better fit in landscape mode. 
                                                     
3. Make image clickable  - Open media details activity when clicked. Third point mentioned in <a href="https://github.com/commons-app/apps-android-commons/issues/2253#issuecomment-450715009">comment</a>

4. Show the popup is editable   -  Fifth point mentioned in <a href="https://github.com/commons-app/apps-android-commons/issues/2253#issuecomment-450715009">comment</a>       

Kindly review the changes so far. 
Thank you!

**Comment by silkypriya** [comment]
The idea to let user categorize the image in case he finds the image is mis-categorized, is not implemented. Yes ,this can be done in later phase. Currently it request for category check. I will change the button text accordingly.
Thank you! @nicolas-raoul for your help.

**Comment by nicolas-raoul** [comment]
I see! Then I would suggest this wording: "Yes, mis-categorized".

**Comment by nicolas-raoul** [comment]
A large proportion of images have zero categories, unfortunately. For these, I would suggest not even showing the categories peer review screen, because images without categories already get marked appropriately after they are uploaded.

**Comment by silkypriya** [comment]
Okay @nicolas-raoul, showing the category review page screen only with images been categorized,would be noice.
Thank you!

**Comment by domdomegg** [comment]
Also some more feedback is maybe to simplify the language - there are a lot of negatives around which are confusing.

E.g. changing questions to be more like:
- Is this image correctly categorized?
- No, edit categories
- Yes

This to me would seem more natural, as the positive (green and to the right and the 'it's fine' case) has positive wording.

**Comment by silkypriya** [comment]
Thank you! @nicolas-raoul , @domdomegg  

Changed the text and fixed dark mode issues.

Screenshots of the result.

 First                   | Second               
:-------------------------:|:-------------------------:
a1 | a3

 Third                   | Forth                
:-------------------------:|:-------------------------:
 a2 | a4 


 Night mode | Night mode 
:-------------------------:|:-------------------------:
b1 | b4

**Comment by silkypriya** [comment]
For Issue - "On clicking NO, a popup shows with some pre-written text. User didn't realize that it is editable."

Is the "EditText Blinking Cursor" is sufficient to show that popup is editable. 
popup

Other possible ways
- Open keyboard along with popup  
- Provide a selectable list of reasons #1824 

Thank you!

**Comment by domdomegg** [comment]
> For Issue - "On clicking NO, a popup shows with some pre-written text. User didn't realize that it is editable."
> 
> Is the "EditText Blinking Cursor" is sufficient to show that popup is editable.
> 
> popup
> 
> Other possible ways
> 
> * Open keyboard along with popup
> * Provide a selectable list of reasons #1824
> 
> Thank you!

I think have the keyboard pop-up, and also maybe have the field blank with what you've got in the screenshot or similar as the hint text. Alternatively the selectable list of reasons is quite good too.

**Comment by nicolas-raoul** [comment]
Nice!
Minor correction: "A random photo from internet, a famous brand logo etc" -> "Logos, screenshots, movie posters are often copyright violations."

**Comment by neslihanturan** [comment]
I loved it @silkypriya , fast and great job:)  I didn't dive into the code yet, but by looking the UI I can add:
- Adding a question mark next to "skip this image" button which will display an explanation about usage of the buton
- Adding another question mark next to Peer Review title (open for discussion) to explain what does this feature do and to underline it is a beta feature.

**Comment by domdomegg** [comment]
> I loved it @silkypriya , fast and great job:) I didn't dive into the code yet, but by looking the UI I can add:
> 
> * Adding a question mark next to "skip this image" button which will display an explanation about usage of the buton
> * Adding another question mark next to Peer Review title (open for discussion) to explain what does this feature do and to underline it is a beta feature.
> 
> And of course, fixing conflicts would be nice:)

I agree with maybe adding information on the feature generally, but think the 'skip this image' option is self-explanatory. Maybe feedback from others?

**Comment by neslihanturan** [comment]
The next image will be loaded randomly, but it will be a recent mobile
update. So I think this can be explained on Skip this image button
explanation.

**Comment by silkypriya** [comment]
Thank you! @nicolas-raoul @domdomegg @neslihanturan 

For the above discussion, can we use "information icon image" in place of "?" similar as in achievement activity to explain what the button does?
Or we can also have information icon image in toolbar explaining the entire flow of this feature.

These are the further changes made

1. Rewording : "A random photo from internet, a famous brand logo etc" -> "Logos, screenshots, 
    movie posters are often copyright violations." and also "NO" -> "NO, MIS-CATEGORIZED".

2. Fixed landscape mode issues. Now it is scrollable in landscape mode.

ezgif com-video-to-gif

3. Added selectable list of reasons in popup 

Screenshot of the result : 

First page            |  Second page 
:-------------------------:|:-------------------------:
 |

**Comment by neslihanturan** [comment]
Hi @silkypriya , can you please fix conflicts?

**Comment by silkypriya** [comment]
Hello @neslihanturan 
I need to fix some error i got while updating my branch with master. I need some time in order to fix the build. I will try to fix it by tomorrow. 
Thank you!

**Comment by domdomegg** [comment]
I think the styles are a bit broken in places so it does still need some attention but hopefully that merge helps.

**Comment by silkypriya** [comment]
Thank you! @domdomegg for your help.

**Comment by neslihanturan** [comment]
I have tested this one, will bee happy to merge after conflicts are fixed. The issues @domdomegg mentined should be fixed after merge:) Thanks @silkypriya

**Comment by neslihanturan** [comment]
Thanks @silkypriya !

**Comment by silkypriya** [comment]
Thankyou! @neslihanturan 

Somes issues left for discussion and implementation.
1. Make image clickable - Open media details activity when clicked. 

2. Not showing the categories peer review screen for the images having zero categories.
   Or let the user categorize the image.

3. Adding a question mark next to "skip this image" button and Peer Review title which will display an 
    explanation about their usage.

Can we have separate issue for theses issues ?
Thank you !

**Comment by nicolas-raoul** [comment]
Yes sure, please create the relevant issues, thanks! :-)

**Comment by neslihanturan** [comment]
Actually they are already added to #2698 , please wrtie comment if you can to take some of them @silkypriya :)

**Comment by silkypriya** [comment]
Thank you! @neslihanturan ,
Currently I have two tasks on. After finishing them I would love to start with this, thankyou!

**Pull request merged**
