### PR TITLE
Update logos in the About page

### LINKED ISSUE #3444: Updating Logos for Github, Facebook and Website in About Activity
**Summary:** 
I think we should be using the latest logos from Facebook and Github for About Activity.

Screenshot_1583107062

### PR DESCRIPTION
**Pull request by 6point022**
**Description (required)**

Updated the website, Facebook and Github logos in the About page.

Fixes #3444 - Updating Logos for Github, Facebook and Website in About Activity

**What changes did you make and why?**

Created vector assets from the Material Design _globe icon_ (official name - _public_), the new Facebook and Github logos, and replaced the old vectors in the drawable folder with these.

**Tests performed (required)**

Tested betaDebug on Redmi Note 5 Pro with API level 28.

**Screenshots showing what changed (optional - for UI changes)**

image

### CODE REVIEW

**Comment by 6point022** [comment]
Thanks a lot for the feedback, @domdomegg.

> I'd like to double check that these comply with brand guidelines set by GitHub and Facebook - where did you source these logos and if they have any restrictions on their usage do you have links to that information?

Source for Github logo: https://github.com/logos
Source for Facebook logo: https://en.facebookbrand.com/facebookapp/assets/f-logo?audience=landing

Both have some Do's and Don'ts mentioned at the above links, and I think I have adhered to those.

> Also, I might just be going crazy but it looks like the globe icon has a smaller radius than the other ones (which makes it look unbalanced) - can you check this too please?

You're right! I notice this too now. However, I can't seem to get them to be the exact same size.

This is how it looks right now:

image

Notice the website icon's bigger gap from the top of the ImageView.

I have tried increasing this vector's height and width but nothing seems to work. 

One way I have found is to just add some top padding to the other two, i.e., Facebook and Github logos.

_Screenshot of Android Studio preview after adding padding._

image

_Screenshot of the activity in phone after adding padding._

image

Still, I am not sure if this is a good way to do this. But in case this is fine, please let me know and I will push those changes. I really appreciate any help and inputs!

**Comment by domdomegg** [comment]
Maybe for the globe icon try this asset: https://drive.google.com/file/d/1DOd6VUULe6rxQPFpsMT-2qxyhgEruGo0/view?usp=sharing

I've cropped it so it has the bounding box just around the circle, without padding.

**Comment by 6point022** [comment]
@domdomegg I think it looks perfect now. 

image

It was quite a challenge though. 😛  I couldn't convert this cropped svg to a vector asset using Android Studio, it was showing an error. Apparently, it doesn't parse a svg with decimal values. I tried using online converters, but the generated xml didn't show anything at all in Studio. Finally, I converted the svg to png and then that png to svg (got rid of all the decimal values), AND IT WORKED! 😄

**Comment by domdomegg** [comment]
(I'll merge it once Travis completes - please remind me if I forget :))

**Comment by misaochan** [comment]
Well done @6point022 ! :)

**Pull request merged**
