### PR TITLE
Remove unused drawables

### PR DESCRIPTION
**Pull request by veyndan**

### CODE REVIEW

**Comment by veyndan** [comment]
These icons aren't referenced anywhere in the code. This is easily verifiable by going to the master branch and doing Right click > Find Usages. For each of them it says that there are "No usages found in Project Files".

**Comment by misaochan** [comment]
Odd, I wonder what they were put there for in the first place. @nicolas-raoul , what do you think?

**Comment by nicolas-raoul** [comment]
Sorry I don't know!
But if the app runs fine without, better remove them :-)

**Comment by misaochan** [comment]
Yeah, I'm good with it if it has been tested.

**Comment by maskaravivek** [comment]
Was looking at android documentation for [supporting multiple screen sizes](https://developer.android.com/guide/practices/screens_support.html) but couldn't figure out if these drawables are actually being used or not while building the prod APK for the app. As far as I knew it was recommended to have atleast all these 5 drawable sizes in your project. But I could find anything to ascertain that they are actually being used. Anyways This looks [interesting](http://stackoverflow.com/questions/37583151/how-to-specify-icons-for-different-densities-screen).

It would be great if someone could test it before merging.

**Comment by veyndan** [comment]
I agree that it is important to include icons for different screen densities. However, these icons aren't being referenced anywhere in the code/xml so we are currently packaging these icons into the APK but are never displaying it to the user. This is all verifiable through the method noted in my first comment and this commit has nothing to do with screen densities as these icons aren't going to be shown regardless of the screen density.

**Comment by veyndan** [comment]
I did a bit of searching and found that many of the icons that are being deleted in this commit were added in 65753550e31b4244d1d91d8ac33864652c56045f. These icons were all referenced in [`styles.xml`](https://github.com/commons-app/apps-android-commons/commit/65753550e31b4244d1d91d8ac33864652c56045f#diff-6f870d7e261f41dd3e52a2a129fa1fc5) of that commit. Later on `styles.xml` was modified in 2fe21253b4ae48dbecf09c9e7137123ad9d18eea and the references to those icons were removed and were replaced with references to other icons. Therefore, the drawables being deleted in this commit shouldn't have any change on the app.

**Pull request merged**
