### PR TITLE
Define a custom TextView that displays HTML

### PR DESCRIPTION
**Pull request by veyndan**
This makes the layout file `activity_about.xml` more declarative as we are defining that Html text is going to be displayed. This also modularises the Html TextView's as we aren't defining the behaviour in `AboutActivity`.

### CODE REVIEW

**Comment by veyndan** [comment]
The codacy check fails due to a lack of Javadoc on the constructor. I feel that it is self explanatory as to what it is doing as this constructor is a common idiom among view creation. Does anyone know how to suppress the check with `@SuppressWarnings(…)`?

**Comment by whym** [comment]
I agree that it's not difficult understand without javadoc, but on the other hand, this app is maintained by volunteers with different levels of familiarity to Android. So I tend to think having javadoc here is slightly better, even if it's effectively just a link to https://developer.android.com/training/custom-views/create-view.html#subclassview .

That said, I do think this is good enough. It's just a matter of making it better now or later.

**Comment by veyndan** [comment]
This app isn't a showcase on how Android works but is just a normal app. Therefore I feel that it is fine to assume that people contributing have an understanding of the Android framework and if need be they can always Google things they don't understand. We don't document standard Java constructs, so I don't think it'd be right to do it for Android. If we documented simple stuff like instantiating Views, then our documentation wouldn't be helpful and just be bloated. Even looking at the implementation of `TextView`, there is no javadoc stating how to instantiate such a class.

**Comment by whym** [comment]
Okay, the link to the developer's guide may not be as good as I initially thought. (I was almost asleep by that time, sorry.)

To put it differently - this may be akin to cases you would use @Override. @Override is kind of a substitute to javadoc, because you can assume that you can rely on the super class's javadoc instead. (And it is treated as a substitute by our current checkstyle confuguration.)

**Comment by veyndan** [comment]
Yes I agree, that also abides by the Java style guide: https://google.github.io/styleguide/javaguide.html#s7.3.2-javadoc-exception-overrides. It states that it is an exception for methods, but I assume they would include constructors in this exception as well.

**Comment by whym** [comment]
The Override annotation doesn't seem to be applicable to constructors, though.
As a substitute, would you disagree with having something like this?

```
    /**
     * @see android.view.View#View(Context, AttributeSet)
     */
```

Again it's okay to leave this issue for future - I just feel like something live above could be a nice thing to have rather than redundant.

**Comment by veyndan** [comment]
As per the Google Java style guide, it also states that [Javadoc is not required for self explanatory methods](https://google.github.io/styleguide/javaguide.html#s7.3.1-javadoc-exception-self-explanatory). Again I would extend that to self explanatory constructors, which I would say this is. However, that is all subjective. I don't have too much of a gripe with the suggested Javadoc but I still feel it is unnecessary. Maybe if some other people could chime in then it'd be more obvious as to which direction the project's code style should take. Note that we aren't actually instantiating this class from Java code, and I don't see any reason as to why we would call this constructor if we did (we'd call `HtmlTextView(Context)`, something which has deliberately been omitted such that if it is required it isn't done too hastily as views defined in XML are preferable).

I don't mind if we continue to discuss this before or after this is merged.

**Comment by misaochan** [comment]
Shall I merge and we continue this discussion after, perhaps in the form of an issue?

**Comment by veyndan** [comment]
That's good with me

**Comment by whym** [comment]
Fine by me too

**Pull request merged**
