### PR TITLE
Fixes #1472

### LINKED ISSUE #1472: Remove deprecated setDestination(Object)
Steps to reproduce

1. Build project
2. Check build info.
We need to change ConfigurableReport.setDestination(Object) to ConfigurableReport.setDestination(File) as former method  is deprecated.

Would you like to work on the issue?
Yes, I would love to work on this issue.

### PR DESCRIPTION
**Pull request by gupta1anubhav**
Fixes #1472 
Deprecation removed

### CODE REVIEW

**Comment by gupta1anubhav** [comment]
plz review @misaochan @nicolas-raoul

**Comment by gupta1anubhav** [comment]
@maskaravivek Plz review the pr

**Comment by misaochan** [comment]
@gupta1anubhav We appreciate the PR, but please be patient. :) The team is pretty busy and backlogged, so generally PRs will take a bit of time to go through.

**Comment by gupta1anubhav** [comment]
@misaochan ok, now I understand

**Comment by gupta1anubhav** [comment]
@misaochan any update?

**Comment by maskaravivek** [comment]
@gupta1anubhav Can you explain what the PR does and how it fixes the issue. Right now i can only guess. :)

**Comment by gupta1anubhav** [comment]
change ConfigurableReport.setDestination(Object) to ConfigurableReport.setDestination(File) as former method is deprecated

**Pull request merged**
