### PR TITLE
Fixed #3500 Error Message for uploading with an already existing title is wrong

### LINKED ISSUE #3500: Error Message for uploading with an already existing title is wrong
**Summary:** 

Try to upload on beta with a title "t" and a dark image. You see the message "title is empty" when it actually already exists
 
**Commons app version:** 

master

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
**Description (required)**
Fixed #3500 Error Message for uploading with an already existing title is wrong

What changes did you make and why?
Fixed bitwise operations in ImageUtils, adapted handleBadImage() method.

**Tests performed (required)**
Tested betaDebug on emulator with API level 28.

### CODE REVIEW

**Comment by macgills** [comment]
I try to upload a dark image, it gives me "title already exists, do you want to proceed", I hit yes and then it doesn't proceed.

**Comment by VitalyVPinchuk** [comment]
Sure I'll check it as soon as beta server is back online

**Comment by macgills** [comment]
@VitalyVPinchuk this can be checked on prod, you don't have to upload anything to repro it

**Comment by VitalyVPinchuk** [comment]
@macgills sorry, my fault. Fixed.

**Comment by VitalyVPinchuk** [comment]
Any feedback or improvements?

**Comment by macgills** [comment]
@VitalyVPinchuk see the discussion on the ticket, we might be abandoning this for a more comprehensive fix

**Pull request closed without merging**
