### PR TITLE
Fixed bug #1399 Overlapping problem

### LINKED ISSUE #1399: Place description getting overlapped with plus fab button Nearby Activity
**Summary:** 

For some place description while clicking on the marker gets overlapped with plus fab button

**Steps to reproduce:** 
Click on any marker place which has a large description.

**Expected behavior:** 

It should not overlap.

**Observed behavior:** 

bug 8

**Device and Android version:** 

Moto g4 plus Android 7.0.0
 
 **Commons app version:** 

2.7.0

**Would you like to work on the issue?**
Yes I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Jatin0312**
## Description

Fixes #1399 

1. Removed overlapping problem for the bottom sheet view for large title of places.
2. Changed Linear Layout height from 72dp to wrap_content to accomodate title which crosses more than three lines or else it will get hidden.

## Tests performed
Moto g4 plus Android 7.0.0

## Screenshots showing what changed
 
whatsapp image 2018-04-01 at 11 49 05 pm
whatsapp image 2018-04-01 at 11 48 54 pm

### CODE REVIEW

**Comment by neslihanturan** [comment]
@Jatin0312 thanks for fast PR:) But I have some questions:
- Why changing so much thing, while the problem is only related with TextView, are all of them needed? 
- Besides, setting dp may not be a good practice for all screen sizes. Ie. my test results on my tablet are as:
Before: 
device-2018-04-02-171010
After:
device-2018-04-02-170655
See, there are so many empty space on left. What about just setting some margin to right side of textview?

Besides, as you can see from my screenshoot2, bottom can be problematic if we add line breaks. We can not change height of the bottom sheet when it is collapsed. So there are two options:
- Adding scrollview
- Adding three dot.
I would add "..." when bottom sheet collapsed and display full text with line breaks when it is expanded.

**Comment by Jatin0312** [comment]
1. Ya, I tried adding scroll view but it hampered the click function and was becoming kind of unusable so better option would be adding three dots. But I will try both ways to ensure usability.
2. Ok, sure I will fix the height of bottom sheet when collapsed and change the size of text view accordingly using margin right.
3. With Linear layout height 72 dp the problem comes when the size of the title crosses three line so I think we should limit the size of title displayed in bottom sheet.
Thanks for the review :)

**Comment by Jatin0312** [comment]
Changed according to reviews.
Description: 
1. Added three dots for large title instead of scroll view since it was hampering clickable behaviour.
2. Added margin right 50dp for title.

Suggestion needed: 
Should I implement like this that on click the bottom sheet the complete title is displayed with line breaks but I think It looks nice for now.


1. whatsapp image 2018-04-03 at 7 20 07 pm 2

2. whatsapp image 2018-04-03 at 7 20 07 pm 1

3. whatsapp image 2018-04-03 at 7 20 07 pm

**Comment by misaochan** [comment]
Thanks for the PR, @Jatin0312 !

Displaying the full name with line breaks onClick would be nice.

**Comment by neslihanturan** [comment]
I am also okay with current implementation

**Comment by Jatin0312** [comment]
I also think the current three dots  okay anyway for displaying complete title the bottom sheet size will be changed and any ways full title is displayed above on the marker also.
So @neslihanturan and @misaochan should I start implementing on click complete title behaviour or not?

**Comment by neslihanturan** [comment]
@Jatin0312 my answer is no, since I don't want to change height of bottom sheet when it is closed.

**Comment by misaochan** [comment]
Yeah, it's not essential to display the entire title I guess. I'm good with merging this so we can move forward with the hotfix ASAP, but maybe we can create an issue to brainstorm ways to display the full title for the future.

**Pull request merged**
