### PR TITLE
[WIP] Nearby arrow marker issue #1452

### LINKED ISSUE #1452: Add direction the user is facing to Nearby real-time position
AFAIK there was a discussion about this somewhere, but I think it was buried under a more general discussion.

Currently, our users see their real-time position as a dot. Which is great! But it would be much more useful if they could see what direction they were facing, similar to popular map apps. IMO this would make it easier for users to navigate using our Nearby map, without implementing full-on routing.

A brief look at how we can do that: https://stackoverflow.com/questions/14611493/point-arrow-to-direction-the-user-is-facing

### LINKED ISSUE #1659: NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util
Crash when opening Nearby (on browse branch, Android 7.1.2)
```
06-23 20:45:33.741 11594 11594 E AndroidRuntime: FATAL EXCEPTION: main
06-23 20:45:33.741 11594 11594 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 11594
06-23 20:45:33.741 11594 11594 E AndroidRuntime: java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in base.apk)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyMapFragment.onCreate(NearbyMapFragment.java:162)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-23 20:45:33.741 11594 11594 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-23 20:45:33.750   786  6707 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity
```

### PR DESCRIPTION
**Pull request by Maeglad**
## Add direction the user is facing to Nearby real-time position

Fixes #1452
Fixes #1659

## Description (required)

Fixes #1452
Getting azimuth:
Data from sensors and screen rotation are collected in NearbyActivity and sent to CompassUtils (new class), static method computes azimuth taking into account rotation of device and swaping coordinate system if needed. After azimuth is computed it is send into NearbyMapFragment. 

Icon rotation:
I could not use Marker class which was used until now for current location marker. I had two options when implementing this. First was to change Marker to MarkerView and second use SymbolLayer which meant adding new layer to map and isolate icon on this layer where it can be rotated.

I discarded first option as MarkerView was depracted.

Using SymbolLayer meant slight changes to current location marker logic as layer does not have marker but only has icons and source set which contains positions of icons. 
These changes were changing current location marker from Marker to Feature, updating animator and evaluator for current location marker.
Fixes #1659
updating mapbox version to latest solved the issue
MapBoxTelemtery class was changed in latest versions. In code we had telemetry disabled. I used Telementry.disableOnUserRequest() to disable it. Reason for change was that old method is no longer static and this should do same thing. 

## Tests performed (required)

api 23, Samsung Galaxy J5 with betaDebug, prodDebug
api 26, emulator with betaDebug, prodDebug
api 23, emulator with betaDebug

In emulator map was broken with black squares appearing on map. It only appears in emulator, on smartphone map works as should without black squares. This error appeared between two test sessions and I believe it is not caused by my code as I tested master branch and map also had black squares. I did testing on mapbox 6.2.0 as master currently does not work due to #1659.

## Screenshots showing what changed (optional)
screenshot with black square on map
screenshot_1529664916

screenshot with arrow marker
screenshot_1529666482

### CODE REVIEW

**Comment by misaochan** [comment]
Nice, thanks for the PR! We will test ASAP. :)

**Comment by neslihanturan** [comment]
I got this error after giving permissions on emulator API level 24.
```
SlotFromBufferLocked: unknown buffer: 0xae68a820
07-22 16:31:27.570 7291-7291/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: fr.free.nrw.commons.debug, PID: 7291
                                                                         java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                             at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                             at fr.free.nrw.commons.location.LatLng.from(LatLng.java:45)
                                                                             at fr.free.nrw.commons.location.LocationServiceManager.getLKL(LocationServiceManager.java:109)
                                                                             at fr.free.nrw.commons.nearby.NearbyActivity.onRequestPermissionsResult(NearbyActivity.java:241)
                                                                             at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6432)
```

**Comment by neslihanturan** [comment]
Bad new is I am not able to reproduce the issue consistently:(

**Comment by neslihanturan** [comment]
I think my crash is not related with your PR, I reproduced it on another PR too. Please ignore it

**Comment by maskaravivek** [comment]
@neslihanturan I have resolved the merge conflicts. If the PR works we can probably merge it. :)

**Comment by neslihanturan** [comment]
Unfortunately, it didn't worked on my test done with API level 19 device, fake location was moving with 50 km/h speed, but marker was still a dot. I will try with real mobing location as soon as I am out. But face location software gave this result:
no_direction_marker

**Comment by neslihanturan** [comment]
Since I couldn't make this issue work, and for a long time there are no upsdtes, closing it.

**Pull request closed without merging**
