### PR TITLE
[WIP] Enhancement: Tapping the "nearest place" card view on the main screen in 2.9 should bring user to Nearby map with that particular pin selected (#2034)

### LINKED ISSUE #2034: Tapping the "nearest place" card view on the main screen in 2.9 should bring user to Nearby map with that particular pin selected
We did not have the time to implement this in #725 , but this would be a pretty useful enhancement. Currently, when the user taps the "nearest place" card view on the main screen, they are just brought to Nearby in general. They should instead be brought to Nearby with that particular pin on the map selected.

You would need to build on the 2.9-release branch.

### PR DESCRIPTION
**Pull request by spelka**
**Description (required)**

Fixes #2034 Tapping the "nearest place" card view on the main screen in 2.9 should bring user to Nearby map with that particular pin selected

What changes did you make and why?

I added two functions in order to implement the enhancement.

The first function, selectNearestMarker, will programatically select the first item in the list of nearby places, which is sorted by distance from nearest to furthest.

The second function, deselectAllMarkers, is used to remove the info window of all selected markers. This was implemented after testing, because if you do not de-select the marker and close its info window, you would end up with many 

**Tests performed (required)**

Tested with the 2.9 branch on a Samsung Galaxy S8+ with API level 27.

Test procedure:
1) Open the app and Sign in. The Home page loads your contributions.

2) Click the "nearest place" card. The Nearby fragment housing the map is loaded. The nearest marker is selected, and its associated infowindow is displayed.

3) Move the camera. The map, markers, and infowindow should shift on the screen as the camera moves. The infowindow should stay open and maintain its position relative to its marker.

3) Zoom in and out. The map should zoom out, the marker and infowindow should stay open.

4) Change orientation. The fragment should be reloaded in the new configuration. The markers and infowindow should still all be displayed.

5) click on the selected marker. The marker is de-selected and the infowindow is closed.

6) click on the marker again. The infowindow is re-opened and information about the location is displayed below

7) click on a different marker. The infowindow and information about the new marker are displayed.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@spelka Can you name the PR more appropriately? 

Also, can you attach a screenshot of how the selected marker looks?

**Comment by spelka** [comment]
Hey, here is a screenshot of what the fragment looks like.

For your reference: on the left you have a standard, manual click on the map marker. The info window is brought up as well as the bottom info panel.

On the right, we have the new programmatic selection of the nearest marker when you click on the "nearest" card view item under the "contributions" tab. Only the info window is brought up.

I blacked out the map to block out the area near which I live, there's nothing relevant to this pull request masked under it.

ss

Let me know if you have any more questions.

**Comment by spelka** [comment]
Hi, I can confirm what @domdomdegg sees. I de-selected the location marker, navigated back to contributions fragment, and then navigated back to the nearby fragment again. The nearest marker is not selected.

The cause of this appears to be that both fragments in the viewpager are kept in memory. The viewpager keeps adjacent fragments in memory to enable smooth swiping between views. As a result, if the user de-selects the marker and navigates away from the fragment, the user's change persists when you navigate back to the nearby map fragment.

I'll have a look into some solutions to this problem.

**Comment by domdomegg** [comment]
Also won't a problem be that if you enter the nearby view without tapping the notification it is still selected, which might be confusing for users?

**Comment by neslihanturan** [comment]
Thanks for your contribution :) , I didn't tested this issue yet, but by reading code I can sat this won't do the job and brings us some bugs.
- updateMapSlightly method is something we call at every 2 seconds when user s moving. We can not deselect all markers and select nearest marker on each step user moved. Ie. user wants to select another marker and move, and suddenly our app forces them to deselect their marker, and select nearest marker which makes no sense. 
- On the other hand, selectNearestMarker() method should work and can be reused. Ideally this deselectAll and selectNearestMarker method should be called somewhere around onClick action of nearest place card view. Maybe after nearby tab select method is called. 

Please ask for more questions @spelka 

Tip for working nearby and sharing screenshots: You can use mock location softwares and use any other location than your location, I frequently use those apps.

**Comment by spelka** [comment]
Hello, I am stuck on this issue and could use some advice.

So far, I have re-written the code so that the deselectAllMarkers() and selectNearestMarker() functions are called when you click on the NearbyNotificationCardView in the ContributionsFragment, as was requested. 

To communicate between the fragments in the viewpager,  I use FragmentManager, in order to access the deselectAllMarkers() and selectNearestMarker() methods from the ContributionFragment (as per https://developer.android.com/training/basics/fragments/communicating).

The issue blocking me is that the NearbyFragment in the ViewPager does not instantiate all of its variables when the application is first loaded. Specifically, the nearbyMapFragment is still null when the NearbyFragment is loaded. Therefore, calling deselectAllMarkers() and selectNearestMarker() methods from the onclick handler will cause NPE.

When the user navigates to the "Nearby" tab, quite a few methods are called in order to complete setting up the fragment. At this point, the fragment has been fully instantiated, and I can use the variables. In fact, navigating back to the "contributions" tab, and clicking the button again correctly results in the nearest pin being selected.

This is a straightforward enhancement, and my goal is to implement the solution with a minimal amount of code added. At this time I don't see how to solve this problem without making some changes to NearbyFragment, and so I am looking for advice on the best way to proceed.

**Comment by spelka** [comment]
@domdomegg @neslihanturan 

Hello,  I think I should have pinged you when making my previous statement. Can you please have a read and respond, when you have time?

**Comment by domdomegg** [comment]
> This is a straightforward enhancement, and my goal is to implement the solution with a minimal amount of code added. At this time I don't see how to solve this problem without making some changes to NearbyFragment, and so I am looking for advice on the best way to proceed.

I agree it's a good idea to add a minimal amount of code. Unfortunately, I'm not fully sure as to what would be the best way to communicate with the fragment while avoiding NPE risks as I'm not that familiar with this code.

Currently the reason I've requested changes is that whenever a user either loads the nearby view or moves the map it will select the nearest marker - but we only want this behavior on clicking the nearby notification. I would suggest checking the onclick behaviour of that notification and add code there, which calls a method in the fragment (ideally during it's initialization - I appreciate the NPE issues) to select the nearest marker. Ideally, the notification click should actually send some sort of marker id so in case we have other notifications in future e.g. "nearby place with new activity"/"nearby place without media" it would be flexible.

**Comment by misaochan** [comment]
> At this time I don't see how to solve this problem without making some changes to NearbyFragment, and so I am looking for advice on the best way to proceed.

It is possible that a refactor is needed. I see no harm with including the necessary changes in your PR, as long as it is documented (i.e. we know why the additional changes were needed :)).

**Comment by neslihanturan** [comment]
I think the selectNearestMarker method from this PR can be reused. The only required fix is calling it where needed. Thus this one also seems like waiting for another person quickly polish it.

**Pull request closed without merging**
