### PR TITLE
#2192 scroll issue  resolved

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Fixed the Scroll issue with about activity and settings activity**

Fixes #2192 About activity

Changed the layout of activity_about and activity_settings

### CODE REVIEW

**Comment by vanshikaarora** [comment]
> @vanshikaarora Thanks for working on it. It looks like unrelated changes have got included in this PR. If you can fix it then we can review and merge the PR. :)

Hey @maskaravivek   Thanks for the reply. Can you please alaborate about the unrelated changes you are talking about

**Comment by maskaravivek** [comment]
Sorry, it looks good. I thought I saw 6 files changes. I might have a different PR open. :)

**Comment by vanshikaarora** [comment]
So is it good to be merged?

**Comment by maskaravivek** [comment]
Am testing the PR. Will merge after testing it. :)

**Comment by vanshikaarora** [comment]
OK :)

**Comment by maskaravivek** [comment]
Works for me. Thanks @vanshikaarora

**Comment by vanshikaarora** [comment]
Thanks for your giving your time @maskaravivek :)

**Comment by domdomegg** [comment]
I think this PR did include unintentional changes - including reverting #2199 and #2273. Will properly have a look later.

**Comment by domdomegg** [comment]
Reopened, see #2290

**Comment by vanshikaarora** [comment]
>I think this PR did include unintentional changes - including reverting #2199 and #2273. Will properly have a look later.

@domdomegg Shall I also include the changes #2199 and #2273 in this PR?

**Comment by domdomegg** [comment]
> > I think this PR did include unintentional changes - including reverting #2199 and #2273. Will properly have a look later.
> 
> @domdomegg Shall I also include the changes #2199 and #2273 in this PR?

I've submitted the changes in #2604. I your changes were made on an out of date version of master, which resulted in merge conflicts which weren't resolved properly. Will be all fixed once #2604 merged :)

**Pull request merged**
