### PR TITLE
Multiple uploads with over haul

### LINKED ISSUE #604: Allow multiple uploads from within the app
The current version of the app only allows multiple uploads when it is used inside of the Gallery. It do not let users to select multiple images to upload.

### LINKED ISSUE #1128: Thinking about a combined "share" GUI
I spent some time in [Sketch](https://www.sketchapp.com/) today thinking about what a user interface might look like if we combined the single-share and multi-share activities into a single workflow.  The thought experiment was about sharing 4 images with the Commons app, noting that we've had requests for 

* the ability to add title + description to all images in a set
* pinch + zoom to scale the image
* ability to review images and see them more clearly
* clearer presentation of the policy declaration that doesn't interfere with the image

share activity - step 1

Both the top and bottom cards would be (independently) collapsable to allow full access to the image.  Without the previous smoky transparent overlay the image is fully visible.  The small images in the top card scroll horizontally and tapping one pulls it up as the full screen image for review.

share activity - step 1ashare activity collapsed - step 1a

Note: if you were uploading only a single image then the top card would be hidden, and this first step of the wizard would be skipped taking you directly to adding title and description.

share activity - step 2

The wizard would step forward through the images making each the background of the whole screen to let you pick the best title + description.  We could name them the same as we do now - prefill the title - with the set name and a sequence number.  It would make sense to auto-collapse the top card as the wizard is now in control of which image is "selected" in the preview list - its tied directly to the step of the wizard that we are on.

stack

When we're done stepping through giving titles to them all, we add categories.  As with the current upload these are common across all the group.  Is there a need to tie them directly to each image?

share activity - step 6

Lastly we would select the license and show the _"By submitting this picture, I declare that this is my own work, that it does not contain copyrighted material or selfies, and otherwise adheres to Wikimedia Commons policies."_ at the point of tapping submit.

share activity - step 7

The number of steps is dynamic based on the number of images shared.

If I share a single image then we would show a 3 step wizard

* Step 1 of 3 - enter title + description
* Step 2 of 3 - select categories
* Step 3 of 3 - license and policy click-through to *submit*

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

Fixes #604
Fixes #1128

## Description (required)

Continued on top of #1796. 

- upload overhaul
- in-app multiple uploads

## Tests performed (required)

Uploads: 
- Camera upload > done
- Camera nearby upload with successful wikidata edit > done
- Single gallery upload > done
- Multiple gallery upload > done
- Gallery upload with successful wikidata edit > done

In the current ShareActivity:

- Tooltips for title, desc, license fields > done
- Language selector for desc > done
- Prefilling of title and desc when upload initiated via Nearby > done
- License selector > done
- Link to license and Commons policies > done
- Zoom in (and back out) > done
- Open location of image on maps > done

Category suggestions/selection:

- When search text field is empty, display:
    - Recent categories > done
    - Location-based category suggestions (if image has geolocation) > not working
    - Title-based category suggestions > not working
    - Wikidata item category (if image is uploaded via Nearby and if that Wikidata item has a category) > not working

- When user types in search text field:
    - Check for categories shortly after typing stops, repeatedly > done
    - Display exact matches at the top > done
    - Categories selected via both of these suggestion types need to be added to the list of category selections > done

Warnings:

- If image is too dark > done
- If image already exists in Commons (via hash check) > done
- If user tries to submit empty title (do not allow to proceed) > The submit button is disabled for this case
- If user does not select any categories

Image templates:
Ensure the same templates are added (not sure if this will be an issue if backend has not changed, but make sure you check). > done

### CODE REVIEW

**Comment by maskaravivek** [comment]
If the user tries to submit empty title (do not allow to proceed) 
> The submit button is disabled for this case. Should proceed button be disabled instead of disabling the Submit button in the final step? 

If user does not select any categories
> Shows no warning as of now. Will be fixing this as well. 

Category suggestion seems to be not working for the following cases. Will be fixing it soon: 
- Location-based category suggestions (if the image has geolocation) > not working
- Title-based category suggestions > not working
- Wikidata item category (if image is uploaded via Nearby and if that Wikidata item has a category) > not working

Also, similar images bit doesn't work for me. Will be fixing it. 

Other than these everything else works smoothly. @misaochan It would be great if you could also do a round of just basic testing and let me know if anything else needs to be fixed for it to be merged into master. :)

**Comment by misaochan** [comment]
Hi @maskaravivek , thanks for picking this up! The UI looks fantastic. :)

- Does multiple uploads work for you? When I select two images from my in-app Gallery, only one is displayed in the upload activity, and only one is actually uploaded. However, multiple uploads works when activated via Share. :)

- The steps in multiple upload are a bit confusing. Step 1 is to title/desc the first image, Step 2 is to title/desc the second image, but there is only one category selection for both? IMO we have to pick one - either we treat all images as separate ones and require separate title/descs for them, or we treat them all as related (as I suggested [here](https://github.com/commons-app/apps-android-commons/issues/604#issuecomment-373308504)) and require only one title/desc and one category selection (adding numbered prefixes to the title as required). I would vote for the second option, and with a limit of 5 uploads per round as mentioned in that comment.

- Typing in the Title/Desc activity (Step 1) feels very laggy. I doubt it is my emulator, since typing in the category activity is fine, and when I loaded a previous version of the app to test, there is no lag in the same emulator. Do you encounter this as well?

- Sometimes when I am halfway through typing a title and pause (e.g. I was going to type "Farm near Belmont", but paused after "Farm"), I get a warning "A file with the name Farm.jpg exists. Please consider changing it." IMO this check should only be done AFTER the user taps Proceed. If there is an ongoing check, this may explain the reason for my lag issue above.

**Comment by misaochan** [comment]
I forgot to mention - please make sure the temp file changes in #1749 are included, otherwise the crashes will resume.

Oh, and we need to make sure that we test on .png, too. :)

**Comment by maskaravivek** [comment]
Thanks for reviewing and testing the PR @misaochan. Will incorporate the feedback based on your comments. 

> The steps in multiple upload are a bit confusing. Step 1 is to title/desc the first image, Step 2 is to title/desc the second image, but there is only one category selection for both? IMO we have to pick one - either we treat all images as separate ones and require separate title/descs AND separate categories for them, or we treat them all as related (as I suggested here) and require only one title/desc and one category selection (adding numbered prefixes to the title as required). I would vote for the second option. 

@misaochan I understand your concerns regarding the steps in multiple uploads but IMO it would be great if we allowed separate title/desc for each of the images even if I am allowed to choose categories once. 
- This would be an enhancement over the current flow where the set is appended with numbers 1..2..3 etc. As title is non editable, I would personally prefer naming it to my satisfaction. 
- On clicking the gallery button, the user can be educated using a Showcase about selecting images of a particular category only. 
- Generally people would be interested about uploading photos of a place/visit which would usually have a common category. For eg. I clicked a lot of pictures of penguins at Boulder's beach and uploaded the photos using multiple uploads option. Here I wanted to select the same category for all photos but it would have been great to name all the photos individually. 
- Categories can be edited later. Right now the app doesn't allow for category edits afterwards but its in our PG 2019 plans(#161).
- Web frontend has the infrastructure to allow for both title/desc and category selection while making multiple uploads but with limited screen space on mobile it might be a good step to atleast start allowing title/desc. Hopefully, we can later evolve the UI to support individual category selection screens or we could have different flows based on user choice. 

> and with a limit of 5 uploads per round as mentioned in that comment.

Regarding putting a restriction on the number of images selected, Android natively doesn't allow to enforce a limit. A custom image picker UI needs to be provided for having this limit in place. For that, we can either use a library(for eg. https://github.com/zhihu/Matisse) that provides a image picker or write a custom implementation for it.

**Comment by maskaravivek** [comment]
> Perhaps in the "Step 1 of 4" title, we can have a subtext that says "(1st image in set)", then "(2nd image in set)", so on and so forth? Then in Step 3 of 4 for categories, the subtext will be "(all images in set)", and similarly for the license step.

Sure. Will add the sub texts. 

> How much time do you reckon it'll take for a custom implementation of a 5 image limit?

If we use a library then it would be much quicker to implement but if we chose to implement it on our own then it would take a week of my time. 

Ashish has worked on a custom UI in the past. @ashishkumar468 Do you feel 1 week should be enough for implementing the custom UI?

Also, I was hoping to get this first merged to master and then work on the image limit thing. I don't want the PR to get to unmanageable size. Just in a few days, we have so many conflicts. :(

> I forgot to mention this earlier - when the user selects the text field in the title/desc step to start typing, I think we should minimize the top card. Otherwise, in smaller screens, the keyboard + card will block the view almost entirely.

Sure will do.

**Comment by misaochan** [comment]
Sure, let's merge this PR when it is ready, and leave the upload limit for the next PR. :) Please ping me when you have implemented the fixes, I can re-test and merge.

**Comment by ashishkumar468** [comment]
> Do you feel 1 week should be enough for implementing the custom UI?

One week may not be sufficient, if we have to consider all the edge cases, as this involves building an entire custom activity/fragment similar to gallery picker, except the files modularisation.

**Comment by misaochan** [comment]
Ah, I see. In that case we may just release without the limit, and then implement the feature of locking multiple uploads for accounts above a certain revert % in the future?

My biggest fear is that one or two newbies could potentially do a lot of damage with unlimited multiple uploads. The risk is small, especially if they have to manually name every file before the upload begins, but it does exist.

**Comment by maskaravivek** [comment]
@misaochan We can probably use a library for now and implement a custom UI in future, keeping the task as a tech debt.

**Comment by misaochan** [comment]
@maskaravivek Fair point. Matisse does look quite reputable. Shall we go with that for now?

**Comment by maskaravivek** [comment]
Have made the following fixes: 
Category suggestions: 
- Location-based category suggestions (if the image has geolocation) 
- Title-based category suggestions
- Wikidata item category (if image is uploaded via Nearby and if that Wikidata item has a category)

Warnings: 
- If the user tries to submit empty title (do not allow to proceed)
- If user does not select any categories
- If the title of the image is duplicate

> Does multiple uploads via in-app Gallery button work for you? 
Yes, it works for me just like the gallery uploads

> Typing in the Title/Desc activity (Step 1) feels very laggy.
Yes, earlier an API call was being made after every character was typed. Fixed. :)

> Sometimes when I am halfway through typing a title and pause (e.g. I was going to type "Farm near Belmont", but paused after "Farm"), I get a warning "A file with the name Farm.jpg exists.

Fixed. Now the check is made only when **Next** is clicked. 

> Warnings should be done after each "Proceed" tap. So "no title" warning after user taps Proceed at Step 1, and "no category" warning after user taps Proceed at Step 2. "No category" can be allowed to proceed after they dismiss the dialog, "no title" should not.

Done. 

> Coordinates are not added to the image template. I just uploaded an image that I checked had location data, but the upload had none. Exif data is not added either, but I'm not sure if that is caused by your PR or by #1854 .

@ashishkumar468 is working on it. 

> I forgot to mention - please make sure the temp file changes in #1749 are included, otherwise the crashes will resume.

@ashishkumar468's fix should take care of this as well. 

> I forgot to mention this earlier - when the user selects the text field in the title/desc step to start typing, I think we should minimize the top card. Otherwise, in smaller screens, the keyboard + card will block the view almost entirely.

Done. 

> Perhaps in the "Step 1 of 4" title, we can have a subtext that says "(1st image in set)", then "(2nd image in set)", so on and so forth? Then in Step 3 of 4 for categories, the subtext will be "(all images in set)", and similarly for the license step.

Fixed.

**Comment by misaochan** [comment]
Tested on API 27 Nexus S emulator, in-app gallery multiple uploads do not work.

Steps:
- Fresh install of app
- Log in
- Tap Gallery button in app
- Go to Google Photos and select 3 images
- Receiving shared content, then ShareActivity loads with just 1 image, Step 1 of 3 (if there are 3 images in set it should be Step 1 of 5).
- Completed all 3 steps, and indeed only 1 image was uploaded.

screenshot_1541334036

```
11-07 00:55:20.481 24487-24487/fr.free.nrw.commons D/ContributionsListFragme: onRequestPermissionsResult: req code =  perm = [android.permission.READ_EXTERNAL_STORAGE] grant =[0]
11-07 00:55:20.482 24487-24487/fr.free.nrw.commons D/ContributionsListFragme: Call controller.startGalleryPick()
11-07 00:55:20.482 24487-24487/fr.free.nrw.commons D/ContributionController: startGalleryPick() called with pickImageIntent
11-07 00:55:20.995 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:12.487 24487-24487/fr.free.nrw.commons D/ContributionsListFragme: OnActivityResult() parameters: Req code: 3 Result code: -1 Data: Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/local%3A1c758eec-6c87-4813-81ed-e5117ed610a8/ORIGINAL/NONE/2091809993 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A1c758eec-6c87-4813-81ed-e5117ed610a8/ORIGINAL/NONE/2091809993 ...} }
11-07 00:56:12.488 24487-24487/fr.free.nrw.commons D/ContributionController: handleImagePicked() called with onActivityResult(). Boolean isDirectUpload: falseString wikiDataEntityId: null
11-07 00:56:12.501 24487-24487/fr.free.nrw.commons I/ContributionController: Image selected
11-07 00:56:12.501 24487-24487/fr.free.nrw.commons D/ContributionController: Put extras into image intent, isDirectUpload is false
11-07 00:56:12.503 27328-29987/system_process I/ActivityManager: START u0 {act=android.intent.action.SEND typ=image/jpeg flg=0x1 cmp=fr.free.nrw.commons/.upload.UploadActivity clip={image/jpeg U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A1c758eec-6c87-4813-81ed-e5117ed610a8/ORIGINAL/NONE/2091809993} (has extras)} from uid 10090
11-07 00:56:12.641 24487-24487/fr.free.nrw.commons I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-07 00:56:12.854 24487-24487/fr.free.nrw.commons D/ExternalStorageUtils: External storage permission not granted, API >= 23
11-07 00:56:12.857 24487-24487/fr.free.nrw.commons D/DexterPermissionObtaine: External storage permission is being requested
11-07 00:56:12.876 27328-28019/system_process I/ActivityManager: START u0 {cmp=fr.free.nrw.commons/com.karumi.dexter.DexterActivity} from uid 10090
11-07 00:56:12.918 24487-24487/fr.free.nrw.commons D/ExternalStorageUtils: External storage permission not granted, API >= 23
11-07 00:56:12.924 24487-24499/fr.free.nrw.commons I/zygote: Background concurrent copying GC freed 8381(559KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 3MB/6MB, paused 5.725ms total 139.265ms
11-07 00:56:12.944 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:13.027 24487-24487/fr.free.nrw.commons I/DescriptionsAdapter$Vie: descItemEditText:android.support.design.widget.TextInputEditText{83a3a80 VFED..CL. ......I. 0,0-0,0 #7f090092 app:id/description_item_edit_text}
11-07 00:56:13.029 24487-24487/fr.free.nrw.commons D/DescriptionsAdapter$Vie: Title is null
11-07 00:56:13.043 24487-24487/fr.free.nrw.commons I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-07 00:56:13.046 24487-24487/fr.free.nrw.commons I/DescriptionsAdapter$Vie: descItemEditText:android.support.v7.widget.AppCompatEditText{4bd25f1 VFED..CL. ......I. 0,0-0,0 #7f090092 app:id/description_item_edit_text}
11-07 00:56:13.047 24487-24487/fr.free.nrw.commons D/DescriptionsAdapter$Vie: Description is fr.free.nrw.commons.upload.Description@2c5a057
11-07 00:56:13.381 27328-27343/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{6412a6b u0 fr.free.nrw.commons/.upload.UploadActivity t68}
11-07 00:56:13.566 24487-24553/fr.free.nrw.commons D/CustomApiResult: API response is
     <?xml version="1.0" encoding="UTF-8"?><api batchcomplete=""><query><userinfo id="6998903" name="Misaochan2"/></query></api>
11-07 00:56:13.752 24487-24487/fr.free.nrw.commons E/RecyclerView: No adapter attached; skipping layout
11-07 00:56:13.796 24487-24487/fr.free.nrw.commons I/Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.
11-07 00:56:13.806 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:14.128 24487-24493/fr.free.nrw.commons I/zygote: Do full code cache collection, code=986KB, data=644KB
11-07 00:56:14.129 24487-24493/fr.free.nrw.commons I/zygote: After code cache collection, code=964KB, data=558KB
11-07 00:56:14.158 24487-24493/fr.free.nrw.commons I/zygote: Do partial code cache collection, code=967KB, data=569KB
    After code cache collection, code=966KB, data=569KB
    Increasing code cache capacity to 3MB
11-07 00:56:14.180 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:14.331 24487-24487/fr.free.nrw.commons D/DexterPermissionObtaine: User has granted us the permission for writing the external storage
11-07 00:56:14.331 24487-24487/fr.free.nrw.commons I/UploadActivity: Received single upload
11-07 00:56:14.548 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:14.671 24487-24487/fr.free.nrw.commons D/ExternalStorageUtils: External storage permission granted, API >= 23
11-07 00:56:14.671 24487-24487/fr.free.nrw.commons I/DexterPermissionObtaine: Storage permissions already granted.
11-07 00:56:14.671 24487-24487/fr.free.nrw.commons I/UploadPresenter: uploadModel.getCount():0
11-07 00:56:14.718 24487-24487/fr.free.nrw.commons D/UploadActivity: Position: 2 Attribution-ShareAlike 3.0
11-07 00:56:14.725 24487-24487/fr.free.nrw.commons I/UploadPresenter: Updating content for currentPage1
11-07 00:56:14.726 24487-24487/fr.free.nrw.commons E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException:  (No such file or directory)
11-07 00:56:14.726 24487-24487/fr.free.nrw.commons W/ImageView: resolveUri failed on bad bitmap uri: 
11-07 00:56:14.776 24487-24564/fr.free.nrw.commons D/FileUtils: Filepath (copied): /data/user/0/fr.free.nrw.commons/cache/1541516174642.jpg
11-07 00:56:14.779 24487-24564/fr.free.nrw.commons I/UploadModel: File path is /data/user/0/fr.free.nrw.commons/cache/1541516174642.jpg
11-07 00:56:14.822 24487-24514/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xe4b84420: ver 3 1 (tinfo 0xe4b83450)
11-07 00:56:14.857 24487-24564/fr.free.nrw.commons D/FileProcessor: Calling GPSExtractor
11-07 00:56:14.858 24487-24564/fr.free.nrw.commons D/FileProcessor: filePath/data/user/0/fr.free.nrw.commons/cache/1541516174642.jpg
    folderTime Number:3
11-07 00:56:14.859 24487-24564/fr.free.nrw.commons D/FileProcessor: fild date:1541516103000 time of creation1541516174000
11-07 00:56:14.860 24487-24564/fr.free.nrw.commons D/FileProcessor: not null fild EXIFfalse coordsnull
11-07 00:56:14.864 24487-24564/fr.free.nrw.commons D/FileProcessor: fild date:1541516109000 time of creation1541516174000
11-07 00:56:14.890 24487-24564/fr.free.nrw.commons D/FileProcessor: not null fild EXIFfalse coordsnull
11-07 00:56:14.900 24487-24564/fr.free.nrw.commons D/FileProcessor: fild date:1541516174000 time of creation1541516174000
11-07 00:56:14.952 24487-24564/fr.free.nrw.commons D/FileProcessor: not null fild EXIFfalse coordsnull
11-07 00:56:15.075 24487-24564/fr.free.nrw.commons I/FileUtils: File SHA1: 39c9f154ebcd247d82570faf8455b63c8c0181c7
11-07 00:56:15.260 24487-24487/fr.free.nrw.commons D/CategoriesModel: Direct category found: 
11-07 00:56:15.261 24487-24487/fr.free.nrw.commons D/CategoriesModel: Image has no direct Cat
11-07 00:56:15.589 24487-24564/fr.free.nrw.commons D/CustomApiResult: API response is
     <?xml version="1.0" encoding="UTF-8"?><api batchcomplete=""><query><allimages/></query></api>
11-07 00:56:16.146 24487-24564/fr.free.nrw.commons D/ImageUtils: total 12192768
11-07 00:56:16.429 24487-24487/fr.free.nrw.commons I/UploadPresenter: uploadModel.getCount():1
11-07 00:56:16.435 24487-24487/fr.free.nrw.commons D/UploadActivity: Position: 2 Attribution-ShareAlike 3.0
11-07 00:56:16.439 24487-24487/fr.free.nrw.commons I/UploadPresenter: Updating content for currentPage1
11-07 00:56:17.181 24487-24487/fr.free.nrw.commons I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
11-07 00:56:17.230 24487-24487/fr.free.nrw.commons I/DescriptionsAdapter$Vie: descItemEditText:android.support.design.widget.TextInputEditText{bf432fd VFED..CL. ......I. 0,0-0,0 #7f090092 app:id/description_item_edit_text}
11-07 00:56:17.231 24487-24487/fr.free.nrw.commons D/DescriptionsAdapter$Vie: Title is null
11-07 00:56:17.248 24487-24487/fr.free.nrw.commons I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
11-07 00:56:17.250 24487-24487/fr.free.nrw.commons I/DescriptionsAdapter$Vie: descItemEditText:android.support.v7.widget.AppCompatEditText{7d0174a VFED..CL. ......I. 0,0-0,0 #7f090092 app:id/description_item_edit_text}
11-07 00:56:17.259 24487-24487/fr.free.nrw.commons D/DescriptionsAdapter$Vie: Description is fr.free.nrw.commons.upload.Description@7eea6bb
11-07 00:56:17.667 24487-24499/fr.free.nrw.commons I/zygote: NativeAlloc concurrent copying GC freed 2821(195KB) AllocSpace objects, 3(46MB) LOS objects, 50% free, 4MB/8MB, paused 781us total 489.891ms
11-07 00:56:17.833 24487-24487/fr.free.nrw.commons I/AssistStructure: Flattened final assist data: 13864 bytes, containing 1 windows, 60 views
```

**Comment by misaochan** [comment]
- Testing suggestions and warnings, results below:

> Category suggestions:
> 
> Location-based category suggestions (if the image has geolocation)
I am actually not having coordinates sent with my upload, or any location-based category suggestions at all, even though my images have geotags. However I'm not sure if it's a Google Photos thing or not. Do coordinates work for you?

> Title-based category suggestions
Works fantastic!

> Wikidata item category (if image is uploaded via Nearby and if that Wikidata item has a category)
Works fantastic

> Warnings:
> 
> If the user tries to submit empty title (do not allow to proceed)
Works excellent

> If user does not select any categories
Works excellent

> If the title of the image is duplicate

I tried this with a multiple image upload. It warned me and asked if I wanted to proceed. I said "no", but instead of being allowed to modify my title, the image I was naming is gone entirely, and I was sent immediately to the 2nd image in the set (which is now the sole image being uploaded).

- An additional bug I found - if you type in a title and desc and go to Step 2, then tap "previous" to go back to Step 1 and modify your title/desc... the title is saved, but the desc is empty. Desc should be saved along with title.

**Comment by maskaravivek** [comment]
> I am actually not having coordinates sent with my upload, or any location-based category suggestions at all, even though my images have geotags. However I'm not sure if it's a Google Photos thing or not. Do coordinates work for you? (problem 2)

Yes, location-based category suggestions work for me and also the coords are set correctly. I uploaded an image with geotags (https://commons.wikimedia.org/wiki/File:Zeta_office_Diamond_District.jpg). I also got the suggestions for the category while uploading. 

> I tried this with a multiple image upload. It warned me and asked if I wanted to proceed. I said "no", but instead of being allowed to modify my title, the image I was naming is gone entirely, and I was sent immediately to the 2nd image in the set (which is now the sole image being uploaded). (problem 3)

fixed. 

Am working on fixing other issues. :)

**Comment by maskaravivek** [comment]
**problem 1** and **problem 3** is fixed now. 

> I am actually not having coordinates sent with my upload, or any location-based category suggestions at all, even though my images have geotags. However I'm not sure if it's a Google Photos thing or not. Do coordinates work for you? (problem 2)

Even exif interface is unable to extract location from the pictures when images are picked using Google photos. @ashishkumar468 would you be able to help with it as you have worked with Exif in the past?

> An additional bug I found - if you type in a title and desc and go to Step 2, then tap "previous" to go back to Step 1 and modify your title/desc... the title is saved, but the desc is empty. Desc should be saved along with title. (problem 4)

Unable to understand how the title/description is being cached. Would need someone's help to fix the issue. 

> Is there a reason the previous upload and title always shows up in the first upload screen, before it is replaced with the current file? It doesn't really impact the final outcome, but could be confusing to the user. (problem 5)

Have tried setting `setBottomCardVisibility` to show a waiting screen but it doesn't work. 

@misaochan Are these issues blocking issues? If these issues are minor then we could merge the PR and open separate issues for each of them. Someone might be able to help in fixing them.

**Comment by misaochan** [comment]
Thanks for fixing problem 1 and 3. I'll test ASAP. :)

> @misaochan Are these issues blocking issues? If these issues are minor then we could merge the PR and open separate issues for each of them. Someone might be able to help in fixing them.

All of this is fairly major IMO, especially as they pertain to uploading, which is the main focus of our app. If the bugs had been in, say, Achievements or such, they might be considered minor.

Maybe you can focus on Problem 5 first, then we can merge your PR and later on get @ashishkumar468 in to see if he has an idea for the other two issues? Currently he already has 2 tasks assigned to him.

**Comment by neslihanturan** [comment]
My test results:
Every uploads from gallery on API 26 and API 23, prod debug failed so far, 
image

Apart from upload problem:
- Use previous title/description stuff was very handy. It is not there now unfortunately. 
- When adding another description in another language, I encountered some problems:
    - I click to +, add another description and can continue without choosing the language. 
    - There is no way to regret from adding another description after tapping to +.
    - It is really hard to find the language from list, it is not sorted in anyway
    - I was able to find Turkish on the list previously. But now, it is not there.

Note: One more interesting thing that happened only on API 26 device, can lead us about reason of fail, during the upload, my emulator makes a sound for warning. During the upload, while uploading progress bar is moving to left and right, the sound of error (or mem leak, permission problems etc., a negative sound) appears once in a second. Then it displays: Failed to post notification on channel “null” toast. I searched for this toast, https://stackoverflow.com/questions/45711925/failed-to-post-notification-on-channel-null-target-api-is-26

**Comment by neslihanturan** [comment]
Yesterday I literally couldn't upload anything. But today all uploads were successful. Tested on same devices. The only difference is:
- Yesterday, before starting to test I had some failed uploads on my contribution list from previous days. Then my consequent uploads failed.
- After my failed tests on yesterday, I used web wizard and uploaded one picture. Then I didn't test this branch again.
- Today, still there was failed uploads on my contrib list, because I can not remove previous failed uploads, but I suspected that having a successful upload from web wizard helped me to have successful uploads today. Does this give you any idea @maskaravivek ?

Sorry I have no logs about failed uploads, I will get one if I can reproduce it. 

On the other hand, even if the upload was successful, the sound problem on API 26 still happens. Negative warning sound repetitively sounds during upload process.

**Comment by maskaravivek** [comment]
@neslihanturan Thanks for testing the PR. I checked the logs that you shared with me, and apparently, the uploads were failing for you because of "not logged in" error. The issue doesn't seem to be related to this PR and can be taken up when we revisit our auth mechanism. If it happens more frequently then we can take it up on a higher priority. 

> Use previous title/description stuff was very handy. It is not there now unfortunately.

I wasn't aware that such a feature existed. Will check and add it. :)

> When adding another description in another language, I encountered some problems:
> I click to +, add another description and can continue without choosing the language.

The description is optional. So validations are not added here. Should it be added? I don't think that descriptions would be posted on Commons if the language is empty. 

> There is no way to regret from adding another description after tapping to +.

Do you mean an option to delete a description? It would be great if you could help by sharing a quick mock on where the delete (x) button should be placed. There's very little space on the screen. 

> It is really hard to find the language from list, it is not sorted in anyway
> I was able to find Turkish on the list previously. But now, it is not there.

I will check why Turkish is not appearing. Infact will try to restore the previous list if that was more useful.

**Comment by maskaravivek** [comment]
@neslihanturan I have fixed the issue with language spinner. 

There's a weird issue that I am facing. On uploading images with multiple descriptions, for some of the languages, the description appears properly. Eg. https://commons.wikimedia.beta.wmflabs.org/wiki/File:Hetest_ehe.jpg

But for others like Turkish, it's not showing up properly. Eg. 
https://commons.wikimedia.beta.wmflabs.org/wiki/File:Hello_world_test_.jpg

Am not sure if there's an issue with the code or with the templates. @ashishkumar468 Do you have any insights on this?

**Comment by neslihanturan** [comment]
By the way I tried to record weird sound during upload (on API 26) 
[Screencast 2018-11-18 14:37:02.mp4.zip](https://github.com/commons-app/apps-android-commons/files/2592719/Screencast.2018-11-18.14.37.02.mp4.zip)

**Comment by neslihanturan** [comment]
Well, tested @maskaravivek . 
- The sound same on master too. 
- Language list is alphabetically ordered in master (pitty me scrolunt until Turkish:( )
- Descriotions on Turkish added with no problem on master.
image

**Comment by neslihanturan** [comment]
And this branch uploads descriptions on another languages with not problem as well. Thanks @maskaravivek ! :)
image

**Comment by misaochan** [comment]
Successfully did a multiple upload via in-app gallery > Google Photos on API 27 :) 
- Date works perfectly
- Desc and language works perfectly
- App handles similar filenames perfectly

Well done @maskaravivek !! :) And thanks for the additional testing @neslihanturan .

**Pull request merged**
