### PR TITLE
Fixes #3694 Pre-select places as depictions

### LINKED ISSUE #3694: When Uploading from Nearby the Place should be added as a pre-selected Depiction
**Summary:** 

nicolas-raoul :
 I think that the item from Nearby (when coming from Nearby) should be added as pre-selected (maybe even undeselectable) in Step 2 or the upload.

### PR DESCRIPTION
**Pull request by byerlyb20**
**Description (required)**

Fixes #3694

- Stop automatically adding `WikidataPlace` as a depiction in `WikidataEditService`, preventing duplication when the depiction is also manually selected on the depicts screen
- Refactor some logic out of `DepictModel.searchAllEntities()` to obtain `DepictedItem` instances directly from a list of places
- When `DepictsFragment` becomes visible, automatically select each unique place associated with an image in the set
    - Use the `Place` from each `UploadItem` returned by `UploadRepository.getUploads()`
    - Obtain `DepictedItem` instances via `DepictsClient`
    - Select each `DepictedItem`
- Add `areContentsTheSame` callback to `UploadDepictsAdapter` to make sure pre-selected depictions aren't unchecked in certain scenarios
- Scroll back to the top of the depicts list every time the list is updated to make sure pre-selected depictions are visible in certain scenarios

**Tests performed (required)**

Tested betaDebug on Pixel 4 XL with API level 30.

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Using this branch, I uploaded this picture: https://commons.wikimedia.org/wiki/File:%E3%81%82%E3%82%84%E3%82%81_at_Institute_for_Nature_Study.jpg
Pre-selection of the place item worked great! :-)
Strangely that item was still added twice, it seems:
Screen Shot 2021-06-15 at 20 22 41

**Comment by byerlyb20** [comment]
Hmmm, that's certainly not intended! I'll see if I can reproduce on my end and get that fixed.

**Comment by byerlyb20** [comment]
Weird — I'm not seeing the same duplication. I uploaded two files and neither had duplicate "depicts" entries:
1. [https://commons.wikimedia.org/wiki/File%3APlimpton_Pond_Dam.jpg](https://commons.wikimedia.org/wiki/File%3APlimpton_Pond_Dam.jpg)
2. [https://commons.wikimedia.org/wiki/File%3APlimpton_Pond_Dam_2.jpg](https://commons.wikimedia.org/wiki/File%3APlimpton_Pond_Dam_2.jpg)

For the first upload, I simply followed the upload process. I did not interact with the depictions screen; rather, I just left "Plimpton Pond Dam" checked. For the second upload, I added another depiction. I also unchecked and rechecked the "Plimpton Pond Dam" depiction. I guess my stress testing isn't all that stressful. I'll keep looking.

@nicolas-raoul Can you think of anything that might help me reproduce your results?

**Comment by nicolas-raoul** [comment]
I tried again and [it](https://commons.wikimedia.org/wiki/File:Stone_at_Tamagawa_Sengen_Jinja_Shrine.jpg) [worked](https://commons.wikimedia.org/wiki/File:Horse_carriage_at_Yebisu_Garden_Place.jpg), I must have messed up the first time sorry!

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
