### PR TITLE
Use an enum for the place description

### PR DESCRIPTION
**Pull request by veyndan**
Use an enum as the switch statement was violating the open-closed principle.

I called the text description for the place as "text" in [`Place.Description`](https://github.com/commons-app/apps-android-commons/compare/master...veyndan:place?expand=1#diff-a9fab34297df8e05376e1f2ff271d081R105) and throughout the PR (due to the code referencing the attribute). I'm undecided as to whether "type" would be a better name for this or not. Any input on this would be good, unless no one cares then I'll just stick with using "text".

### CODE REVIEW

**Comment by whym** [comment]
How about calling the new class ``Place.Type`` or ``Place.PlaceType`` instead of ``Place.Description``? "description" might sound like it's instance-based rather than type-based.

**Comment by veyndan** [comment]
> …instance-based rather than type-based

I'm not totally sure what you mean by this. An enum is a class and the enum is describing the description of the place. I feel that calling it `Type` or `PlaceType` doesn't make it obvious that there are attributes associated with each item in the enum i.e. `text` and `icon`, whereas calling it `Description` does make it obvious.

**Comment by whym** [comment]
I think it can cause confusion at first glance, because on Wikidata, "[description](https://www.wikidata.org/wiki/Help:Description)" has a special meaning associated with Wikidata items (analogous to instances).

That said, this is not something surfaced in the UI anyway. If other developers are fine with it, I won't object.

**Comment by whym** [comment]
By the way, I have tested it and nearby map/list worked fine for me.

**Comment by veyndan** [comment]
Thanks for the link! After having a quick glance, I agree that `Description` for the enum is a bad name, but I still think calling it some variation of `Type` isn't descriptive at all. A more obvious name would be better but I can't think of any atm.

**Comment by whym** [comment]
All right, it could be improved but I guess it doesn't justify further delay for this merge. If it's okay for you, I suggest adding a "TODO" comment for naming.

**Comment by veyndan** [comment]
`TODO` comment added

**Pull request merged**
