### PR TITLE
Fixes App crashes on clicking Save (EditActivity)

### LINKED ISSUE #5632: [Bug]: App crashes on clicking Save (EditActivity)
### Summary

App crashes on rotating image and clicking on save on few images.

### Steps to reproduce

1. Select a image from gallery
2. Click on Edit Image
3. Rotate Image
4. Click on save Image

### Expected behaviour

App should not crash and rotated image should be shown

### Actual behaviour

App crashes

### Device name

Samsung S21

### Android version

Android 14

### Commons app version

4.2.1-debug-issues5439

### Device logs

```
java.lang.NullPointerException
at fr.free.nrw.commons.edit.EditActivity.copyExifData(EditActivity.kt:260)
at fr.free.nrw.commons.edit.EditActivity.getRotatedImage(EditActivity.kt:241)
at fr.free.nrw.commons.edit.EditActivity.init$lambda$3(EditActivity.kt:125)
at fr.free.nrw.commons.edit.EditActivity.$r8$lambda$fIjJEeuPIZcPAnhPtUzdHmWgXF0(Unknown Source:0)
at fr.free.nrw.commons.edit.EditActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:8043)
at android.widget.TextView.performClick(TextView.java:17816)
at android.view.View.performClickInternal(View.java:8020)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:31850)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8893)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/114223204/f48ad2c7-82ad-4220-85f0-42713f432c3b

### Would you like to work on the issue?

Yes

### PR DESCRIPTION
**Pull request by kanahia1**
**Description (required)**

Fixes #5632

What changes did you make and why?

**Tests performed (required)**

Tested prodDebug on Samsung S21 FE with API level 33.

**Screenshots (for UI changes only)**
Tested on same picture as in #5632 

https://github.com/commons-app/apps-android-commons/assets/114223204/b9f71729-c2bc-4a4c-926d-ac573ec52c03

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
No more crash, thanks!
Saving still fails, but I guess that's another issue?

**Comment by neeldoshii** [comment]
Thank you for the contribution.

This does indeed solve the app crash, but still few nitpicks 
1. You have 66 commits can you perform git reset and have one.
2. The reason I am not convinced in this is because this PR #5569 solves exif null pointer as well as it handles the saving of rotated image. Would you mind updating the code to saving the rotated image and also considering https://github.com/commons-app/apps-android-commons/pull/5569#discussion_r1537706356 to fix security issues of exif data.

**Comment by kanahia1** [comment]
@nicolas-raoul, Sure we can open a new issue for the saving.

**Comment by nicolas-raoul** [comment]
It is true that `git rebase` would have made the commits of this PR cleaner. I suggest always running it before sending a PR, it not only makes review easier, but can help contributors spot problems that would otherwise be hard to notice.

@neeldoshii Would you like to create an issue (and possibly PR) for what you think are the next steps on this? :-)

**Pull request merged**
