### PR TITLE
Add nearby tutorial

### LINKED ISSUE #706: Add brief explanation to Nearby Places UI
I think it currently isn't very clear to a lot of users what Nearby Places does, and there isn't space in the action bar to make the title more explicit. Perhaps we could have an additional UI component (like a subtitle) to explain the feature?

### PR DESCRIPTION
**Pull request by neslihanturan**
## Description

Fixes #706 

Adds Material Showcase library and educates the user about nearby. **Help wanted** from a native speaker to make messages more descriptive.

## Tests performed

Manual tests, on API level 19

## Screenshots showing what changed
nearby_tutorial

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @neslihanturan , I just tested this on an API 25 Nexus S emulator. The first time I log in and load Nearby, the tutorial loads perfectly. Great job! :) However, there are a few minor issues that I would request changes for:

- IMO "Got it" should be a button, to make it more obvious that the user should tap it. Also we need to be consistent as to whether we use an exclamation mark at the end or not. :)
- I don't personally feel that the instructions for the "center" button are necessary, since it is available in almost all other map apps and not specific to our app. What do you think?
- Suggestions for texts:
 - (1) These are the places near you that need pictures to illustrate their articles
 - (2) [Focus on list button] Tapping this button brings up a list of these places
 - (3) [When user selects a pin] You can upload a picture for any place from your gallery or camera

If I switch to a different activity and come back to Nearby, it also works as intended and does not re-display the tutorial. However, if I log out and log back in again, opening Nearby will reliably cause this crash for me:

```
04-30 18:13:55.897 7145-7145/fr.free.nrw.commons.debug W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
        at fr.free.nrw.commons.CommonsApplication.$jacocoInit(CommonsApplication.java)
        at fr.free.nrw.commons.CommonsApplication.<init>(CommonsApplication.java)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
04-30 18:13:55.898 7145-7145/fr.free.nrw.commons.debug W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by neslihanturan** [comment]
Thanks for review @misaochan :) I will fix accordingly

**Comment by neslihanturan** [comment]
Crash exists on master too, I created an issue #1480 . But I am fixing other issues.

**Comment by neslihanturan** [comment]
I dont get FileNotFound exception neither on this branch nor on master. I get Srecurity exception on both branches. Do you able to reproduce FileNotFound exception on master and this branch both?

**Comment by misaochan** [comment]
I have never gotten the FNF exception on master, and I reliably get it every time on this branch. However, I will try again with a different device later and see if it makes a difference.

**Comment by neslihanturan** [comment]
@misaochan 
- I tried to make dismiss text bold, since library doesnt provide too much option to customize dismiss button. How it looks to you?
- Will be displayed only once even after logging out
- Strings are updated

**Comment by misaochan** [comment]
@neslihanturan Thanks for sorting out the strings. :) The demo on https://github.com/deano2390/MaterialShowcaseView 's readme seems to show the use of a button. Are you sure this isn't a possibility with this library?

**Comment by misaochan** [comment]
Oh, okay, I see what you mean now. Yeah, I guess bolded is the best we can do. Will test when I can - having Android Studio issues at the moment. :/

**Comment by misaochan** [comment]
Finally managed to test, looks good to me. :) Please feel free to squash and merge after you fix the conflicts.

**Comment by neslihanturan** [comment]
Ready to be merged @misaochan , conflicts are fixed:)

**Comment by misaochan** [comment]
@neslihanturan It tells me that there are conflicting files still, though. A translation commit might have come in after you made the changes?

**Comment by neslihanturan** [comment]
Fixed again @misaochan :)

**Comment by misaochan** [comment]
Thanks @neslihanturan . :)

**Pull request merged**
