### PR TITLE
ConnectRefuseError: removed the proxy from properties.gradle file to allow downloading of build tools during CI.

### LINKED ISSUE #5431: Pull requests CI failing with "ConnectException", "IllegalStateException: Failed to find Build Tools revision 30.0.3"
Example with an empty pull request: https://github.com/commons-app/apps-android-commons/actions/runs/7511731633/job/20451652398#step:8:1

This could be a CI misconfiguration.
Anyone has any idea how to solve this?

NO-OP change to test our CI: https://github.com/commons-app/apps-android-commons/pull/5432

### PR DESCRIPTION
**Pull request by rohit9625**
**Description (required)**
Fixes #5431 
What changes did you make and why?
Comment out the lines related to the proxy in the file `properties.gradle`. This proxy was causing the ConnectException error while downloading the build tools and Android SDK Tools **version** - **26.1.1** and **30.0.3**.

Also, I added some debugging commands in the workflow file `android.yml` for a better understanding of the issues. However some tests are failing, and that may be because of the use of deprecated features in our app. So, we need to work on migrating later.

**Tests performed (required)**

Tested betaDebug on my repo with CI.

**Screenshots (for UI changes only)**
Not related to UI.

### CODE REVIEW

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Checking the log, while I see `2024-01-14T07:13:05.5511545Z BUILD SUCCESSFUL in 6m 26s` at the end, I also see a large amount of exceptions like the one below. I wonder whether it is something that can be ignored and is only shown due to the additional debug information.

Sorry for the contradicting ask, but would you mind removing the changes related to debug information?
Thanks a lot!

```
2024-01-14T07:12:36.2769032Z fr.free.nrw.commons.upload.UploadMediaPresenterTest STANDARD_ERROR
2024-01-14T07:12:36.2771962Z     java.lang.instrument.IllegalClassFormatException: Error while instrumenting fr/free/nrw/commons/upload/mediaDetails/UploadMediaPresenter with JaCoCo 0.8.10.202304240956/8ea9668.
2024-01-14T07:12:36.2774396Z     	at org.jacoco.agent.rt.internal_4a7f17c.CoverageTransformer.transform(CoverageTransformer.java:94)
2024-01-14T07:12:36.2776989Z     	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
2024-01-14T07:12:36.2778729Z     	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
2024-01-14T07:12:36.2780935Z     	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
2024-01-14T07:12:36.2783013Z     	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2024-01-14T07:12:36.2784644Z     	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
2024-01-14T07:12:36.2786705Z     	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
2024-01-14T07:12:36.2788185Z     	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
2024-01-14T07:12:36.2789918Z     	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
2024-01-14T07:12:36.2792186Z     	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
2024-01-14T07:12:36.2793826Z     	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
2024-01-14T07:12:36.2795746Z     	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2024-01-14T07:12:36.2797693Z     	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2024-01-14T07:12:36.2798802Z     	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
2024-01-14T07:12:36.2799962Z     	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
2024-01-14T07:12:36.2801129Z     	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
2024-01-14T07:12:36.2802365Z     	at org.junit.runners.model.TestClass.getSortedDeclaredFields(TestClass.java:77)
2024-01-14T07:12:36.2803750Z     	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:70)
2024-01-14T07:12:36.2804973Z     	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
2024-01-14T07:12:36.2806153Z     	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:111)
2024-01-14T07:12:36.2807323Z     	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:91)
2024-01-14T07:12:36.2808572Z     	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
2024-01-14T07:12:36.2809972Z     	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:75)
2024-01-14T07:12:36.2844022Z     	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:109)
2024-01-14T07:12:36.2848632Z     	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:104)
2024-01-14T07:12:36.2850167Z     	at jdk.internal.reflect.GeneratedConstructorAccessor509.newInstance(Unknown Source)
2024-01-14T07:12:36.2852035Z     	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2024-01-14T07:12:36.2853865Z     	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2024-01-14T07:12:36.2855537Z     	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2024-01-14T07:12:36.2857596Z     	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
2024-01-14T07:12:36.2859346Z     	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
2024-01-14T07:12:36.2861303Z     	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
2024-01-14T07:12:36.2864395Z     	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
2024-01-14T07:12:36.2866019Z     	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
2024-01-14T07:12:36.2867871Z     	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
2024-01-14T07:12:36.2869355Z     	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
2024-01-14T07:12:36.2870969Z     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:77)
2024-01-14T07:12:36.2872786Z     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
2024-01-14T07:12:36.2874655Z     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
2024-01-14T07:12:36.2876896Z     	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
2024-01-14T07:12:36.2878991Z     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
2024-01-14T07:12:36.2880463Z     	at jdk.internal.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
2024-01-14T07:12:36.2881876Z     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-01-14T07:12:36.2883191Z     	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-01-14T07:12:36.2884319Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2024-01-14T07:12:36.2885656Z     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2024-01-14T07:12:36.2887162Z     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2024-01-14T07:12:36.2888933Z     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2024-01-14T07:12:36.2890368Z     	at jdk.proxy2/jdk.proxy2.$Proxy5.processTestClass(Unknown Source)
2024-01-14T07:12:36.2891441Z     	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
2024-01-14T07:12:36.2892863Z     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
2024-01-14T07:12:36.2894339Z     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
2024-01-14T07:12:36.2895695Z     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
2024-01-14T07:12:36.2897157Z     	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
2024-01-14T07:12:36.2899148Z     	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
2024-01-14T07:12:36.2901971Z     	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
2024-01-14T07:12:36.2903830Z     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2024-01-14T07:12:36.2905415Z     	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2024-01-14T07:12:36.2907500Z     Caused by: java.io.IOException: Error while instrumenting fr/free/nrw/commons/upload/mediaDetails/UploadMediaPresenter with JaCoCo 0.8.10.202304240956/8ea9668.
2024-01-14T07:12:36.2909702Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
2024-01-14T07:12:36.2911870Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:111)
2024-01-14T07:12:36.2913452Z     	at org.jacoco.agent.rt.internal_4a7f17c.CoverageTransformer.transform(CoverageTransformer.java:92)
2024-01-14T07:12:36.2914489Z     	... 57 more
2024-01-14T07:12:36.2917334Z     Caused by: java.lang.IllegalStateException: Cannot process instrumented class fr/free/nrw/commons/upload/mediaDetails/UploadMediaPresenter. Please supply original non-instrumented classes.
2024-01-14T07:12:36.2919905Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:238)
2024-01-14T07:12:36.2921996Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:56)
2024-01-14T07:12:36.2923646Z     	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassVisitor.visitField(ClassVisitor.java:356)
2024-01-14T07:12:36.2925019Z     	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.readField(ClassReader.java:1137)
2024-01-14T07:12:36.2926895Z     	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.accept(ClassReader.java:739)
2024-01-14T07:12:36.2928229Z     	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.accept(ClassReader.java:424)
2024-01-14T07:12:36.2929616Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:91)
2024-01-14T07:12:36.2931102Z     	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:109)
2024-01-14T07:12:36.2932716Z     	... 58 more
```

**Comment by rohit9625** [comment]
It's fine Mr. @nicolas-raoul. I made the required changes :)
However, I think we need to remove all deprecated features and upgrade to newer ones using the migration guide mentioned in the logs.

**Review by nicolas-raoul — APPROVED** [review]
Thanks Rohit!

(I guess the exceptions we were seeing previously were not really errors, they were probably part of checking for the presence of something before using something else.)

**Comment by rohit9625** [comment]
Mention not Mr. @nicolas-raoul, solving issues improving my problem-solving skills and I am enjoying it :)
Thank you for helping me get familiar with the source code.

**Pull request merged**
