### PR TITLE
Direct nearby uploads feature branch - code cleanup

### PR DESCRIPTION
**Pull request by psh**
I just made a quick pass through the feature branch and did some code cleanup - 

* Removed dead / redundant code
* Removed unused imports
* Converted anonymous inner classes to Java 8 lambdas
* Reduced feature envy + cleaned up code - `LatLng` formats its own GmmIntentUri and removed redundant object creation
* Reduced feature envy + cleaned up code - `Place` knows if it has various site links, cleaning up code that uses them

### CODE REVIEW

**Comment by misaochan** [comment]
Tested on Android 7.0, works well for me. Thanks @psh !

**Comment by misaochan** [comment]
Edit: Oh, whoops, the sitelinks for Wikidata and Wikipedia etc stopped working after the merge (I hadn't thought to test them beforehand). :/

`12-31 01:12:45.050: D/HTTPRequest(8893): [HTTP] Request with response code = 304: No additional information`

@psh could you look into this please?

**Comment by psh** [comment]
The particular network requests in question originate from mapbox - asking (for instance) for a map tile with a URL like `https://maps.wikimedia.org/osm-intl/13/2042/3140.png` and indicate that the caching is working correctly - mapbox on your phone asked for tiles that were cached in each case of the 304 status (an indicator from the server that that particular data item hasn't changed since the last 200 request).

**Comment by misaochan** [comment]
Sorry, seems it was my connection messing up the second time I tried, lol. The links work perfectly now.

Thanks for clarifying the debug HTTP messages, I was wondering why I kept getting them.

**Pull request merged**
