### PR TITLE
include app descriptions and title to be translated

### PR DESCRIPTION
**Pull request by Clockery**

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Thanks! You are from Code-in I guess?

**Comment by Clockery** [comment]
Yeah, I am :) I didn't realise the pull request had been sent, my net was down for a while! Thanks a lot :)

**Comment by nicolas-raoul** [comment]
Please submit the task for review :-)

**Comment by Clockery** [comment]
Sure, but wait, this is all that has to be done for the task?

**Comment by Clockery** [comment]
I've submitted the task for review, but shouldn't the files be translated on TWN? How is that done?

**Comment by nicolas-raoul** [comment]
Oh yes indeed, I forgot that was only the first step!
Sorry about my mistake ('-_-)

For Translatewiki, if you identify what setting files need to be changed how, that's good enough.
First, please find our current translatewiki configuration file, where these files are referenced: https://github.com/commons-app/apps-android-commons/tree/master/app/src/main/res/values

**Comment by Clockery** [comment]
This file, right? https://github.com/commons-app/apps-android-commons/tree/master/app/src/main/res

**Comment by nicolas-raoul** [comment]
Let's continue the conversation at https://github.com/commons-app/apps-android-commons/issues/790

**Comment by Clockery** [comment]
Sure :)

**Pull request merged**
