### PR TITLE
Added the error message to the filed upload notification

### LINKED ISSUE #4510: Show login errors to user
**Summary:** 
When there is a login error during upload (for example when user changed their password) show error to user. 

**Steps to reproduce:** 

1. Change your password on Commons
2. Try to upload a file with Android app 
3. Instead of telling me what the problem is, app only says that upload failed 

**System logs:**

```
[ERROR] [file-logging-thread-1] [OkHttpConnectionFactory$UnsuccessfulResponseInterceptor] : java.io.IOException: {"errors":[{"code":"login-required","text":"You must be logged in.","module":"query+notifications"}],"docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.","servedby":"mw2364"}
```
.

### PR DESCRIPTION
**Pull request by jeremybowenn**
Added the error message to the file upload notification

Fixes #4510 

Changed the StashUploadResult to return a message with the status so we can show it in notifications and the user can see what went wrong

Logged in, changed password via main site, uploaded image, failed, notification body contained message
Logged in, uploaded successfully and verified normal message was unchanged

Tested ProdDebug on Pixel 5 with API level 28

upload-error-message

### CODE REVIEW

**Review by neslihanturan — COMMENTED** [review]
Hey @jeremybowenn , thanks a lot for the contribution. I am getting 
```
e: /home/nes/AndroidStudioProjects/CommonsApp12/apps-android-commons/app/src/main/java/fr/free/nrw/commons/upload/worker/UploadWorker.kt: (281, 94): No value passed for parameter 'message'
```
error on build. Do you able to build this branch with no problem? If so do you have any estimation about what can be the problem on my side?

**Comment by jeremybowenn** [comment]
@neslihanturan Hmm, it's building fine for me. I added a default case, so maybe that will help the build get past any missing params? Let me know if that helps or not.

**Comment by jeremybowenn** [comment]
@neslihanturan Found the problem. Totally my bad, though I still don't know why my compiler didn't pick up on it. Hopefully, that should fix the build.

**Comment by neslihanturan** [comment]
Hey @jeremybowenn , currently there is no visible issues with the PR. However, when I tried to cut my internet connection while I upload a photo, upload fails as expected but the notification does not say anything about the reason. Can you say which kind of scenario you have tested and verified the PR is working?

image

**Comment by neslihanturan** [comment]
Hey, is this PR is still active?:)

**Comment by jeremybowenn** [comment]
Hey, sorry, I've been a bit busy and this got lost in the shuffle.

I tested this using a pixel 5 emulator on my computer that wasn't connected
to the internet so that all uploads would fail.

I can check the code in master this weekend to ensure everything is working
right.

**Comment by neslihanturan** [comment]
Hi @jeremybowenn , is there any uodate :)

**Comment by jeremybowenn** [comment]
@neslihanturan Sorry for the wait. For my own clarification, did this go into master and you are having problems there, or are you testing my branch and having issues with it on there? If you are on master or another branch, then I don't think it'll work because this hasn't merged yet I believe.

As for testing on my own branch, I'm running into an error on login about Chain validation failed which is preventing me from logging in to test the uploader. If you can confirm that this is happening on my branch and tell me what I'm doing wrong for logging in, I'll get in and try to figure it out asap.

**Comment by neslihanturan** [comment]
Hey @jeremybowenn , my tests results were on your branch and with beta flavor. Here is the repeated test when I turn off the internet during the upload. I get the same result, no information on notification :(
image

image

**Review by neslihanturan — CHANGES_REQUESTED** [review]
my tests consistently gives the same result with master. So this PR seems like don't make any effect.

**Comment by jeremybowenn** [comment]
Sorry for all the wasted time! I made some bad assumptions about the code that should be fixed now. When I try to upload with the wifi turned off now, it shows the following error. The full text is "No content provider: /data/user/0/fr.free.nrw.commons.beta/cache/CommonsContributions/fbe1b980-bfd3-4743-a765-d6d714856e255395746841364598558.jpg" This is directly copied from the exception that was thrown in upload process, so I'm not sure if it will be helpful to some people. Should I also handle translating these errors into something more user-friendly or would you rather do that some other time?

wifi-failure-notification
.

**Comment by Kennysong55** [comment]
Do the right thing

**Comment by 4D17Y4** [comment]
> Sorry for all the wasted time! I made some bad assumptions about the code that should be fixed now. When I try to upload with the wifi turned off now, it shows the following error. The full text is "No content provider: /data/user/0/fr.free.nrw.commons.beta/cache/CommonsContributions/fbe1b980-bfd3-4743-a765-d6d714856e255395746841364598558.jpg" This is directly copied from the exception that was thrown in upload process, so I'm not sure if it will be helpful to some people. Should I also handle translating these errors into something more user-friendly or would you rather do that some other time?
> 
> wifi-failure-notification .

Its better if you can pinpoint these errors and add those conditions. 
This would be great, thanks.

**Comment by neslihanturan** [comment]
Hi @jeremybowenn , is this PR still active?:)

**Comment by jeremybowenn** [comment]
@neslihanturan Sorry, but I don't think I'm going to be able to come back to this. Others are more than welcome to use my code to finish this off.

**Comment by 4D17Y4** [comment]
Thanks for your inputs @jeremybowenn,
Closing this one.

**Pull request closed without merging**
