### PR TITLE
UploadController: Added support for using author names. Fixes #1707.

### LINKED ISSUE #1707: Use author's name from Preferences if available
In my Preferences on Commons I can set a personalized string to be used in the author field of my photos (Preferences → Upload wizard → Author's name). It would be nice if the app could apply it as well. I know some users prefer to use their full name there rather than their username.

### PR DESCRIPTION
**Pull request by cvhariharan**
## UploadController: added support for using author name from preferences.

Fixes #1707

## Description
An author name can be set in settings to use instead of username while uploading images.

## Tests performed
Uploaded multiple test images.

Tested on {API 27 & OnePlus 6}, with {ProdDebug}.

## Screenshots 
Screenshot 1
Screenshot 2

### CODE REVIEW

**Comment by maskaravivek** [comment]
@cvhariharan Can you test the PR once to see if the set author name is actually being used in the uploaded image.

**Comment by cvhariharan** [comment]
I have tested it and it works. It displays the author name on the website, if enabled and set, else it just defaults to username.

**Comment by domdomegg** [comment]
**Test results**

All automated tests pass

Tested `2.9.0-debug-master~3901ba89` on `Galaxy Nexus (emulator)` at API level `28`

- Case 1: disabled
    - https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test1856_1.jpg
- Case 2: enabled, with custom username set to "domdomegg" (lowercase "d")
    - https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test1856_2.jpg
- Case 3: enabled, but without username provided
    - https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test1856_3.jpg
- Case 4: enabled, with custom username set to "£:unicorn:" (to test handling of special characters)
    - https://commons.wikimedia.beta.wmflabs.org/wiki/File:Test1856_4.jpg

All worked flawlessly

**Comment by domdomegg** [comment]
Given I've now worked on this @maskaravivek can you review and merge this?

**Comment by neslihanturan** [comment]
Congratz your first time contribution @cvhariharan :fireworks:

**Comment by cvhariharan** [comment]
@neslihanturan Thanks!

**Pull request merged**
