### PR TITLE
Fix #2179: Update ACRA version and theme

### LINKED ISSUE #2179: ACRA reporting dialog looks old
**Summary:** 

Now we've got beautiful material design in the rest of the app, the crash reporting dialog does look pretty outdated. While of course we hope as few users as possible see it, I think it'd be nice if it did look good.

You'll likely want to create a custom dialog theme in `styles.xml`. It might help to see the current theme, which is the default `Theme.Dialog` from the support library: https://chromium.googlesource.com/android_tools/+/e429db7f48cd615b0b408cda259ffbc17d3945bb/sdk/platforms/android-24/data/res/values/themes.xml#680

**Steps to reproduce:** 

You can force a crash by adding

```
if (true) throw new Error("Test ACRA error");
```

Into some activitiy's `onCreate` method. The `if (true)` allows it to compile without complaining that it will always error (even though it will). 

**Screen-shots:** 

screenshot_1545258309

### PR DESCRIPTION
**Pull request by JasonObeid**
Fixes #2179, ACRA reporting dialog looks old

Updated to ACRA version 5.13, applied a material theme.

**Tests performed (required)**

Tested the master branch on an emulator of a Pixel 2 with API level 28.

I forced an exception to test the new version and theme of ACRA.

**Screenshots showing what changed (optional - for UI changes)**

I couldn't fix the padding, [but I found a reference which may be useful](https://gitlab.com/fdroid/fdroidclient/merge_requests/186/commits?commit_id=49d01e0ca3e77de396417603b735c3ccd6c16847)

A material warning icon may look nicer than the blank image that I used.

image

### CODE REVIEW

**Comment by domdomegg** [comment]
Seems to have issues with `fr.free.nrw.commons.category.CategoryDaoTest`. Not sure why.

**Comment by domdomegg** [comment]
Sorry for taking forever to get round to this.

Now it emails a blank body with a `.stacktrace` attachment which is a different format than we used to - it is as bit annoying to analyse (I'm not sure if there's a ACRA .stacktracer viewer?). Do you think you can see if there's anyway to report it in an email in a similar way as we used to?

For reference, this is what emails previously looked like:
```
USER_COMMENT=Testing PR #2219
ANDROID_VERSION=9
APP_VERSION_NAME=2.10.1-debug-master
BRAND=google
PHONE_MODEL=Android SDK built for x86
CUSTOM_DATA=
STACK_TRACE=java.lang.Error: Test ACRA error
at fr.free.nrw.commons.explore.categories.ExploreActivity.onCreate(ExploreActivity.java:73)
at android.app.Activity.performCreate(Activity.java:7136)
at android.app.Activity.performCreate(Activity.java:7127)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Here's the sample report that this PR is generating:
[ACRA-report.zip](https://github.com/commons-app/apps-android-commons/files/2975060/ACRA-report.zip)

**Comment by JasonObeid** [comment]
> Sorry for taking forever to get round to this.
> 
> Now it emails a blank body with a `.stacktrace` attachment which is a different format than we used to - it is as bit annoying to analyse (I'm not sure if there's a ACRA .stacktracer viewer?). Do you think you can see if there's anyway to report it in an email in a similar way as we used to?
> 
> For reference, this is what emails previously looked like:
> 
> ```
> USER_COMMENT=Testing PR #2219
> ANDROID_VERSION=9
> APP_VERSION_NAME=2.10.1-debug-master
> BRAND=google
> PHONE_MODEL=Android SDK built for x86
> CUSTOM_DATA=
> STACK_TRACE=java.lang.Error: Test ACRA error
> at fr.free.nrw.commons.explore.categories.ExploreActivity.onCreate(ExploreActivity.java:73)
> at android.app.Activity.performCreate(Activity.java:7136)
> at android.app.Activity.performCreate(Activity.java:7127)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
> at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:193)
> at android.app.ActivityThread.main(ActivityThread.java:6669)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```
> Here's the sample report that this PR is generating:
> [ACRA-report.zip](https://github.com/commons-app/apps-android-commons/files/2975060/ACRA-report.zip)

Sure, I will look into this

**Comment by JasonObeid** [comment]
I got the reports to send as plain text, but the formatting is atrocious.

there are \n and \t escape sequences, but they aren't formatting the text within the email.

image

Do you have any ideas?

We can also change what content to include in the report. For now I copied the content of the old email.
https://github.com/ACRA/acra/wiki/ReportContent

**Comment by domdomegg** [comment]
> I got the reports to send as plain text, but the formatting is atrocious.
> 
> there are \n and \t escape sequences, but they aren't formatting the text within the email.
> 
> image
> 
> Do you have any ideas?
> 
> We can also change what content to include in the report. For now I copied the content of the old email.
> https://github.com/ACRA/acra/wiki/ReportContent

Nice! Thanks for getting to work on this so quickly. I'm not quite sure to be honest - that looks like JSON so maybe using the GSON library (that's already used elsewhere in the project) decoding it could allow us to pretty print it better?

If you push your changes to this branch and I could take a deeper look when I have the time.

**Comment by JasonObeid** [comment]
Sorry I'm not sure how to commit changes to a specific branch. How would I go about doing that?

For now I'll show you the changes I made as a comment.

There are only 3 changes which are denoted by '>>>>'
````
import org.acra.ACRA;
import org.acra.annotation.*;
>>>>import static org.acra.ReportField.*;

import java.io.File;

import javax.inject.Inject;
import javax.inject.Named;

import fr.free.nrw.commons.auth.SessionManager;
import fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsDao;
import fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao;
import fr.free.nrw.commons.category.CategoryDao;
import fr.free.nrw.commons.concurrency.BackgroundPoolExceptionHandler;
import fr.free.nrw.commons.concurrency.ThreadPoolService;
import fr.free.nrw.commons.contributions.ContributionDao;
import fr.free.nrw.commons.data.DBOpenHelper;
import fr.free.nrw.commons.di.ApplicationlessInjection;
import fr.free.nrw.commons.kvstore.JsonKvStore;
import fr.free.nrw.commons.kvstore.JsonKvStore;
import fr.free.nrw.commons.logging.FileLoggingTree;
import fr.free.nrw.commons.logging.LogUtils;
import fr.free.nrw.commons.modifications.ModifierSequenceDao;
import fr.free.nrw.commons.upload.FileUtils;
import fr.free.nrw.commons.utils.ConfigUtils;
import io.reactivex.android.schedulers.AndroidSchedulers;
import io.reactivex.schedulers.Schedulers;
import timber.log.Timber;

@AcraCore(
        buildConfigClass = BuildConfig.class,
        resReportSendSuccessToast = R.string.crash_dialog_ok_toast,
        >>>>reportContent = {USER_COMMENT, APP_VERSION_CODE, APP_VERSION_NAME, ANDROID_VERSION, PHONE_MODEL, CUSTOM_DATA, STACK_TRACE}
)

@AcraMailSender(
        mailTo = "commons-app-android-private@googlegroups.com",
        >>>>reportAsFile = false
)

@AcraDialog(
        resTheme = R.style.Theme_AppCompat_Dialog,
        resText = R.string.crash_dialog_text,
        resTitle = R.string.crash_dialog_title,
        resCommentPrompt = R.string.crash_dialog_comment_prompt
)

**Comment by domdomegg** [comment]
> Sorry I'm not sure how to commit changes to a specific branch. How would I go about doing that?

No problem - you've done it anyways (0236c4d18fb73fe81b0db494ba039b09c01d0d02). I just meant commit and push your changes to the branch that you had submitted this PR from, which in your case is your master branch.

I will try to have a look at this properly later.

**Comment by domdomegg** [comment]
Having read the [migration guide](https://github.com/ACRA/acra/wiki/Migrating), I think we should set the `reportFormat` in to `StringFormat.KEY_VALUE_LIST` in the `@AcraCore` config.

```
reportFormat = StringFormat.KEY_VALUE_LIST
```

**Comment by domdomegg** [comment]
There's still more styling work that could be done to make it feel more part of the commons application. However this at least gets us most of the way there, and future PRs can fix the exact styling.

**Pull request merged**
