### PR TITLE
Fixes #4437 - Changed indentation on files with 2 spaces to 4 spaces

### LINKED ISSUE #4437: Few Files not follow 4 space convention for indentation
**Summary:** 

Since the space convention is 4, there are few files that follow 2 space convention e.g, ExploreListFragment, BookmarkListFragment. So it would be better to make all the files coherent wrt indentation.

### PR DESCRIPTION
**Pull request by JBrown526**
**Description (required)**

Fixes #4437 

What changes did you make and why?

Used autoformatting in Android Studio on all files that had indentation with 2 spaces instead of 4

**Tests performed (required)**

None

### CODE REVIEW

**Review by nicolas-raoul — APPROVED** [review]
This will have a big impact on existing and in-preparation pull requests, but this is needed and the timing is good (just after release branch was merged into master).

**Comment by nicolas-raoul** [comment]
Ah, would you mind rebasing from master?

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Needs rebasing

**Comment by JBrown526** [comment]
Think it should be fixed now, let me know if I need to do anything else. I struggled a bit to figure out how it worked so there might have been an oopsie somewhere

**Comment by nicolas-raoul** [comment]
Very sorry, it seems that today's changes made this PR conflict again... would you mind rebasing again?

**Comment by JBrown526** [comment]
Should be all good again

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
