### PR TITLE
Wikidata edit fix

### LINKED ISSUE #1601: Nearby edits didn't edit Wikidata items
**Summary:** 

Nearby edits didn't edit Wikidata items. I uploaded this image via nearby map: https://commons.m.wikimedia.org/wiki/File:Centre_de_Recerca_Matem%C3%A0tica_3.jpg , by selecting nearby marker of this wikidata item: https://www.wikidata.org/wiki/Q2757630

Upload completed with no problem, displayed on my contirbutions list, but marker is still on map and wikidata item doesn't have the image.

**Add System logs:**

Sorry nothing beneficial

**Expected behavior:** 

Wikidata item should be edited with my user name

**Observed behavior:** 

Wikidata item is still there

**Device and Android version:** 

Android 4.2.2
 
 **Commons app version:** 

Current master

### PR DESCRIPTION
**Pull request by maskaravivek**
## Title (required)

Fixes #1601

### CODE REVIEW

**Comment by neslihanturan** [comment]
Only one line fix, it will be easier if you do. So I don't create another PR. Then wikidata uploads are linked.
- Currently if you upload from map, wikidata uploads are successful. 
- But if you upload from list, it doesn't. Because a line was missing:
In PlaceRenderer.java class, add this line just below line 130 **"editor.putString(WIKIDATA_ENTITY_ID_PREF, place.getWikiDataEntityId());"** then is will look like: 
`
    private void storeSharedPrefs() {
        SharedPreferences.Editor editor = directPrefs.edit();
        Timber.d("directPrefs stored");
        editor.putString("Title", place.getName());
        editor.putString("Desc", place.getLongDescription());
        editor.putString("Category", place.getCategory());
        editor.putString(WIKIDATA_ENTITY_ID_PREF, place.getWikiDataEntityId());
        editor.apply();
    }`

**Comment by maskaravivek** [comment]
@neslihanturan Thanks for the tip. :)

I have added the line that you mentioned. @misaochan Can you help in testing this PR.

**Comment by nicolas-raoul** [comment]
Tested with one image, it works :-)

**Comment by nicolas-raoul** [comment]
I cna confirm that uploads from Nearby (both map and list) are both working.

**Comment by misaochan** [comment]
I have successfully added https://www.wikidata.org/wiki/Q19871703 via Nearby Map, and https://www.wikidata.org/wiki/Q2137835 via Nearby List. :)

Great job @maskaravivek and @neslihanturan !

**Pull request merged**
