### PR TITLE
Fixes #3345

### LINKED ISSUE #3345: Not able to Explore Images when I am not logged into the app.
**Summary:** 

Not able to Explore Images when I am not logged into the app. This is the same exception which is coming when we are trying to login into the app.

**Steps to reproduce:** 

How can we reproduce the issue? 

What did you expect the app to do, and what did you see instead?

I Except the app to show me the images.

**System logs:**
**This is the request string** 
```
--D/OkHttp: --> GET https://commons.wikimedia.beta.wmflabs.org/w/api.php?action=query&format=json&formatversion=2&generator=categorymembers&gcmtype=file&gcmsort=timestamp&gcmdir=desc&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gcmtitle=Category%3AUploaded_with_Mobile%2FAndroid&gcmlimit=10
```

**This is the logs of the error**
```
E/CategoryImagesListFragment: Error occurred while loading images inside a category
    javax.net.ssl.SSLHandshakeException: Chain validation failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:351)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:310)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:178)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
E/CategoryImagesListFragment:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableCollectSingle.subscribeActual(ObservableCollectSingle.java:49)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.security.cert.CertificateException: Chain validation failed
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
    	... 49 more
```

**Screen-shots:** 
d1

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**
Due to certificate issues on beta, app is not able to login, download images
Fixes #3345 

What changes did you make and why?
 * Trust all hosts for beta
* Added a custom NetworkFetcher for Fresco when on beta

**Tests performed (required)**

Tested betaDebug on Api 29

### CODE REVIEW

**Comment by maskaravivek** [comment]
@ashishkumar468 Can you check the build failure?

**Comment by ashishkumar468** [comment]
@maskaravivek  I have fixed the travis-error, please have a look

**Comment by maskaravivek** [comment]
I understand that this might not be the best way to fix it but this is the best we can do to unblock ourselves. The ideal way would be to report the issue to the Commons backend team and request them to fix the SSL error.

**Comment by sivaraam** [comment]
> I understand that this might not be the best way to fix it but this is the best we can do to unblock ourselves. The ideal way would be to report the issue to the Commons backend team and request them to fix the SSL error.

So, IIUC the temporary fix done in this PR is a stopgap. Then I think this clears my confusion as to why we actually needed a custom network fetcher to fix the `Chain verification error` 😌 

That said, I would be glad to act as intermediary in the communicating this issue to the commons backend team to help resolve this issue properly. For that, it would be nice if someone can summarize the actual problem 🙂

**Comment by ashishkumar468** [comment]
@sivaraam  Android is complaining that the possible cause of such errors could be one of these
The CA that issued the server certificate was unknown
The server certificate wasn't signed by a CA, but was self-signed
The server configuration is missing an intermediate CA

[This](https://developer.android.com/training/articles/security-ssl) is where you can find more details.

**Comment by sivaraam** [comment]
@ashishkumar0207 To get an idea about the issue, I built a beta version of the app as of [fe56cef](https://github.com/commons-app/apps-android-commons/commits/fe56cefdbca21125e9202b30c408b3736dc3421d) (which doesn't include fixes in PRs #3349 and #3350). Then I tried to log in using my Beta account and I was able to do so successfully. So, that made me wonder: Is this issue specific to certain Android versions? My device runs Android 5.1.1.

Also, to ensure I understand this correctly, I see that the Android guide page you linked to speaks of solutions to the following exception:
```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

Does the solution for that also apply to fixing the following exception mentioned in #3345? 
```
javax.net.ssl.SSLHandshakeException: Chain validation failed
```

**Comment by ashishkumar468** [comment]
@sivaraam Yes, this issue is only oreo+. Also about the docs, they mention that the 

> java.security.cert.CertPathValidatorException

could be one of the common problems and not the only common problem associated with the SSL.
I agree that this is not the best solution, but we will be more clear after we have insights from the backend team.

**Comment by sivaraam** [comment]
I think I have a theory for why log-in doesn't work for the beta cluster but works for the prod cluster. Note that the following is just a speculation made by analysing the source code of the app and the [wikimedia-android-data-client](https://github.com/wikimedia/wikimedia-android-data-client) library. I haven't verified this yet but this does look promising to me to an extent.

The problem doesn't seem to be related to the Commons server (as I've been suspecting ever since I looked up the commons reasons behind the reasons behind the error). Instead the problem seems to lie in the way we use the wikipedia data client library. Particularly the following line:

https://github.com/wikimedia/wikimedia-android-data-client/blob/master/src/main/java/org/wikipedia/login/LoginClient.java#L69

If my speculation is correct. the above is the line which gets executed when we try to log-in to the beta cluster using just a username and password without any 2FA code. In that case, `loginreturnurl` seems to set to `Service.WIKIPEDIA_URL` i.e., `https://www.wikipedia.org/`. This might be the reason behind the `Chain verification error` we get when trying to log in to the beta cluster because `https://www.wikipedia.org/` and `https://commons.wikimedia.beta.wmflabs.org` are signed using different SSL certificates.

In case you're wondering why this doesn't affect the logins in the prod version, that might be because `https://www.wikipedia.org/` and `https://commons.wikimedia.org/` share the same certificate.

I'm still not sure as to why this only affects Android Oreo+ devices. :thinking: 

Also, this is just a speculation and I haven't verified this completely yet as I do not have a device running Android 9 or above currently. Just wanted to share my speculation just in case someone else might be able to verify this. Hope this is helpful! :slightly_smiling_face:

**Comment by sivaraam** [comment]
I was able to debug this a little more yesterday and it seems the above speculation is invalid. I came to know that we're getting the chain verification failed exception when trying to [get the login token](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java#L263) which is before we try to login using the credentials.

So, I've sent a mail to the [wikitech-l](https://lists.wikimedia.org/mailman/listinfo/wikitech-l). I've Cc-ed those of you whose email I could get my hands on. Let's hope we get some help! The mail can found [here](https://lists.wikimedia.org/pipermail/wikitech-l/2020-January/093035.html).

**Comment by sivaraam** [comment]
I got the [following response](https://lists.wikimedia.org/pipermail/wikitech-l/2020-January/093036.html) in the thread:

> The ssl tester site is reporting that ocsp stapling is misconfigured on
> that domain, maybe that's causing the issue(?)
>
> One of the biggest differences is that beta uses lets encrypt. If for some
> reason the platform you are testing on didnt have lets encrypt certs
> installed, that could cause this. However lets encrypt at this point is
> very widely supported.
>

Here's the link to the SSL [tester report](https://www.ssllabs.com/ssltest/analyze.html?d=commons.wikimedia.beta.wmflabs.org). Here's the relevant portion:

image

This might be a possible reason.

**Comment by sivaraam** [comment]
There's already an open task in Phabricator related to OCSP stapling.

https://phabricator.wikimedia.org/T243881

**Comment by misaochan** [comment]
Pinging @maskaravivek and @ashishkumar468 as they are familiar with the issue.

**Comment by sivaraam** [comment]
As per [this comment](https://phabricator.wikimedia.org/T243881#5861983), the certificate issue has been fixed. I've verified this. I've opened #3396 to revert the stopgap changes that were added to work around the cert issue.

**Pull request merged**
