### PR TITLE
Make P18 edits to corresponding wikidata entity on uploading from Nearby

### PR DESCRIPTION
**Pull request by maskaravivek**
## Description

Fixes part of #252 ie. "Edit P18 property in Wikidata to add the uploaded image"

## Tests performed

Tested on a real android phone by uploading an image from the list of nearby places needing pictures. 
- Uploaded a picture
- Opened the wikidata entity to check if the image got associated
- Refreshed the nearby list, the item no longer shows 🎉 

Note: After performing the test I have gone back to the entity and removed the image as I used a random image for testing. 

## Screenshots showing what changed

The GIF was too big so had to upload elsewhere: https://imgur.com/a/qCfFgv5

### CODE REVIEW

**Comment by neslihanturan** [comment]
Team, before testing this PR I want to make sure that, even if while we are on betaDebug, if we upload a photo via nearby, then it will be uploaded to real servers. Am I correct? So to test this we might need to take a photo of nearby place:)

**Comment by nicolas-raoul** [comment]
I just built from https://github.com/maskaravivek/apps-android-commons/tree/wikidata then opened Nearby and tapped on the pin for https://www.wikidata.org/wiki/Q30297420 then pressed "Gallery" and selected a photo of the thing, then modified slightly the prefilled description and entered metadata as usual before tapping the floppy icon.

Unfortunately, the Wikidata item does not seem to have got any edit: https://www.wikidata.org/w/index.php?title=Q30297420&action=history
The image has been uploaded successfully though: https://commons.wikimedia.org/wiki/File:Building_that_hosts_the_Salt_Science_Research_Foundation.jpg

**Comment by misaochan** [comment]
@neslihanturan The image will be uploaded to the beta server I believe, but the Wikidata edit will be real. Either way, we should use prodDebug for testing. Either by taking real photos of Nearby places, or by uploading a test photo and then deleting. We discussed how to delete Wikidata edits on #252 . :)

**Comment by maskaravivek** [comment]
@nicolas-raoul Am sorry, that the wiki data edit didn't work for you as expected.
Right now I am handling the error silently if the edit call fails. Do you think that some error toast should be displayed if the edit fails? 

I will also add some more logs so that debugging error cases becomes easier.

**Comment by misaochan** [comment]
Hi @maskaravivek , I experienced a few strange bugs while testing this.

My steps:
1. Uploaded a bogus picture for https://www.wikidata.org/wiki/Q19817749 . After the upload went through, the picture was actually added to the P18 claim, yay! **However, Nearby did not reflect the change** - the pin did not disappear even after I refreshed it.
2. Deleted bogus picture.
3. Uploaded a proper picture for https://www.wikidata.org/wiki/Q5355155 . After the upload went through, I checked the P18 claim on that item, nothing was added. However, then I went back to the first Wikidata item (Q19817749) and **the picture was there instead**!
4. So if you look at Q19817749 now, the edit history shows 2 images added. The first image was intended for that item, and the second image was actually uploaded via Q5355155 but ended up in Q19817749 instead.

**Comment by maskaravivek** [comment]
@misaochan Thanks for helping with testing. :)
- Now I have added listeners so the nearby map should refresh immediately after the edit is made. 
- I am unable to reproduce the issue where every time the edit is being made for a single wikidata entity.

Have yet not figured out how to add authentication for these edits. :(

**Comment by misaochan** [comment]
@maskaravivek Are you able to upload at all after your recent changes? All of my uploads fail with the error logs below. Both Nearby direct uploads as well as the usual uploads from the main screen, with different images. I have logged out and logged back in again twice, with neither one fixing the issue.

Also, I think you may need to rebase `commons-app:wikidataEdits` on master, as there are several changes not authored by you in the commit history here. :)

```
05-15 19:20:09.982 21597-21628/fr.free.nrw.commons.debug E/WTF: Result: org.mediawiki.api.ApiResult@3afe3a9
05-15 19:20:10.024 21597-21628/fr.free.nrw.commons.debug E/ApacheHttpClientMediaWi: mustbeloggedin
05-15 19:21:04.764 21597-21597/fr.free.nrw.commons.debug E/ViewRootImpl: sendUserActionEvent() mView == null
05-15 19:21:17.943 21597-21597/fr.free.nrw.commons.debug E/ViewRootImpl: sendUserActionEvent() mView == null
05-15 19:22:28.330 21597-21628/fr.free.nrw.commons.debug E/WTF: Result: org.mediawiki.api.ApiResult@cffc3d
05-15 19:22:28.352 21597-21628/fr.free.nrw.commons.debug E/ApacheHttpClientMediaWi: mustbeloggedin

```

**Comment by nicolas-raoul** [comment]
I just clone Vivek's repo, switch to the "wikidataEdits" branch, switched to prodDebug, ran the app, touched Nearby, selected a nearby pin, touched the "+", select a picture, touched the upload button, and the floppy.
The image was uploaded [successfully](https://commons.wikimedia.org/wiki/File:App_wikidata_test.jpeg) but the [selected Wikidata item](https://www.wikidata.org/wiki/Q30297420) still has no P18.
Am I doing something wrong?

**Comment by misaochan** [comment]
@nicolas-raoul I don't think there is any "wikidataEdits" branch in Vivek's repo. :) Are you perchance testing the wikidataEdits branch of commons-app instead? That would explain why it isn't working for you, since this PR hasn't been merged into `commons-app:wikidataEdits` yet. To test this PR, I am using `git fetch commons-app pull/1495/head:pr-1495`.

**Comment by nicolas-raoul** [comment]
@misaochan Thanks, I cloned the right repo+branch now :-)
Same problem happens, though, the upload was successful but the [image](https://commons.wikimedia.org/wiki/File:App_wikidata_test.jpeg) is still not linked to from Wikidata.

**Comment by misaochan** [comment]
@neslihanturan , we need you to test and see if either my or Nicolas's problems are reproducible. :) I think it should be fine to upload a bogus picture and then manually delete the p18 link on Wikidata, but if you are really concerned about it, you can use the sandbox entity at #252

**Comment by maskaravivek** [comment]
@misaochan I am able to make authenticated edits now. 

https://www.wikidata.org/w/index.php?title=Q13406268&action=history

Yes, I am also facing an issue while uploading/making edits if I install this build over a previously installed version but logging out and logging in again solves it for me. Could you share some logs that might help in detecting the issue? 

Anyone who is testing the PR can skip the whole upload flow and check just the edits if they wish. Paste this snippet in any of the activities and trigger it on its start. Might be helpful while we are debugging various issues. 

```
private void edit() {
        Timber.d("Attempting to edit Wikidata property %s", "Q13406268");
        Observable.fromCallable(() -> mediaWikiApi.wikidatCreateClaim("Q13406268", "P18", "value", "\"Hamburg,_Speicherstadt,_Wasserschloss_--_2016_--_2944-50.jpg\""))
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(result -> {
                    if(result) {
                        ViewUtil.showLongToast(getBaseContext(), "Image added corresponding to wiki data entity successfully!");
                    } else {
                        Timber.d("Unable to make wiki data edit for entity %s", "Q13406268");
                    }
                }, throwable -> Timber.e(throwable, "Error occurred while making claim"));
    }
```

**Comment by maskaravivek** [comment]
@nicolas-raoul I have added logs that might help us identify why the edits are failing for you. Would it be possible for you to retry and share the logs?

**Comment by misaochan** [comment]
Hi @maskaravivek ,

I just retested this on my real device running Android 7.0. It works!!! Well done!! 👍 Uploading a picture added the P18 entity appropriately to https://www.wikidata.org/wiki/Q19876257 and https://www.wikidata.org/wiki/Q14935526 (I will delete those later). The Wikidata edits are also authenticated for me. Excellent work.

A few minor issues:
- After the upload completes, there is a toast that notifies the user and the map refreshes (great!), but the point is still displayed then. It continues to be displayed until I manually relaunch the activity. I'm not sure how easy it will be to fix this bug - it's possible that re-adding refresh functionality to Nearby may be the easiest short term fix.
- I personally feel that the toast is not very non-tech-user friendly. How about something like: "Image successfully added to [entity name] on Wikidata!"?

**Comment by misaochan** [comment]
@maskaravivek I'm happy to go ahead and merge this since @neslihanturan is experiencing issues with her VPN. If there are problems later we can solve them in a different PR.

Please sort out the minor changes requested, then I can merge. :)

**Comment by maskaravivek** [comment]
@misaochan 
- I tried uploading an image and the nearby list updated instantly for me without having to go back. 
- Fetching the entity name will require another API call as the `wbcreateclaim` response doesn't contain the entity name. Can we avoid the API call?

**Comment by misaochan** [comment]
> I tried uploading an image and the nearby list updated instantly for me without having to go back.

Hmm, that has never happened for me. But I guess we can merge this PR first and then debug this issue later since it isn't a major one.

Have addressed the second point in Hangouts. :)

**Comment by maskaravivek** [comment]
@misaochan I have made the change suggested by you. 

Yes, let's merge this first and then we can debug this issue.

**Comment by misaochan** [comment]
Thanks @maskaravivek ! Can't wait to release this feature. :)

**Pull request merged**
