### PR TITLE
Refactor curlatLng to currentLatLng

### LINKED ISSUE #5559: Refactor `curlatLng` to `currentLatLng`

### PR DESCRIPTION
**Pull request by aahlad2000**
**Description (required)**

Fixes #5559

What changes did you make and why?
Refactor the variable curlatLng to currentLatLng

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on Samsung A50 with API level 33.

**Screenshots (for UI changes only)**

### CODE REVIEW

**Comment by aahlad2000** [comment]
Hi @nicolas-raoul, can you please help to review my Pull request. Hope, this is correct.
This is for the issue :
https://github.com/commons-app/apps-android-commons/issues/5559

Thanks!

**Comment by rohit9625** [comment]
Sure we will :)
But you should have some patience and have to wait for at least 2 weeks after creating PR.

You can look after another issue and work on that. This PR will be reviewed soon.

**Review by brijesh027 — APPROVED** [review]
As per the requested code refactor, this pull request fulfills by replacing all the old variable 'curLatLng' with new variable 'currentLatLng'

**Comment by nicolas-raoul** [comment]
Sorry could you please resolve thee conflicts? Thanks! :-)

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
conflict

**Comment by aahlad2000** [comment]
Resolved conflicts, can you please help to review this again, thanks :)

**Comment by aahlad2000** [comment]
@nicolas-raoul @brijesh027 @prtksxna @rohit9625, due to too many conflicts, I have raised a new PR:
Refactor curlatLng to currentLatLng **#5646(https://github.com/commons-app/apps-android-commons/pull/5646)**

Can you please help to review and approve this. Thanks :)

**Pull request closed without merging**
