### PR TITLE
Issue-944: Fix for same activity getting instantiated multiple times

### PR DESCRIPTION
**Pull request by ramarajesh2112**
This is happening because the finish() method on current activity is not
called before switching to the new activity

### CODE REVIEW

**Comment by maskaravivek** [comment]
Now when I go to any Activity from `ContributionsActivity` and press back, the app closes. The expected behaviour is that `ContributionsActivity` will open again. We need to avoid duplicate activities but some sort of back stack should be maintained in IMO. Parent activity concept could be helpful in this scenario. 

https://developer.android.com/training/implementing-navigation/ancestral.html

**Comment by ramarajesh2112** [comment]
@maskaravivek It looks like for able to use the TaskStackBuilder the minSdkVersion should be atleast of 16 whereas currently we have it at 15. Is there any reason why the app is supporting versions from 15? Can I update it to 16 for this change?

**Comment by nicolas-raoul** [comment]
Sounds like a valid case for increasing, if TaskStackBuilder is the best practice.

**Comment by neslihanturan** [comment]
I think we should prioritize this problem and solve it before next release. Because it is a very visible problem.

**Comment by ramarajesh2112** [comment]
@misaochan @nicolas-raoul @maskaravivek I updated the logic such that we have some back stack with ContributionsActivity at the root. Also I changed the activity creation logic so that it will re-use existing instances instead of creating duplicate activities. 

Also, I investigated a bit with regards to parentActivity and TaskStackBuilder but they didn't feel the right way to solve the issue because of the following reasons
1. parentActivity seems to be tightly coupled with the ActionBar for navigation which we do not have.
`    <style name="DarkAppTheme" parent="Theme.AppCompat.NoActionBar">`
and 
`    <style name="LightAppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
2. TaskStackBuilder seemed like an overkill for the problem which can be simply achieved by setting the right intent flags and also it required an API upgrade.

**Comment by maskaravivek** [comment]
Have tested it on Nexus 5. Works perfectly. Going ahead and merging it. Great job @ramarajesh2112

**Pull request merged**
