### PR TITLE
5115: Fix AdvanceQueryFragmentUnitTests

### LINKED ISSUE #5115: Fix unit tests: AdvanceQueryFragmentUnitTests
Broken since https://github.com/commons-app/apps-android-commons/pull/5091 it seems.

Anyone please feel free to send a pull request, thanks! :-)

### PR DESCRIPTION
**Pull request by bosankus**
Fixes #5115 

What changes did you make and why?

- AdvanceQueryFragment was migrated to ViewBinding implementations, and the test cases consisted few redundant tests along with few failed tests too. The change includes fixing all unit test cases.
- Few changes were made on AdvanceQueryFragment to pass the test case.

### CODE REVIEW

**Review by nicolas-raoul — APPROVED** [review]
This solves the testBetaDebugUnitTest error, and the advanced query feature's behavior is unchanged.

**Comment by nicolas-raoul** [comment]
I will merge in a few days unless @psh has comments about these changes :-)

**Comment by psh** [comment]
This is a _vast_ improvement over the old test.  Good job!

**Comment by nicolas-raoul** [comment]
Thanks a lot @bosankus!

**Pull request merged**
