### PR TITLE
Revert back to MainScope for database and ui updates

### LINKED ISSUE #5898: Recently after every upload I get "IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time."
It started this week, probably caused by a recent commit?

Tasks:
1. Reproduce the issue
2. Find since what commit it started (use git bisect)
3. Either revert the commit or improve it.

If you can upload without any such issue please let me know. Thanks! :-)

```
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.kt:435)
at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.kt:505)
at fr.free.nrw.commons.customselector.database.UploadedStatusDao_Impl.insert(UploadedStatusDao_Impl.java:120)
at fr.free.nrw.commons.customselector.database.UploadedStatusDao.insertUploaded(UploadedStatusDao.kt:51)
at fr.free.nrw.commons.upload.worker.UploadWorker$saveIntoUploadedStatus$1$1.invokeSuspend(UploadWorker.kt:538)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at android.os.Handler.handleCallback(Handler.java:991)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8787)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7cb3322, Dispatchers.Main]
```

### PR DESCRIPTION
**Pull request by rohit9625**
**Description (required)**

Fixes #5898 

What changes did you make and why?
Revert back to **MainScope()** in the `ImageLoader.kt` file because that code block contains both UI and database operations.

**Tests performed (required)**

Tested prodDebug on Samsung A14 with API level 34.

**Screenshots (for UI changes only)**
None

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Would you mind linking to the commit that this is reverting? Thanks a lot! 🙂

**Comment by rohit9625** [comment]
How to do that? 😅

**Comment by nicolas-raoul** [comment]
Don't worry I found it: https://github.com/commons-app/apps-android-commons/commit/cdc4f89da551b9be51ee17f488a6c766e6decbd0#diff-2f6019450f14d4da6fa575a7edebd478f4dc0828fc14b95a2ec0b9d83104da8cL68 :-)

It gives context on the revert.

**Comment by rohit9625** [comment]
Thank you @nicolas-raoul 
Should I fix the failing tests or someone is working on it?

**Comment by nicolas-raoul** [comment]
Testing this now, it indeed fixes #5919 :-)

I don't think anyone is working on the unit tests, feel free to work on them, thanks a lot! #5921

**Review by nicolas-raoul — APPROVED** [review]

**Pull request merged**
