### PR TITLE
Added advanced query support in Nearby

### LINKED ISSUE #3410: More powerful pin filtering of Nearby map via allowing users to modify SPARQL query
As requested by @VojtechDostal , power users familiar with SPARQL would find it useful to be able to partially modify the SPARQL query themselves to filter results. We can probably implement this in a similar manner to https://tools.wmflabs.org/wikishootme#lat=50.0720077&lng=14.424068199999999&zoom=15

### PR DESCRIPTION
**Pull request by ashishkumar468**
**Description (required)**

Fixes #3410

What changes did you make and why?
* Added Option to open advanced query button in nearby
* Parse lat/long from the advanced query, otherwise use user's current location

**Tests performed (required)**

Tested betaDebug on API 29

**Screenshots (for UI changes only)**
image
image

https://user-images.githubusercontent.com/17375274/143683016-ef1e9609-cc45-42af-8bea-c1920061589c.mp4

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
It works great!
The customization is not saved, though: When I restart the app, it is back to the default query. Is that intended?
My understanding was that the customization would be saved and used all the time (that's why the reset button is important).

**Comment by misaochan** [comment]
Thanks for testing @nicolas-raoul ! Re: saving, I think we assumed based on your comment at https://github.com/commons-app/apps-android-commons/issues/3410#issuecomment-832007133 that a save function wasn't particularly useful. Was there a misunderstanding? :)

**Review by misaochan — CHANGES_REQUESTED** [review]
Tested with real device running Android 10, prodDebug. All works well for me, just pending appropriate logs for debugging as discussed with Ashish.

**Comment by ashishkumar468** [comment]
> Tested with real device running Android 10, prodDebug. All works well for me, just pending appropriate logs for debugging as discussed with Ashish (and also test coverage).

Added the logs as discussed. Will be logging additional log line to identify if the nearby query has been made by an advanced query

**Comment by nicolas-raoul** [comment]
Sorry for the misunderstanding, at the time I misunderstood that as a way to save different queries, rather than just have a single one. 😭

**Comment by misaochan** [comment]
Hmm. I think for now we will go ahead with the PR, but we can create a new issue to discuss this? I am a bit worried that if we save the query indefinitely, people might forget that they have a custom query and submit a bug report when their next Nearby usage doesn't return the usual results. :) We may need to add a "Custom SPARQL used" indicator of some sort if we implement save.

**Comment by misaochan** [comment]
Works well for me, thanks @ashishkumar468 !

**Pull request merged**
