### PR TITLE
Fixed issue #894

### PR DESCRIPTION
**Pull request by JohnKal**
This line solves the problem with the device rotation.

### CODE REVIEW

**Comment by neslihanturan** [comment]
I tested it and yes, it solves the problem. But, on rotation moment contribution list appears and disapears very fast. Since it is very fast I couldn't get screen shots. Did you see that @JohnKal ?

**Comment by JohnKal** [comment]
@neslihanturan yes i see it now. If it is a problem i will try to fix it.

**Comment by neslihanturan** [comment]
@misaochan and @maskaravivek , I think we should prioritize this one also before release. What do you think about merging this PR?

**Comment by misaochan** [comment]
Yeah, sounds good to me. We can create a new issue for the appearing/disappearing if needed.

**Pull request merged**
