### PR TITLE
#3806 Apply codestyle to project 

### LINKED ISSUE #3806: Apply codestyle to project
**Summary:** 

Most files do not adhere to the codestyle. The project should be reformatted.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by macgills**
**Description (required)**

Fixes #3806 

What changes did you make and why?
- codestyle applied

**Tests performed (required)**

Tested ProdDebug on Nexus5x with API level 27

### CODE REVIEW

**Comment by neslihanturan** [comment]
This PR is huge and will make every other PR conlicted :/ Can't we make it part by part?

**Comment by neslihanturan** [comment]
Wait, is this an automated process, manual or mixed @macgills ?

**Comment by macgills** [comment]
@neslihanturan it is automated.

I am however running into the fact that the checkstyle config doesn't use Google's Java style but a modified version, so I am investigating fixing that

**Comment by ashishkumar468** [comment]
This seems to be a lot of changes, should we consider waiting till 2-13-release is merged with master to avoid possible merge conflict cases, since this is an automated process, this can be easily done again

**Comment by macgills** [comment]
I am making this draft just in case we need it to reference the current disconnect between what `checkstyle` says the codestyle is and what `Google Java` style is.

The [docs](https://github.com/commons-app/commons-app-documentation/blob/master/android/Code-style.md) make no mention of the alterations to Google Java style so when I integrated the style with the project I just used that.

Checkstyle could very well be irrelevant to the project now? It's primary purpose is that it might create too much console output and crash the build? That seems to be the only scenario it will fail the build as of right now.

**Pull request closed without merging**
