### PR TITLE
Fixed “Dumping memory, app will freeze. Brrr.” message

### LINKED ISSUE #2717: “Dumping memory, app will freeze. Brrr.” message
Getting 
{“Dumping memory, app will freeze. Brrr.” message}after uploading  a picture.
Is this something that i can also work on?

Screenshot_20190322-225712
Screenshot_20190322-225739

### PR DESCRIPTION
**Pull request by noahwalugembe**
Getting {“Dumping memory, app will freeze. Brrr.” message} error after uploading a picture.

Using ClickableSpan may still cause leaks even on versions higher than KitKat. If you look into implementation of the ClickableSpan you will notice that it doesn't extend NoCopySpan, so it leaks in onSaveInstanceState()

Fixes #2717 “Dumping memory, app will freeze. Brrr.” message

URLSpan class extends ClickableSpan implements ParcelableSpan hance avoiding the memeory leak
URLSpan open the url, by launching an an Activity with an Intent#ACTION_VIEW intent.
https://developer.android.com/reference/android/text/style/URLSpan

What changes did you make and why?

implementation{strBuilder.setSpan(new URLSpan(url),start, end, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);}

instead of

ClickableSpan clickable = new ClickableSpan() {
public void onClick(View view) {
// Handle hyperlink click
String hyperLink = span.getURL();
launchBrowser(hyperLink);
}
};
strBuilder.setSpan(clickable, start, end, flags);
strBuilder.removeSpan(span);

### CODE REVIEW

**Comment by noahwalugembe** [comment]
Hi @sivaraam @neslihanturan  i have used git checkout -b <new_branch> origin/master to base my branch to remote master.

**Comment by sivaraam** [comment]
Hi @noahwalugembe, You PR still seems to include changes from other PR. Could please paste the output of `git remote -v` here?

**Comment by noahwalugembe** [comment]
> git remote -v

origin  https://github.com/noahwalugembe/apps-android-commons.git (fetch)
origin  https://github.com/noahwalugembe/apps-android-commons.git (push)

**Comment by madhurgupta10** [comment]
@noahwalugembe Please resolve the merge conflicts too :)

**Comment by sivaraam** [comment]
@noahwalugembe You don't seem to be having the Commons app repo as one of your remotes. Do this to add it to your remotes:

`git remote add commons-app https://github.com/commons-app/apps-android-commons`

Then start again using the following:
1. `git fetch commons-app`
2. `git checkout -b <new_branch> commons-app/master`

**Comment by noahwalugembe** [comment]
The new updates in UploadActivity resolved the memory leak we cant now experience the this problem

**Pull request closed without merging**
