### PR TITLE
Fixes #1361 Add manual refresh on same location

### LINKED ISSUE #1361: Nearby places refresh issue
**Summary:** 
There is an issue with manual refresh on nearby places activity

**Steps to reproduce:** 
1. Open nearby places from navigation drawer
2. Now open some other app from task manager
3. Turn off the internet
4. Open wikimedia app again
5. The list of places disappears 
6. Turn on the internet
7. Press refresh, a toast appears stating location has not changed and no refresh takes place

**Expected behavior:** 
A refresh should start

**Observed behavior:** 
No refresh and toast saying location has not changed

**Would you like to work on the issue?**
Yes I would like to work on it

### PR DESCRIPTION
**Pull request by devaar100**
## Description

Fixes #1361 
Allowed refresh on same location if list currently empty

## Tests performed
Tested on Android version 6.0.1

### CODE REVIEW

**Comment by misaochan** [comment]
I would recommend rebasing on 2.7.x-release and submitting your PR to that branch. :)

**Comment by devaar100** [comment]
@misaochan thanks sir will do ;)

**Comment by neslihanturan** [comment]
Can you test the app again @devaar100 ? I think the issue you halve solved is not possible in any case currently. Because we update the list according to network connection.

**Comment by neslihanturan** [comment]
If you fix the conflicts, I can test this:)

**Comment by neslihanturan** [comment]
Since we listen the network connectivity, producing related issue should be impossible anymore

**Pull request closed without merging**
