### PR TITLE
Fixes #2388 Replace Toasts with Snackbars

### LINKED ISSUE #2388: Replace toasts with snackbars where appropriate
**Summary:** 

App uses toasts at many places which can be replaced by Snackbars for better UI.

**Commons app version:** 

Latest master

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by neeldoshii**
## Fixes

* Fixes #2388 

## Purpose/ Description

I have used the methods of Snackbars from ViewUtil and utilized it to convert some toasts to Snackbar. 
Note : It doesn't refactor every toast but it covers most of the toasts to snackbar. 

## Video

**Permission Utils Toast (Before)**

https://github.com/commons-app/apps-android-commons/assets/60827173/f0a679ce-7182-4e75-8b2a-9c3ad8839450

**Permission Utils Snackbar (After)**

[permission_snackbar.webm](https://github.com/commons-app/apps-android-commons/assets/60827173/565369a7-d7db-40de-af8a-0bb0311dd8e2)

**Depiction Toast (Before)**

[depiction.webm](https://github.com/commons-app/apps-android-commons/assets/60827173/5817f962-269e-4748-8ae3-504f3d308a3b)

**Depiction Snackbar (After)**

https://github.com/commons-app/apps-android-commons/assets/60827173/4ae545e1-d8dd-471e-85f0-bcbc689923d7

**Recent Search Toast(Before)

https://github.com/commons-app/apps-android-commons/assets/60827173/8c33ab40-d9e1-49a0-8de7-ae1ae08114f1

**Recent Search Snackbar(After)

https://github.com/commons-app/apps-android-commons/assets/60827173/93d40c23-36ab-4d6e-a22b-526f573dfed4

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Sorry for the delay in reviewing this!
Would you mind fixing the conflicts and unit tests?
Thanks!

**Review by nicolas-raoul — CHANGES_REQUESTED** [review]
Conflict

**Comment by neeldoshii** [comment]
Completing my leftover PR task.
Things have changed a lot from the time I implemented initially.

Current approach what I am planning
1. Clear all commits full fresh start.
2. Create a composable SnackBar widget utility object. 

Reason:
- Slow migration towards Material 3
- Initial small steps towards getting close to getting compose.
- Removing toast completely from the app.

**Comment by nicolas-raoul** [comment]
Should this be a draft? 🙂

**Comment by neeldoshii** [comment]
> Should this be a draft? 🙂

Yes, my bad

**Pull request closed without merging**
