### PR TITLE
Help button

### LINKED ISSUE #1397: Addition : Adding a link to Help page in Tutorial
**Summary:** 

We can add a small button for more help in the last slide of tutorial to open a link to [Help page](https://commons.m.wikimedia.org/wiki/Help:Contents) of wikimedia commons. Here they can learn more about 
- licensing,
- Privacy policy
- copyrights and other related stuff.

### PR DESCRIPTION
**Pull request by 97balakrishnan**
## Description

Fixes #1397

Added a button to open the wikimedia commons help page at the end of the tutorial

## Tests performed
Tested on Android 6.0.1 Moto G3

## Screenshots showing what changed
 alt link
alt link

### CODE REVIEW

**Comment by misaochan** [comment]
Sorry, just managed to look at this. I definitely agree that the "more help" action should be the secondary one. I would recommend a link in the bottom right corner instead.

Additionally, perhaps "more information" might be better than "more help"?

What do you think @neslihanturan ?

**Comment by 97balakrishnan** [comment]
Ok I'll make the changes

**Comment by 97balakrishnan** [comment]
Is top right better ? @misaochan

**Comment by misaochan** [comment]
I'd personally go with bottom right, but we can wait for Neslihan to weigh in. :)

**Comment by 97balakrishnan** [comment]
Ok :)

**Comment by 97balakrishnan** [comment]
I've initially pushed the top right version, will modify after further discussions :)

**Comment by neslihanturan** [comment]
Bottom right is better for me too @misaochan

**Comment by 97balakrishnan** [comment]
Okk I'll change that @neslihanturan

**Comment by maskaravivek** [comment]
@97balakrishnan were you able to make this change. We can go ahead and merge it once the UI is fixed. :)

**Comment by 97balakrishnan** [comment]
Sorry for the long delay

**Comment by 97balakrishnan** [comment]
alt link

**Comment by neslihanturan** [comment]
Works as intended @97balakrishnan , thanks!

**Pull request merged**
