### PR TITLE
Fix empty default lang bug

### LINKED ISSUE #4583: Descriptions in Nearby are in the wrong language
**Summary:** 

Descriptions in Nearby are in random languages for me. I've seen Arabic and German so far (and also English, which is correct for my phone language).

**Steps to reproduce:** 

The easiest way is to go to Nearby list and look at all the descriptions. But the bug carries over into the details shown in the individual places, and also the autofill when uploading for a Nearby place.

**Device and Android version:** 

Samsung Galaxy S20FE, Android 11
 
**Commons app version:** 

3.1-release

**Screen-shots:** 

Screenshot_20210826-012122_Commons

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
Fixes #4583 Empty default lang bug

**Tests performed**
Tested betaDebug on Pixel 5 with API level 30

### CODE REVIEW

**Comment by misaochan** [comment]
Hi @madhurgupta10 , unfortunately the issue for me is not solved. :(

I notice that it seems to mostly happen when instanceOf is being used (because the item has no Wikidata description). For instance, see the screenshot below:

And then look at https://www.wikidata.org/wiki/Q19873498 . So the desc should say "historic site", but on our app it says "historische Stätte in Australien" (which I presume is German).

**Comment by madhurgupta10** [comment]
@misaochan Could you please try this (not a solution but a check) and let me know if it solves the issue

Go To Settings < Scroll to App user interface language < Tap on English (even if it is already selected)

Then try the nearby again

**Comment by madhurgupta10** [comment]
@misaochan I did some digging for this issue, I can confirm that the request and response are both completed in the lang "en" It seems like that the backend is providing this result

image

**Comment by misaochan** [comment]
> @misaochan Could you please try this (not a solution but a check) and let me know if it solves the issue
> 
> Go To Settings < Scroll to App user interface language < Tap on English (even if it is already selected)
> 
> Then try the nearby again

I tried this, does not solve the problem for me.

> @misaochan I did some digging for this issue, I can confirm that the request and response are both completed in the lang "en" It seems like that the backend is providing this result

Hmm, sorry if I'm missing something... I understand that this is the current longDescription, but we don't get longDescription directly from the backend. It is a concatenation of the label and either the description (if there is a description), or the instanceOf (if there is no description).

So we do get the instanceOf from the backend in this case... but we've been getting instanceOf from the backend for a long time, and it has previously said "historic site" for me. This issue is fairly recent.

**Comment by madhurgupta10** [comment]
> If you go to the coordinates for https://www.wikidata.org/wiki/Q19873498 (check the Wikidata coords, then use them in your emulator), what do you see in our app for that item? Does it also say "historische Stätte in Australien" for you?

Yes

**Comment by madhurgupta10** [comment]
> So we do get the instanceOf from the backend in this case... but we've been getting instanceOf from the backend for a long time, and it has previously said "historic site" for me. This issue is fairly recent.

I did a careful research on this issue, I found out that earlier we were using `item.getClassLabel().getValue()` instead of `description` (see the 2nd screenshot below) that is why "historic site" was displayed instead of "historische Stätte in Australien" I can confirm this with the following test where I changed back to `item.getClassLabel().getValue()` and got the following result



Screenshot 2021-09-07 215214

**Comment by madhurgupta10** [comment]
The API gives us "de" instead of "en" for description that is why we are getting wrong lang
image

One way to solve this is to use "label" instead of "description"

**Comment by misaochan** [comment]
Interesting discovery, thanks for looking into it @madhurgupta10 ! I wonder why this only happens for some descriptions and not for others... the majority of the descriptions are still in English.

@nicolas-raoul could you weigh in on this please?

**Comment by nicolas-raoul** [comment]
Screen Shot 2021-09-08 at 08 30 06

The only solution would be for someone to write descriptions in English. Until there is an English description, we should continue using a description in another language, which might or might not be readable by the user but is better than nothing in my opinion. Like everything in Wikimedia, people will probably only start writing descriptions when they see a need for it.

**Comment by misaochan** [comment]
Merging this anyway as it fixes a separate bug. Thanks!

**Pull request merged**
