### PR TITLE
Closes #3061

### LINKED ISSUE #3061: App crashes in ContributionListFragment
**System logs:**

```
--------- beginning of crash
2019-07-09 11:25:17.416 13854-13854/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
Process: fr.free.nrw.commons.beta, PID: 13854
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
at android.app.Activity.performSaveInstanceState(Activity.java:1477)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4631)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3934)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3999)
at android.app.ActivityThread.-wrap25(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
2019-07-09 11:25:17.431 13854-13854/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
at android.app.Activity.performSaveInstanceState(Activity.java:1477)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4631)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3934)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3999)
at android.app.ActivityThread.-wrap25(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

### PR DESCRIPTION
**Pull request by ashishkumar468**
* Added null check for contribution with position in ContributionsListFragment

**Description (required)**

Fixes #3061 App Crashes in ContributionListFragment

What changes did you make and why?
Null checks on Contribution before extracting the uri's lastPathSegment
**Tests performed (required)**

Tested betaDebug on Pixel Api 27

### CODE REVIEW

**Comment by ashishkumar468** [comment]
@neslihanturan The NPE is happening because we are trying to fetch the id of the contribution from the cursor position and if the cursor gets closed somehow and we try to fetch the id then, null value will be returned, and that is why I have handled that. With the cursor based implementation, there are chances of the cursor getting closed when the app goes in background (Handled by the framework with the current implementation as far as I understand). An effect of this will be that in such cases, the position will not be retained on configuration changes.

**Comment by neslihanturan** [comment]
This should solve your reported issue @PavelAplevich

**Comment by PavelAplevich** [comment]
@neslihanturan @ashishkumar468 With this fix, app looks good. I think all works correctly

**Comment by misaochan** [comment]
Thanks @ashishkumar468 and @PavelAplevich !

**Pull request merged**
