### PR TITLE
Fixes Issue #5713: "Edit location" is hard to use (and confusing)

### LINKED ISSUE #5713: "Edit location" is hard to use (and confusing)
### Feedback

When geotagged picture is being uploaded, and _"Edit location"_ button is clicked, there are several usability problems, see this video:

https://github.com/commons-app/apps-android-commons/assets/156656/325f4a12-bb14-4cf4-8631-a1fa40de6412

- `00:00:02` on opening; the map is positioned on user's current position, and not to the location of GPS EXIF Tags in the picture which would make sense (that one is already being tracked in https://github.com/commons-app/apps-android-commons/issues/5704)
- `00:00:10` even when user manually navigates to picture location and presses and presses `Show in map app`, the location selected in the other app (OsmAnd in this case) is not the location of the GPS EXIF tags from the picture, but currently viewed map center (which is going to be off, even if user tried to carefully position it in the middle). It should instead always position on exact location contained in the GPS EXIF tags.
- `00:00:34` when users presses `Edit location`, the map jump from EXIF GPS location to current center of the map, thus losing the original picture position. It should instead start from the EXIF GPS position and only move at explicit user click to move it somewhere else; as it is likely that the user only wants to move it slightly from location recorded in EXIF GPS tags (as the location of the subject of the picture is usually not the exactly same as the location of the phone, as you usually take picture of object at several (or several dozen) meters away.

### Wiki username

Mnalis

### Device name

Samsung Galaxy S23+

### Android version

Android 14 (OneUI 6.1)

### Commons app version

5.0.1~af028cbdd (latest F-droid)

### PR DESCRIPTION
**Pull request by Jason-Whitmore**
**Description (required)**

Fixes #5713

What changes did you make and why?

Changes were made for both functionality and clarity.

Functionality:

Changes for functionality were made to solve the first 2 subissues that were described in issue #5713. The third subissue was discussed further in the comments and does not seem to be a bug at this point.

To fix subissue 1, an if check was added to see if the selected image had EXIF location data. If it did, the map center would move to the EXIF location. If the image did not have EXIF location data, the map center would move to the device's GPS location (if available).

To fix subissue 2, the correct location variable was used in the (renamed) showInMapApp() method so that the map app would center on the location EXIF data.

Clarity:

Changes for clarity included moving around, rewriting, or adding code (such as helper methods). Also, redundant code was removed. These changes make the code easier to understand and should help with long term maintenance.

**Tests performed (required)**

Tested betaDebug on Android Studio Emulator with API level 34.

**Screenshots (for UI changes only)**

In this first video, the device's GPS location is set to NYC. The first image selected for upload contains EXIF location data of Seattle. When the "Edit Location" button is pressed, the map will center on the EXIF location. The second image selected for upload does not contain EXIF location data. When the "Edit Location" button is pressed, the map will center on the device's GPS location in NYC.

[issue5713_part1_compressed.webm](https://github.com/commons-app/apps-android-commons/assets/30037173/1e7bb1e1-ed54-4b0e-8765-9c7ca1e1c6ac)

In this second video, the image with EXIF data is selected for upload. In the "Edit Location" menu, the map center is moved out into the water and then the "Show in Map App" button is pressed. The external map app correctly centers on the image's EXIF location, rather than centering on the water.

[issue5713_part2_compressed.webm](https://github.com/commons-app/apps-android-commons/assets/30037173/eec8a319-ae89-47fc-bfac-e2749bfb881a)

---

### CODE REVIEW

**Review by nicolas-raoul — COMMENTED** [review]
Two minor things:

When tapping Edit, the pin "jumps" a bit:
https://github.com/user-attachments/assets/5702fa4e-4306-48bf-a5a9-28a4dfa682a7

After reinstalling the app (or wiping its storage), the first time GPS location is shown rather than EXIF location:
https://github.com/user-attachments/assets/52cd7b82-4973-494d-91b0-e1173fa10ce7
Probably related to granting permission.

I am fine with merging as-is and creating separate issues, but if you know how to fix them before merging that would be even better. 🙂

**Comment by Jason-Whitmore** [comment]
I'll fix those two problems and re-request a review when I'm done.

Thank you for providing those videos.

**Comment by Jason-Whitmore** [comment]
I saw the issue and fixed it.

The first new commit fixes the issue. The second commit contains some minor changes to the javadocs.

Please let me know if there are any other issues. Thank you!

**Review by nicolas-raoul — APPROVED** [review]
Works great both for new uploads and already uploaded pictures. Code looks good. Thanks a lot Jason!

**Pull request merged**
