### PR TITLE
Show media details on clicking image in Peer Review

### LINKED ISSUE #2763: Peer review: show description
Description often says why a picture is special. For instance:

Title: Abdel Rawid
Description: Soccer player in the 2020 Iraqi Olympics team

That can change the reviewer's perception from "_Hum probably another worthless selfie_" to "_Whoa this is a very valuable picture_".

### PR DESCRIPTION
**Pull request by cypherop**
**Description (required)**

Fixes #2763 

**What changes did you make and why?**

Currently on clicking the image it does nothing. Now it will show the media details on clicking the image same as there is for explore and contributions fragment.

**Tests performed (required)**

Tested ProdDebug on Motorola Moto G5 plus with API level 24.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Hi, I see some problems with the implementations, but before reviewing I want to make sure if the PR is awake of not?

**Comment by sp2710** [comment]
@neslihanturan Sorry for late reply. I am done with my exams so now I can work on this.

**Comment by neslihanturan** [comment]
Awesome @sp2710 ! As you can see from conflicts, our Review Activity is refactored. If conflicts are too complicated, you can consider to open a refresh PR too. And please make sure you checked our current media details activity implementations beforehand.

**Comment by domdomegg** [comment]
Closing stale PR for now, reopen if more work happening on it.

**Pull request closed without merging**
