### PR TITLE
#3624 DateTimeFormat wrong - match pattern returned from servers

### LINKED ISSUE #3624: DateTimeFormat wrong
**Summary:** 

Cannot save contribution on successful upload because format is not is08601 datetime

**Steps to reproduce:** 

Attempt to upload anything, see failure.

**System logs:**

```
W/UploadService: Exception during upload
    java.text.ParseException: Unparseable date: "2020-04-07T14:16:51Z"
        at java.text.DateFormat.parse(DateFormat.java:362)
        at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$5$UploadService(UploadService.java:290)
```
 
**Commons app version:** 

master.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by macgills**
Fixes #3624 

What changes did you make and why?

Used the right format

**Tests performed (required)**

getting timeouts but wrote unit test, if anyone can test that'd be great

### CODE REVIEW

**Comment by misaochan** [comment]
Tested on prodDebug, works for me, thanks @macgills !

**Comment by misaochan** [comment]
Hm, I just noticed that there seems to be a discrepancy in the dates. E.g. https://commons.wikimedia.org/wiki/File:Fruit_tea_store.jpg  - Summary section says "Date | 2 January 2020 (according to Exif data)", whereas the EXIF section at the bottom says "Date and time of data generation | 15:01, 1 January 2020". 

Not sure if it's caused by this PR though.

**Comment by misaochan** [comment]
So I looked up the ISO 8601 https://www.w3.org/TR/NOTE-datetime and it seems like the time zone designator for UTC should be `Z`, not `X`?

**Comment by macgills** [comment]
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
image
Z does stand for UTC in the 8601 however X here is a pattern that matches on Z and other timezone info that I think will never exist for these dates because these dates are generated to be UTC serverside.

**Comment by macgills** [comment]
> Hm, I just noticed that there seems to be a discrepancy in the dates. E.g. https://commons.wikimedia.org/wiki/File:Fruit_tea_store.jpg - Summary section says "Date | 2 January 2020 (according to Exif data)", whereas the EXIF section at the bottom says "Date and time of data generation | 15:01, 1 January 2020".
Not sure if it's caused by this PR though.

I would doubt it, this date format is used only for `dateCreated` which is a local field added on a successful upload, never touches a server.

**Comment by misaochan** [comment]
Thanks for the clarification, I'll create a new issue then. :)

**Pull request merged**
