### PR TITLE
improvements for #499 issue

### PR DESCRIPTION
**Pull request by amylin0147**
tackles issue #499 making it multiline so you can see what you write in the title

### CODE REVIEW

**Comment by akaita** [comment]
The error in CI is really because `master` was broken when you created your branch.
The change is good. LGTM 🚀

**Comment by whym** [comment]
This makes the title field larger (taller) after a long text is entered, while @nicolas-raoul's request in #499 sounded like the title field should be taller by default. (at least that was my understanding)

Both would be good, but I tend to see the automatic enlargement (this commit) is slightly better.

@nicolas-raoul: what do you think?

**Comment by whym** [comment]
@amylin0147: Can the commit message "modify title editText" perhaps be more precise? I'd use something like "Make the title field multiline".

In case you are not familiar with git: changing a commit message can be done with "git amend".

**Comment by whym** [comment]
Thanks for the update @amylin0147. As I said, this might be slightly different from @nicolas-raoul's request but I'd consider the task is solved.

**Comment by nicolas-raoul** [comment]
Sounds good to me :-)

**Pull request merged**
