### PR TITLE
Fixes #1225

### LINKED ISSUE #1225: Unable to start the app on pre-lollipop devices
**Summary:** 
On pre-lollipop devices (tested with physical device and emulator) the app never starts. Crashes immediately.

**Steps to reproduce:** 
Just start the app on a pre-lollipop device

**Add System logs:**
```
02-28 12:29:37.486 2502-2502/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons.debug, PID: 2502
                                                 java.lang.RuntimeException: Unable to get provider fr.free.nrw.commons.modifications.ModificationsContentProvider: java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.modifications.ModificationsContentProvider" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.free.nrw.commons.debug-1, /system/lib]]
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.modifications.ModificationsContentProvider" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.free.nrw.commons.debug-1, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
```

**Device and Android version:** 
4.4

### PR DESCRIPTION
**Pull request by knight-shade**
## Description
Fixes #1225 
Added multidex library v1.0.2 and now CommonsApplication extends from MultiDexApplication.

### CODE REVIEW

**Comment by misaochan** [comment]
Thanks for the report and the quick PR, guys! :)

**Comment by knight-shade** [comment]
@maskaravivek  It is already present. By the way due to this fix, app failed a staggering 84 tests :worried: 
Since multidex installation failed for each of 84 test. Attached a screenshot below:
screenshot from 2018-03-02 23-18-01

**Comment by maskaravivek** [comment]
Sorry, I am not an expert with tests :( 

@psh Do you have any suggestions here.

**Comment by neslihanturan** [comment]
@knight-shade thanks! It fixes the bug, however I cant merge this since this broken tests currently. On the other hand I am using you changes to be able to continue testing on prelollipop:)

**Comment by misaochan** [comment]
Ouch!! Yeah, I'm not sure why that's happening. @whym any ideas?

**Comment by knight-shade** [comment]
@neslihanturan @misaochan I have found a fix for it, and pushed a commit for the same. All tests passes successfully.

**Comment by neslihanturan** [comment]
Thanks @knight-shade !

**Pull request merged**
