### PR TITLE
Do not create another dialog with the same custom view - reuse the old one

### LINKED ISSUE #3032: Dialog not showing up.
**Summary:** 

Dialogs are not showing up(sometimes) in the HomePage, because the parser says that the current dialog view already has a parent and adding it to another parent would require us to remove this dialog view from the existing parent.

**System logs:**

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4837)
        at com.android.internal.app.AlertController.setupCustomContent(AlertController.java:627)
        at com.android.internal.app.AlertController.setupView(AlertController.java:521)
        at com.android.internal.app.AlertController.installContent(AlertController.java:264)
        at android.app.AlertDialog.onCreate(AlertDialog.java:436)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
        at android.app.Dialog.show(Dialog.java:302)
        at fr.free.nrw.commons.utils.DialogUtil.showSafely(DialogUtil.java:33)
        at fr.free.nrw.commons.utils.DialogUtil.showAlertDialog(DialogUtil.java:140)
        at fr.free.nrw.commons.utils.DialogUtil.showAlertDialog(DialogUtil.java:96)
        at fr.free.nrw.commons.contributions.ContributionsFragment.showNearbyCardPermissionRationale(ContributionsFragment.java:523)
        at fr.free.nrw.commons.contributions.ContributionsFragment.checkPermissionsAndShowNearbyCardView(ContributionsFragment.java:504)
        at fr.free.nrw.commons.contributions.ContributionsFragment.onResume(ContributionsFragment.java:484)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2499)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:926)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2605)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2577)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:267)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:463)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:453)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:173)
        at android.app.Activity.performResume(Activity.java:7325)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-23 10:36:28.746 10262-10262/fr.free.nrw.commons.beta E/ContributionsFragment: onFragmentResumed fr.free.nrw.commons.contributions.ContributionsListFragment

**Device and Android version:** 

Google Pixel, Api 27
 
**Commons app version:** 

2.10.2-debug

### PR DESCRIPTION
**Pull request by albendz**
**Description (required)**

Fixes #3032 Dialog Not Showing UP

What changes did you make and why?

**Tests performed (required)**

Tested Debug on Pixel XL with API level 26. 
1. On a screen with a dialog
2. Suspend
3. Resume

Verified: no exception and no duplicated dialogs

No UI changes.

### CODE REVIEW

**Comment by ilgazer** [comment]
> On a screen with a dialog
> Suspend
> Resume

I cannot duplicate the original bug in Genymotion API 23. Do you consistently get double dialogs when you follow these steps?

**Comment by albendz** [comment]
I messed that one up - you will not get double dialogs, that was part of a debug change I made. You will see the exception though.

**Comment by neslihanturan** [comment]
Hi @albendz , I approved this by reading the code but can you provide me the test scenario so that I can test it too?

**Comment by albendz** [comment]
I'm having trouble building latest from master (some gradle build failure on debug resources) so I'm  not able to retry the steps but from what I remember:
1. Disable location
2. Open the app to see the location permissions dialog
3. Suspend the app
4. Resume

You will see in logs an error about a dialog parent. The dialog is actually being created again with the same inner content view, which is where this error is happening. The original dialog isn't being dismissed, it's the new one that doesn't actually get created.

**Comment by albendz** [comment]
Confirmed that is the repo. You will get this error in the logs: 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Pull request merged**
