### PR TITLE
Resolves Reloading of image on moving to next question in peer review

### LINKED ISSUE #2698: Improve peer review feature quality
**Summary:** 

After #2602 is merged #2253 is completed. Now some quality issues from hackathon still needs to be fixed.

- [ ] Code style issues @maskaravivek 
- [x] Move from XML to JSON @maskaravivek 
- [ ] It scrolls, I would prefer static/ support different screen sizes
- [x] Images moves on swipe, just questions should move instead @vanshikaarora 
- [ ] A beta alert should be added somewhere
- [x] Make image clickable - Open media details activity when clicked.
- [ ] Not showing the categories peer review screen for the images having zero categories.
- [ ] Or let the user categorize the image.
- [x] Adding a question mark next to "skip this image" button and Peer Review title which will display an explanation about their usage. @silkypriya 
- [x] Refactor asynctasks to Rxjava implementation @vanshikaarora 
- [ ] Write unit tests with kotlin @neslihanturan 
- [ ] Optimize randomizer
- [x] Extracting string resources for i18n

I am willing to work on some of them. But we can share, anyone wants to work on them please comment down.

### PR DESCRIPTION
**Pull request by vanshikaarora**
**Description (required)**

Fixes sub-task of #2698 to stop reloading of image while moving to the next question for the same image. 
Fixes #2698 Improve peer review feature quality

### Changes made
- Removed the image and caption from ReviewImageFragment.java to ReviewActivity.java
- Correspondingly loading image and progressbar in ReviewActivity.java

### CODE REVIEW

**Comment by domdomegg** [comment]
Please can you resolve the merge conflicts and I can review.

**Comment by vanshikaarora** [comment]
@domdomegg I have resolved the merge conflicts. Kindly review :)

**Comment by vanshikaarora** [comment]
@domdomegg I have made the changes. Here is the modified UI.
Kindly review :)

WhatsApp Image 2019-03-23 at 11 08 24 PM

**Comment by vanshikaarora** [comment]
Thanks for approving the PR @domdomegg  :)

**Pull request merged**
