### PR TITLE
Update gradle version from 3.3 to 4.0

### PR DESCRIPTION
**Pull request by tobias47n9e**
With Android Studio 3 the app cannot be built at the moment. This
is caused by Gradle 3.3 not supporting the forTask() method.
Updating gradle to 4.0 resolves the issue.

### CODE REVIEW

**Comment by misaochan** [comment]
Are other folks okay with this?

**Comment by whym** [comment]
Fine by me except that it would be better to upgrade it to the official 4.0 (which is yet to come) later.

Also, I wonder if it might be better to go with the newer 4.0 RC1 or M2.

**Comment by tobias47n9e** [comment]
I updated to the 4.0rc1 version and building still works.

**Comment by whym** [comment]
Thanks! It works for me on Android Studio 2.3.2.

**Comment by misaochan** [comment]
Whoops, I forgot to ask, shouldn't we update the value of `gradleVersion = 2.3.0` in gradle.properties as well?

**Comment by whym** [comment]
That is for android library for gradle, right? Maybe we should, but I believe it is an independent thing to decide.

**Pull request merged**
