### PR TITLE
Fixed Padding for FAB in nearby #2779

### LINKED ISSUE #2779: Upload FAB Missing Padding in Nearby
**Summary:** 
Upload FAB Button is Missing Padding in Nearby 

**Screenshot**
Screenshot_20190328-082901

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by madhurgupta10**
**Description**
Fixed Padding for Upload FAB in nearby

Fixes #2779 Upload FAB Missing Padding in Nearby

**Tests performed**

Tested betaDebug on Xiaomi Mi A1 with API level 28.

**Screenshots showing what changed**

Before
Screenshot_20190328-082901

After
Screenshot_20190328-083417

### CODE REVIEW

**Comment by neslihanturan** [comment]
Can you please add some other screenshots with other screen sizes too, by using an emulator? Ie. tablet screen.

**Comment by madhurgupta10** [comment]
@neslihanturan I wanted to do that but the app seems to be crashing on Tablets #2766 :(

**Comment by madhurgupta10** [comment]
@neslihanturan I was able to fix the tablet app crash issue #2766 , I will open another PR for it
Screenshot_1553788419
Screenshot_1553788427
Screenshot_20190328-210406
Screenshot_20190328-210530

**Comment by domdomegg** [comment]
The gallery icon seems to be further from the + icon now. Can this be like previously, as it looks unbalanced now. Otherwise this PR seems good.

**Comment by madhurgupta10** [comment]
@domdomegg That is because of extra FAB (android:id="@+id/fab_commons_page") in nearby, I don't know if it is even in use or not.

**Comment by domdomegg** [comment]
It doesn't seem to be used anywhere - probably worth removing or changing the padding settings as formatting looks weird with the extra gap there.

**Comment by madhurgupta10** [comment]
@domdomegg Could you please review #2787 in high priority, due to the crash I am unable to test other UI changes.

**Comment by madhurgupta10** [comment]
> It doesn't seem to be used anywhere - probably worth removing or changing the padding settings as formatting looks weird with the extra gap there.

@domdomegg Even removing it, didn't helped, to fix that small gap, I probably have to go through many changes, not in UI but also in NearbyMapFragment, Also opening it horizontally in Landscape mode This might take a long time to do so, better to do it in a separate PR IMO.

**Comment by madhurgupta10** [comment]
@domdomegg Done :) 
Screenshot_20190329-053448

**Comment by madhurgupta10** [comment]
@neslihanturan @domdomegg please review the new changes :)

**Comment by neslihanturan** [comment]
Worked fine for me, thanks @madhurgupta10

**Pull request merged**
