### PR TITLE
Fixed indefinite repeat images are showed when browsing some categories(Fixed #2182 #2523)

### LINKED ISSUE #2182: Explore category shows same image indefinitely
**Steps to reproduce:** 

1. Go to Explore
2. Type "pictures of the year" in the search bar (UPDATE: category has changed, use `Velles (Indre)` instead)
3. Select the "categories" tab
4. Tap the first one https://commons.wikimedia.org/wiki/Category:Pictures_of_the_Year
5. Scroll its media
6. Notice that after two other picture, the picture https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg is repeated infinitely
7. Scrolling more just makes that same picture appear more.

**System logs:**

```
12-20 12:07:05.183 31263  5939 D CustomApiResult: API response is
12-20 12:07:05.183 31263  5939 D CustomApiResult:  <?xml version="1.0" encoding="UTF-8"?><api><continue iistart="2007-02-11T14:50:24Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/><query><pages><page _idx="33050273" pageid="33050273" ns="14" title="Category:Pictures of the Year/2013 (finalist)"/><page _idx="30597925" pageid="30597925" ns="14" title="Category:Picture of the year barnstars"/><page _idx="3207499" pageid="3207499" ns="4" title="Commons:Grafika roku"/><page _idx="1662301" pageid="1662301" ns="6" title="File:POTY Feb 11.jpg" imagerepository="local"><imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/5/56/POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301"><extmetadata><DateTime value="2007-02-11 22:18:06" source="mediawiki-metadata" hidden=""/><ObjectName value="POTY Feb 11" source="mediawiki-metadata" hidden=""/><CommonsMetadataExtension value="1.2" source="extension" hidden=""/><Categories value="Media lacking a description|Pictures of the Year|Self-published work" source="commons-categories" hidden=""/><Assessments value="" source="commons-categories" hidden=""/><DateTimeOriginal value="" source="commons-desc-page"/><Credit value="&lt;span class=&quot;int-own-work&quot; lang=&quot;en&quot;&gt;Own work&lt;/span&gt;" source="commons-desc-page" hidden=""/><Artist value="&lt;a href=&quot;//commons.wikimedia.org/wiki/User:Alvesgaspar&quot; title=&quot;User:Alvesgaspar&quot;&gt;Alvesgaspar&lt;/a&gt; (&lt;a href=&quot;//commons.wikimedia.org/wiki/User_talk:Alvesgaspar&quot; title=&quot;User talk:Alvesgaspar&quot;&gt;talk&lt;/a&gt;&lt;span style=&quot;white-space:nowrap&quot;&gt; &lt;b&gt;·&lt;/b&gt;&lt;/span&gt; &lt;a href=&quot;//commons.wikimedia.org/wiki/Special:Contributions/Alvesgaspar&quot; title=&quot;Special:Contributions/Alvesgaspar&quot;&gt;contribs&lt;/a&gt;)" source="commons-desc-page"/><LicenseShortName value="CC BY-SA 2.5" source="commons-desc-page" hidden=""/><UsageTerms value="Creative Commons Attribution-Share Alike 2.5" source="commons-desc-page" hidden=""/><AttributionRequired value="true" source="commons-desc-page" hidden=""/><LicenseUrl value="https://creativecommons.org/licenses/by-sa/2.5" source="commons-desc-page" hidden=""/><Copyrighted value="True" source="commons-desc-page" hidden=""/><Restrictions value="" source="commons-desc-page" hidden=""/><License value="cc-by-sa-2.5" source="commons-templates" hidden=""/></extmetadata></ii></imageinfo></page><page _idx="24840980" pageid="24840980" ns="14" title="Category:Pictures of the Year/2012 (finalist)"/><page _idx="20107176" pageid="20107176" ns="14" title="Category:Pictures of the Year/2011 (finalist)"/><page _idx="20107168" pageid="20107168" ns="14" title="Category:Pictures of the Year/2010 (finalist)"/><page _idx="20107166" pageid="20107166" ns="14" title="Category:Pictures of the Year/2009 (finalist)"/><page _idx="20107165" pageid="20107165" ns="14" title="Category:Pictures of the Year/2007 (finalist)"/><page _idx="20081670" pageid="20081670" ns="14" title="Category:Pictures of the Year exhibitions"/></pages></query></api>
12-20 12:07:05.230 31263 31263 W System.err: java.lang.ClassCastException: fr.free.nrw.commons.category.CategoryDetailsActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesActivity
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.handleSuccess(CategoryImagesListFragment.java:245)
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.bridge$lambda$0$CategoryImagesListFragment(CategoryImagesListFragment.java)
12-20 12:07:05.230 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$4.accept(Unknown Source)
12-20 12:07:05.230 31263 31263 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-20 12:07:05.230 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutObserver.onNext(ObservableTimeoutTimed.java:94)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
12-20 12:07:05.231 31263 31263 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 12:07:05.231 31263 31263 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-20 12:07:05.231 31263 31263 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
12-20 12:07:05.231 31263 31263 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-20 12:07:05.231 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-20 12:07:05.231 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-20 12:07:05.232 31263 31263 D MediaDetailPagerFragmen: Skipping getCount. Returning as activity is destroyed!
12-20 12:07:05.256 31263 31263 W View    : requestLayout() improperly called by android.widget.ProgressBar{691c78 V.ED..... ......ID 468,624-612,768 #7f090113 app:id/loadingImagesProgressBar} during layout: running second layout pass
12-20 12:07:05.796 31263  5939 D CustomApiResult: API response is
12-20 12:07:05.796 31263  5939 D CustomApiResult:  <?xml version="1.0" encoding="UTF-8"?><api><continue iistart="2007-02-11T14:50:24Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/><query><pages><page _idx="33050273" pageid="33050273" ns="14" title="Category:Pictures of the Year/2013 (finalist)"/><page _idx="30597925" pageid="30597925" ns="14" title="Category:Picture of the year barnstars"/><page _idx="3207499" pageid="3207499" ns="4" title="Commons:Grafika roku"/><page _idx="1662301" pageid="1662301" ns="6" title="File:POTY Feb 11.jpg" imagerepository="local"><imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/5/56/POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301"><extmetadata><DateTime value="2007-02-11 22:18:06" source="mediawiki-metadata" hidden=""/><ObjectName value="POTY Feb 11" source="mediawiki-metadata" hidden=""/><CommonsMetadataExtension value="1.2" source="extension" hidden=""/><Categories value="Media lacking a description|Pictures of the Year|Self-published work" source="commons-categories" hidden=""/><Assessments value="" source="commons-categories" hidden=""/><DateTimeOriginal value="" source="commons-desc-page"/><Credit value="&lt;span class=&quot;int-own-work&quot; lang=&quot;en&quot;&gt;Own work&lt;/span&gt;" source="commons-desc-page" hidden=""/><Artist value="&lt;a href=&quot;//commons.wikimedia.org/wiki/User:Alvesgaspar&quot; title=&quot;User:Alvesgaspar&quot;&gt;Alvesgaspar&lt;/a&gt; (&lt;a href=&quot;//commons.wikimedia.org/wiki/User_talk:Alvesgaspar&quot; title=&quot;User talk:Alvesgaspar&quot;&gt;talk&lt;/a&gt;&lt;span style=&quot;white-space:nowrap&quot;&gt; &lt;b&gt;·&lt;/b&gt;&lt;/span&gt; &lt;a href=&quot;//commons.wikimedia.org/wiki/Special:Contributions/Alvesgaspar&quot; title=&quot;Special:Contributions/Alvesgaspar&quot;&gt;contribs&lt;/a&gt;)" source="commons-desc-page"/><LicenseShortName value="CC BY-SA 2.5" source="commons-desc-page" hidden=""/><UsageTerms value="Creative Commons Attribution-Share Alike 2.5" source="commons-desc-page" hidden=""/><AttributionRequired value="true" source="commons-desc-page" hidden=""/><LicenseUrl value="https://creativecommons.org/licenses/by-sa/2.5" source="commons-desc-page" hidden=""/><Copyrighted value="True" source="commons-desc-page" hidden=""/><Restrictions value="" source="commons-desc-page" hidden=""/><License value="cc-by-sa-2.5" source="commons-templates" hidden=""/></extmetadata></ii></imageinfo></page><page _idx="24840980" pageid="24840980" ns="14" title="Category:Pictures of the Year/2012 (finalist)"/><page _idx="20107176" pageid="20107176" ns="14" title="Category:Pictures of the Year/2011 (finalist)"/><page _idx="20107168" pageid="20107168" ns="14" title="Category:Pictures of the Year/2010 (finalist)"/><page _idx="20107166" pageid="20107166" ns="14" title="Category:Pictures of the Year/2009 (finalist)"/><page _idx="20107165" pageid="20107165" ns="14" title="Category:Pictures of the Year/2007 (finalist)"/><page _idx="20081670" pageid="20081670" ns="14" title="Category:Pictures of the Year exhibitions"/></pages></query></api>
12-20 12:07:05.817   790   888 D WifiStateMachine: updateCapabilities for config:mywififalse,false
12-20 12:07:05.844 31263 31263 W System.err: java.lang.ClassCastException: fr.free.nrw.commons.category.CategoryDetailsActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesActivity
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.handleSuccess(CategoryImagesListFragment.java:245)
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.bridge$lambda$0$CategoryImagesListFragment(CategoryImagesListFragment.java)
12-20 12:07:05.845 31263 31263 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$4.accept(Unknown Source)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutObserver.onNext(ObservableTimeoutTimed.java:94)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
12-20 12:07:05.845 31263 31263 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 12:07:05.845 31263 31263 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-20 12:07:05.845 31263 31263 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
12-20 12:07:05.845 31263 31263 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-20 12:07:05.845 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-20 12:07:05.845 31263 31263 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-20 12:07:05.846 31263 31263 D MediaDetailPagerFragmen: Skipping getCount. Returning as activity is destroyed!
```

**Device and Android version:** 

Android 7.1.2 LineageOS

**Commons app version:** 

2.9.0.118

**Screen-shots:** 

screenshot_20181220-120208

### PR DESCRIPTION
**Pull request by zhao-gang**
**Description (required)**

Fixes #2182

This patch saves all the continue node attributes in API response. This fixed a problem when only part of the continue parameters are saved and used, causing client requests the same image from the server indefinitely.

**Tests performed (required)**

Tested ProdDebug on Nexus 6P with API level 27.

**Screenshots showing what changed (optional - for UI changes)**

Now scrolling Pictures of the Year category won't show this [image](https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg) indefinitely.

fix-2182

### CODE REVIEW

**Comment by zhao-gang** [comment]
This patch deleted two file: ContinueUtils.java and QueryContinue.java

I kept {save|get}QueryContinueParameters methods in ApacheHttpClientMediaWikiApi.java, because I found this two methods are only used in this file. And put these methods to a separate Class would need to pass more parameters to these methods, making it unnecessarily complex.

Now continue attributes are saved as a HashMap. It will be cast to json and saved to SharedPrefs. From SharedPrefs it can be cast back to a HashMap, and using the HashMap to add continue parameters to the request. So class QueryContinue is also not needed.

Hope above explanations will help the review of this PR :-)

**Comment by zhao-gang** [comment]
@maskaravivek Thanks for your review.

 I checked that the three same images are in different URL and from different query request.
First response:
`...<continue iistart="2007-02-11T14:50:24Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||" />...`
`<imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/5/56/POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301">...`

Second response:
`...<continue iistart="2007-02-11T11:31:18Z" gcmcontinue="2014-05-29 03:53:32|33050273" continue="gcmcontinue||"/>...`
`...<imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/archive/5/56/20070211221806%21POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301">...`

Third response:
`...<continue gcmcontinue="2012-06-30 16:19:27|20081600" continue="gcmcontinue||"/>...`
`<imageinfo><ii url="https://upload.wikimedia.org/wikipedia/commons/archive/5/56/20070211145024%21POTY_Feb_11.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301">`

You can see the continue nodes and image urls are all different in these three responses. So I think the three same images are normal results from the server. They just happen to be the same image.

As the saving of continue node attributes, I agree these attributes are not needed to be saved in SharedPrefs. Saving these attributes in Bundle when onSaveInstanceState is called might be enough. I will update the PR soon.

**Comment by maskaravivek** [comment]
Hmm. I don't understand this completely. 

@nicolas-raoul @misaochan Can you take a look?

**Comment by nicolas-raoul** [comment]
@zhao-gang So do you mean it is a server-side API bug? If yes, would you mind creating a new issue on https://phabricator.wikimedia.org ? Thanks for the investigation! :-)

**Comment by zhao-gang** [comment]
> @zhao-gang So do you mean it is a server-side API bug? If yes, would you mind creating a new issue on https://phabricator.wikimedia.org ? Thanks for the investigation! :-)

I am not sure whether it's a bug if the server returned three same images(in different URL) in three consecutive query request? 

One thing that seems suspicious is that the three images have the same descriptionurl `descriptionurl="https://commons.wikimedia.org/wiki/File:POTY_Feb_11.jpg" ` and descriptionshorturl `descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=1662301"` as in above three server responses.

**Comment by zhao-gang** [comment]
Changes:
Rebased with current master
Removed category continue node attributes from SharedPrefs

**Comment by zhao-gang** [comment]
Changes: 
Rebased with current master

**Comment by domdomegg** [comment]
Seem to get same result even with the original master this was created against (ecc05c1ca)

| About | Explore |
| - | - |
| Screenshot_1552834230 | Screenshot_1552834237 |

**Comment by domdomegg** [comment]
Whoops didn't see discussion https://github.com/commons-app/apps-android-commons/issues/2182#issuecomment-469035884

@zhao-gang Does this PR still fix the [underlying issue you identified](https://github.com/commons-app/apps-android-commons/issues/2182#issuecomment-473301713)? If so do you have any example categories to test against?

**Comment by zhao-gang** [comment]
@domdomegg I tested this PR solved the issue #2182. You can use category `Velles (Indre)` to test, as described in issue #2523.

**Comment by zhao-gang** [comment]
@domdomegg After some research I found this two same images(both have the name `Place de la Bascule Velles`) are in different image urls: https://upload.wikimedia.org/wikipedia/commons/9/93/Place_de_la_Bascule_Velles.JPG and https://upload.wikimedia.org/wikipedia/commons/archive/9/93/20120116155010%21Place_de_la_Bascule_Velles.JPG. For the second image request the server will not return the `continue` parameter, which indicates there's no more images for this category.

As the above explanation shows, I think this is a normal result. As long as we don't make requests which let's the server return the same image with the same image url indefinitely, we are in the right path.

**Comment by zhao-gang** [comment]
Update the code to be more coherent with server's API documentation. Specifically, check if `queryContinueParam` is `null`, or if `queryContinueParam` doesn't have `continue` parameter. if above is true, set `hasMoreImages` to false. 

P.S. This change doesn't have visible changes in category `Velles (Indre)`.

**Comment by neslihanturan** [comment]
Does this issue still exist?

**Comment by nicolas-raoul** [comment]
@neslihanturan  I have not seen this problem for a long time.

**Comment by neslihanturan** [comment]
Thanks a lot for your effort on this issue @zhao-gang , but this issue is no longer exists.

**Pull request closed without merging**
