### PR TITLE
Fix security exception crash while accessing network location provider

### LINKED ISSUE #1480: Nearby crashes after logging out and in
**Summary:** 

Nearby crashes after logging out and in.

**Steps to reproduce:** 

Open app, open nearby, log out, log in, open nearby again

**Add System logs:**
```
E/LocationServiceManager: Security exception
                                                                                 java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
                                                                                     at android.os.Parcel.readException(Parcel.java:1599)
                                                                                     at android.os.Parcel.readException(Parcel.java:1552)
                                                                                     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:123)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:111)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity.onStart(NearbyActivity.java:299)
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                     at android.app.Activity.performStart(Activity.java:6253)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Device and Android version:** 

API level 19
 
 **Commons app version:** 

current master

### PR DESCRIPTION
**Pull request by maskaravivek**
## Description

Fixes #1480

The app was not asking for permissions before subscribing to location updates from the network provider. This was leading to a security exception. 

## Tests performed

Unable to reproduce the crash using the steps mentioned in the issue. 

@neslihanturan @misaochan Can you guys help in testing if its reproducible on your end.

### CODE REVIEW

**Comment by neslihanturan** [comment]
@maskaravivek I dont get security exception with steps. But still I do get crash with meaningless logs:/

`05-07 11:27:07.439 4640-4691/fr.free.nrw.commons.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa249f920
05-07 11:27:07.842 4640-4728/fr.free.nrw.commons.debug A/libc: /usr/local/google/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: attempt to write a readonly database" failed
05-07 11:27:07.843 4640-4728/fr.free.nrw.commons.debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4728 (DefaultFileSour)
`

**Comment by albendz** [comment]
Testing on a Samsung physical device with Android 7.0, API 24. Consistently crashes prior to changes and consistently crashes after changes. Have not been able to confirm stacktraces are the same since Android Studio keeps cleaning them up (let me know of a way to save them if further testing is needed).

Just to clarify repro: Open app, go to nearby, log out, log in, go to nearby -> crash

**Comment by maskaravivek** [comment]
@albendz Logs would be quite helpful to debug further. Can you please try using `pidcat` for logs. 

https://github.com/JakeWharton/pidcat

**Comment by maskaravivek** [comment]
@albendz Are you sure that this PR doesn't fix the issue for you. I tried reproducing it and was able to successfully reproduce it without the fix. After this fix, the error was no longer occurring for me.

**Comment by albendz** [comment]
I'll retest and hopefully get back to you soon.

**Comment by misaochan** [comment]
Sorry for the slow response @maskaravivek  - I will try to help test as well, today or tomorrow.

**Comment by albendz** [comment]
Yes, I'm sure. Though, I still can't confirm the error I'm seeing is the same as what you fixed. I don't see an exception, only "05-13 20:49:25.156 18785-18890/fr.free.nrw.commons.debug A/libc: /usr/local/google/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: attempt to write a readonly database" failed
    Fatal signal 6 (SIGABRT), code -6 in tid 18890 (DefaultFileSour)" both with and without your changes. I confirmed that when stepping through your code with a debugger, you changes were hit. This may be a separate issue I am hitting.

**Comment by maskaravivek** [comment]
Thanks for helping in testing @albendz. 

The error that you are facing seems to be different than what I have fixed in the PR. The important logline seems to be: 

```
Fatal signal 6 (SIGABRT), code -6 in tid 18890 (DefaultFileSour)
```

And the possible reasons could be: 
- https://stackoverflow.com/questions/36693887/what-is-fatal-signal-6-in-android-logcat
- https://github.com/mapbox/mapbox-android-demo/issues/48

In any case, IMO this PR can be merged as it fixes an issue where location permissions were not being checked before registering for location updates.

**Comment by misaochan** [comment]
I am experiencing the same issue when following the steps at #1480  - logs below. However, I am OK with merging this PR since it fixes a different issue, but not closing #1480 . @neslihanturan , what do you think?

```
05-14 20:57:14.763 7270-7316/fr.free.nrw.commons.debug A/libc: /usr/local/google/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: attempt to write a readonly database" failed
05-14 20:57:14.784 7270-7316/fr.free.nrw.commons.debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7316 (DefaultFileSour)
05-14 20:57:14.848 7443-7443/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'google/sdk_google_phone_x86/generic_x86:7.1.1/NYC/4498512:userdebug/test-keys'
    Revision: '0'
    ABI: 'x86'
    pid: 7270, tid: 7316, name: DefaultFileSour  >>> fr.free.nrw.commons.debug <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    Abort message: '/usr/local/google/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: attempt to write a readonly database" failed'
        eax 00000000  ebx 00001c66  ecx 00001c94  edx 00000006
        esi 90585978  edi 90585920
        xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
        eip b0225424  ebp 90584c48  esp 90584bec  flags 00000296
05-14 20:57:14.850 7443-7443/? A/DEBUG: backtrace:
        #00 pc ffffe424  [vdso:b0225000] (__kernel_vsyscall+16)
        #01 pc 0007a03c  /system/lib/libc.so (tgkill+28)
        #02 pc 00075885  /system/lib/libc.so (pthread_kill+85)
        #03 pc 0002785a  /system/lib/libc.so (raise+42)
        #04 pc 0001ee36  /system/lib/libc.so (abort+86)
        #05 pc 00023d48  /system/lib/libc.so (__libc_fatal+40)
        #06 pc 0001f300  /system/lib/libc.so (__assert2+64)
        #07 pc 0049cff4  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #08 pc 0049d107  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #09 pc 0049a379  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #10 pc 00499afc  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #11 pc 0014cb5f  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #12 pc 0013d6fc  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #13 pc 0013d5b7  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #14 pc 0013d48a  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #15 pc 00127c32  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #16 pc 0012f65a  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #17 pc 0012f4f0  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #18 pc 00273a3c  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #19 pc 00273b93  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #20 pc 0012e4b2  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #21 pc 0012e3e7  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
05-14 20:57:14.851 7443-7443/? A/DEBUG:     #22 pc 00350cb9  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #23 pc 00350bc5  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #24 pc 0012c4bb  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #25 pc 0012c32a  /data/app/fr.free.nrw.commons.debug-1/lib/x86/libmapbox-gl.so
        #26 pc 00074fe2  /system/lib/libc.so (_ZL15__pthread_startPv+210)
        #27 pc 0002029e  /system/lib/libc.so (__start_thread+30)
        #28 pc 0001e076  /system/lib/libc.so (__bionic_clone+70)
05-14 20:57:15.527 1665-7448/system_process W/ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity
```

and

```
05-14 20:57:15.635 7451-7451/? W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
        at fr.free.nrw.commons.CommonsApplication.$jacocoInit(CommonsApplication.java)
        at fr.free.nrw.commons.CommonsApplication.<init>(CommonsApplication.java)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
```

**Comment by albendz** [comment]
Based on what Vivek sent, the SIGABRT 6 issue is related to something else. If you're seeing that, it's not the issue. Since that seems to be caused by overloading the UI thread, we might be doing the repro too quickly...

**Comment by misaochan** [comment]
I waited for over 10 seconds after logging in before I loaded Nearby, to be sure that speed wasn't the issue. :) However, I personally think it would be best to focus on fixing the jacoco.exec error instead of SIGABRT, as the latter is much more general and can potentially be caused by library errors. After we fix jacoco, we can see if the crash still occurs.

**Comment by neslihanturan** [comment]
@misaochan I agree with you. My tests gave same results so we should leave #1480 open but also merge this PR

**Pull request merged**
