### PR TITLE
Rename values-skr-arab to values-skr

### PR DESCRIPTION
**Pull request by whym**
Fixes the build error of 64c3d402cad40db5098a53ec29793ce335255936. This is a TranslateWiki.Net issue similar to #761 and #349.

### CODE REVIEW

**Comment by janpio** [comment]
There will probably be some changes required on TranslateWiki side so this doesn't appear again with their next commit (if at all possible).

**Comment by whym** [comment]
@janpio Yep, and it's also been done at https://gerrit.wikimedia.org/r/#/c/370456/, thanks to @Nikerabbit's swift response.

**Comment by janpio** [comment]
Awesome.

(Maybe silly question: Where can I see the translatewiki repo being changed here?)

**Comment by whym** [comment]
> Where can I see the translatewiki repo being changed here?

I believe the repository is in Wikimedia's Diffusion (part of Phabricator).
Follow the "(diffusion)" link from
https://gerrit.wikimedia.org/r/#/c/362954/ .
They also have a GitHub mirror
https://github.com/wikimedia/translatewiki/commit/acc6781204c7d32471e65bfdc655ff8687f3fb89

**Comment by janpio** [comment]
Thanks!

The relevant repo and file then is:
https://phabricator.wikimedia.org/diffusion/GTWN/repository/master/
https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml

(or
https://github.com/wikimedia/translatewiki/
https://github.com/wikimedia/translatewiki/blob/master/groups/Wikimedia/CommonsAndroid.yaml)

**Comment by janpio** [comment]
(Now documented at https://github.com/commons-app/apps-android-commons/wiki/Translating-the-App#configuration)

**Pull request merged**
