### PR TITLE
[WIP] Rewrite of the API layer

### PR DESCRIPTION
**Pull request by psh**
## Description

This PR move us most of the way toward a rewrite of the API layer of the app with a couple of goals
* Move off the deprecated Apache based libraries and consolidate onto a single networking library (OkHttp)
* Move off the deprecated XML based mediawiki api and to using the JSON based mediawiki api

The work is *not complete* but I wanted this in the team's hands sooner rather than later!  Aiming to merge to a centralized feature branch to continue the work.

## Tests performed

At this point it's possible to log into the app (beta and prod variants) and view your contributions.  I only have a single "useful" notification so testing loading those was a little sketchy, so it would be great if someone else could take a look.  There are a couple of gaps in the API still needing to be filled in; manual testing will fail if you bump into a `// TODO` comment on an unimplemented method.

## Still to do

Look at the `// TODO` comments in the code - there are a couple of spots still to fill in.  I've not tackled upload yet, but got some of the infrastructure in place for someone to be able to fill that in.  It's going to need a little creativity to pull *progress notifications* from the OkHttp upload.

~The modeling of responses is another area for refactoring to better adhere to the Open/Closed principle; infrastructure is in place to be able to return something other than my initial `ApiResponse` class, just now need to break it up a little.~  ✅ **Done**

Also missing is Javadoc.  Yeah, about that.  😉

### CODE REVIEW

**Comment by maskaravivek** [comment]
@psh Awesome work with the rewrite. We will review and get it merged as soon as possible. 

Any particular reason for choosing OkHttp over Retrofit. I am not sure if the choice of the library has already been discussed.

**Comment by psh** [comment]
@maskaravivek I thought seriously about using Retrofit - its basically my "go to" library when talking pure REST services.  

We have a single server-side endpoint that takes the "action" parameter to determine which API to call - mirroring SOAP style services and less a clean REST interface.  It's easy to add the extra GET parameter on the Retrofit interface to hide that - 

```java
interface Wikimedia {
    @GET("/w/api.php?action=query&list=logevents&letype=upload&leprop=title|timestamp|ids")
    QueryApiResponse logEvents(@Query("leuser") String user, @Query("lelimit") int limit);
}
```
But there are optional parameters - hard to handle when you're defining a fixed interface.  If you don't encode the fixed query parameters and drop them directly on the interface method there's very little difference in public API to what is in the code right now running over "bare" OkHttp.

Similarly it's easy enough to create the interface method for a POST that encodes as *form encoded* data, but it's not as easy to say "I want to default one form parameter for **action**" - ending up as a leaky abstraction where "action" becomes visible for a few methods and not others.

Retrofit runs over the top of OkHttp so would fit the overall goal of moving off the deprecated Apache HTTP libraries at the cost of *adding* another library; we already have OkHttp in the project.  Another point in its favor is that it's used in the main Wikipedia app, so we'd be aligning our tech stack with theirs.  

Where Retrofit excels is in the marshaling of request parameters and parsing responses.  This would definitely save a few lines of code in the request builder class.

**Comment by maskaravivek** [comment]
@psh Thanks for the really insightful response. I agree with the benefits of using OkHttp. My initial concern was raised because of the very fact that I see a lot of Retrofit usage in the Wikipedia app. I wasn't aware that it also uses simply OkHttp too. All the code that I have come across in the Wikipedia app seems to use Retrofit. Please correct me if I am wrong. :)

**Comment by maskaravivek** [comment]
Thanks for the clarification @psh. I seem to agree with the benefits of OkHttp that you have pointed out. Having just little first-hand experience with both these libraries, I just wanted to be sure that both libraries were considered before choosing OkHttp. 

We will review it soon and try to get it merged. :)

**Comment by maskaravivek** [comment]
@psh Let us know when the PR is ready for review

**Comment by maskaravivek** [comment]
Quite recently we have stuggled a lot with the current implementation of `HttpClient`. It would be really great to make use of these changes in our app as it uses `OkHttp`. 

@psh Is this PR complete from your end? We can probably start testing and add the newer network calls to it and merge it to master. 

Its astonishing that the PR still has no merge conflicts with master. :D

**Pull request closed without merging**
