### PR TITLE
Implement direct uploads from Nearby List

### PR DESCRIPTION
**Pull request by misaochan**
Hooks up the camera and gallery buttons in Nearby List, as part of the requirement for #252 . Title and desc fields are autofilled, similar in scope to #1060 .

Category suggestions and Wikidata edits have not been implemented.

### CODE REVIEW

**Comment by neslihanturan** [comment]
Thanks @misaochan , it works as intended. I restarted Travis CI tests, lets see if it can pass this time.

**Comment by neslihanturan** [comment]
Travis logs says: 
`:app:compileBetaDebugUnitTestJavaWithJavac/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/nearby/NearbyAdapterFactoryTest.java:127: error: cannot find symbol
    private class MockPlaceClickedListener implements PlaceRenderer.PlaceClickedListener {
                                                                   ^
  symbol:   class PlaceClickedListener
  location: class PlaceRenderer
/home/travis/build/commons-app/apps-android-commons/app/src/test/java/fr/free/nrw/commons/nearby/NearbyAdapterFactoryTest.java:41: error: no suitable constructor found for NearbyAdapterFactory(<null>)
        NearbyAdapterFactory testObject = new NearbyAdapterFactory(null);`

**Comment by misaochan** [comment]
@neslihanturan Yeah, we need to overhaul several of the Nearby tests before releasing the direct uploads feature. However, I'm not sure if we want to block individual PRs for it? AFAIK some Nearby tests would have failed ever since the UI overhaul at the start of this branch (#1018 ).

**Comment by neslihanturan** [comment]
So there is no block to merging it @misaochan :)

**Pull request merged**
