### PR TITLE
Changed Logs Dir

### LINKED ISSUE #2968: App should not clutter download folder with log files
`/sdcard/Download/logs/prod/CommonsAppLogs.0.log`

It's annoying to have logging stuff in my download folder when I want to keep this folder clean.

Use the corresponding `data/` folder instead.

### PR DESCRIPTION
**Pull request by shankarpriyank**
Fixes #2968 

Changed the directory where the logs are stored

### CODE REVIEW

**Comment by shankarpriyank** [comment]
Ideally, the logs should be there.

**Comment by nicolas-raoul** [comment]
Still nothing, though I uploaded many files. Ah, maybe logs only appear when a crash happens?

Are you seeing files being populated? If yes in what folder? Thanks!

**Comment by shankarpriyank** [comment]
I am a bit occupied this week my university exams are going on, I will get back to you by 17th

**Comment by shankarpriyank** [comment]
I tested both on this branch and master, can't see any logs being generated

**Comment by nicolas-raoul** [comment]
Thanks for checking!
That's problematic... and would probably need to be fixed first. Would you mind creating a new issue about this? Thanks!

**Comment by shankarpriyank** [comment]
> Thanks for checking! That's problematic... and would probably need to be fixed first. Would you mind creating a new issue about this? Thanks!

Sure, do you mind stating once what is the ideal behavior?

**Comment by RitikaPahwa4444** [comment]
I was uploading pictures from my `Downloads` folder on Commons when I found a folder named `logs`. Opening it from the File Manager showed two folders: `prod `and `beta`. The log files have all the debug and error messages. They appear somewhat like this: 

Screenshot from 2023-05-12 13-54-20

Is this what we are looking for in the master branch? I tested it on Redmi 5A with API level 27.

**Comment by shankarpriyank** [comment]
Thanks @RitikaPahwa4444 this is the ideal behavior on master, can you please test this branch too?

**Comment by RitikaPahwa4444** [comment]
Hi @shankarpriyank, I couldn't find any logs files being generated by this branch.

**Comment by shankarpriyank** [comment]
> Hi @shankarpriyank, I couldn't find any logs files being generated by this branch.

Ahh. 
Thanks for testing it.
Btw did you check the app directory for log files too?

**Comment by RitikaPahwa4444** [comment]
I'm not sure if this could have caused the logs to appear or they were present already and I could not differentiate them but I had deleted all the log files yesterday to see if I could discover something. I am able to see the logs now, but not in the `Android/data/fr.free.nrw.commons` directory. This is where I found them:

logs

**Comment by shankarpriyank** [comment]
Hey @RitikaPahwa4444 , I could not understand your comment properly 

> this could have caused the logs to appear

What could have caused the logs to appear?
But anyways, finally we can see some logs.
And I think the location of the file is also working as intended.
Cause as specified the file should appear in the following directory
`/storage/emulated/0/Android/data/<package-name>/files/logs/beta/
`

@nicolas-raoul the logs are generating as intended on Ritika's device

**Comment by shankarpriyank** [comment]
Got it! thanks for the explanation.
I think the directory is correct, I am also not a pro in the directory system but I just read a few articles around it, seems like this is the way a lot of apps do it, and it working as intended.
The main problem is I can't see any logs being generated on my device 🥲

**Comment by domdomegg** [comment]
Closing this as it's now stale

**Pull request closed without merging**
